news9 = [
	{title : "‘The Innovators’ by Walter Isaacson", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/books/review/the-innovators-by-walter-isaacson.html", time: "1 day ago"}, 
	{title : "The Physical Web", site: "github.co", href: "https://github.com/google/physical-web", time: "4 days ago"}, 
	{title : "Refactoring Ruby with Monads", site: "codon.co", href: "http://codon.com/refactoring-ruby-with-monads", time: "3 days ago"}, 
	{title : "Mistakes AngularJS Developers Make", site: "airpair.co", href: "http://www.airpair.com/angularjs/posts/top-10-mistakes-angularjs-developers-make", time: "3 days ago"}, 
	{title : "Haskell, Monads and Purity", site: "jelv.i", href: "http://jelv.is/blog/Haskell-Monads-and-Purity/", time: "3 days ago"}, 
	{title : "Show HN: Poll – Voting done simply in real time", site: "lab.i", href: "http://poll.lab.io", time: "1 day ago"}, 
	{title : "Rockwool vs. Perlite vs. Hydroton vs. Soil", site: "hydronerd.co", href: "http://hydronerd.com/2014/10/rockwool-vs-perlite-vs-hydroton-vs-soil/", time: "1 day ago"}, 
	{title : "The Star7 PDA Prototype, Genesis of Java [video] (1992)", site: "youtube.co", href: "https://www.youtube.com/watch?v=Ahg8OBYixL0", time: "1 day ago"}, 
	{title : "The Immaturity and Arrogance of Uber", site: "medium.co", href: "https://medium.com/@petersimsie/the-immaturity-and-arrogance-of-uber-eea64bcfa5bf", time: "23 hours ago"}, 
	{title : "Graphite-News: Keeping up to speed with whats new in your monitoring tool", site: "jilles.ne", href: "http://www.jilles.net/perma/2014/10/03/introducing-graphite-news/", time: "1 day ago"}, 
	{title : "Vim blowfish encryption", site: "dgl.c", href: "https://dgl.cx/2014/10/vim-blowfish", time: "1 day ago"}, 
	{title : "Why haven't quadcopters been scaled up yet?", site: "stackexchange.co", href: "http://aviation.stackexchange.com/questions/3300/why-havent-quadcopters-been-scaled-up-yet", time: "2 days ago"}, 
	{title : "Inspeqtor – Monitor your application infrastructure", site: "github.co", href: "https://github.com/mperham/inspeqtor", time: "1 day ago"}, 
	{title : "Show HN: Simple email rendering tool to handle multi-language email content", site: "github.co", href: "https://github.com/KeepSafe/ks-email-parser", time: "22 hours ago"}, 
	{title : "Where the Printf Rubber Meets the Road (2010)", site: "hostilefork.co", href: "http://blog.hostilefork.com/where-printf-rubber-meets-road/", time: "2 days ago"}, 
	{title : "Big robot fleet takes to UK waters", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29464273", time: "1 day ago"}, 
	{title : "Times Articles Removed from Google Results in Europe", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/media/times-articles-removed-from-google-results-in-europe.html", time: "2 days ago"}, 
	{title : "Machine Learning with Knowledge Graphs [video]", site: "nzhiltsov.blogspot.co", href: "http://nzhiltsov.blogspot.com/2014/10/machine-learning-with-knowledge-graphs.html", time: "1 day ago"}, 
	{title : "Apple Expected to Consume 25% of All DRAM in 2015", site: "hothardware.co", href: "http://hothardware.com/m/News/Apple-Expected-To-Consume-25-Of-All-DRAM-In-2015-Impact-Industry-Trends/default.aspx", time: "23 hours ago"}, 
	{title : "Navy: Self-guided unmanned patrol boats make debut", site: "myfoxal.co", href: "http://www.myfoxal.com/story/26706962/navy-self-guided-unmanned-patrol-boats-make-debut", time: "1 day ago"}, 
	{title : "In 1888, one man patented a machine for vending “healthy” electric shocks", site: "arstechnica.co", href: "http://arstechnica.com/science/2014/10/a-look-at-the-1888-patent-for-an-electric-shock-vending-machine", time: "1 day ago"}, 
	{title : "Do Deep Nets Really Need to be Deep? [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1312.6184v5.pdf", time: "3 days ago"}, 
	{title : "When 911 calls fail", site: "theverge.co", href: "http://www.theverge.com/2014/10/3/6414949/911-call-failures-fcc", time: "3 days ago"}, 
	{title : "CERN turns 60", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/cern-turns-60", time: "2 days ago"}, 
	{title : "Bitcoin trader floods market with $300 orders, causing price to flatline", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?flatine", time: "22 hours ago"}, 
	{title : "Reading the Silk Road configuration", site: "erratasec.co", href: "http://blog.erratasec.com/2014/10/reading-silk-road-configuration.html", time: "3 days ago"}, 
	{title : "The Most Ambitious Environmental Lawsuit Ever", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/02/magazine/mag-oil-lawsuit.html", time: "1 day ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://m.bbc.com/news/science-environment-29465446", time: "2 days ago"}, 
]