news16 = [
	{title : "NgMario", site: "blnight.github.i", href: "http://blnight.github.io/ngMario/#/game", time: "2 days ago"}, 
	{title : "To Find Meteorites, Listen to the Legends of Australian Aborigines", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/science-nature/find-meteorites-listen-legends-australian-aborigines-180952941/", time: "1 day ago"}, 
	{title : "Granny Smith apples promote growth of friendly bacteria in the colon", site: "wsu.ed", href: "https://news.wsu.edu/2014/09/29/an-apple-a-day-could-keep-obesity-away/#.VCqA_GeSz94", time: "2 days ago"}, 
	{title : "Common Parts Library", site: "octopart.co", href: "http://octopart.com/common-parts-library?a=1", time: "7 days ago"}, 
	{title : "Show HN: Hackers Job Apply", site: "github.co", href: "https://github.com/lukasz-madon/hackers-job-apply", time: "2 days ago"}, 
	{title : "C++11/14 compiler and library shootout", site: "cpprocks.co", href: "http://cpprocks.com/c1114-compiler-and-library-shootout/", time: "4 days ago"}, 
	{title : "Why women leave tech: It's the culture, not because 'math is hard'", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture/", time: "3 days ago"}, 
	{title : "MiniKanren – An embedded DSL for logic programming", site: "minikanren.or", href: "http://minikanren.org/", time: "5 days ago"}, 
	{title : "A Fresh Look at Rust", site: "pocoo.or", href: "http://lucumr.pocoo.org/2014/10/1/a-fresh-look-at-rust/", time: "6 days ago"}, 
	{title : "Microsoft makes more money from Samsung than from Skype, Windows Phone, and Xbox", site: "qz.co", href: "http://qz.com/276242/microsoft-makes-more-money-from-samsung-than-from-skype-windows-phone-and-xbox-combined/", time: "1 day ago"}, 
	{title : "Eleven awesome things you can do with csvkit", site: "opennews.or", href: "https://source.opennews.org/en-US/articles/eleven-awesome-things-you-can-do-csvkit/", time: "1 day ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341/", time: "2 days ago"}, 
	{title : "The Downtown Project Suicides", site: "recode.ne", href: "http://recode.net/2014/10/01/the-downtown-project-suicides-can-the-pursuit-of-happiness-kill-you/", time: "5 days ago"}, 
	{title : "Issue #3 – Better Late Than Never", site: "neovim.or", href: "http://neovim.org/news/2014/sept/", time: "27 days ago"}, 
	{title : "For developers: These shirts make you look better than your code – ShirtJS", site: "shirtjs.co", href: "http://shirtjs.com/", time: "1 day ago"}, 
	{title : "Writing a simple operating system from scratch (2010) [pdf]", site: "bham.ac.u", href: "http://www.cs.bham.ac.uk/~exr/lectures/opsys/10_11/lectures/os-dev.pdf", time: "8 days ago"}, 
	{title : "The Ebola Patient Was Sent Home Because of Bad Software", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/10/the-ebola-patient-was-sent-home-because-of-an-electronic-health-record-problem/381087/", time: "2 days ago"}, 
	{title : "Show HN: Franc – Detect natural languages", site: "github.co", href: "https://github.com/wooorm/franc", time: "3 days ago"}, 
	{title : "Aids: Origin of pandemic 'was 1920s Kinshasa'", site: "bbc.co", href: "http://www.bbc.com/news/health-29442642", time: "3 days ago"}, 
	{title : "Show HN: The Wide Language Index", site: "widelanguageindex.or", href: "http://widelanguageindex.org/", time: "2 days ago"}, 
	{title : "The next generation storage engine for Couchbase Server: ForestDB", site: "couchbase.co", href: "http://blog.couchbase.com/next-generation-storage-engine-couchbase-server-and-couchbase-lite-forestdb-now-available-beta", time: "1 day ago"}, 
	{title : "Aboard a Cargo Colossus: Maersk’s New Container Ships", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/business/international/aboard-a-cargo-colossus-maersks-new-container-ships.html?hp&action=click&pgtype=Homepage&version=HpSumSmallMediaHigh&module=second-column-region&region=top-news&WT.nav=top-news&_r=0", time: "3 days ago"}, 
	{title : "Arduino LED Startup Counter", site: "matthack.co", href: "http://matthack.com/startup-counter/", time: "2 days ago"}, 
	{title : "A Plan to Use Survivors’ Blood for Ebola Treatment in Africa", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/health/use-of-ebola-survivors-blood-as-possible-treatment-gains-support.html?ref=science", time: "2 days ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage", time: "2 days ago"}, 
]