news4 = [
	{title : "Square Raises $150M at a $6B Valuation", site: "bits.blogs.nytimes.co", href: "http://bits.blogs.nytimes.com/2014/10/05/square-raises-150-million-at-a-6-billion-valuation/", time: "23 hours ago"}, 
	{title : "Reddit CEO Calls Out Former Reddit Employee on Reddit", site: "reddit.co", href: "https://np.reddit.com/r/IAmA/comments/2iea97/i_am_a_former_reddit_employee_ama/cl1ygat?context=3", time: "7 hours ago"}, 
	{title : "New npm documentation", site: "npmjs.co", href: "https://docs.npmjs.com/", time: "6 hours ago"}, 
	{title : "Why Apple's iPhone encryption won't stop NSA", site: "siliconexposed.blogspot.co", href: "http://siliconexposed.blogspot.com/2014/10/why-apples-iphone-encryption-wont-stop.html", time: "1 day ago"}, 
	{title : "Same-Sex Marriage Is Now Legal for a Majority of the USA", site: "fivethirtyeight.co", href: "http://fivethirtyeight.com/datalab/same-sex-marriage-is-now-legal-for-a-majority-of-the-u-s/", time: "1 hour ago"}, 
	{title : "How fast is fscanf?", site: "github.co", href: "https://github.com/alexflint/fscanf-speed", time: "1 day ago"}, 
	{title : "Hewlett-Packard Plans to Break in Two", site: "wsj.co", href: "http://online.wsj.com/articles/hewlett-packard-plans-to-break-in-two-1412530028?mod=djemalertTECH", time: "1 day ago"}, 
	{title : "'Open Source is awful in many ways, and people should be aware of this'", site: "plus.google.co", href: "https://plus.google.com/app/basic/stream/z13rdjryqyn1xlt3522sxpugoz3gujbhh04", time: "12 hours ago"}, 
	{title : "Beginnings of Science Fiction", site: "wewanttolearn.wordpress.co", href: "http://wewanttolearn.wordpress.com/2014/10/05/beginnings-of-sf/", time: "19 hours ago"}, 
	{title : "Learn JavaScript by adventuring around in the terminal", site: "github.co", href: "https://github.com/sethvincent/javascripting", time: "6 hours ago"}, 
	{title : "On the Computational Complexity of MapReduce", site: "jeremykun.co", href: "http://jeremykun.com/2014/10/05/on-the-computational-complexity-of-mapreduce/", time: "1 day ago"}, 
	{title : "How to Work Quietly", site: "idonethis.co", href: "http://blog.idonethis.com/quiet-work/", time: "3 hours ago"}, 
	{title : "NPR's Fresh Air interviews Walter Isaacson, author of 'The Innovators'", site: "npr.or", href: "http://www.npr.org/2014/10/06/353269811/how-the-cold-war-and-george-orwell-helped-make-the-internet-what-it-is", time: "5 hours ago"}, 
	{title : "This Is What Common Core Looks Like", site: "erickerickson.or", href: "http://www.erickerickson.org/blog/2014/09/30/this-is-what-common-core-looks-like/", time: "5 hours ago"}, 
	{title : "Google to Make Security Guards Employees, Rather Than Contractors", site: "wsj.co", href: "http://blogs.wsj.com/digits/2014/10/03/google-to-make-security-guards-as-employees-rather-than-contractors/", time: "1 day ago"}, 
	{title : "Show HN: Pykov – a tiny Python module on finite regular Markov chains", site: "github.co", href: "https://github.com/riccardoscalco/Pykov", time: "19 hours ago"}, 
	{title : "Cheap Beer and the Psychology of PlayStation Now Pricing", site: "psychologyofgames.co", href: "http://www.psychologyofgames.com/2014/08/cheep-beer-and-the-psychology-of-playstation-now-pricing/", time: "1 day ago"}, 
	{title : "HTTP Considered Unethical", site: "alexgaynor.ne", href: "https://alexgaynor.net/2014/oct/06/http-considered-unethical/", time: "3 hours ago"}, 
	{title : "One in three Jobs will be taken by software or robots by 2025", site: "computerworld.co", href: "http://www.computerworld.com/article/2691607/one-in-three-jobs-will-be-taken-by-software-or-robots-by-2025.html", time: "2 hours ago"}, 
	{title : "Surveillance drives South Koreans to encrypted messaging apps", site: "theverge.co", href: "http://www.theverge.com/2014/10/6/6926205/surveillance-drives-south-koreans-to-encrypted-messaging-apps", time: "2 hours ago"}, 
	{title : "FBI director says Chinese hackers are like a “drunk burglar”", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/fbi-director-says-chinese-hackers-are-like-a-drunk-burglar/", time: "3 hours ago"}, 
	{title : "What is probabilistic programming?", site: "pl-enthusiast.ne", href: "http://www.pl-enthusiast.net/2014/09/08/probabilistic-programming/", time: "1 day ago"}, 
	{title : "Our Understanding of Giraffes Does Not Measure Up", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/science/our-understanding-of-giraffes-does-not-measure-up.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "1 day ago"}, 
	{title : "Coyote Creek is a foul wasteland minutes from mega-rich Silicon Valley", site: "mirror.co.u", href: "http://www.mirror.co.uk/news/world-news/welcome-jungle-coyote-creek-foul-4392415", time: "4 hours ago"}, 
	{title : "Why the Scroll Event Change in iOS 8 Is a Big Deal", site: "telerik.co", href: "http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/", time: "3 hours ago"}, 
	{title : "Freedom from Food", site: "aeon.c", href: "http://aeon.co/magazine/health/would-we-opt-out-of-food-if-given-the-chance/", time: "9 hours ago"}, 
	{title : "Mono 3.10.0", site: "mono-project.co", href: "http://www.mono-project.com/docs/about-mono/releases/3.10.0/", time: "12 hours ago"}, 
	{title : "Hewlett-Packard Announces Breakup Plan", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/business/hewlett-packard-announces-breakup-plan.html?src=busln&_r=0", time: "14 hours ago"}, 
]