news7 = [
	{title : "Attack code for 'unpatchable' USB flaw released", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/technology-29475566", time: "7 hours ago"}, 
	{title : "What It's Like to Build a Startup in Gaza", site: "wired.co", href: "http://www.wired.com/2014/10/like-build-startup-gaza-strip-bombs-drop/", time: "3 days ago"}, 
	{title : "Using Machine Learning and Node.js to detect the gender of Instagram Users", site: "totems.c", href: "http://totems.co/?p=11084", time: "7 days ago"}, 
	{title : "The Evils of Open Source", site: "xavierriley.co.u", href: "http://xavierriley.co.uk/the-evils-of-open-source/", time: "10 hours ago"}, 
	{title : "Marriott Hotels fined $600,000 by FCC for jamming Wi-Fi hotspots [pdf]", site: "fcc.go", href: "http://transition.fcc.gov/Daily_Releases/Daily_Business/2014/db1003/DA-14-1444A1.pdf", time: "3 days ago"}, 
	{title : "Shadow Internet That’s 100 Times Faster Than Google Fiber", site: "wired.co", href: "http://www.wired.com/2014/06/esnet", time: "21 hours ago"}, 
	{title : "Monit issues takedown request for Inspeqtor (both open source monitoring tools)", site: "twitter.co", href: "https://twitter.com/mperham/status/518796150733033472", time: "10 hours ago"}, 
	{title : "The Greatest Ancient Picture Gallery", site: "nybooks.co", href: "http://www.nybooks.com/articles/archives/2014/oct/23/greatest-ancient-picture-gallery/", time: "1 day ago"}, 
	{title : "Tuples in Swift: How to Create, Read, and Return Them", site: "codingexplorer.co", href: "http://www.codingexplorer.com/tuples-in-swift-create-read-and-return/", time: "9 hours ago"}, 
	{title : "Installing Nvidia CUDA on Ubuntu 14.04 for Linux GPU Computing", site: "quantstart.co", href: "http://www.quantstart.com/articles/Installing-Nvidia-CUDA-on-Ubuntu-14-04-for-Linux-GPU-Computing", time: "13 hours ago"}, 
	{title : "Apple sapphire crystal supplier GT Advanced files for bankruptcy", site: "9to5mac.co", href: "http://9to5mac.com/2014/10/06/gtat-sapphire-apple-bankrupt/", time: "11 hours ago"}, 
	{title : "Apple Sapphire Glass Supplier, GT Advanced, Files for Bankruptcy", site: "businessinsider.co", href: "http://www.businessinsider.com/gt-advanced-files-for-bankruptcy-2014-10", time: "9 hours ago"}, 
	{title : "Attack code for 'unpatchable' USB flaw released", site: "bbc.co", href: "http://www.bbc.com/news/technology-29475566", time: "9 hours ago"}, 
	{title : "Animating Images with CSS", site: "pencilscoop.co", href: "http://www.pencilscoop.com/2014/04/animating-images-with-css-keyframes/", time: "9 hours ago"}, 
	{title : "A new type of software helps researchers decide what they should be looking for", site: "economist.co", href: "http://www.economist.com/news/science-and-technology/21621704-new-type-software-helps-researchers-decide-what-they-should-be-looking", time: "1 day ago"}, 
	{title : "Glut of postdoc researchers stirs quiet crisis in science", site: "bostonglobe.co", href: "http://www.bostonglobe.com/metro/2014/10/04/glut-postdoc-researchers-stirs-quiet-crisis-science/HWxyErx9RNIW17khv0MWTN/story.html", time: "10 hours ago"}, 
	{title : "Consider the Lobster (2004)", site: "gourmet.co", href: "http://www.gourmet.com/magazine/2000s/2004/08/consider_the_lobster?printable=true", time: "3 days ago"}, 
	{title : "Microsoft imagines an incredible transparent smart cover for Surface tablets", site: "theverge.co", href: "http://www.theverge.com/2014/10/6/6918753/microsoft-flexsense-transparent-smart-cover-research-project", time: "9 hours ago"}, 
	{title : "Haskell's Prelude is adding Foldable/Traversable", site: "yesodweb.co", href: "http://www.yesodweb.com/blog/2014/10/classy-base-prelude", time: "19 hours ago"}, 
	{title : "Dealer’s Hand: Why are so many people paying so much money for art? (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/12/02/dealers-hand", time: "1 day ago"}, 
	{title : "Maps attributed to Marco Polo sketch what looks like the coast of Alaska", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/history/did-marco-polo-discover-america-180952765/", time: "1 day ago"}, 
	{title : "Naive Bayes and Text Classification I – Introduction and Theory", site: "sebastianraschka.co", href: "http://sebastianraschka.com/Articles/2014_naive_bayes_1.html", time: "1 day ago"}, 
	{title : "Massive electrode array will do first large-scale recording of brain activity", site: "kurzweilai.ne", href: "http://www.kurzweilai.net/massive-electrode-array-system-will-do-first-large-scale-network-recording-of-brain-activity", time: "1 day ago"}, 
	{title : "Why do roots of polynomials tend to have absolute value 1?", site: "mathoverflow.ne", href: "http://mathoverflow.net/questions/182412/why-do-roots-of-polynomials-tend-to-have-absolute-value-1", time: "1 day ago"}, 
	{title : "The Power of Interoperability: Why Objects Are Inevitable (2013) [pdf]", site: "cmu.ed", href: "http://www.cs.cmu.edu/~aldrich/papers/objects-essay.pdf", time: "1 day ago"}, 
	{title : "Tech hiring, poker, and (not) playing to win. – Michael O. Church", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2014/10/06/tech-hiring-poker-and-not-playing-to-win/", time: "11 hours ago"}, 
	{title : "Hacked Screenshots Show Friend-To-Friend Payments Feature in Facebook Messenger", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/pay-with-facebook-messenger/", time: "1 day ago"}, 
	{title : "Show HN: AhhLife, a free replacement for OhLife", site: "ahhlife.co", href: "http://ahhlife.com", time: "13 hours ago"}, 
	{title : "How I deploy node apps on Linux, 2014 edition", site: "medium.co", href: "https://medium.com/@mikemaccana/how-i-deploy-node-apps-on-linux-2014-edition-309d606219ca", time: "14 hours ago"}, 
]