news20 = [
	{title : "Python REPL with syntax highlighting, autocomplete and multiline editing", site: "github.co", href: "https://github.com/jonathanslenders/python-prompt-toolkit", time: "7 days ago"}, 
	{title : "Why I took on building a better way to frame any poster, print or photo", site: "medium.co", href: "https://medium.com/@jhubball/custom-framing-is-a-racket-61461b12278d", time: "4 days ago"}, 
	{title : "Show HN: HelloBitcoin. A “Hello World” of Bitcoin, Written in Go", site: "github.co", href: "https://github.com/prettymuchbryce/hellobitcoin", time: "3 days ago"}, 
	{title : "How I hit my first $100 month on Udemy.com", site: "dennisjsmith.co", href: "http://dennisjsmith.com/how-i-hit-my-first-100-month-on-udemy-com/", time: "2 days ago"}, 
	{title : "Booking.com donates $60000 to Perl development", site: "perlfoundation.or", href: "http://news.perlfoundation.org/2014/10/bookingcom-donates-60000-to-pe.html", time: "3 days ago"}, 
	{title : "Power Up Your Team with Nonviolent Communication Principles", site: "firstround.co", href: "http://firstround.com/article/power-up-your-team-with-nonviolent-communication-principles", time: "2 days ago"}, 
	{title : "Major Updates to Firebase User Authentication", site: "firebase.co", href: "https://www.firebase.com/blog/2014-10-03-major-updates-to-firebase-user-auth.html", time: "3 days ago"}, 
	{title : "Apple allows hot code push for JS downloaded and run by WebKit", site: "meteor.co", href: "https://www.meteor.com/blog/2014/10/02/Apple-hot-code-push-mobile", time: "4 days ago"}, 
	{title : "Creating your own Heroku on EC2", site: "clearbit.c", href: "http://blog.clearbit.co/ec2-heroku?hn", time: "3 days ago"}, 
	{title : "Three months at Y Combinator: what it’s like and how to get in", site: "frontapp.co", href: "http://blog.frontapp.com/three-months-at-y-combinator-what-its-like-and-how-to-get-in/", time: "4 days ago"}, 
	{title : "Adventures in 19th-century photography", site: "mortalmuses.co", href: "http://mortalmuses.com/2014/10/03/adventures-in-19th-century-photography/", time: "3 days ago"}, 
	{title : "“How to Start a Startup” Audio Files", site: "github.co", href: "https://github.com/NathanEpstein/How_To_Start_A_Startup.git", time: "3 days ago"}, 
	{title : "Drug recommended to help cut drink dependence", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/uk-29468885", time: "3 days ago"}, 
	{title : "Geometric Madness: Implementation of computational geometry algorithms [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=fu-uW7CQkVo", time: "3 days ago"}, 
	{title : "The origins of language are not what inherited disorders seemed to suggest", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/the-family-that-couldnt-say-hippopotamus?utm_source=RSS_Feed&utm_medium=RSS&utm_campaign=RSS_Syndication", time: "3 days ago"}, 
	{title : "Study suggests that memory loss in Alzheimer's patients may be reversed", site: "neurosciencenews.co", href: "http://neurosciencenews.com/alzheimers-memory-loss-reversal-1377/", time: "4 days ago"}, 
	{title : "Data science: How mood and tempo can influence artist discovery?", site: "apassant.ne", href: "http://apassant.net/2014/10/03/how-mood-and-tempo-can-influence-artist-discovery/", time: "2 days ago"}, 
	{title : "BookKeeper: High-availability scalable distributed logging", site: "muratbuffalo.blogspot.co", href: "http://muratbuffalo.blogspot.com/2014/09/paper-summary-high-availability.html", time: "3 days ago"}, 
	{title : "Elusive Form of Evolution Seen in Spiders", site: "simonsfoundation.or", href: "http://www.simonsfoundation.org/quanta/20141002-in-social-spiders-evidence-that-groups-evolve/", time: "4 days ago"}, 
	{title : "Jank Free: Let's Make the Web Silky Smooth", site: "jankfree.or", href: "http://jankfree.org/", time: "3 days ago"}, 
	{title : "SAT solving – An alternative to brute force Bitcoin mining (2013)", site: "jheusser.github.i", href: "https://jheusser.github.io/2013/02/03/satcoin.html", time: "4 days ago"}, 
	{title : "Show HN: OrderCircle – Wholesale ordering software for small businesses", site: "ordercircle.co", href: "http://ordercircle.com", time: "5 days ago"}, 
	{title : "Cavium sponsors FreeBSD's ARMv8 implementation", site: "cavium.co", href: "http://www.cavium.com/newsevents-Cavium-Sponsor-FreeBSD-ARMv8-Based-Implementation.html", time: "4 days ago"}, 
	{title : "Scientists to ‘fast-track’ evidence linking global warming to wild weather", site: "independent.co.u", href: "http://www.independent.co.uk/environment/climate-change/scientists-to-fasttrack-evidence-linking-global-warming-to-wild-weather-9773767.html", time: "2 days ago"}, 
	{title : "Show HN: X-Windows independent C library for Linux that simulates keyboard input", site: "github.co", href: "https://github.com/solusipse/cpress", time: "2 days ago"}, 
]