news18 = [
	{title : "This is Water: a commencement speech by David Foster Wallace [pdf]", site: "purdue.ed", href: "http://web.ics.purdue.edu/~drkelly/DFWKenyonAddress2005.pdf", time: "2 days ago"}, 
	{title : "Three Years on Rikers Without Trial", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/06/law-3", time: "4 days ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29465446", time: "3 days ago"}, 
	{title : "Hackers’ Attack Cracked 10 Financial Institutions in Major Assault", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/03/hackers-attack-cracked-10-banks-in-major-assault/", time: "2 days ago"}, 
	{title : "New Map Exposes Previously Unseen Details of Seafloor", site: "ucsd.ed", href: "https://scripps.ucsd.edu/news/new-map-exposes-previously-unseen-details-seafloor", time: "3 days ago"}, 
	{title : "Place SSH users in Docker jails (or as replacement for docker-bash / dockersh)", site: "github.co", href: "https://github.com/clevcode/docker-cmd", time: "3 days ago"}, 
	{title : "How the Shinkansen bullet train made Tokyo into the monster it is today", site: "theguardian.co", href: "http://www.theguardian.com/cities/2014/sep/30/-sp-shinkansen-bullet-train-tokyo-rail-japan-50-years", time: "6 days ago"}, 
	{title : "Brain Gain: the underground world of neuroenhancing drugs (2009)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2009/04/27/brain-gain?utm_source=tny&utm_campaign=generalsocial&utm_medium=facebook&mbid=social_facebook", time: "3 days ago"}, 
	{title : "NASA Eyes Crew Deep Sleep Option for Mars Mission", site: "discovery.co", href: "http://news.discovery.com/space/nasa-eyes-crew-deep-sleep-option-for-mission-to-mars-141003.htm", time: "3 days ago"}, 
	{title : "if (osName.startsWith('windows 9'))", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22%29", time: "5 days ago"}, 
	{title : "Rocket Internet Shares Fall Below Issue Price at Debut", site: "wsj.co", href: "http://online.wsj.com/articles/rocket-internet-shares-fall-below-issue-price-at-debut-1412237549", time: "4 days ago"}, 
	{title : "Celebs whose nude photos were stolen threaten Google with $100M lawsuit", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/celebs-whose-nude-photos-were-stolen-threaten-google-with-100m-lawsuit/", time: "3 days ago"}, 
	{title : "Building a Better Build: Our Transition from Ant to SBT", site: "codeascraft.co", href: "http://codeascraft.com/2014/09/30/building-a-better-build-our-transition-from-ant-to-sbt/", time: "5 days ago"}, 
	{title : "Show HN: Make your site faster", site: "eager.i", href: "https://eager.io/app/ZYBle8qUhKFJ?n", time: "4 days ago"}, 
	{title : "Many to Many Joins with Ecto and Elixir", site: "coffeesforclosures.co", href: "http://www.coffeesforclosures.com/many-to-many-joins-with-ecto-and-elixir/", time: "3 days ago"}, 
	{title : "The FBI Says How It ‘Legally’ Pinpointed Silk Road’s Server", site: "wired.co", href: "http://www.wired.com/2014/09/the-fbi-finally-says-how-it-legally-pinpointed-silk-roads-server/", time: "31 days ago"}, 
	{title : "Thinking about quitting your job? Go tell your boss", site: "ronsho.co", href: "http://www.ronsho.com/2014/10/quitting-job-tell-boss/", time: "1 day ago"}, 
	{title : "Dominus is now open source.  Multiplayer browser game made with Meteor", site: "github.co", href: "https://github.com/dan335/dominus", time: "2 days ago"}, 
	{title : "South by Southwest’s unpaid labor problem", site: "salon.co", href: "http://www.salon.com/2014/02/26/south_by_southwest%E2%80%99s_unpaid_labor_problem_why_its_risking_a_class_action_lawsuit/", time: "1 day ago"}, 
	{title : "Watch the Navy’s Robotic Gunboats Swarm the James River", site: "medium.co", href: "https://medium.com/war-is-boring/watch-the-navys-robotic-gunboats-swarm-the-james-river-86abe382600f", time: "1 day ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage/", time: "2 days ago"}, 
	{title : "Debian Linux Wheezy OpenVPN and Squid3 How to with Transparent Proxying", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/debian-linux-wheezy-openvpn-squid3-howto-with-transparent-proxying/", time: "2 days ago"}, 
]