news21 = [
	{title : "Compromise needed on smartphone encryption", site: "washingtonpost.co", href: "http://www.washingtonpost.com/opinions/compromise-needed-on-smartphone-encryption/2014/10/03/96680bf8-4a77-11e4-891d-713f052086a0_story.html?hpid=z4", time: "2 days ago"}, 
	{title : "Beyond Light Table", site: "chris-granger.co", href: "http://www.chris-granger.com/2014/10/01/beyond-light-table/", time: "5 days ago"}, 
	{title : "Synergy (GPL'd Software KVM) switches to paid downloads", site: "synergy-project.or", href: "http://synergy-project.org/download/?paid", time: "4 days ago"}, 
	{title : "Yehuda Katz: Let's Talk about Rust", site: "confreaks.co", href: "http://confreaks.com/videos/4159-gogaruco2014-lets-talk-about-rust", time: "3 days ago"}, 
	{title : "PossibleDB", site: "github.co", href: "https://github.com/runexec/possibledb", time: "3 days ago"}, 
	{title : "Show HN: A web microframework prototype written in pure Jim Tcl", site: "github.co", href: "https://github.com/dbohdan/jimhttp", time: "3 days ago"}, 
	{title : "Systemd to the rescue", site: "achernya.co", href: "http://blog.achernya.com/2014/10/systemd-to-rescue.html", time: "3 days ago"}, 
	{title : "Apple will face $350M trial over iPod DRM", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/apple-will-face-350m-trial-over-ipod-drm/", time: "3 days ago"}, 
	{title : "Do things that scare you", site: "justinjackson.c", href: "http://justinjackson.ca/do-things-that-scare-you/", time: "2 days ago"}, 
	{title : "The trajectory of a software engineer… and where it all goes wrong", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "3 days ago"}, 
	{title : "The shodan programmer", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2013/04/22/gervais-macleod-23-the-shodan-programmer/", time: "3 days ago"}, 
	{title : "Show HN: D3js Client – Tableau Like Interface in the Browser: InfoCaptor 2.1", site: "infocaptor.co", href: "http://www.infocaptor.com", time: "3 days ago"}, 
	{title : "Can a Computer Replace Your Doctor?", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/21/sunday-review/high-tech-health-care-useful-to-a-point.html", time: "15 days ago"}, 
	{title : "Americans abroad are giving up their citizenship as banks shut down accounts", site: "theguardian.co", href: "http://www.theguardian.com/money/2014/sep/24/americans-chased-by-irs-give-up-citizenship-after-being-forced-out-of-bank-accounts", time: "11 days ago"}, 
	{title : "A Year After Death of Silk Road, Darknet Markets Are Booming", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/10/a-year-after-death-of-silk-road-darknet-markets-are-booming/380996/", time: "4 days ago"}, 
	{title : "An interactive 3D visualization of the stellar neighborhood", site: "chromeexperiments.co", href: "http://stars.chromeexperiments.com/", time: "3 days ago"}, 
	{title : "Offline-first is people-first", site: "nolanlawson.co", href: "http://nolanlawson.com/2014/10/03/offline-first-is-people-first/", time: "2 days ago"}, 
	{title : "Ham radio exams, algorithms, and scaling on the fly", site: "dobbe.u", href: "http://grant.dobbe.us/2014/10/ham-radio-exams-algorithms-and-scaling-on-the-fly/", time: "4 days ago"}, 
	{title : "Aaron's Law Is Doomed Leaving US Hacking Law 'Broken'", site: "forbes.co", href: "http://www.forbes.com/sites/thomasbrewster/2014/08/06/aarons-law-is-doomed-leaving-us-hacking-law-broken/", time: "3 days ago"}, 
	{title : "Work Habits at Apple", site: "oleb.ne", href: "http://oleb.net/blog/2014/09/work-habits-at-apple/", time: "6 days ago"}, 
	{title : "Samsung paid Microsoft 1B under the patent agreement last year", site: "recode.ne", href: "http://recode.net/2014/10/03/microsoft-says-samsung-owes-it-6-9-million-in-contract-dispute/", time: "2 days ago"}, 
	{title : "Can You Rewire a Batter's Brain with Video Games?", site: "wsj.co", href: "http://online.wsj.com/articles/baseballs-science-experiment-1411135882", time: "3 days ago"}, 
	{title : "Evaluating the security of OpenWRT, Part 3: adventures in NOEXECSTACK’land", site: "oldcomputerjunk.ne", href: "http://blog.oldcomputerjunk.net/2014/evaluating-the-security-of-openwrt-part-3-adventures-in-noexecstackland/", time: "3 days ago"}, 
	{title : "Show HN: Duckling – Open-source datetime expression parsing", site: "duckling-lib.or", href: "http://duckling-lib.org/", time: "5 days ago"}, 
	{title : "Tarana Wireless: connecting the last-mile with non-line-of-sight wireless", site: "taranawireless.co", href: "http://www.taranawireless.com", time: "4 days ago"}, 
	{title : "How does SQLite work? Part 2: disk seeks are slow don't do them", site: "jvns.c", href: "http://jvns.ca/blog/2014/10/02/how-does-sqlite-work-part-2-btrees/", time: "3 days ago"}, 
	{title : "The tourist map of laptops", site: "gnod.co", href: "http://things.gnod.com/laptops/", time: "3 days ago"}, 
]