news29 = [
	{title : "Apple Pay: An in-depth look at what's behind the secure payment system", site: "tuaw.co", href: "http://www.tuaw.com/2014/10/02/apple-pay-an-in-depth-look-at-whats-behind-the-secure-payment/", time: "4 days ago"}, 
	{title : "World’s first “solar battery” runs on light and air", site: "osu.ed", href: "http://news.osu.edu/news/2014/10/03/batteries-included-a-solar-cell-that-stores-its-own-power/", time: "3 days ago"}, 
	{title : "Looking for help improving performance of GNU Make", site: "gnu.or", href: "http://lists.gnu.org/archive/html/help-make/2014-10/msg00000.html", time: "4 days ago"}, 
	{title : "Cumulus Linux – first impressions", site: "packetlife.ne", href: "http://packetlife.net/blog/2014/oct/1/cumulus-linux-first-impressions/", time: "4 days ago"}, 
	{title : "XSA-108 Advisory", site: "xen.or", href: "http://xenbits.xen.org/xsa/advisory-108.html", time: "5 days ago"}, 
	{title : "Whats Wrong with Markdown", site: "adamhyde.ne", href: "http://www.adamhyde.net/whats-wrong-with-markdown/", time: "4 days ago"}, 
	{title : "Korea begins commercialized LTE service based on IPv6", site: "whowired.co", href: "http://www.whowired.com/news/articleView.html?idxno=404401", time: "4 days ago"}, 
	{title : "Bye Bye JavaScript Promises", site: "sriku.or", href: "http://sriku.org/blog/2014/02/11/bye-bye-js-promises/", time: "5 days ago"}, 
	{title : "Reducing Infrustration: smooth delivery with immutable infrastructure", site: "radify.i", href: "http://radify.io/blog/reducing-infrustration", time: "3 days ago"}, 
	{title : "Chickens have gotten ridiculously large since the 1950s", site: "vox.co", href: "http://www.vox.com/xpress/2014/10/2/6875031/chickens-breeding-farming-boilers-giant", time: "3 days ago"}, 
	{title : "The Researcher's Bible (1985)", site: "ed.ac.u", href: "http://homepages.inf.ed.ac.uk/bundy/how-tos/resbible.html", time: "4 days ago"}, 
	{title : "Maaxi app aims to help black cabs counter rise of Uber", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/technology-29458897", time: "3 days ago"}, 
	{title : "An Overview of General Performance Metrics of Binary Classifier Systems [pdf]", site: "sebastianraschka.co", href: "http://sebastianraschka.com/PDFs/articles/performance_metrics.pdf", time: "3 days ago"}, 
	{title : "FloppyNerd – WebGL/Three.js datacenter game", site: "floppynerd.s", href: "http://floppynerd.se", time: "3 days ago"}, 
	{title : "What if AWS goes pop, runs out of cash?", site: "channelregister.co.u", href: "http://www.channelregister.co.uk/2014/09/25/public_iaas_crisis/", time: "3 days ago"}, 
	{title : "Sudoku, Linear Optimization, and the Ten Cent Diet", site: "googleresearch.blogspot.co", href: "http://googleresearch.blogspot.com/2014/09/sudoku-linear-optimization-and-ten-cent.html", time: "6 days ago"}, 
	{title : "Dear Reddit Employees: No Desire to Move? Let’s Talk", site: "odesk.co", href: "https://www.odesk.com/blog/2014/10/dear-reddit-employees-desire-move-lets-talk/", time: "3 days ago"}, 
	{title : "Why no one wants to host the 2022 olympics", site: "yahoo.co", href: "https://sports.yahoo.com/news/why-no-one-wants-to-host-the-2022-olympics-225450509.html?soc_src=mediacontentstory", time: "4 days ago"}, 
	{title : "Why Scrum Should Basically Just Die in a Fire", site: "gilesbowkett.blogspot.co", href: "http://gilesbowkett.blogspot.com/2014/09/why-scrum-should-basically-just-die-in.html", time: "3 days ago"}, 
	{title : "A Path to Full-time Open Source", site: "mikeperham.co", href: "http://www.mikeperham.com/2014/10/01/the-path-to-full-time-open-source/", time: "5 days ago"}, 
	{title : "I can see why it would be impossible to explain quaternions without boobs", site: "twitter.co", href: "https://twitter.com/HazelMcKendrick/status/516897598608003072", time: "3 days ago"}, 
	{title : "1 Year development plan for Straight, a Bitcoin payment processor", site: "romansnitko.co", href: "http://straight.romansnitko.com/1yeardevplan.html", time: "3 days ago"}, 
	{title : "A Visual Tour of Erlang (2012) [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lHoWfeNuAN8", time: "4 days ago"}, 
	{title : "A Lua interpreter written in C#", site: "moonsharp.or", href: "http://www.moonsharp.org/", time: "4 days ago"}, 
	{title : "Disassembling an attempted Shellshock exploit", site: "iinteractive.co", href: "http://iinteractive.com/notebook/2014/10/02/shellshock.html", time: "4 days ago"}, 
	{title : "Aerodrums", site: "aerodrums.co", href: "http://aerodrums.com/aerodrums/", time: "4 days ago"}, 
	{title : "Lever (YC S12) Raises $10M to Build a Human Resources and Hiring Platform", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/02/lever/", time: "4 days ago"}, 
	{title : "Why They Called It the Manhattan Project (2007)", site: "nytimes.co", href: "http://www.nytimes.com/2007/10/30/science/30manh.html?pagewanted=all", time: "4 days ago"}, 
]