news11 = [
	{title : "I come to bury IAmCarbonatedMilk.com, not to praise it (2002)", site: "salon.co", href: "http://www.salon.com/2002/08/03/deleteddomains/", time: "1 day ago"}, 
	{title : "Welcome to the World of Regulatory Hackers", site: "1776dc.co", href: "http://1776dc.com/news/2014/10/03/welcome-to-the-world-of-regulatory-hackers/", time: "1 day ago"}, 
	{title : "Sthttpd: Tiny and fast http server with a mature codebase", site: "github.co", href: "https://github.com/rmdir/sthttpd", time: "2 days ago"}, 
	{title : "New tool helps debug Java exceptions faster", site: "excepterror.co", href: "http://www.excepterror.com", time: "2 days ago"}, 
	{title : "Two birds and a liar’s game", site: "thatgeoguy.c", href: "https://thatgeoguy.ca/blog/2014/10/04/two-birds-and-a-liars-game/", time: "2 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://paulgraham.com/before.html", time: "4 days ago"}, 
	{title : "Why the U.S. Military Is into Bee Brain Surgery", site: "nautil.u", href: "http://nautil.us/issue/11/light/why-the-us-military-is-into-bee-brain-surgery", time: "1 day ago"}, 
	{title : "Non-weak DSA key? oxymoronic, perhaps (2010)", site: "meyering.ne", href: "http://meyering.net/nuke-your-DSA-keys/", time: "1 day ago"}, 
	{title : "Daya Bay places new limit on sterile neutrinos", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/daya-bay-places-new-limit-on-sterile-neutrinos", time: "1 day ago"}, 
	{title : "Hiker Discovers an Abandoned Town Inside Tennessee's Great Smoky Mountains", site: "huffingtonpost.co", href: "http://www.huffingtonpost.com/roadtrippers/hiker-discovers-an-abando_b_5927164.html", time: "22 hours ago"}, 
	{title : "Reddit, Redditors and Self-Promotion", site: "youtube.co", href: "https://www.youtube.com/watch?v=uOtuEDgYTwI", time: "1 day ago"}, 
	{title : "A Virologist Takes You Inside the Ebola Protective Suit", site: "npr.or", href: "http://www.npr.org/blogs/goatsandsoda/2014/10/04/352804648/a-virologist-takes-you-inside-the-ebola-protective-suit", time: "1 day ago"}, 
	{title : "Bezier.js, for doing bezier curve things", site: "pomax.github.i", href: "http://pomax.github.io/bezierjs/", time: "1 day ago"}, 
	{title : "India, U.S. Agree to Joint Exploration of Mars", site: "wsj.co", href: "http://blogs.wsj.com/indiarealtime/2014/10/01/india-u-s-to-agree-to-joint-exploration-of-mars", time: "4 days ago"}, 
	{title : "The Aral Sea was once the fourth largest lake in the world. Watch it dry up", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/capital-weather-gang/wp/2014/09/30/the-aral-sea-was-once-the-fourth-largest-lake-in-the-world-watch-it-dry-up/", time: "6 days ago"}, 
	{title : "Bitcoin's Killer Apps", site: "chain.co", href: "http://blog.chain.com/post/99177371581/bitcoins-killer-apps", time: "2 days ago"}, 
	{title : "What do the top 1% of software engineers do?", site: "quora.co", href: "http://www.quora.com/What-do-the-top-1-of-software-engineers-do-that-the-other-99-do-not", time: "1 day ago"}, 
	{title : "A table of electric clay (2013) [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lvtfD_rJ2hE", time: "1 day ago"}, 
	{title : "Which Flavor of Tokenization Is Used by Apple Pay", site: "pomcor.co", href: "http://pomcor.com/2014/10/05/which-flavor-of-tokenization-is-used-by-apple-pay/", time: "1 day ago"}, 
	{title : "What Venture Capitalists will not tell you", site: "linkedin.co", href: "https://www.linkedin.com/today/post/article/20141005202543-140792-what-venture-capitalists-will-not-tell-you", time: "21 hours ago"}, 
	{title : "Nereus deep sea sub 'implodes' 10km-down", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-27374326", time: "1 day ago"}, 
	{title : "BDD anti patterns", site: "jcowie.co.u", href: "http://jcowie.co.uk/articles/BDD-Antipatterns/", time: "1 day ago"}, 
	{title : "Dirty Assembly Tricks in NES Assembly (2013)", site: "andrewkelley.m", href: "http://andrewkelley.me/post/jamulator.html#dirty-assembly-tricks", time: "3 days ago"}, 
	{title : "Online JavaScript minifier", site: "javascriptcompress.herokuapp.co", href: "http://javascriptcompress.herokuapp.com/", time: "1 day ago"}, 
	{title : "C++ and the Perils of Double-Checked Locking (2004) [pdf]", site: "aristeia.co", href: "http://www.aristeia.com/Papers/DDJ_Jul_Aug_2004_revised.pdf", time: "2 days ago"}, 
	{title : "Digital revolution has yet to fulfil its promise of productivity and better jobs", site: "economist.co", href: "http://www.economist.com/news/special-report/21621237-digital-revolution-has-yet-fulfil-its-promise-higher-productivity-and-better", time: "3 days ago"}, 
	{title : "How Exercise May Protect Against Depression", site: "well.blogs.nytimes.co", href: "http://well.blogs.nytimes.com/2014/10/01/how-exercise-may-protect-against-depression/?src=me", time: "4 days ago"}, 
	{title : "Dollar a Day", site: "dollaraday.c", href: "https://dollaraday.co/", time: "5 days ago"}, 
	{title : "NFL Bans Beats Headphones on Camera", site: "recode.ne", href: "http://recode.net/2014/10/04/nfl-bans-beats-headphones-on-camera/", time: "1 day ago"}, 
]