news6 = [
	{title : "Linux Software Releases, September 2014", site: "linuxsoftnews.wordpress.co", href: "http://linuxsoftnews.wordpress.com/2014/09/19/linux-software-release-september-2014/", time: "14 hours ago"}, 
	{title : "I want problems, not solutions", site: "medium.co", href: "https://medium.com/@MrJamesFisher/i-want-problems-not-solutions-284b8d5b651", time: "3 hours ago"}, 
	{title : "Bugzilla Zero-Day Exposes Zero-Day Bugs", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/bugzilla-zero-day-exposes-zero-day-bugs", time: "12 hours ago"}, 
	{title : "IRIS+", site: "3drobotics.co", href: "http://3drobotics.com/iris-plus/", time: "3 days ago"}, 
	{title : "Researchers see signature of “Majorana particles” inside superconducting iron", site: "scientificamerican.co", href: "http://www.scientificamerican.com/article/majorana-particle-matter-and-antimatter/", time: "3 days ago"}, 
	{title : "Bugzilla 0-day exposes 0-days", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/bugzilla-zero-day-exposes-zero-day-bugs/", time: "12 hours ago"}, 
	{title : "Spain is trying to get rid of Uber: drivers will face fines up to €18K", site: "novobrief.co", href: "http://novobrief.com/spain-trying-push-uber-country-drivers-will-face-fines-e18000/", time: "16 hours ago"}, 
	{title : "iPhone Encryption and the Return of the Crypto Wars", site: "schneier.co", href: "https://www.schneier.com/blog/archives/2014/10/iphone_encrypti_1.html", time: "7 hours ago"}, 
	{title : "Aboard Amtrak", site: "spnzr.co", href: "http://spnzr.com/aboard-amtrak", time: "3 days ago"}, 
	{title : "Ebola virus outbreak timeline", site: "abc.net.a", href: "http://www.abc.net.au/news/2014-07-31/ebola-timeline-deadliest-outbreak/5639060", time: "11 hours ago"}, 
	{title : "Stop Australia's Data Retention Bill", site: "stopthespies.or", href: "https://stopthespies.org/?live", time: "1 day ago"}, 
	{title : "OpenBSD 5.6: What will be there", site: "openbsd.or", href: "http://www.openbsd.org/56.html", time: "1 day ago"}, 
	{title : "HexLogic – Logic gates in a hexagon grid", site: "anubiann00b.github.i", href: "http://anubiann00b.github.io/HexLogic/", time: "1 day ago"}, 
	{title : "Why can't Apple decrypt your iPhone?", site: "cryptographyengineering.co", href: "http://blog.cryptographyengineering.com/2014/10/why-cant-apple-decrypt-your-iphone.html", time: "2 days ago"}, 
	{title : "Why Facebook Was So Aggressive About Migrating Users Over to Messenger", site: "fastcompany.co", href: "http://www.fastcompany.com/3036695/fast-feed/this-is-why-facebook-was-so-aggressive-about-migrating-users-over-to-messenger", time: "8 hours ago"}, 
	{title : "First womb-transplant baby born", site: "bbc.co", href: "http://www.bbc.com/news/health-29485996", time: "2 days ago"}, 
	{title : "Startups Spend with Abandon, Flush with Capital", site: "wsj.co", href: "http://online.wsj.com/articles/startups-spend-with-abandon-flush-with-capital-1412549853", time: "23 hours ago"}, 
	{title : "1041uuu Pixel Art", site: "1041uuu.tumblr.co", href: "http://1041uuu.tumblr.com/", time: "1 day ago"}, 
	{title : "[iOS8 Tutorial] Interactive Notifications with Notification Actions", site: "thinkandbuild.i", href: "http://www.thinkandbuild.it/interactive-notifications-with-notification-actions/", time: "6 hours ago"}, 
	{title : "Modern art was CIA 'weapon' in the cultural Cold War", site: "independent.co.u", href: "http://www.independent.co.uk/news/world/modern-art-was-cia-weapon-1578808.html", time: "6 hours ago"}, 
	{title : "Understanding XOR: it's just a diff", site: "biesnecker.co", href: "http://biesnecker.com/2014/10/06/swapping-variables-with-xor/", time: "8 hours ago"}, 
	{title : "Geena Davis' Two Easy Steps to Make Hollywood Less Sexist (Guest Column) (2013)", site: "hollywoodreporter.co", href: "http://www.hollywoodreporter.com/news/geena-davis-two-easy-steps-664573", time: "7 hours ago"}, 
	{title : "The Magic CmdLine and how I got it back", site: "ntua.g", href: "http://users.softlab.ece.ntua.gr/~ttsiod/bashheimer.html", time: "3 days ago"}, 
	{title : "Google+ is hurting the Internet. Europeans have the power to stop it", site: "focusontheuser.e", href: "http://focusontheuser.eu/", time: "18 hours ago"}, 
	{title : "Bruce Byfield: LibreOffice, OpenOffice, and Rumors of Unification", site: "linuxpromagazine.co", href: "http://www.linuxpromagazine.com/Online/Blogs/Off-the-Beat-Bruce-Byfield-s-Blog/LibreOffice-OpenOffice-and-rumors-of-unification", time: "7 hours ago"}, 
	{title : "The slaying of bearwhale. 30k BTC sell order being chewed through", site: "youtube.co", href: "http://www.youtube.com/watch?v=-uX_bB_4VJk", time: "15 hours ago"}, 
	{title : "How We Drove 10K Unique Visitors to a New Product in a Month", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/237922", time: "7 hours ago"}, 
]