news13 = [
	{title : "A curated list of awesome command-line frameworks, toolkits, guides and gizmos", site: "github.co", href: "https://github.com/alebcay/awesome-shell?utm_campaign=explore-email&utm_medium=email&utm_source=newsletter&utm_term=weekly", time: "6 days ago"}, 
	{title : "Tilde.club", site: "tilde.clu", href: "http://tilde.club/", time: "3 days ago"}, 
	{title : "Microservices for the Grumpy Neckbeard", site: "chrisstucchio.co", href: "http://www.chrisstucchio.com/blog/2014/microservices_for_the_grumpy_neckbeard.html", time: "41 days ago"}, 
	{title : "Nobel Prize for the brain's GPS discovery", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/health-29504761", time: "14 hours ago"}, 
	{title : "Ban travelers from Ebola-ravaged countries?", site: "washingtonpost.co", href: "http://www.washingtonpost.com/news/to-your-health/wp/2014/10/01/why-hasnt-the-u-s-closed-its-airports-to-travelers-from-ebola-ravaged-countries/", time: "5 days ago"}, 
	{title : "The Crow and the Cave Dweller", site: "medium.co", href: "https://medium.com/@aaronmentele/the-crow-and-the-cave-dweller-b230cc750694", time: "4 days ago"}, 
	{title : "The end of neighbours", site: "macleans.c", href: "http://www.macleans.ca/society/the-end-of-neighbours/", time: "56 days ago"}, 
	{title : "Bill Gates's Favorite Business Book", site: "wsj.co", href: "http://online.wsj.com/articles/bill-gatess-favorite-business-book-1405088228", time: "87 days ago"}, 
	{title : "Reddit’s crappy ultimatum to remote workers and offices", site: "shortlogic.tumblr.co", href: "http://shortlogic.tumblr.com/post/99014759324/reddits-crappy-ultimatum", time: "4 days ago"}, 
	{title : "Productising a Service Business (Part 1)", site: "theprocedurepeople.co", href: "http://www.theprocedurepeople.com/blog/2014/09/22/productising-a-service-business-part-one-separating-capabilities-from-products/", time: "14 days ago"}, 
	{title : "Stop the Spies – Campaign against mass surveillance down under (Australia)", site: "stopthespies.or", href: "https://stopthespies.org", time: "40 days ago"}, 
	{title : "Learn Lua in 15 Minutes", site: "tylerneylon.co", href: "http://tylerneylon.com/a/learn-lua/", time: "469 days ago"}, 
	{title : "PyCA's Cryptography library", site: "cryptography.i", href: "https://cryptography.io/en/latest/", time: "100 days ago"}, 
	{title : "Mysterious Mac and PC malware that jumps airgaps?", site: "arstechnica.co", href: "http://arstechnica.com/security/2013/10/meet-badbios-the-mysterious-mac-and-pc-malware-that-jumps-airgaps/", time: "340 days ago"}, 
	{title : "Startpage Search Engine: The world's most private search", site: "startpage.co", href: "https://www.startpage.com/", time: "297 days ago"}, 
	{title : "Colorsublime", site: "colorsublime.co", href: "http://colorsublime.com/", time: "366 days ago"}, 
	{title : "15 Sorting Algorithms in 6 Minutes", site: "youtube.co", href: "https://www.youtube.com/watch?v=kPRA0W1kECg", time: "311 days ago"}, 
	{title : "Jewish Nobel Laureates", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/List_of_Jewish_Nobel_laureates", time: "359 days ago"}, 
	{title : "Designing In The Open", site: "bradfrostweb.co", href: "http://bradfrostweb.com/blog/post/designing-in-the-open/", time: "378 days ago"}, 
	{title : " headache relief for programmers: regular expression generator", site: "txt2re.co", href: "http://txt2re.com", time: "910 days ago"}, 
	{title : "Education in Finland", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Education_in_Finland", time: "426 days ago"}, 
	{title : "How facebook managed growth from 30 to 200 engineers", site: "algeri-wong.co", href: "http://algeri-wong.com/yishan/engineering-management.html", time: "1478 days ago"}, 
	{title : "Hal Finney being cryopreserved now", site: "extropy.or", href: "http://lists.extropy.org/pipermail/extropy-chat/2014-August/082585.html", time: "39 days ago"}, 
	{title : "Germany’s great tuition fees U-turn", site: "timeshighereducation.co.u", href: "http://www.timeshighereducation.co.uk/features/feature-germanys-great-tuition-fees-u-turn/2011168.fullarticle", time: "5 days ago"}, 
	{title : "Machine Learning is the new Algorithms", site: "nlpers.blogspot.co", href: "http://nlpers.blogspot.com/2014/10/machine-learning-is-new-algorithms.html", time: "3 days ago"}, 
	{title : "Learning Online", site: "christinacacioppo.co", href: "http://christinacacioppo.com/blog/learning-online", time: "7 days ago"}, 
	{title : "All of IT", site: "eldelshell.co", href: "http://www.eldelshell.com/all-of-it.html", time: "1 day ago"}, 
	{title : "Linux Challenge Blackbox #1", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/linux-challenge-blackbox-1/", time: "1 day ago"}, 
	{title : "Accidental release of 45L of polio virus solution into the environment – Belgium", site: "europa.e", href: "http://www.ecdc.europa.eu/en/press/news/_layouts/forms/News_DispForm.aspx?List=8db7286c-fe2d-476c-9133-18ff4cb1b568&ID=1065", time: "3 days ago"}, 
]