news15 = [
	{title : "Shapecatcher: Draw the Unicode character you want", site: "shapecatcher.co", href: "http://shapecatcher.com", time: "4 days ago"}, 
	{title : "Analyzing AngelList Job Postings, Part 2: Salary and Equity Benchmarks", site: "codingvc.co", href: "http://codingvc.com/analyzing-angellist-job-postings-part-2-salary-and-equity-benchmarks", time: "3 days ago"}, 
	{title : "An Analysis of Shell Shock Malware", site: "erenyagdiran.github.i", href: "http://erenyagdiran.github.io/An-Analysis-of-Shell-shock-malware/", time: "2 days ago"}, 
	{title : "Sourcery (YC W13) Raises $2.5M to Connect Kitchens and Local Food Suppliers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/sourcery-raises-2-5m-to-connect-kitchens-and-local-food-suppliers/", time: "3 days ago"}, 
	{title : "Windows 95 on Android Wear [video]", site: "youtube.co", href: "http://youtube.com/watch?v=GZx-LJH5J_I", time: "1 day ago"}, 
	{title : "Forty Portraits in Forty Years", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/03/magazine/01-brown-sisters-forty-years.html", time: "2 days ago"}, 
	{title : "Google Project Zero: More Mac OS X and iPhone Sandbox Escapes", site: "googleprojectzero.blogspot.co", href: "http://googleprojectzero.blogspot.com/2014/10/more-mac-os-x-and-iphone-sandbox.html", time: "4 days ago"}, 
	{title : "Lever (YC S12) raises $10M to make hiring awesome", site: "lever.c", href: "https://blog.lever.co/the-next-chapter/", time: "4 days ago"}, 
	{title : "Reddit/Hacker News clone using the MEAN stack", site: "thinkster.i", href: "https://thinkster.io/angulartutorial/mean-stack-tutorial/", time: "4 days ago"}, 
	{title : "Show HN: GifBook – Animated GIFs as paper flip books", site: "gifbook.i", href: "https://gifbook.io/?hn", time: "3 days ago"}, 
	{title : "Great books about mathematics", site: "kjro.s", href: "http://wp.kjro.se/2013/12/27/5-insanely-great-books-about-mathematics-you-should-read/", time: "283 days ago"}, 
	{title : "iPhone 6 prototype turns up on eBay", site: "ebay.co", href: "http://www.ebay.com/itm/Brand-New-Rare-Apple-iPhone-6-Prototype-64gb-/171483815097?", time: "20 hours ago"}, 
	{title : "Why women leave tech: It's the culture", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture", time: "1 day ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341", time: "1 day ago"}, 
	{title : "Saeed Malekpour, programmer and political prisoner in Iran", site: "github.co", href: "https://github.com/saeedmalekpour", time: "2 days ago"}, 
	{title : "TXR: A Programming Language for Convenient Data Munging", site: "nongnu.or", href: "http://www.nongnu.org/txr", time: "2 days ago"}, 
	{title : "We Got Accepted into Techstars and Turned Them Down", site: "talkroute.co", href: "http://talkroute.com/got-accepted-into-techstars-turned-it-down/", time: "4 days ago"}, 
	{title : "Why is 0x00400000 the default base address for an executable?", site: "msdn.co", href: "http://blogs.msdn.com/b/oldnewthing/archive/2014/10/03/10562176.aspx", time: "3 days ago"}, 
	{title : "'God View': Uber Allegedly Stalked Users for Party-Goers' Viewing Pleasure", site: "forbes.co", href: "http://www.forbes.com/sites/kashmirhill/2014/10/03/god-view-uber-allegedly-stalked-users-for-party-goers-viewing-pleasure/", time: "1 day ago"}, 
	{title : "Why Coconuts Could Be the Hydrogen Storage Material of the Future", site: "technologyreview.co", href: "http://www.technologyreview.com/view/531416/why-coconuts-could-be-the-hydrogen-storage-material-of-the-future/", time: "3 days ago"}, 
	{title : "Show HN: JuliusJS – Speech recognition in JavaScript", site: "github.co", href: "https://github.com/zzmp/juliusjs", time: "3 days ago"}, 
	{title : "How the world’s health organizations failed to stop the Ebola disaster", site: "washingtonpost.co", href: "http://www.washingtonpost.com/sf/national/2014/10/04/how-ebola-sped-out-of-control/", time: "1 day ago"}, 
	{title : "The history of our world in 18 minutes", site: "ted.co", href: "https://www.ted.com/talks/david_christian_big_history", time: "1 day ago"}, 
	{title : "Ello: Be ready to say goodbye", site: "zdnet.co", href: "http://www.zdnet.com/ello-be-ready-to-say-goodbye-7000034333/", time: "1 day ago"}, 
	{title : "Pangrams on the web", site: "farside.org.u", href: "https://www.farside.org.uk/201410/pangrams_on_the_web", time: "3 days ago"}, 
	{title : "Tobacco plant may be key to Ebola drugs", site: "cnn.co", href: "http://www.cnn.com/2014/10/03/health/ebola-tobacco-plant/", time: "3 days ago"}, 
]