news5 = [
	{title : "Make your smartwatch even less useful by installing Windows 95", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/make-your-smartwatch-even-less-useful-by-installing-windows-95/", time: "5 hours ago"}, 
	{title : "Show HN: Generate interactive heatmaps from your Google Location History data", site: "theopolisme.github.i", href: "http://theopolisme.github.io/location-history-visualizer/", time: "1 day ago"}, 
	{title : "'You Have the Right to Remain Silent.' or Do You?", site: "npr.or", href: "http://www.npr.org/2014/10/05/353893046/you-have-the-right-to-remain-silent-or-do-you?utm_campaign=storyshare&utm_source=facebook.com&utm_medium=social", time: "12 hours ago"}, 
	{title : "Car sharing: A cheaper alternative to owning a car in Japan", site: "japantimes.co.j", href: "http://www.japantimes.co.jp/news/2014/10/06/reference/car-sharing-cheaper-alternative-owning-car-city/", time: "12 hours ago"}, 
	{title : "I'm Agile but My Contract Isn't", site: "stridenyc.co", href: "http://www.stridenyc.com/blog/2014/10/3/im-agile-but-my-contract-isnt-how-to-align-contracts-with-agile-software-development-teams", time: "11 hours ago"}, 
	{title : "John Oliver Explores the Sad Reality of Civil Forfeitures – Rolling Stone", site: "rollingstone.co", href: "http://www.rollingstone.com/tv/videos/john-oliver-amplifies-the-absurdity-of-civil-forfeitures-20141006", time: "7 hours ago"}, 
	{title : "Terrestriality", site: "theappendix.ne", href: "http://theappendix.net/issues/2014/4/terrestriality", time: "1 day ago"}, 
	{title : "Show HN: Qbox Releases QES Elasticsearch Connector for Magento", site: "qbox.i", href: "http://blog.qbox.io/qbox-releases-qes-elasticsearch-connector-for-magento", time: "5 hours ago"}, 
	{title : "How con artists trick your mind", site: "bbc.co", href: "http://www.bbc.com/future/story/20141003-the-mind-tricks-of-scammers", time: "2 days ago"}, 
	{title : "Latest Ebola Statistics", site: "ebolastats.inf", href: "http://ebolastats.info/", time: "13 hours ago"}, 
	{title : "Krugman on Bitcoin", site: "nytimes.co", href: "http://mobile.nytimes.com/blogs/krugman/2014/10/04/the-long-cryptocon/", time: "18 hours ago"}, 
	{title : "Managing Issues and Pull Requests Across Repositories", site: "github.co", href: "https://github.com/blog/1901-managing-issues-and-pull-requests-across-repositories", time: "5 hours ago"}, 
	{title : "The Man Who Smuggles Traders Joe’s into Canada", site: "priceonomics.co", href: "http://priceonomics.com/the-man-who-smuggles-traders-joes-into-canada/", time: "3 days ago"}, 
	{title : "Adobe and Microsoft Partner at Adobe MAX", site: "youtube.co", href: "http://www.youtube.com/watch?v=tR5JPw4HiTY&feature=youtu.be", time: "4 hours ago"}, 
	{title : "Ebola in Spain: Nurse 'infected in Madrid'", site: "bbc.co", href: "http://www.bbc.com/news/world-europe-29514920", time: "8 hours ago"}, 
	{title : "Breaking the Waves", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/02/10/breaking-the-waves-2", time: "1 day ago"}, 
	{title : "NASA may get astronauts to Mars using deep sleep and intravenous drips", site: "geek.co", href: "http://www.geek.com/science/nasa-may-get-astronauts-to-mars-using-deep-sleep-and-intravenous-drips-1606052/", time: "5 hours ago"}, 
	{title : "New Class of Vulnerability in Perl Web Applications", site: "gerv.ne", href: "http://blog.gerv.net/2014/10/new-class-of-vulnerability-in-perl-web-applications/", time: "5 hours ago"}, 
	{title : "Ebola, Beyond the Headlines", site: "gatesnotes.co", href: "http://www.gatesnotes.com/Health/Ebola-Beyond-the-Headlines", time: "9 hours ago"}, 
	{title : "Programming and Computer Science: an imminent divorce?", site: "txus.i", href: "http://blog.txus.io/2014/10/programming-and-computer-science-an-imminent-divorce/", time: "4 hours ago"}, 
	{title : "Building an iOS8 Today widget – the good/bad/ugly", site: "medium.co", href: "https://medium.com/ios-os-x-development/learnings-from-building-a-today-view-extension-in-ios-8-710d5f481594", time: "6 hours ago"}, 
	{title : "Building a testable Go web app", site: "sourcegraph.co", href: "https://sourcegraph.com/blog/building-a-testable-webapp", time: "1 day ago"}, 
	{title : "Why Ello Needs Craig Newmark(?)", site: "dentthefuture.co", href: "http://blog.dentthefuture.com/2014/why-ello-needs-craig-newmark/", time: "5 hours ago"}, 
	{title : "Kurt Vonnegut, the Art of Fiction No. 64 (1977)", site: "theparisreview.or", href: "http://www.theparisreview.org/interviews/3605/the-art-of-fiction-no-64-kurt-vonnegut", time: "1 day ago"}, 
	{title : "Stress Gives You Daughters, Sons Make You Liberal", site: "nautil.u", href: "http://nautil.us/issue/13/symmetry/stress-gives-you-daughters-sons-make-you-liberal", time: "10 hours ago"}, 
	{title : "A Warning to the Tech Community on Abusive Journalists", site: "zdziarski.co", href: "http://www.zdziarski.com/blog/?p=3958", time: "10 hours ago"}, 
]