news12 = [
	{title : "The Quest to Build an Elevator into Space", site: "gizmodo.co", href: "http://gizmodo.com/the-quest-to-build-an-elevator-to-space-1638192427", time: "3 days ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977", time: "3 days ago"}, 
	{title : "Early Digital Research CP/M Source Code", site: "computerhistory.or", href: "http://www.computerhistory.org/_static/atchm/early-digital-research-cpm-source-code/", time: "5 days ago"}, 
	{title : "How feminism helped me solve one of file systems’ oldest conundrums", site: "valerieaurora.or", href: "http://blog.valerieaurora.org/2014/10/03/operating-systems-war-story-how-feminism-helped-me-solve-one-of-file-systems-oldest-conundrums/", time: "22 hours ago"}, 
	{title : "Windows 95 on Android Smartwatch", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6910791/least-useful-hack-ever-puts-windows-95-on-your-smartwatch", time: "1 day ago"}, 
	{title : "AngularJS Tutorial: a comprehensive 10,000 word guide", site: "airpair.co", href: "http://www.airpair.com/angularjs", time: "3 days ago"}, 
	{title : "In 1976 I discovered Ebola, now I fear an unimaginable tragedy", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/04/ebola-zaire-peter-piot-outbreak", time: "1 day ago"}, 
	{title : "Biggest patent win ever? Microsoft's billion dollar a year Samsung deal", site: "zdnet.co", href: "http://www.zdnet.com/biggest-patent-win-ever-microsofts-billion-dollar-a-year-samsung-deal-7000034353/", time: "1 day ago"}, 
	{title : "How Would the FDA Respond If We Had a Drug to Cure Aging?", site: "kolber.typepad.co", href: "http://kolber.typepad.com/ethics_law_blog/2014/09/how-would-the-fda-respond-if-we-had-a-drug-to-cure-aging-guest-post-by-kira-peikoff.html", time: "21 hours ago"}, 
	{title : "U.S. Navy Tests Robot Boat Swarm to Overwhelm Enemies", site: "ieee.or", href: "http://spectrum.ieee.org/automaton/robotics/military-robots/us-navy-robot-boat-swarm", time: "1 day ago"}, 
	{title : "HP to split into two companies", site: "cnn.co", href: "http://money.cnn.com/2014/10/05/technology/hp-restructuring-split/index.html", time: "1 day ago"}, 
	{title : "After raising $50M, Reddit forces all remote workers to relocate to SF", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/01/after-raising-50m-reddit-forces-remote-workers-to-relocate-to-sf-or-get-fired/", time: "5 days ago"}, 
	{title : "Sex for the pleasure of women: The amazing heroes behind inventing the Pill", site: "salon.co", href: "http://www.salon.com/2014/10/04/sex_for_the_pleasure_of_women_the_amazing_heroes_behind_the_invention_of_the_pill/", time: "1 day ago"}, 
	{title : "The Bézier Game", site: "method.a", href: "http://bezier.method.ac/", time: "21 days ago"}, 
	{title : "Dispatch from Worldcon", site: "nplusonemag.co", href: "https://nplusonemag.com/online-only/online-only/dispatch-from-worldcon/", time: "5 days ago"}, 
	{title : "Introducing the Gartner Programming Language Index for 2014", site: "gartner.co", href: "http://blogs.gartner.com/mark_driver/2014/10/02/gartner-programming-language-index-for-2014/", time: "2 days ago"}, 
	{title : "Hiring a Startup Lawyer", site: "adlervermillion.co", href: "http://adlervermillion.com/tech-law-link-list-hiring-lawyers/", time: "20 days ago"}, 
	{title : "THANKS HN! How Hacker News + Product Hunt Fueled 300,000 Views in 30 Days", site: "medium.co", href: "https://medium.com/@jadlimcaco/an-overnight-success-660739c2a7e9", time: "3 days ago"}, 
	{title : "Show HN: Furtive – A forward-thinking, CSS micro-framework", site: "furtive.c", href: "http://furtive.co/", time: "6 days ago"}, 
	{title : "Lennart Poettering on the state of open source communities", site: "plus.google.co", href: "https://plus.google.com/+LennartPoetteringTheOneAndOnly/posts/J2TZrTvu7vd", time: "17 hours ago"}, 
	{title : "Three Words Entrepreneurs (and VC’s) Should Take to Heart", site: "bothsidesofthetable.co", href: "http://www.bothsidesofthetable.com/2014/10/05/three-words-every-entrepreneur-and-vc-should-take-to-heart/", time: "1 day ago"}, 
	{title : "What I Learned from My Time in Prison", site: "dailystormer.co", href: "http://www.dailystormer.com/what-i-learned-from-my-time-in-prison/", time: "4 days ago"}, 
	{title : "Monit issues DMCA takedown against Mike Perham's open source Inspeqtor project", site: "github.co", href: "https://github.com/github/dmca/commit/e8e7a27dd17ad6fe8d53fbb8f6084b560b2d3a29", time: "9 hours ago"}, 
	{title : "JSON Web Tokens", site: "jwt.i", href: "http://jwt.io/?", time: "29 days ago"}, 
	{title : "Toshi – An Open Source Bitcoin Node for Developers", site: "coinbase.co", href: "http://blog.coinbase.com/post/97671295752/introducing-toshi-an-open-source-bitcoin-node-for", time: "20 days ago"}, 
	{title : "Is Overleaf the Wordpress for LaTeX?", site: "writelatex.co", href: "https://www.writelatex.com/overleaf", time: "4 days ago"}, 
	{title : "The Eudyptula Challenge", site: "eudyptula-challenge.or", href: "http://eudyptula-challenge.org", time: "13 hours ago"}, 
	{title : "How do project owners use pull requests on GitHub?", site: "gousios.g", href: "http://www.gousios.gr/blog/How-do-project-owners-use-pull-requests-on-Github/", time: "3 days ago"}, 
	{title : "Ello, goodbye", site: "aralbalkan.co", href: "https://aralbalkan.com/notes/ello-goodbye/", time: "10 days ago"}, 
]