news3 = [
	{title : "Tech World Vexed by Slow Progress on Batteries", site: "wsj.co", href: "http://online.wsj.com/news/article_email/tech-world-vexed-by-slow-progress-on-batteries-1412552377-lMyQjAxMTE0MjAzNjUwNjY3Wj", time: "13 hours ago"}, 
	{title : "An exchange on capital, debt, and the future", site: "thebaffler.co", href: "http://www.thebaffler.com/odds-and-ends/soak-the-rich", time: "5 hours ago"}, 
	{title : "Teaching CS in K12 – Using easy assignments to introduce deep concepts", site: "cestlaz.github.i", href: "http://cestlaz.github.io/2014/10/05/easy-assignments.html#.VDLZUPdw474.hackernews", time: "7 hours ago"}, 
	{title : "Unintentionally in YC", site: "medium.co", href: "https://medium.com/@andrewjiang/unintentionally-in-yc-9dd0ccbaeb44", time: "6 hours ago"}, 
	{title : "AngularJS Tutorial: A Comprehensive 10,000 Word Guide", site: "airpair.co", href: "http://www.airpair.com/angularjs?ti=#MxkrVCfYlQfeQLBy.99", time: "8 hours ago"}, 
	{title : "PHP Framework CodeIgniter Has a New Home", site: "ellislab.co", href: "https://ellislab.com/blog/entry/your-favorite-php-framework-codeigniter-has-a-new-home", time: "5 hours ago"}, 
	{title : "Does It Help to Know History?", site: "newyorker.co", href: "http://www.newyorker.com/news/daily-comment/help-know-history", time: "3 hours ago"}, 
	{title : "Show HN: Exist – understand your life through data", site: "exist.i", href: "https://exist.io/", time: "3 hours ago"}, 
	{title : "Microsoft’s ‘RoomAlive’ transforms any room into a giant Xbox game", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6912979/microsoft-roomalive-research-projector-system", time: "1 day ago"}, 
	{title : "Roll your own autocomplete solution using Tries (2012)", site: "vivekn.co", href: "http://vivekn.com/blog/2012/02/25/roll-your-own-autocomplete-solution-using-tries/", time: "3 hours ago"}, 
	{title : "Magnetic items in an MRI machine [video]", site: "iflscience.co", href: "http://www.iflscience.com/health-and-medicine/how-dangerous-are-magnetic-items-near-mri-machine", time: "48 minutes ago"}, 
	{title : "Show HN: Tempmail.de – Temporary, disposable, anonymous email address", site: "tempmail.d", href: "http://tempmail.de", time: "18 hours ago"}, 
	{title : "Open Explorer: Follow expeditions around the world", site: "openexplorer.co", href: "https://openexplorer.com", time: "10 hours ago"}, 
	{title : "GNU Bash commit messages", site: "gnu.or", href: "http://git.savannah.gnu.org/cgit/bash.git/log/", time: "2 hours ago"}, 
	{title : "Quantitative Analysis of Pooled Ridesharing", site: "telegraphresearch.co", href: "http://www.telegraphresearch.com/ridesharing/", time: "7 hours ago"}, 
	{title : "How does a computer chip work?", site: "quora.co", href: "http://www.quora.com/Computer-Science/How-does-a-computer-chip-work/answer/Subhasis-Das?share=1", time: "1 day ago"}, 
	{title : "The Archipelago of Weird (2005)", site: "siderea.livejournal.co", href: "http://siderea.livejournal.com/201206.html", time: "7 hours ago"}, 
	{title : "Hundreds of Devices Hidden Inside New York City Phone Booths", site: "buzzfeed.co", href: "http://www.buzzfeed.com/josephbernstein/exclusive-hundreds-of-devices-hidden-inside-new-york-city-ph", time: "18 hours ago"}, 
	{title : "Venture capital and the great big Silicon Valley asshole game", site: "pando.co", href: "http://pando.com/2014/10/06/venture-capital-and-the-great-big-silicon-valley-asshole-game/", time: "1 hour ago"}, 
	{title : "Help improve gcc", site: "gnu.or", href: "https://gcc.gnu.org/ml/gcc/2014-10/msg00040.html", time: "7 hours ago"}, 
	{title : "YouTube's joke of a fair-use appeal process", site: "jwz.or", href: "http://www.jwz.org/blog/2014/10/youtubes-joke-of-a-fair-use-appeal-process/", time: "5 hours ago"}, 
	{title : "Glut of postdoc researchers stirs quiet crisis in science", site: "bostonglobe.co", href: "https://www.bostonglobe.com/metro/2014/10/04/glut-postdoc-researchers-stirs-quiet-crisis-science/HWxyErx9RNIW17khv0MWTN/story.html", time: "1 day ago"}, 
	{title : "Monit's DMCA takedown notice for Inspeqtor", site: "github.co", href: "https://github.com/github/dmca/blob/master/2014-10-05-tildeslash.md", time: "9 hours ago"}, 
	{title : "Firechat and nearby communication", site: "breizh-entropy.or", href: "http://breizh-entropy.org/~nameless/random/posts/firechat_and_nearby_communication/", time: "1 day ago"}, 
	{title : "Zen Buddhism and Alan Watts", site: "aeon.c", href: "http://aeon.co/magazine/philosophy/tim-lott-zen-buddhism-alan-watts/", time: "1 day ago"}, 
	{title : "Autothysis SSD drives impede unauthorised access", site: "securedrives.co.u", href: "http://securedrives.co.uk/index.php?route=product/category&path=73_75", time: "1 day ago"}, 
	{title : "Shielding Applications from an Untrusted Cloud with Haven [pdf]", site: "usenix.or", href: "https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-baumann.pdf", time: "6 hours ago"}, 
	{title : "How the Z80's registers are implemented", site: "righto.co", href: "http://www.righto.com/2014/10/how-z80s-registers-are-implemented-down.html", time: "1 day ago"}, 
]