news8 = [
	{title : "Show HN: Turning a classic gamebook into interactive fiction", site: "github.co", href: "https://github.com/cjauvin/gamebook.js", time: "1 day ago"}, 
	{title : "Isomorphic JavaScript", site: "isomorphic.ne", href: "http://isomorphic.net/", time: "16 hours ago"}, 
	{title : "Visual Revolution of the Vanishing of Ethan Carter", site: "theastronauts.co", href: "http://www.theastronauts.com/2014/03/visual-revolution-vanishing-ethan-carter/", time: "6 days ago"}, 
	{title : "A survey of the current state of Golang ORMs", site: "go-steel-programmers.or", href: "http://present.go-steel-programmers.org/talk-review-orms/gsp-go-orms.slide#1", time: "1 day ago"}, 
	{title : "Hacker's Guide to Setting Up Your Mac", site: "lapwinglabs.co", href: "http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac", time: "4 days ago"}, 
	{title : "ScoutBot: Automated network scanning, environment assessments, and more", site: "lansec.ne", href: "http://lansec.net/project/scoutbot/", time: "1 day ago"}, 
	{title : "Somewhere in the Philippines, there are roads named after countries", site: "nicluo.co", href: "http://nicluo.com/somewhere-in-the-philippines-theres-roads-of-every-country-in-the-world/", time: "23 hours ago"}, 
	{title : "Learn Swift for Free (expires Oct. 31)", site: "udemy.co", href: "https://www.udemy.com/learn-swift/?couponCode=LEARN_SWIFT_HACKERNEWS", time: "13 hours ago"}, 
	{title : "Cool-retro-term: A terminal emulator which mimics the old cathode display", site: "github.co", href: "https://github.com/Swordfish90/cool-retro-term", time: "4 days ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd", time: "4 days ago"}, 
	{title : "This is the last photo we’ll ever run of the NYSE trading floor", site: "marketwatch.co", href: "http://www.marketwatch.com/story/this-is-the-last-photo-well-ever-run-of-the-nyse-trading-floor-2014-10-01", time: "14 hours ago"}, 
	{title : "Saving Cyla", site: "theglobeandmail.co", href: "http://www.theglobeandmail.com/life/health-and-fitness/health/video-saving-cyla-inside-the-operating-room-as-a-young-ontario-woman-undergoes-brain-surgery-while-awake/article20895176/", time: "1 day ago"}, 
	{title : "Shen Under BSD", site: "shenlanguage.or", href: "http://www.shenlanguage.org/shenbsd.htm", time: "1 day ago"}, 
	{title : "New web privacy system could revolutionise the safety of surfing", site: "ucl.ac.u", href: "http://www.ucl.ac.uk/news/news-articles/1014/061014_COWL", time: "16 hours ago"}, 
	{title : "Viomba: A/B test your website and measure your design with eye tracking", site: "viomba.co", href: "http://www.viomba.com", time: "1 day ago"}, 
	{title : "The Potential Power of Networked Community Building", site: "thefnf.or", href: "https://lists.thefnf.org/pipermail/discuss/2014-October/001932.html", time: "1 day ago"}, 
	{title : "What the Hell Was Megadeth, Arizona?", site: "medium.co", href: "https://medium.com/cuepoint/what-the-hell-was-megadeth-arizona-3519a751149d", time: "12 hours ago"}, 
	{title : "Oxygen absorbing material may allow us to breathe underwater", site: "gizmag.co", href: "http://www.gizmag.com/crystalline-material-absorb-oxygen-denmark/34064/", time: "12 hours ago"}, 
	{title : "Show HN: Mojulo – Pixelated Math Rendering Sandbox Toy", site: "maxbittker.github.i", href: "http://maxbittker.github.io/Mojulo/", time: "2 days ago"}, 
	{title : "Show HN: PixelTool – a tool for overlaying designs for pixel perfect front-end", site: "spencer-walden.co", href: "http://www.spencer-walden.com/pixeltool/", time: "1 day ago"}, 
	{title : "To Reach China, LinkedIn Plays by Local Rules", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/technology/to-reach-china-linkedin-plays-by-local-rules.html", time: "21 hours ago"}, 
	{title : "Engineering management lessons", site: "defmacro.or", href: "http://www.defmacro.org/2014/10/03/engman.html", time: "3 days ago"}, 
	{title : "Untangling how cables coil", site: "mit.ed", href: "http://newsoffice.mit.edu/2014/predict-cable-coiling-1003", time: "1 day ago"}, 
	{title : "As Many as 5K .Com’s Taken Away by Sealed Court Order by Verisign", site: "thedomains.co", href: "http://www.thedomains.com/2014/10/02/as-many-as-5k-coms-taken-away-by-sealed-court-order-by-verisign-including-some-of-mine/", time: "3 days ago"}, 
	{title : "How to change or build your career", site: "sivers.or", href: "http://sivers.org/career", time: "1 day ago"}, 
	{title : "My Approach to Life Logging. Meet Nomie", site: "icorbin.co", href: "http://blog.icorbin.com/my-take-on-life-tracking-meet-nomie/", time: "13 hours ago"}, 
	{title : "Some ideas for native Bitcoin apps", site: "cdixon.or", href: "http://cdixon.org/2014/10/04/some-ideas-for-native-bitcoin-apps/", time: "2 days ago"}, 
	{title : "English Proficiency Index", site: "ef.co", href: "http://www.ef.com/epi", time: "1 day ago"}, 
]