news2 = [
	{title : "Reverse engineering the binary data format for Star Wars: Yoda Stories", site: "zachtronics.co", href: "http://www.zachtronics.com/yoda-stories/", time: "52 minutes ago"}, 
	{title : "The 2014 Nobel Prize in Physiology or Medicine", site: "nobelprize.or", href: "http://www.nobelprize.org/nobel_prizes/medicine/laureates/2014/press.html", time: "15 hours ago"}, 
	{title : "How mozzarella became the perfect pizza cheese", site: "bbc.co", href: "http://www.bbc.com/future/story/20141006-the-secrets-of-perfect-pizza", time: "4 hours ago"}, 
	{title : "Hooknook: Like GitHub Pages for Your Server", site: "washington.ed", href: "http://homes.cs.washington.edu/~asampson/blog/hooknook.html", time: "8 hours ago"}, 
	{title : "A Scalability Roadmap", site: "bitcoinfoundation.or", href: "https://bitcoinfoundation.org/2014/10/a-scalability-roadmap/", time: "6 hours ago"}, 
	{title : "Stamplay: IFTTT for developers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/06/stamplay-is-ifttt-for-back-end-development/", time: "17 hours ago"}, 
	{title : "Boiling Sous-Vide Eggs Using Clojure's Transducers", site: "eikeland.s", href: "http://blog.eikeland.se/2014/10/06/pid-transducer/", time: "12 hours ago"}, 
	{title : "Unfinished game – learn by practice", site: "github.co", href: "https://github.com/rezoner/unfinished-asteroids", time: "20 hours ago"}, 
	{title : "EBay Opens Fine Art Live-Auction Sites, for Second Time", site: "bits.blogs.nytimes.co", href: "http://bits.blogs.nytimes.com/2014/10/06/ebay-opens-fine-art-live-auction-sites-for-second-time/", time: "1 hour ago"}, 
	{title : "Missing Maps: a human genome project for cities", site: "theguardian.co", href: "http://www.theguardian.com/cities/2014/oct/06/missing-maps-human-genome-project-unmapped-cities", time: "7 hours ago"}, 
	{title : "Show HN: GetMetrics – Metrics and Notifications for Stripe", site: "getmetrics.i", href: "https://getmetrics.io", time: "9 hours ago"}, 
	{title : "Building packages at scale", site: "perkin.org.u", href: "http://www.perkin.org.uk/posts/building-packages-at-scale.html", time: "12 hours ago"}, 
	{title : "FlexSense: A Transparent Self-Sensing Deformable Surface [video]", site: "microsoft.co", href: "http://research.microsoft.com/apps/video/default.aspx?id=230399", time: "7 hours ago"}, 
	{title : "Peru: The Future of Gastronomy", site: "cntraveler.co", href: "http://www.cntraveler.com/stories/2014-09-23/peru-the-future-of-gastronomy", time: "13 hours ago"}, 
	{title : "Live Coding in VR with Oculus Rift, Firefox WebVR, JavaScript, Three.js [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=db-7J5OaSag", time: "1 day ago"}, 
	{title : "Tango: Distributed Data Structures Over a Shared Log", site: "muratbuffalo.blogspot.co", href: "http://muratbuffalo.blogspot.com/2014/09/paper-summary-tango-distributed-data.html", time: "9 hours ago"}, 
	{title : "The Bacon Boom Was Not an Accident", site: "businessweek.co", href: "http://www.businessweek.com/articles/2014-10-06/bacon-why-americas-favorite-food-mania-happened?google_editors_picks=true", time: "9 hours ago"}, 
	{title : "Avoiding the Top Security Flaws", site: "ieee.or", href: "http://cybersecurity.ieee.org/center-for-secure-design/avoiding-the-top-10-security-flaws.html", time: "8 hours ago"}, 
	{title : "Graph of the routed autonomous systems", site: "polzunov.co", href: "http://as-graph.polzunov.com/", time: "10 hours ago"}, 
	{title : "Procedural colors for video games", site: "noctua-software.co", href: "http://blog.noctua-software.com/procedural-colors-for-game.html", time: "14 hours ago"}, 
	{title : "Clocks Make Workers Less Creative and Less Happy", site: "theatlantic.co", href: "http://www.theatlantic.com/business/archive/2014/10/clocks-make-workers-less-creative/381064/", time: "5 hours ago"}, 
	{title : "Fast Resettable Flag Vector", site: "upcoder.co", href: "http://upcoder.com/9/fast-resettable-flag-vector/", time: "12 hours ago"}, 
	{title : "Revisiting Android disk encryption", site: "nelenkov.blogspot.co", href: "http://nelenkov.blogspot.com/2014/10/revisiting-android-disk-encryption.html", time: "17 hours ago"}, 
	{title : "HFT in my backyard – More on piracy", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/06/hft-in-my-backyard-more-on-piracy", time: "10 hours ago"}, 
	{title : "A look at the Apple ‘Skankphone’, built before the original iPhone release", site: "thenextweb.co", href: "http://thenextweb.com/apple/2014/10/05/apple-skankphone-built-original-iphone-release/", time: "22 hours ago"}, 
	{title : "Emotional Renovations: How your brain twists together emotion and place", site: "nautil.u", href: "http://nautil.us/issue/8/home/emotional-renovations", time: "5 hours ago"}, 
	{title : "Battle Over Use of Word ‘How’ as Trademark", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/business/chobani-and-dov-seidman-wrestle-over-use-of-how-trademark.html?partner=rss&emc=rss&smid=tw-nytimes&_r=1", time: "13 hours ago"}, 
	{title : "PayPal's Incentive Problem", site: "stratechery.co", href: "http://stratechery.com/2014/paypals-incentive-problem/", time: "7 hours ago"}, 
	{title : "Tesla wants to sell you a used Model S", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/06/tesla-wants-to-sell-you-a-used-model-s/", time: "5 hours ago"}, 
]