news26 = [
	{title : "CDN53", site: "zorinaq.co", href: "http://blog.zorinaq.com/?e=77", time: "3 days ago"}, 
	{title : "How I Accidentally Became an Android Developer", site: "medium.co", href: "https://medium.com/@redman/how-i-accidentally-became-an-android-developer-my-journey-from-ios-to-android-52438ca4fd0", time: "3 days ago"}, 
	{title : "Adaptive Path: Where We’re Going Next", site: "adaptivepath.co", href: "http://www.adaptivepath.com/ideas/adaptive-path-where-were-going-next/", time: "4 days ago"}, 
	{title : "‘The Innovators’ by Walter Isaacson: How Women Shaped Technology", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/fashion/the-innovators-by-walter-isaacson-how-women-shaped-technology.html?_r=1", time: "4 days ago"}, 
	{title : "Clojure from the ground up: debugging", site: "aphyr.co", href: "http://aphyr.com/posts/319-clojure-from-the-ground-up-debugging", time: "4 days ago"}, 
	{title : "The Secret to Getting Top-Secret Secrets", site: "medium.co", href: "https://medium.com/matter/the-secret-to-getting-top-secret-secrets-1f693eaf609a", time: "6 days ago"}, 
	{title : "Write your own Virtual CPU in C++", site: "megalomaniacbore.blogspot.co", href: "http://megalomaniacbore.blogspot.com/2014/04/virtual-cpu-in-c-4001-cpu.html", time: "9 days ago"}, 
	{title : "Cops kill Georgia grandpa in no-knock raid triggered by burglary suspect’s tip", site: "rawstory.co", href: "http://www.rawstory.com/rs/2014/10/cops-kill-georgia-grandpa-in-no-knock-raid-triggered-by-burglary-suspects-tip", time: "3 days ago"}, 
	{title : "Cognitive Artificial Intelligence: The MicroPsi Project", site: "micropsi.co", href: "http://www.micropsi.com/", time: "10 days ago"}, 
	{title : "Show HN: Pagerbot, a chat bot for managing PagerDuty on-call schedules", site: "stripe.co", href: "https://stripe.com/blog/pagerbot", time: "10 days ago"}, 
	{title : "On the Design of Editors for Small Computers (1972)", site: "ed.ac.u", href: "http://history.dcs.ed.ac.uk/archive/apps/Whitfield-Thesis/thesis.html", time: "9 days ago"}, 
	{title : "Shen – A Sufficiently Advanced Lisp [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lMcRBdSdO_U&list=UU_QIfHvN9auy2CoOdSfMWDw", time: "12 days ago"}, 
	{title : "Why Docker and containerization is a boon to web software startups", site: "dell.co", href: "http://eir.dell.com/docker-containerization-boon-web-software-startups/", time: "4 days ago"}, 
	{title : "Show HN: For the Badge – Badges for your repos", site: "forthebadge.co", href: "http://forthebadge.com/", time: "26 days ago"}, 
	{title : "The descent to C", site: "greenend.org.u", href: "http://www.chiark.greenend.org.uk/~sgtatham/cdescent/", time: "251 days ago"}, 
	{title : "Modern Microprocessors: A 90 Minute Guide (2012)", site: "lighterra.co", href: "http://www.lighterra.com/papers/modernmicroprocessors/", time: "245 days ago"}, 
	{title : "An upgrade to attoparsec, Haskell parsing library: more speed, more power", site: "serpentine.co", href: "http://www.serpentine.com/blog/2014/05/31/attoparsec/", time: "128 days ago"}, 
	{title : "The Egg", site: "galactanet.co", href: "http://www.galactanet.com/oneoff/theegg_mod.html", time: "240 days ago"}, 
	{title : "The Urban Village", site: "mit.ed", href: "http://senseable.mit.edu/urbanvillages/", time: "2 days ago"}, 
	{title : "A Tiny Emissary from the Ancient Past", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/25/science/a-tiny-emissary-from-the-ancient-past.html", time: "10 days ago"}, 
	{title : "Olfactory Dysfunction Predicts 5-Year Mortality in Older Adults", site: "plosone.or", href: "http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0107541", time: "5 days ago"}, 
	{title : "Read Slowly to Benefit Your Brain and Cut Stress", site: "wsj.co", href: "http://online.wsj.com/articles/read-slowly-to-benefit-your-brain-and-cut-stress-1410823086?", time: "18 days ago"}, 
	{title : "Write every day", site: "mlafeldt.github.i", href: "http://mlafeldt.github.io/blog/write-every-day/", time: "14 days ago"}, 
	{title : "Mou 1.0 coming early 2015", site: "indiegogo.co", href: "https://www.indiegogo.com/projects/mou-1-0-markdown-editor-on-os-x-for-you/x/8756561", time: "4 days ago"}, 
	{title : "If programming languages were vehicles", site: "amazonaws.co", href: "http://s3.crashworks.org.s3-website-us-east-1.amazonaws.com/if-programming-languages-were-vehicles/", time: "3 days ago"}, 
	{title : "Boring Future, Volume 1", site: "frankchimero.co", href: "http://frankchimero.com/blog/boring-future-volume-1/", time: "4 days ago"}, 
	{title : "Ranking universities based on career outcomes", site: "linkedin.co", href: "http://blog.linkedin.com/2014/10/01/ranking-universities-based-on-career-outcomes/", time: "5 days ago"}, 
	{title : "Show HN: 1HOP, a free tool to handle deep linking across all devices", site: "commandiq.co", href: "https://1hop.commandiq.com", time: "26 days ago"}, 
	{title : "Nosh – filling the gap caused by the systemd tool not being portable", site: "ntlworld.co", href: "http://homepage.ntlworld.com/jonathan.deboynepollard/Softwares/nosh.html", time: "11 days ago"}, 
]