news23 = [
	{title : "RamdaJS – A practical functional library for JavaScript", site: "ramdajs.co", href: "http://ramdajs.com/", time: "3 days ago"}, 
	{title : "Using Tweets to Predict Which States Are Overweight", site: "slate.co", href: "http://www.slate.com/blogs/future_tense/2014/10/02/university_of_arizona_researchers_analyze_food_references_in_twitter_data.html", time: "3 days ago"}, 
	{title : "SweetAlert – a beautiful replacement for JavaScript's alert()", site: "tristanedwards.m", href: "http://tristanedwards.me/sweetalert", time: "5 days ago"}, 
	{title : "Adventures in empty UDP scanning", site: "rapid7.co", href: "https://community.rapid7.com/community/infosec/blog/2014/10/03/adventures-in-empty-udp-scanning", time: "3 days ago"}, 
	{title : "Samsung paid Microsoft $1B in Android patent-licensing royalties in 2013", site: "zdnet.co", href: "http://www.zdnet.com/samsung-paid-microsoft-1-billion-in-android-patent-licensing-royalties-in-2013-7000034342/", time: "2 days ago"}, 
	{title : "6DOF Positional Tracking with the Wiimote", site: "franklinta.co", href: "http://franklinta.com/2014/09/30/6dof-positional-tracking-with-the-wiimote", time: "3 days ago"}, 
	{title : "What is Yahoo really worth?", site: "economist.co", href: "http://www.economist.com/news/business/21621812-investors-put-low-value-yahoos-core-businessfor-now-what-it-really-worth", time: "3 days ago"}, 
	{title : "A PHP class for retrieving accurate IP address information for the client", site: "github.co", href: "https://github.com/Vectorface/whip", time: "3 days ago"}, 
	{title : "The single vigilante behind Facebook's 'real name' crackdown", site: "dailydot.co", href: "http://www.dailydot.com/technology/realnamepolice-facebook-real-names-policy/", time: "3 days ago"}, 
	{title : "Amazon Launches WriteOn to Compete Against Crowd-Writing Sites Like Wattpad", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/amazon-launches-writeon-to-compete-against-crowd-writing-sites-like-wattpad/", time: "3 days ago"}, 
	{title : "USB armory – a open hardware flash drive sized computer", site: "inversepath.co", href: "http://inversepath.com/usbarmory", time: "3 days ago"}, 
	{title : "D3.geo.zoom now supports smooth animated zooming", site: "jasondavies.co", href: "http://www.jasondavies.com/maps/zoom/", time: "3 days ago"}, 
	{title : "Web Audio Hackday 2014 Berlin", site: "janmonschke.co", href: "http://janmonschke.com/blog/2014/10/03/web-audio-hackday-2014.html", time: "3 days ago"}, 
	{title : "Washington Post employees slam owner Jeff Bezos", site: "salon.co", href: "http://www.salon.com/2014/10/03/%E2%80%9Canother_wall_street_smash_and_grab%E2%80%9D_washington_post_employees_slam_owner_jeff_bezos/", time: "2 days ago"}, 
	{title : "Fun with HTTP Headers (2005)", site: "nextthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers?Cneonction=close", time: "4 days ago"}, 
	{title : "Soylent 1.1", site: "soylent.m", href: "http://blog.soylent.me/post/98982202087/introducing-soylent-1-1", time: "4 days ago"}, 
	{title : "Show HN: Build real-time web apps with other people... in real-time!", site: "loggur.co", href: "https://www.loggur.com", time: "4 days ago"}, 
	{title : "Technology is not creating jobs: it is eating them", site: "onepercentbreadsticks.co", href: "http://onepercentbreadsticks.com/first-world-problems", time: "3 days ago"}, 
	{title : "Could Ebola vaccine delay be due to an intellectual property spat?", site: "cbc.c", href: "http://www.cbc.ca/news/canada/manitoba/could-ebola-vaccine-delay-be-due-to-an-intellectual-property-spat-1.2786214", time: "3 days ago"}, 
	{title : "Show HN: MGBDTC – the easiest way to track what your employees are learning", site: "mgbdtc.co", href: "https://mgbdtc.com", time: "3 days ago"}, 
	{title : "Computers are made of metal, not category theory", site: "chrisstucchio.co", href: "http://www.chrisstucchio.com/blog/2014/computers_are_made_of_metal.html", time: "5 days ago"}, 
	{title : "Finger Trees", site: "gibiansky.co", href: "http://andrew.gibiansky.com/blog/haskell/finger-trees/", time: "13 days ago"}, 
	{title : "Show HN: Moo.do – Simple, Powerful Organizational Tool", site: "moo.d", href: "http://moo.do/?hn", time: "7 days ago"}, 
	{title : "Y Combinator and the Negative Externalities of Hackernews", site: "danilocampos.co", href: "http://danilocampos.com/2014/09/y-combinator-and-the-negative-externalities-of-hacker-news/", time: "6 days ago"}, 
	{title : "US top cop decries encryption, demands backdoors", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/us-top-cop-decries-encryption-demands-backdoors/", time: "5 days ago"}, 
]