news14 = [
	{title : "Journey into information theory", site: "khanacademy.or", href: "https://www.khanacademy.org/computing/computer-science/informationtheory", time: "1 day ago"}, 
	{title : "Libsqlfs: A POSIX-style file system on top of an SQLite database", site: "github.co", href: "https://github.com/guardianproject/libsqlfs", time: "3 days ago"}, 
	{title : "U.S. Law Enforcement Seeks to Halt Apple-Google Encryption of Mobile Data", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/u-s-seeks-to-reverse-apple-android-data-locking-decision.html", time: "6 days ago"}, 
	{title : "Universal SSL", site: "cloudflare.co", href: "https://blog.cloudflare.com/introducing-universal-ssl/", time: "7 days ago"}, 
	{title : "John Carmack on Inlined Code", site: "number-none.co", href: "http://number-none.com/blow/john_carmack_on_inlined_code.html", time: "10 days ago"}, 
	{title : "Bill Gates: Bitcoin Is 'Better Than Currency'", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/238103", time: "2 days ago"}, 
	{title : "Keynote: Dries Buytaert. Scaling open source projects", site: "drupal.or", href: "https://amsterdam2014.drupal.org/keynote-dries-buytaert", time: "1 day ago"}, 
	{title : "Uber Improves Life, Economists Agree", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/01/upshot/uber-improves-life-economists-agree.html", time: "1 day ago"}, 
	{title : "Shellshock will happen again", site: "mecheye.ne", href: "http://blog.mecheye.net/2014/10/shellshock-will-happen-again/", time: "1 day ago"}, 
	{title : "HackCampus Internship Programme", site: "hackcampus.i", href: "http://hackcampus.io/internship/#hero", time: "1 day ago"}, 
	{title : "CDC confirms first Ebola case diagnosed in US", site: "cnbc.co", href: "http://www.cnbc.com/id/102037055", time: "6 days ago"}, 
	{title : "ForestDb – A Fast Key-Value Storage Engine Based on Hierarchical B+-Tree Trie", site: "github.co", href: "https://github.com/couchbaselabs/forestdb", time: "2 days ago"}, 
	{title : "The badge of ignorance", site: "medium.co", href: "https://medium.com/@emilepetrone/the-badge-of-ignorance-185c85ac9a30", time: "1 day ago"}, 
	{title : "Let's Talk about Reddit and Self Promotion", site: "reddit.co", href: "http://www.reddit.com/r/videos/comments/2idhxn/lets_talk_about_reddit_and_selfpromotion/", time: "1 day ago"}, 
	{title : "HTTP/2 Frequently Asked Questions", site: "http2.github.i", href: "http://http2.github.io/faq/", time: "3 days ago"}, 
	{title : "Content Security Policy (CSP) for the web we have", site: "mozilla.or", href: "https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/", time: "2 days ago"}, 
	{title : "Show HN: GoldenLayout – JavaScript Layout Manager", site: "golden-layout.co", href: "https://golden-layout.com/", time: "4 days ago"}, 
	{title : "How Archerfish Hunt With Their Spit (2013)", site: "wired.co", href: "http://www.wired.com/2013/11/archerfish-physics/", time: "2 days ago"}, 
	{title : "An Australian researcher has worked out how to store 1000TB on a CD", site: "sciencealert.com.a", href: "http://www.sciencealert.com.au/news/20140309-26116.html", time: "4 days ago"}, 
	{title : "Sway: A new presentation application from Microsoft", site: "sway.co", href: "https://sway.com/", time: "5 days ago"}, 
	{title : "The Sound So Loud That It Circled the Earth Four Times", site: "nautil.u", href: "http://nautil.us/blog/the-sound-so-loud-that-it-circled-the-earth-four-times", time: "7 days ago"}, 
	{title : "Show HN: Star Wars GUI / MultiTouch UI", site: "chrisgannon.wordpress.co", href: "http://chrisgannon.wordpress.com/2014/09/24/star-wars-guimultitouch-ui-controls-again/", time: "2 days ago"}, 
	{title : "WebSharper: Make web apps in F#", site: "websharper.co", href: "http://websharper.com/", time: "3 days ago"}, 
	{title : "Stampede – Texas Advanced Computing Center", site: "utexas.ed", href: "https://www.tacc.utexas.edu/stampede/", time: "2 days ago"}, 
	{title : "A mixed bag on apps: What the NY Times learned with NYT Opinion and NYT Now", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/a-mixed-bag-on-apps-what-the-new-york-times-learned-with-nyt-opinion-and-nyt-now/", time: "2 days ago"}, 
	{title : "Contact Lost with Planes One by One as FAA Fire Spread", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/contact-lost-with-planes-one-by-one-as-faa-center-fire-spread.html", time: "4 days ago"}, 
	{title : "The Fourth Skull: A Tale of Authenticity and Fraud (2013)", site: "theappendix.ne", href: "http://theappendix.net/issues/2013/4/the-fourth-skull-a-tale-of-authenticity-and-fraud", time: "2 days ago"}, 
	{title : "The NSA and Me", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/the-nsa-and-me/", time: "4 days ago"}, 
	{title : "HFT in my backyard – III", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/02/hft-in-my-backyard-iii/", time: "4 days ago"}, 
	{title : "Most People with Addiction Simply Grow Out of It", site: "substance.co", href: "http://www.substance.com/most-people-with-addiction-simply-grow-out-of-it-why-is-this-widely-denied/13017/", time: "5 days ago"}, 
]