news1 = [
	{title : "Yahoo Hacked", site: "googleusercontent.co", href: "http://webcache.googleusercontent.com/search?q=cache:I8s8KmZhwXMJ:www.futuresouth.us/yahoo_hacked.html+&cd=1&hl=en&ct=clnk&client=firefox-a", time: "10 hours ago"}, 
	{title : "The force vectors on a skateboard during an Ollie", site: "wired.co", href: "http://www.wired.com/2014/10/skateboard-physics-empzeal/", time: "2 hours ago"}, 
	{title : "Become Estonia’s e-resident", site: "e-estonia.co", href: "http://e-estonia.com/e-residents/become-e-resident/", time: "8 hours ago"}, 
	{title : "Overstock.com Assembles Coders to Create a Bitcoin-Like Stock Market", site: "wired.co", href: "http://www.wired.com/2014/10/overstock-com-assembles-coders-build-bitcoin-like-stock-market/", time: "3 hours ago"}, 
	{title : "Life of an HTTP request, as seen by my toy web server", site: "tia.mat.b", href: "http://tia.mat.br/blog/html/2014/10/06/life_of_a_http_request.html", time: "2 hours ago"}, 
	{title : "Show HN: Nightmare – Simple browser automation", site: "nightmarejs.or", href: "http://www.nightmarejs.org/", time: "9 hours ago"}, 
	{title : "LambdaNative – A cross-platform development environment written in Scheme", site: "github.co", href: "https://github.com/part-cw/lambdanative/wiki", time: "11 hours ago"}, 
	{title : "Inside the Biggest-Ever Hedge-Fund Scandal", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/13/empire-edge", time: "12 hours ago"}, 
	{title : "There Is No Maker Movement in China", site: "ello.c", href: "https://ello.co/cshirky/post/FQKBh4QMjfaqBM1C4XYnjw", time: "7 hours ago"}, 
	{title : "State of the Lua Ecosystem (2013)", site: "speakerdeck.co", href: "https://speakerdeck.com/catwell/state-of-the-lua-ecosystem", time: "3 hours ago"}, 
	{title : "Mailgun forwarding can result in your domain being treated as spam", site: "rajivm.co", href: "https://blog.rajivm.com/mailgun-forwarding-spam.html", time: "5 hours ago"}, 
	{title : "Soft Errors Are Hard Problems (2009)", site: "geekhold.co", href: "http://codingrelic.geekhold.com/2009/09/soft-errors-are-hard-problems.html", time: "1 hour ago"}, 
	{title : "Not on a Social Network? You’ve Still Got a Privacy Problem", site: "wired.co", href: "http://www.wired.com/2014/10/privacy-friendster/", time: "9 hours ago"}, 
	{title : "A Toast Story", site: "psmag.co", href: "http://www.psmag.com/navigation/health-and-behavior/toast-story-latest-artisanal-food-craze-72676/", time: "5 hours ago"}, 
	{title : "Crypto Museum", site: "cryptomuseum.co", href: "http://www.cryptomuseum.com/index.htm", time: "11 hours ago"}, 
	{title : "Man-Computer Symbiosis (1960)", site: "mit.ed", href: "http://groups.csail.mit.edu/medg/people/psz/Licklider.html", time: "3 hours ago"}, 
	{title : "History of Apache Storm and Lessons Learned", site: "nathanmarz.co", href: "http://nathanmarz.com/blog/history-of-apache-storm-and-lessons-learned.html", time: "10 hours ago"}, 
	{title : "Shdr – Online GLSL shader editor and validator with live preview", site: "bkcore.co", href: "http://bkcore.com/blog/3d/shdr-online-glsl-shader-editor-viewer-validator.html", time: "7 hours ago"}, 
	{title : "The Contrarians on Stress: It Can Be Good for You", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/your-money/the-contrarians-on-stress-it-can-be-good-for-you-.html?smid=fb-nytimes&smtyp=cur&bicmp=AD&bicmlukp=WT.mc_id&bicmst=1409232722000&bicmet=1419773522000&_r=0", time: "3 hours ago"}, 
	{title : "Heathkit", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Heathkit", time: "1 hour ago"}, 
	{title : "Show HN: Aiveo – Free issue tracking tool", site: "aiveo.c", href: "http://aiveo.ca", time: "1 hour ago"}, 
	{title : "Ranges in C++: Counted Iterables and Efficiency", site: "ericniebler.co", href: "http://ericniebler.com/2014/10/06/counted-ranges-and-efficiency/", time: "6 hours ago"}, 
	{title : "Show HN: ScreenSlicer – Automatic, zero-config web scraping", site: "github.co", href: "https://github.com/MachinePublishers/ScreenSlicer", time: "8 hours ago"}, 
	{title : "Pharocloud – hosting for Smalltalk web-applications", site: "pharocloud.co", href: "http://pharocloud.com/", time: "2 hours ago"}, 
	{title : "Show HN: Clojure in the Open – simple tasks from open-source projects", site: "longstorm.or", href: "http://www.longstorm.org/weekly/cito/1/", time: "8 hours ago"}, 
	{title : "The Forgotten Female Programmers Who Created Modern Tech", site: "npr.or", href: "http://www.npr.org/blogs/alltechconsidered/2014/10/06/345799830/the-forgotten-female-programmers-who-created-modern-tech", time: "3 hours ago"}, 
	{title : "In the medical response to Ebola, Cuba is punching above its weight", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/worldviews/wp/2014/10/04/in-the-medical-response-to-ebola-cuba-is-punching-far-above-its-weight/", time: "12 hours ago"}, 
	{title : "Project Cybersyn and the origins of the Big Data nation", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/13/planning-machine", time: "5 hours ago"}, 
]