news19 = [
	{title : "Introducing the World’s Most Precise Clock", site: "ieee.or", href: "http://spectrum.ieee.org/aerospace/satellites/introducing-the-worlds-most-precise-clock", time: "3 days ago"}, 
	{title : "Decoding Nature's Soundtrack", site: "nautil.u", href: "http://nautil.us/issue/12/feedback/decoding-natures-soundtrack?utm_source=tss&utm_medium=desktop&utm_campaign=linkfrom", time: "2 days ago"}, 
	{title : "Roller Coaster Tycoon was written in x86 Assembly by one guy", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/RollerCoaster_Tycoon#Development", time: "2 days ago"}, 
	{title : "Labour is steadily losing out to capital", site: "economist.co", href: "http://www.economist.com/news/special-report/21621160-labour-steadily-losing-out-capital-those-have-shall-be-given", time: "3 days ago"}, 
	{title : "Inside McLaren's 650S supercar factory", site: "cnet.co", href: "http://www.cnet.com/pictures/inside-mclaren/", time: "2 days ago"}, 
	{title : "Soylent and It's Side Effects", site: "ethanglover.bi", href: "http://ethanglover.biz/blog/soylent-side-effects.php", time: "2 days ago"}, 
	{title : "Privacy Statements for Windows 10 Technical Preview", site: "microsoft.co", href: "http://windows.microsoft.com/en-gb/windows/preview-privacy-statement", time: "2 days ago"}, 
	{title : "Installing Apple CarPlay and Taking It for a Spin", site: "consumerreports.or", href: "http://www.consumerreports.org/cro/news/2014/10/installing-apple-carplay-on-pioneer-stereo-and-taking-it-for-spin/index.htm", time: "3 days ago"}, 
	{title : "Show HN: Create Your Own Startup Metrics Dashboard", site: "pubnub.co", href: "http://www.pubnub.com/developers/demos/startup-metrics-dashboard/", time: "3 days ago"}, 
	{title : "Isomorphic JavaScript: Angular.js is not the answer", site: "berzniz.co", href: "http://berzniz.com/post/99158163051/isomorphic-javascript-angular-js-is-not-the-answer", time: "2 days ago"}, 
	{title : "How Computers Boot Up (2008)", site: "duartes.or", href: "http://duartes.org/gustavo/blog/post/how-computers-boot-up/", time: "2 days ago"}, 
	{title : "Is Docker ready for production? Feedbacks of a 2 weeks hands on", site: "t37.ne", href: "https://t37.net/is-docker-ready-for-production-feedbacks-of-a-2-weeks-hands-on.html", time: "3 days ago"}, 
	{title : "HackCampus Internship: A programme built by students for students in the UK", site: "hackcampus.i", href: "http://hackcampus.io/internship/", time: "2 days ago"}, 
	{title : "The surprising and continuing influence of Swami Vivekananda (2012)", site: "wsj.co", href: "http://online.wsj.com/news/articles/SB10001424052702303404704577305581227233656", time: "9 days ago"}, 
	{title : "The self-made man", site: "slate.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/the_self_made_man_history_of_a_myth_from_ben_franklin_to_andrew_carnegie.html", time: "6 days ago"}, 
	{title : "Avoid OOP (Overzealous Optimization Programming)", site: "colintoh.co", href: "http://colintoh.com/blog/avoid-oop", time: "1 day ago"}, 
	{title : "How WP Engine Hijacked My Business", site: "matthewwoodward.co.u", href: "http://www.matthewwoodward.co.uk/reviews/webhost-trusted-wp-engine-hijacked-business-avoid-them/", time: "1 day ago"}, 
	{title : "Japan's groundbreaking bullet train is 50 years old", site: "businessinsider.co", href: "http://www.businessinsider.com/shinkansen-bullet-train-now-50-years-old-2014-10?op=1", time: "2 days ago"}, 
	{title : "Good looking addresses – solving the “Berlin, Berlin” bug", site: "opencagedata.co", href: "http://blog.opencagedata.com/post/99059889253/good-looking-addresses-solving-the-berlin-berlin", time: "3 days ago"}, 
	{title : "Finally, a 2nd Ave. Subway [video]", site: "nytimes.co", href: "http://www.nytimes.com/video/nyregion/100000003149427/living-city-finally-a-2nd-ave-subway.html?src=vidm", time: "2 days ago"}, 
	{title : "Desktop PCs aren’t going anywhere–because they’re cheap (2011)", site: "jseliger.wordpress.co", href: "https://jseliger.wordpress.com/2011/10/09/desktop-pcs-arent-going-anywhere-despite-the-growth-of-phones-and-tablets%E2%80%94because-theyre-cheap", time: "2 days ago"}, 
	{title : "The very laws of physics imply that artificial intelligence must be possible", site: "aeon.c", href: "http://aeon.co/magazine/technology/david-deutsch-artificial-intelligence/", time: "6 days ago"}, 
	{title : "Rise of the Robots: On Peter Thiel's argument about robots and low wages", site: "project-syndicate.or", href: "http://www.project-syndicate.org/commentary/j--bradford-delong-questions-paypal-co-founder-peter-thiel-s-argument-that-robots-will-save-us-from-a-low-wage-future", time: "2 days ago"}, 
	{title : "Sweden to become first EU country to officially recognize State of Palestine", site: "rt.co", href: "http://rt.com/news/192904-sweden-to-recognize-palestine/", time: "1 day ago"}, 
	{title : "N.C.A.A. Fan Map: How the Country Roots for College Football", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/03/upshot/ncaa-football-fan-map.html", time: "3 days ago"}, 
	{title : "Etsy’s Trying to Fix Tech’s Women Problem. Why Aren’t You?", site: "medium.co", href: "https://medium.com/matter/this-is-the-last-thing-youll-ever-need-to-read-about-sexism-in-tech-56b9a3a77af0", time: "4 days ago"}, 
	{title : "Ebola: The tolling bell", site: "stanford.ed", href: "http://stanfordlawyer.law.stanford.edu/2014/10/ebola-the-tolling-bell/", time: "3 days ago"}, 
	{title : "Unpatchable Malware That Infects USBs", site: "wired.co", href: "http://www.wired.com/2014/10/code-published-for-unfixable-usb-attack/", time: "4 days ago"}, 
]