news27 = [
	{title : "Why the Heyday of Credit Card Fraud Is Almost Over", site: "slate.co", href: "http://www.slate.com/blogs/moneybox/2014/10/03/credit_card_fraud_getting_rid_of_magstripes_will_stop_fake_cards.html", time: "3 days ago"}, 
	{title : "When Ben Bernanke can't refinance his house loan", site: "bloomberg.co", href: "http://mobile.bloomberg.com/news/2014-10-02/you-know-it-s-a-tough-market-when-ben-bernanke-can-t-refinance.html", time: "3 days ago"}, 
	{title : "Route leak incident on October 2, 2014", site: "cloudflare.co", href: "https://blog.cloudflare.com/route-leak-incident-on-october-2-2014/", time: "4 days ago"}, 
	{title : "Ericsson open-sources OpenWebRTC, rival to Google’s WebRTC implementation", site: "gigaom.co", href: "https://gigaom.com/2014/10/02/ericsson-open-sources-openwebrtc-to-provide-alternative-to-googles-webrtc-implementation/", time: "4 days ago"}, 
	{title : "CUPS 2.0", site: "cups.or", href: "https://www.cups.org/documentation.php/doc-2.0/relnotes.html", time: "4 days ago"}, 
	{title : "Beautiful Chemistry", site: "beautifulchemistry.ne", href: "http://beautifulchemistry.net/", time: "4 days ago"}, 
	{title : "Orleans – Distributed Virtual Actors for Programmability and Scalability", site: "microsoft.co", href: "http://research.microsoft.com/en-us/projects/orleans/", time: "4 days ago"}, 
	{title : "A possible future for PHP", site: "karlitschek.d", href: "http://karlitschek.de/2014/10/a-possible-future-for-php/", time: "4 days ago"}, 
	{title : "Facebook plots first steps into healthcare", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/03/us-facebook-health-idUSKCN0HS09720141003", time: "3 days ago"}, 
	{title : "Hackers Have Found a Flaw in Macs", site: "businessinsider.co", href: "http://www.businessinsider.com/hackers-use-macbackdooriworm-on-mac-os-x-and-reddit-2014-10?utm_content=buffer9fb64&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer", time: "3 days ago"}, 
	{title : "Reddit requiring remote office, WFH employees to move to SF or lose their jobs", site: "nbcbayarea.co", href: "http://www.nbcbayarea.com/news/local/Reddit-Criticized-On-Reddit-For-Requiring-Workers-To-Move-to-SF--277930941.html", time: "3 days ago"}, 
	{title : "Lyft Drivers Are Burning Their Pink Mustaches", site: "vice.co", href: "http://www.vice.com/read/burning-mustaches-with-angry-lift-drivers-103", time: "3 days ago"}, 
	{title : "The Herculean Effort Taken by One Group to Show Hollywood Is Sexist", site: "fivethirtyeight.co", href: "http://fivethirtyeight.com/features/how-to-measure-women-film-annenberg/", time: "3 days ago"}, 
	{title : "Foodservice Startup Sourcery (YC W13) Streamlines How Kitchens Source Food", site: "forbes.co", href: "http://www.forbes.com/sites/ellenhuet/2014/10/03/sourcery-foodservice-platform-launch/", time: "3 days ago"}, 
	{title : "Wal-Mart Senior Greeter Story", site: "interomojo.co", href: "http://interomojo.com/2011/07/04/monday-mojo-wal-mart-senior-greeter/", time: "3 days ago"}, 
	{title : "Trends in the Silk Road 2.0", site: "lau.i", href: "http://lau.im/articles/analyzing-silk-road-2-0-part-1/", time: "7 days ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977&c=5&lng=en&p=0", time: "3 days ago"}, 
	{title : "Building an alternative Silicon Valley", site: "austingrandt.co", href: "http://austingrandt.com/building-alternative-silicon-valley/", time: "3 days ago"}, 
	{title : "Growth, efficiency, and yield of commercial broilers from 1957, 1978, and 2005", site: "oxfordjournals.or", href: "http://ps.oxfordjournals.org/content/early/2014/09/26/ps.2014-04291.abstract", time: "3 days ago"}, 
	{title : "Moving to Sublime 3 after 15 yrs with TextPad – reasons, comparisons, and tips", site: "aliteralmind.wordpress.co", href: "http://aliteralmind.wordpress.com/2014/10/02/textpad_to_sublime/", time: "4 days ago"}, 
	{title : "Implementing highly efficient data structures with Monoids and Fingertrees", site: "codementor.i", href: "https://www.codementor.io/haskell-tutorial/monoids-fingertrees-implement-abstract-data", time: "4 days ago"}, 
	{title : "Why women leave tech because they have good taste", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/why-women-leave-tech-they-have-good-taste.html", time: "3 days ago"}, 
	{title : "My experience with using cp to copy 432 million files (39 TB)", site: "gnu.or", href: "http://lists.gnu.org/archive/html/coreutils/2014-08/msg00012.html", time: "25 days ago"}, 
	{title : "My coworkers made me use Mac OS 9", site: "arstechnica.co", href: "http://arstechnica.com/apple/2014/09/my-coworkers-made-me-use-mac-os-9-for-their-and-your-amusement/", time: "8 days ago"}, 
	{title : "Cubic Bezier Curves – Under the Hood", site: "vimeo.co", href: "http://vimeo.com/106757336", time: "4 days ago"}, 
	{title : "Apple's livesteam outage was easily preventable", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/apple-livestream-outage.html", time: "5 days ago"}, 
]