news10 = [
	{title : "Dubai detectives to get Google Glass", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/02/us-emirates-dubai-google-police-idUSKCN0HR0W320141002", time: "1 day ago"}, 
	{title : "Linked lists with wait-free reads in C++", site: "concurrencyfreaks.blogspot.co", href: "http://concurrencyfreaks.blogspot.com/2014/10/linked-lists-with-wait-free-reads-in-c.html", time: "3 days ago"}, 
	{title : "How a Trillion-Dollar Market Remains Hidden in Plain Sight", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/how-a-trillion-dollar-market-remains-hidden-in-plain-sight/", time: "1 day ago"}, 
	{title : "Statistical Flaw Punctuates Brain Research in Elite Journals", site: "scientificamerican.co", href: "http://blogs.scientificamerican.com/talking-back/2014/03/27/statistical-flaw-punctuates-brain-research-in-elite-journals/", time: "1 day ago"}, 
	{title : "Bitcoin falls below $300, lowest in 11 months", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?below300", time: "1 day ago"}, 
	{title : "Postgres 9.5 feature highlight: row-level security and policies", site: "otacoo.co", href: "http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-row-level-security/", time: "3 days ago"}, 
	{title : "Usaddress – Python library for parsing unstructured address strings with NLP", site: "rtfd.or", href: "http://usaddress.rtfd.org/", time: "3 days ago"}, 
	{title : "Caesium: A brief history of timekeeping", site: "bbc.co", href: "http://www.bbc.com/news/magazine-29476893", time: "2 days ago"}, 
	{title : "Reddit", site: "samaltman.co", href: "http://blog.samaltman.com/reddit", time: "6 days ago"}, 
	{title : "Exploring Change Blindness", site: "learnforeverlearn.co", href: "http://learnforeverlearn.com/changeblindness/", time: "1 day ago"}, 
	{title : "Is Google Making Students Stupid?", site: "theatlantic.co", href: "http://www.theatlantic.com/education/archive/2014/09/is-google-making-students-stupid/380944/", time: "1 day ago"}, 
	{title : "Throw Out the College Application System", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/opinion/sunday/throw-out-the-college-application-system.html", time: "1 day ago"}, 
	{title : "Show HN: Open-Source, Free, Agile Project Management Tool", site: "taiga.i", href: "http://www.taiga.io", time: "5 days ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec04/#", time: "4 days ago"}, 
	{title : "The USSR used a nuclear charge to stop a gas well fire in 1966", site: "coal-seam-gas.co", href: "http://www.coal-seam-gas.com/accidents/ussr.htm", time: "5 days ago"}, 
	{title : "Novena Update", site: "bunniestudios.co", href: "http://www.bunniestudios.com/blog/?p=4146", time: "3 days ago"}, 
	{title : "Personal site, terminal style", site: "silvioporcellana.co", href: "http://silvioporcellana.com/", time: "1 day ago"}, 
	{title : "Lilblue Linux: Adventures Beyond the Land of Posix", site: "gentoo.or", href: "http://blogs.gentoo.org/blueness/2014/10/04/lilblue-linux-release-20140925-adventures-beyond-the-land-of-posix/", time: "2 days ago"}, 
	{title : "Comparisons among Java-based CSV parsers", site: "github.co", href: "https://github.com/uniVocity/csv-parsers-comparison", time: "1 day ago"}, 
	{title : "Facebook's Bus Drivers Seek Union", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/business/facebooks-bus-drivers-seek-union.html", time: "20 hours ago"}, 
	{title : "Colonizing the Solar System Is Humankind’s Insurance Policy Against Extinction", site: "singularityhub.co", href: "http://singularityhub.com/2014/10/05/elon-musk-is-right-colonizing-the-solar-system-is-humankinds-insurance-policy-against-extinction/", time: "20 hours ago"}, 
	{title : "Yahoo Acquires Mobile Messaging App MessageMe", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/yahoo-acquires-mobile-messaging-app-messageme/", time: "3 days ago"}, 
	{title : "Qubitekk offers hope for protecting computers in the age of quantum computing", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/05/duncan-earl-interview/view-all/", time: "1 day ago"}, 
	{title : "Code Browser – A Folding Text Editor", site: "tibleiz.ne", href: "http://tibleiz.net/code-browser/index.html", time: "2 days ago"}, 
	{title : "When is a recursive function not a recursive function?", site: "russet.org.u", href: "http://www.russet.org.uk/blog/3015", time: "1 day ago"}, 
	{title : "The Books We Talk About (and Those We Don’t)", site: "nybooks.co", href: "http://www.nybooks.com/blogs/nyrblog/2014/oct/01/books-we-talk-about/", time: "2 days ago"}, 
	{title : "Modernized time.h for ISO C (1998)", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~mgk25/time/c/", time: "2 days ago"}, 
	{title : "Storage Scalability in Docker", site: "redhat.co", href: "http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/?utm_content=buffer8a955&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer", time: "2 days ago"}, 
]