news17 = [
	{title : "Pace4000 hidden testing modes", site: "sodnpoo.co", href: "http://www.sodnpoo.com/posts.xml/pace4000_testing_modes.xml", time: "2 days ago"}, 
	{title : "With Dry Taps and Toilets, California Drought Turns Desperate", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/california-drought-tulare-county.html?smid=tw-share", time: "4 days ago"}, 
	{title : "To catch a gravitational wave", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/october-2014/to-catch-a-gravitational-wave", time: "2 days ago"}, 
	{title : "Bash bug: the other two RCEs, or how we chipped away at the original fix", site: "lcamtuf.blogspot.co", href: "http://lcamtuf.blogspot.com/2014/10/bash-bug-how-we-finally-cracked.html", time: "5 days ago"}, 
	{title : "Show HN: M.py: inline and minify all CSS and JavaScript references in your HTML", site: "github.co", href: "https://github.com/nate-parrott/m.py", time: "2 days ago"}, 
	{title : "This American Life tries to turn its radio audience onto podcasting", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/this-american-life-tries-to-turn-its-radio-audience-onto-podcasting-with-its-new-show-serial/", time: "2 days ago"}, 
	{title : "Using Alchemy's semantic analysis function with Go to process Twitter data", site: "drshrey.github.i", href: "http://drshrey.github.io/jekyll/update/natural-language-processing/golang/2014/09/18/writing-my-first-nlp-app.html", time: "1 day ago"}, 
	{title : "Bang – An Atari 2600 VCS Demo", site: "xayax.ne", href: "http://xayax.net/bang!/", time: "2 days ago"}, 
	{title : "Lecture 1 – How to Start a Startup [video]", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec01/", time: "13 days ago"}, 
	{title : "Kimono Labs (YC W14) Hackathon This Weekend--win a BTC", site: "kimonolabs.co", href: "https://www.kimonolabs.com/hacks", time: "2 days ago"}, 
	{title : "In Colorado, a Rebranding of Pot Inc.", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/fashion/in-colorado-a-rebranding-of-pot-inc-marijuana.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "2 days ago"}, 
	{title : "Show HN: Dependency Update as a Service", site: "tachikoma.i", href: "http://tachikoma.io/", time: "2 days ago"}, 
	{title : "Best Papers vs. Top Cited Papers in Computer Science", site: "arnetminer.or", href: "http://arnetminer.org/conferencebestpapers", time: "5 days ago"}, 
	{title : "A State of Xen – Chaos Monkey and Cassandra", site: "netflix.co", href: "http://techblog.netflix.com/2014/10/a-state-of-xen-chaos-monkey-cassandra.html", time: "3 days ago"}, 
	{title : "Schneier on Incident Response", site: "lwn.ne", href: "http://lwn.net/Articles/612818/", time: "2 days ago"}, 
	{title : "How to get every game on STEAM for free", site: "gamasutra.co", href: "http://www.gamasutra.com/blogs/LeszekLisowski/20141001/226840/How_to_get_every_game_on_STEAM_for_free.php", time: "2 days ago"}, 
	{title : "Colleges Make It Easier for Students to Show, Not Tell, in Their Applications", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/28/education/college-admissions-goucher-video.html", time: "2 days ago"}, 
	{title : "William Binney Explains Snowden Docs", site: "alexaobrien.co", href: "http://www.alexaobrien.com/secondsight/wb/binney.html", time: "6 days ago"}, 
	{title : "National Nurse Survey Shows Hospitals Still Not Prepared for U.S. Ebola Patients", site: "nationalnursesunited.or", href: "http://www.nationalnursesunited.org/press/entry/national-nurse-survey-shows-hospitals-still-not-prepared-for-us-ebola/", time: "2 days ago"}, 
	{title : "How the Hash Works in Ruby", site: "gotealeaf.co", href: "http://www.gotealeaf.com/blog/how-the-hash-works-in-ruby/", time: "2 days ago"}, 
	{title : "Why Not Eat Octopus?", site: "newyorker.co", href: "http://www.newyorker.com/tech/elements/eating-octopus", time: "2 days ago"}, 
	{title : "Phison USB Custom Firmware and Existing Firmware Patches", site: "github.co", href: "https://github.com/adamcaudill/Psychson", time: "3 days ago"}, 
	{title : "BAP: Binary Analysis Platform", site: "cmu.ed", href: "http://bap.ece.cmu.edu/", time: "5 days ago"}, 
	{title : "The Ambiguities of Prison Gangs", site: "theatlantic.co", href: "http://www.theatlantic.com/national/archive/2014/10/gangs-and-prisons/381034/?single_page=true", time: "3 days ago"}, 
	{title : "Can Big Data Tell Us What Clinical Trials Don’t?", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/magazine/can-big-data-tell-us-what-clinical-trials-dont.html?rref=magazine&module=Ribbon&version=context&region=Header&action=click&contentCollection=Magazine&pgtype=article", time: "2 days ago"}, 
	{title : "Supporting idea convergence through pedagogical scripts and Etherpad APIs", site: "reganmian.ne", href: "http://reganmian.net/blog/2014/10/03/supporting-idea-convergence-through-pedagogical-scripts/", time: "2 days ago"}, 
	{title : "“The Peripheral” by William Gibson (Excerpt)", site: "williamgibsonbooks.co", href: "http://williamgibsonbooks.com/books/the_peripheral_excerpt.asp", time: "2 days ago"}, 
]