news30 = [
	{title : "Ex-Apple managers reveal Cupertino’s killer workload", site: "cultofmac.co", href: "http://www.cultofmac.com/298485/ex-apple-managers-reveal-cupertinos-killer-workload/", time: "3 days ago"}, 
	{title : "Ello Says You're Not a Product, but You Are – The Atlantic", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/09/ello-says-youre-not-a-product-but-you-are/380809/", time: "4 days ago"}, 
	{title : "Actions have consequences (or: why I'm not fixing Intel's bugs any more)", site: "mjg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32778.html", time: "4 days ago"}, 
	{title : "Reddit source code", site: "github.co", href: "https://github.com/reddit/reddit/", time: "5 days ago"}, 
	{title : "How We Use AWS, Ansible, and Packer to Make Deployment Awesome", site: "branchmetrics.i", href: "http://branchmetrics.io/blog/2014/09/19/how-we-deploy/", time: "4 days ago"}, 
	{title : "How to find growing files on Linux", site: "aarvik.d", href: "http://aarvik.dk/how-to-find-growing-files-on-linux/", time: "3 days ago"}, 
	{title : "Lecture 3: How to Start a Startup", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec03/", time: "6 days ago"}, 
	{title : "Scientists twist radio beams to send data at 32 Gb/sec (x30 faster than LTE)", site: "ibtimes.co.u", href: "http://www.ibtimes.co.uk/scientists-twist-radio-beams-to-send-data-at-32-gigabits-per-second-30-times-faster-than-4g-lte-1465957", time: "3 days ago"}, 
	{title : "15 years of whois client", site: "bofh.i", href: "http://blog.bofh.it/debian/id_452", time: "3 days ago"}, 
	{title : "CVE-2014-7284: Lack of randomness in Linux kernel network secrets", site: "secondlookforensics.co", href: "http://secondlookforensics.com/ngro-linux-kernel-bug/", time: "4 days ago"}, 
	{title : "Uncharted ocean mountains, trenches and ridges revealed by satellite map", site: "theguardian.co", href: "http://www.theguardian.com/science/2014/oct/03/uncharted-mountains-underwater-scars-revealed-satellite-map", time: "3 days ago"}, 
	{title : "Turn an Android smartphone into a cosmic ray telescope", site: "wisc.ed", href: "http://wipac.wisc.edu/news/view/262", time: "4 days ago"}, 
	{title : "How to do research at the MIT AI Lab (1988) [pdf]", site: "umass.ed", href: "https://people.cs.umass.edu/~emery/misc/how-to.pdf", time: "4 days ago"}, 
	{title : "The State of C (1988)", site: "drdobbs.co", href: "http://www.drdobbs.com/cpp/the-state-of-c/223000089", time: "4 days ago"}, 
	{title : "How Hong Kong Protesters Are Connecting, Without Cell or Wi-Fi Networks", site: "npr.or", href: "http://www.npr.org/blogs/alltechconsidered/2014/09/29/352476454/how-hong-kong-protesters-are-connecting-without-cell-or-wi-fi-networks", time: "7 days ago"}, 
	{title : "Redesigning the OpenDNS DNS database for low latency", site: "opendns.co", href: "http://labs.opendns.com/2014/10/01/redesigning-dns-database-low-latency/", time: "5 days ago"}, 
	{title : "First Blood Test to Diagnose Depression in Adults?", site: "northwestern.ed", href: "http://www.northwestern.edu/newscenter/stories/2014/09/first-blood-test-to-diagnose-depression-in-adults.html", time: "5 days ago"}, 
	{title : "Atlantic.net launches $0.99 SSD-based VPS servers", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/atlantic-net-launches-0-99month-ssd-based-vps-hosting-service/", time: "6 days ago"}, 
	{title : "C for Rubyists", site: "omniref.co", href: "https://www.omniref.com/ruby/2.1.2/files/ruby.c#annotation=4029392&line=1", time: "6 days ago"}, 
	{title : "The Source of Bad Writing", site: "wsj.co", href: "http://online.wsj.com/articles/the-cause-of-bad-writing-1411660188", time: "3 days ago"}, 
	{title : "My data is bigger than your data", site: "lintool.github.i", href: "http://lintool.github.io/my-data-is-bigger-than-your-data/", time: "4 days ago"}, 
	{title : "New material steals oxygen from the air", site: "sciencedaily.co", href: "http://www.sciencedaily.com/releases/2014/09/140930113254.htm", time: "4 days ago"}, 
	{title : "C# 6 Cuts", site: "trelford.co", href: "http://www.trelford.com/blog/post/austerity.aspx", time: "4 days ago"}, 
	{title : "Backer News: fresh crowdfunding projects", site: "backernews.co", href: "http://backernews.com/", time: "4 days ago"}, 
	{title : "Douglas Model 671/684: The X-15’s Shadow (2012)", site: "falsesteps.wordpress.co", href: "http://falsesteps.wordpress.com/2012/08/11/douglas-model-671684-the-x-15s-shadow/", time: "4 days ago"}, 
	{title : "The New and Improved C# 6.0", site: "microsoft.co", href: "http://msdn.microsoft.com/en-us/magazine/dn802602.aspx", time: "4 days ago"}, 
	{title : "Modules in C99", site: "snaipe.m", href: "http://snaipe.me/c/modules-in-c99/", time: "4 days ago"}, 
]