news38 = [
	{title : "An Apology", site: "rackspace.co", href: "http://www.rackspace.com/blog/an-apology/", time: "4 days ago"}, 
	{title : "The government says iPhone encryption helps criminals. They're wrong", site: "vox.co", href: "http://www.vox.com/2014/9/29/6854679/iphone-encryption-james-comey-government-backdoor", time: "4 days ago"}, 
	{title : "EveryoneAPI", site: "everyoneapi.co", href: "https://www.everyoneapi.com/", time: "5 days ago"}, 
	{title : "Lecture 2: How to Start a Startup", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec02/", time: "10 days ago"}, 
	{title : "Bad science is tolerable, résumé padding is not", site: "johndcook.co", href: "http://www.johndcook.com/blog/2011/09/12/bad-science-is-tolerable-resume-padding-is-not/", time: "5 days ago"}, 
	{title : "Linux from Scratch", site: "linuxfromscratch.or", href: "http://www.linuxfromscratch.org/", time: "5 days ago"}, 
	{title : "How to Start a Startup: Fall 2014", site: "samaltman.co", href: "http://startupclass.samaltman.com/", time: "19 days ago"}, 
	{title : "One of the ShellShock perl script used to take control of vulnerable machines", site: "pastebin.c", href: "http://pastebin.ca/2850380", time: "5 days ago"}, 
	{title : "Apple takes down another indie dev", site: "rollins.i", href: "http://blog.rollins.io/2014/09/30/the-king-makers-apple-takes-down-an-indie-dev/", time: "5 days ago"}, 
	{title : "SwiftOnSecurity: A story about Jessica", site: "swiftonsecurity.tumblr.co", href: "http://swiftonsecurity.tumblr.com/post/98675308034/a-story-about-jessica", time: "5 days ago"}, 
	{title : "The Compucolor 8001 (1976)", site: "oldcomputers.ne", href: "http://oldcomputers.net/compucolor-8001.html", time: "5 days ago"}, 
	{title : "Blink an LED with JavaScript – Spark Blog", site: "spark.i", href: "http://blog.spark.io/2014/09/29/blink-an-led-with-javascript/", time: "4 days ago"}, 
	{title : "I'm not sure it's Mou against the world", site: "larryhynes.ne", href: "http://larryhynes.net/2014/09/mou-against-the-world.html", time: "4 days ago"}, 
	{title : "Show HN: Realm for Android", site: "realm.i", href: "http://realm.io/news/realm-for-android/", time: "5 days ago"}, 
	{title : "Adobe joins the Chromebook party, starting with Photoshop", site: "chrome.blogspot.co", href: "http://chrome.blogspot.com/2014/09/adobe-joins-chromebook-party-starting.html", time: "6 days ago"}, 
	{title : "Microsoft’s new Sway app – WYSIWYG", site: "theverge.co", href: "http://www.theverge.com/2014/10/1/6879999/microsoft-sway-office-app", time: "4 days ago"}, 
	{title : "Functional Programming in Swift", site: "objc.i", href: "http://www.objc.io/books/", time: "4 days ago"}, 
	{title : "Fixing the Internet for confidentiality and security", site: "markshuttleworth.co", href: "http://www.markshuttleworth.com/archives/1407", time: "5 days ago"}, 
	{title : "Show HN: Sync Done Beautifully", site: "pixelapse.co", href: "https://www.pixelapse.com/sync", time: "5 days ago"}, 
	{title : "Gifshot: JS library to create animated GIFs from media streams, videos, images", site: "yahoo.github.i", href: "http://yahoo.github.io/gifshot/", time: "5 days ago"}, 
	{title : "A brief history of CPAN", site: "cpan.i", href: "http://cpan.io/ref/history.html", time: "5 days ago"}, 
	{title : "Schrödinger's Shift Key", site: "allenpike.co", href: "http://www.allenpike.com/2014/schrodingers-shift-key/", time: "4 days ago"}, 
	{title : "76 of 79 Deceased NFL Players Found to Have Brain Disease", site: "pbs.or", href: "http://www.pbs.org/wgbh/pages/frontline/sports/concussion-watch/76-of-79-deceased-nfl-players-found-to-have-brain-disease/", time: "4 days ago"}, 
	{title : "Why women leave tech: It's the culture", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture", time: "23 hours ago"}, 
	{title : "What the Tortoise Said to Achilles (1895)", site: "ditext.co", href: "http://www.ditext.com/carroll/tortoise.html", time: "8 days ago"}, 
	{title : "Game development resources page", site: "zeef.co", href: "https://game-development.zeef.com/", time: "4 days ago"}, 
]