news5 = [
	{title : "An Australian researcher has worked out how to store 1000TB on a CD", site: "sciencealert.com.a", href: "http://www.sciencealert.com.au/news/20140309-26116.html", time: "3 days ago"}, 
	{title : "Sway: A new presentation application from Microsoft", site: "sway.co", href: "https://sway.com/", time: "4 days ago"}, 
	{title : "The Power of Interoperability: Why Objects Are Inevitable (2013) [pdf]", site: "cmu.ed", href: "http://www.cs.cmu.edu/~aldrich/papers/objects-essay.pdf", time: "1 day ago"}, 
	{title : "The Sound So Loud That It Circled the Earth Four Times", site: "nautil.u", href: "http://nautil.us/blog/the-sound-so-loud-that-it-circled-the-earth-four-times", time: "6 days ago"}, 
	{title : "Comparisons among Java-based CSV parsers", site: "github.co", href: "https://github.com/uniVocity/csv-parsers-comparison", time: "14 hours ago"}, 
	{title : "Show HN: Star Wars GUI / MultiTouch UI", site: "chrisgannon.wordpress.co", href: "http://chrisgannon.wordpress.com/2014/09/24/star-wars-guimultitouch-ui-controls-again/", time: "1 day ago"}, 
	{title : "Reddit", site: "samaltman.co", href: "http://blog.samaltman.com/reddit", time: "5 days ago"}, 
	{title : "WebSharper: Make web apps in F#", site: "websharper.co", href: "http://websharper.com/", time: "2 days ago"}, 
	{title : "HP to split into two companies", site: "cnn.co", href: "http://money.cnn.com/2014/10/05/technology/hp-restructuring-split/index.html", time: "7 hours ago"}, 
	{title : "Stampede – Texas Advanced Computing Center", site: "utexas.ed", href: "https://www.tacc.utexas.edu/stampede/", time: "1 day ago"}, 
	{title : "A mixed bag on apps: What the NY Times learned with NYT Opinion and NYT Now", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/a-mixed-bag-on-apps-what-the-new-york-times-learned-with-nyt-opinion-and-nyt-now/", time: "1 day ago"}, 
	{title : "Contact Lost with Planes One by One as FAA Fire Spread", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/contact-lost-with-planes-one-by-one-as-faa-center-fire-spread.html", time: "3 days ago"}, 
	{title : "The Fourth Skull: A Tale of Authenticity and Fraud (2013)", site: "theappendix.ne", href: "http://theappendix.net/issues/2013/4/the-fourth-skull-a-tale-of-authenticity-and-fraud", time: "1 day ago"}, 
	{title : "The NSA and Me", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/the-nsa-and-me/", time: "3 days ago"}, 
	{title : "HFT in my backyard – III", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/02/hft-in-my-backyard-iii/", time: "3 days ago"}, 
	{title : "When 911 calls fail", site: "theverge.co", href: "http://www.theverge.com/2014/10/3/6414949/911-call-failures-fcc", time: "2 days ago"}, 
	{title : "Most People with Addiction Simply Grow Out of It", site: "substance.co", href: "http://www.substance.com/most-people-with-addiction-simply-grow-out-of-it-why-is-this-widely-denied/13017/", time: "4 days ago"}, 
	{title : "The USSR used a nuclear charge to stop a gas well fire in 1966", site: "coal-seam-gas.co", href: "http://www.coal-seam-gas.com/accidents/ussr.htm", time: "4 days ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd", time: "3 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://paulgraham.com/before.html", time: "4 days ago"}, 
	{title : "Linux Challenge Blackbox #1", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/linux-challenge-blackbox-1/", time: "5 hours ago"}, 
	{title : "The Magic CmdLine and how I got it back", site: "ntua.g", href: "http://users.softlab.ece.ntua.gr/~ttsiod/bashheimer.html", time: "2 days ago"}, 
	{title : "Accidental release of 45L of polio virus solution into the environment – Belgium", site: "europa.e", href: "http://www.ecdc.europa.eu/en/press/news/_layouts/forms/News_DispForm.aspx?List=8db7286c-fe2d-476c-9133-18ff4cb1b568&ID=1065", time: "2 days ago"}, 
	{title : "Let's Talk about Reddit and Self Promotion", site: "reddit.co", href: "http://www.reddit.com/r/videos/comments/2idhxn/lets_talk_about_reddit_and_selfpromotion/", time: "5 hours ago"}, 
	{title : "Researchers see signature of “Majorana particles” inside superconducting iron", site: "scientificamerican.co", href: "http://www.scientificamerican.com/article/majorana-particle-matter-and-antimatter/", time: "2 days ago"}, 
	{title : "HTTP/2 Frequently Asked Questions", site: "http2.github.i", href: "http://http2.github.io/faq/", time: "2 days ago"}, 
	{title : "Content Security Policy (CSP) for the web we have", site: "mozilla.or", href: "https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/", time: "1 day ago"}, 
	{title : "Show HN: GoldenLayout – JavaScript Layout Manager", site: "golden-layout.co", href: "https://golden-layout.com/", time: "3 days ago"}, 
	{title : "How Archerfish Hunt With Their Spit (2013)", site: "wired.co", href: "http://www.wired.com/2013/11/archerfish-physics/", time: "1 day ago"}, 
]