news4 = [
	{title : "A Virologist Takes You Inside the Ebola Protective Suit", site: "npr.or", href: "http://www.npr.org/blogs/goatsandsoda/2014/10/04/352804648/a-virologist-takes-you-inside-the-ebola-protective-suit", time: "15 hours ago"}, 
	{title : "Why the U.S. Military Is into Bee Brain Surgery", site: "nautil.u", href: "http://nautil.us/issue/11/light/why-the-us-military-is-into-bee-brain-surgery", time: "17 hours ago"}, 
	{title : "Viomba: A/B test your website and measure your design with eye tracking", site: "viomba.co", href: "http://www.viomba.com", time: "16 hours ago"}, 
	{title : "Do Deep Nets Really Need to be Deep? [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1312.6184v5.pdf", time: "2 days ago"}, 
	{title : "I come to bury IAmCarbonatedMilk.com, not to praise it (2002)", site: "salon.co", href: "http://www.salon.com/2002/08/03/deleteddomains/", time: "1 day ago"}, 
	{title : "Engineering management lessons", site: "defmacro.or", href: "http://www.defmacro.org/2014/10/03/engman.html", time: "2 days ago"}, 
	{title : "IRIS+", site: "3drobotics.co", href: "http://3drobotics.com/iris-plus/", time: "2 days ago"}, 
	{title : "Lilblue Linux: Adventures Beyond the Land of Posix", site: "gentoo.or", href: "http://blogs.gentoo.org/blueness/2014/10/04/lilblue-linux-release-20140925-adventures-beyond-the-land-of-posix/", time: "1 day ago"}, 
	{title : "Glut of postdoc researchers stirs quiet crisis in science", site: "bostonglobe.co", href: "https://www.bostonglobe.com/metro/2014/10/04/glut-postdoc-researchers-stirs-quiet-crisis-science/HWxyErx9RNIW17khv0MWTN/story.html", time: "5 hours ago"}, 
	{title : "A table of electric clay (2013) [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lvtfD_rJ2hE", time: "17 hours ago"}, 
	{title : "Which Flavor of Tokenization Is Used by Apple Pay", site: "pomcor.co", href: "http://pomcor.com/2014/10/05/which-flavor-of-tokenization-is-used-by-apple-pay/", time: "9 hours ago"}, 
	{title : "Show HN: Open-Source, Free, Agile Project Management Tool", site: "taiga.i", href: "http://www.taiga.io", time: "4 days ago"}, 
	{title : "Novena Update", site: "bunniestudios.co", href: "http://www.bunniestudios.com/blog/?p=4146", time: "2 days ago"}, 
	{title : "The Physical Web", site: "github.co", href: "https://github.com/google/physical-web", time: "3 days ago"}, 
	{title : "Nereus deep sea sub 'implodes' 10km-down", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-27374326", time: "9 hours ago"}, 
	{title : "Sthttpd: Tiny and fast http server with a mature codebase", site: "github.co", href: "https://github.com/rmdir/sthttpd", time: "1 day ago"}, 
	{title : "Two birds and a liar’s game", site: "thatgeoguy.c", href: "https://thatgeoguy.ca/blog/2014/10/04/two-birds-and-a-liars-game/", time: "1 day ago"}, 
	{title : "NFL Bans Beats Headphones on Camera", site: "recode.ne", href: "http://recode.net/2014/10/04/nfl-bans-beats-headphones-on-camera/", time: "6 hours ago"}, 
	{title : "New tool helps debug Java exceptions faster", site: "excepterror.co", href: "http://www.excepterror.com", time: "1 day ago"}, 
	{title : "CERN turns 60", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/cern-turns-60", time: "1 day ago"}, 
	{title : "Online JavaScript minifier", site: "javascriptcompress.herokuapp.co", href: "http://javascriptcompress.herokuapp.com/", time: "10 hours ago"}, 
	{title : "Show HN: PixelTool – a tool for overlaying designs for pixel perfect front-end", site: "spencer-walden.co", href: "http://www.spencer-walden.com/pixeltool/", time: "17 hours ago"}, 
	{title : "Cool-retro-term: A terminal emulator which mimics the old cathode display", site: "github.co", href: "https://github.com/Swordfish90/cool-retro-term", time: "4 days ago"}, 
	{title : "C++ and the Perils of Double-Checked Locking (2004) [pdf]", site: "aristeia.co", href: "http://www.aristeia.com/Papers/DDJ_Jul_Aug_2004_revised.pdf", time: "1 day ago"}, 
	{title : "Digital revolution has yet to fulfil its promise of productivity and better jobs", site: "economist.co", href: "http://www.economist.com/news/special-report/21621237-digital-revolution-has-yet-fulfil-its-promise-higher-productivity-and-better", time: "2 days ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec04/#", time: "3 days ago"}, 
	{title : "A new type of software helps researchers decide what they should be looking for", site: "economist.co", href: "http://www.economist.com/news/science-and-technology/21621704-new-type-software-helps-researchers-decide-what-they-should-be-looking", time: "1 day ago"}, 
	{title : "How Exercise May Protect Against Depression", site: "well.blogs.nytimes.co", href: "http://well.blogs.nytimes.com/2014/10/01/how-exercise-may-protect-against-depression/?src=me", time: "3 days ago"}, 
	{title : "Dollar a Day", site: "dollaraday.c", href: "https://dollaraday.co/", time: "4 days ago"}, 
]