news20 = [
	{title : "Why women leave tech because they have good taste", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/why-women-leave-tech-they-have-good-taste.html", time: "2 days ago"}, 
	{title : "My experience with using cp to copy 432 million files (39 TB)", site: "gnu.or", href: "http://lists.gnu.org/archive/html/coreutils/2014-08/msg00012.html", time: "24 days ago"}, 
	{title : "My coworkers made me use Mac OS 9", site: "arstechnica.co", href: "http://arstechnica.com/apple/2014/09/my-coworkers-made-me-use-mac-os-9-for-their-and-your-amusement/", time: "7 days ago"}, 
	{title : "Cubic Bezier Curves – Under the Hood", site: "vimeo.co", href: "http://vimeo.com/106757336", time: "3 days ago"}, 
	{title : "Apple's livesteam outage was easily preventable", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/apple-livestream-outage.html", time: "4 days ago"}, 
	{title : "CppCon 2014: Mike Acton “Data-Oriented Design and C++”", site: "youtube.co", href: "https://www.youtube.com/watch?v=rX0ItVEVjHc", time: "5 days ago"}, 
	{title : "Microsoft’s Cube debuts at Decibel, creating a one-of-a-kind digital dance party", site: "microsoft.co", href: "http://blogs.microsoft.com/next/2014/09/24/microsoft-cube-decibel-dance-music/", time: "9 days ago"}, 
	{title : "Beaker Notebook v1.0 released – open-source polyglot data science web app", site: "beakernotebook.co", href: "http://beakernotebook.com", time: "11 days ago"}, 
	{title : "Is Coding Art?", site: "newrepublic.co", href: "http://www.newrepublic.com/article/119215/geek-sublime-vikram-chandra-review-coding-art", time: "4 days ago"}, 
	{title : "Cloudera Acquires DataPad Technology Assets and Team", site: "cloudera.co", href: "http://www.cloudera.com/content/cloudera/en/about/press-center/press-releases/2014/09/30/cloudera-acquires-datapad-technology-assets-and-team-to-strength.html", time: "5 days ago"}, 
	{title : "An Inside Look at Anonymous, the Radical Hacking Collective", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/09/08/masked-avengers", time: "33 days ago"}, 
	{title : "Dear clueless assholes: stop bashing bash and GNU", site: "weev.livejournal.co", href: "https://weev.livejournal.com/409835.html", time: "7 days ago"}, 
	{title : "Reddit’s crappy ultimatum to remote workers and offices", site: "shortlogic.tumblr.co", href: "http://shortlogic.tumblr.com/post/99014759324/reddits-crappy-ultimatum", time: "3 days ago"}, 
	{title : "Patoline: A modern digital typesetting system", site: "patoline.or", href: "http://patoline.org/", time: "85 days ago"}, 
	{title : "Why I've Said Goodbye to Mobile in Favor of PC", site: "gamasutra.co", href: "http://gamasutra.com/blogs/ThomasHenshell/20140807/222732/Why_Ive_Said_Goodbye_to_Mobile_in_Favor_of_PC.php", time: "55 days ago"}, 
	{title : "Butterfly: Your everyday terminal in your web browser", site: "paradoxxxzero.github.i", href: "http://paradoxxxzero.github.io/2014/02/28/butterfly.html", time: "219 days ago"}, 
	{title : "Choosing a Web Framework/Language Combo – Ruby on Rails", site: "jacquesmattheij.co", href: "http://jacquesmattheij.com/choosing-web-framework-language-combo-srs-ruby-on-rails", time: "38 days ago"}, 
	{title : "Ageing: The girls who never grow older", site: "bbc.co", href: "http://www.bbc.com/future/story/20140520-the-girls-who-never-age", time: "138 days ago"}, 
	{title : "Windows 10: Code that uses 'os.StartsWith(“Windows 9”)'", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22", time: "1 day ago"}, 
	{title : "Jibo, the first family robot", site: "myjibo.co", href: "http://www.myjibo.com/", time: "81 days ago"}, 
	{title : "The Architecture of Open Source Applications", site: "aosabook.or", href: "http://aosabook.org/en/index.html", time: "382 days ago"}, 
	{title : "Two technologies which are bad for you", site: "medium.co", href: "https://medium.com/@jlouis666/two-technologies-which-are-bad-for-you-160311ad6b24", time: "30 days ago"}, 
	{title : "The Man Who Invented Modern Probability", site: "nautil.u", href: "http://nautil.us/issue/4/the-unlikely/the-man-who-invented-modern-probability", time: "409 days ago"}, 
	{title : "The Happy Demise of the 10X Engineer", site: "a16z.co", href: "http://a16z.com/2014/07/30/the-happy-demise-of-the-10x-engineer/", time: "67 days ago"}, 
	{title : "When to Hold Out For a Lower Airfare", site: "fivethirtyeight.co", href: "http://fivethirtyeight.com/features/when-to-hold-out-for-a-lower-airfare/", time: "167 days ago"}, 
	{title : "The Command Line for Your Datacenter", site: "mesosphere.i", href: "http://mesosphere.io/2014/09/02/introducing-mesos-cli/", time: "32 days ago"}, 
	{title : "Google's Physical Web", site: "google.github.i", href: "http://google.github.io/physical-web/", time: "3 days ago"}, 
	{title : "Hacker News is 44% 18-24 year olds, 77% male", site: "pingdom.co", href: "http://royal.pingdom.com/2012/08/21/report-social-network-demographics-in-2012/", time: "774 days ago"}, 
	{title : "Maaxi app aims to help black cabs counter rise of Uber", site: "bbc.co", href: "http://www.bbc.com/news/technology-29458897", time: "2 days ago"}, 
]