news33 = [
	{title : "Vogue magazine interview with Jony Ive", site: "vogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive", time: "4 days ago"}, 
	{title : "React Apps Using Flux and Backbone: A How To", site: "toptal.co", href: "http://www.toptal.com/front-end/simple-data-flow-in-react-applications-using-flux-and-backbone", time: "4 days ago"}, 
	{title : "Google execs have ideas on how to run your business", site: "technologyreview.co", href: "http://www.technologyreview.com/news/531056/google-execs-have-ideas-on-how-to-run-your-business/", time: "6 days ago"}, 
	{title : "10x: Architecture at Clay.io", site: "zolmeister.co", href: "http://zolmeister.com/2014/10/10x-architecture-at-clay-io.html", time: "4 days ago"}, 
	{title : "Microsoft developer explains on Reddit why Windows 10 is called Windows 10", site: "imgur.co", href: "https://i.imgur.com/SeH6xiI.png", time: "4 days ago"}, 
	{title : "Literary Lions Unite in Protest Over Amazon’s E-Book Tactics", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/29/business/literary-lions-unite-in-protest-over-amazons-e-book-tactics.html", time: "6 days ago"}, 
	{title : "UK Legalizes CD Ripping and Cloud Backups Today", site: "torrentfreak.co", href: "http://torrentfreak.com/uk-government-legalizes-cd-ripping-cloud-backups-today-141001/", time: "4 days ago"}, 
	{title : "Google announces 10% price cut for all Compute Engine instances", site: "thenextweb.co", href: "http://thenextweb.com/google/2014/10/01/google-announces-10-price-cut-compute-engine-instances-google-drive-passed-240m-active-users/", time: "4 days ago"}, 
	{title : "Show HN: NIH-DB fork it and write your own", site: "github.co", href: "https://github.com/tjake/nih-db", time: "4 days ago"}, 
	{title : "Visual Revolution of the Vanishing of Ethan Carter", site: "theastronauts.co", href: "http://www.theastronauts.com/2014/03/visual-revolution-vanishing-ethan-carter/", time: "5 days ago"}, 
	{title : "Reddit disallows remote work after $50MM investment round", site: "twitter.co", href: "https://twitter.com/dhh/status/517372782976696321", time: "4 days ago"}, 
	{title : "Building OS X Apps with JavaScript", site: "tylergaw.co", href: "http://tylergaw.com/articles/building-osx-apps-with-js", time: "7 days ago"}, 
	{title : "Why Windows 9 is Windows 10", site: "imgur.co", href: "http://i.imgur.com/p7eQQK3.png", time: "4 days ago"}, 
	{title : "It Just Works", site: "rustyshelf.or", href: "http://rustyshelf.org/2014/10/01/it-just-works/", time: "4 days ago"}, 
	{title : "Digital Ocean gives away t-shirts for commiting to public GitHub repo in October", site: "digitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/", time: "3 days ago"}, 
	{title : "Gauged – Fast, append-only storage layer for numeric data that changes over time", site: "github.co", href: "https://github.com/chriso/gauged", time: "4 days ago"}, 
	{title : "Immigration Crackdown on Digital Nomads in Chiang Mai, Thailand", site: "johnnyfd.co", href: "http://www.johnnyfd.com/2014/09/live-updates-immigration-crackdown-in.html", time: "4 days ago"}, 
	{title : "Show HN: A Google Calendar Door Sign", site: "newfangled.m", href: "http://newfangled.me/door-sign/", time: "7 days ago"}, 
	{title : "Your Agile, Free and Open Source Project Management Tool", site: "taiga.i", href: "https://taiga.io/", time: "4 days ago"}, 
	{title : "Hacktoberfest", site: "digitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/#comment-1615829197", time: "4 days ago"}, 
	{title : "Apple Says iPhone 6 and 6 Plus Bending Complaints Number Less Than 10", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/25/apple-says-iphone-6-and-6-plus-bending-complaints-number-less-than-10/?ncid=rss&cps=gravity", time: "4 days ago"}, 
	{title : "Microsoft developer explains why Windows 10 is called Windows 10", site: "reddit.co", href: "http://www.reddit.com/r/technology/comments/2hwlrk/new_windows_version_will_be_called_windows_10/ckwq83x", time: "4 days ago"}, 
	{title : "How American parenting is killing the American marriage", site: "qz.co", href: "http://qz.com/273255/how-american-parenting-is-killing-the-american-marriage/", time: "4 days ago"}, 
	{title : "Make in India", site: "makeinindia.co", href: "http://makeinindia.com/sectors/", time: "10 days ago"}, 
	{title : "Rails is great! Thank you", site: "github.co", href: "https://github.com/rails/rails/issues/16731", time: "5 days ago"}, 
	{title : "Gilad Bracha: A DOMain of Shadows", site: "gbracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html", time: "5 days ago"}, 
	{title : "Students are cash cows, and schools the predators", site: "salon.co", href: "http://www.salon.com/2014/10/01/college_is_ripping_you_off_students_are_cash_cows_and_schools_the_predators/?", time: "4 days ago"}, 
	{title : "COGNITIVE SLAVES (aka Crowdslaving)", site: "globalguerrillas.typepad.co", href: "http://globalguerrillas.typepad.com/globalguerrillas/2010/09/cognitive-slaves.html", time: "3 days ago"}, 
	{title : "Show HN: Airtable, a real-time spreadsheet-database hybrid", site: "airtable.co", href: "https://airtable.com/invite/a3sz9t7b", time: "9 days ago"}, 
]