news3 = [
	{title : "Where the Printf Rubber Meets the Road (2010)", site: "hostilefork.co", href: "http://blog.hostilefork.com/where-printf-rubber-meets-road/", time: "1 day ago"}, 
	{title : "First womb-transplant baby born", site: "bbc.co", href: "http://www.bbc.com/news/health-29485996", time: "1 day ago"}, 
	{title : "Times Articles Removed from Google Results in Europe", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/media/times-articles-removed-from-google-results-in-europe.html", time: "1 day ago"}, 
	{title : "Dubai detectives to get Google Glass", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/02/us-emirates-dubai-google-police-idUSKCN0HR0W320141002", time: "16 hours ago"}, 
	{title : "How a Trillion-Dollar Market Remains Hidden in Plain Sight", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/how-a-trillion-dollar-market-remains-hidden-in-plain-sight/", time: "12 hours ago"}, 
	{title : "The Most Ambitious Environmental Lawsuit Ever", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/02/magazine/mag-oil-lawsuit.html", time: "23 hours ago"}, 
	{title : "When is a recursive function not a recursive function?", site: "russet.org.u", href: "http://www.russet.org.uk/blog/3015", time: "23 hours ago"}, 
	{title : "How con artists trick your mind", site: "bbc.co", href: "http://www.bbc.com/future/story/20141003-the-mind-tricks-of-scammers", time: "1 day ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://m.bbc.com/news/science-environment-29465446", time: "1 day ago"}, 
	{title : "Code Browser – A Folding Text Editor", site: "tibleiz.ne", href: "http://tibleiz.net/code-browser/index.html", time: "1 day ago"}, 
	{title : "Qubitekk offers hope for protecting computers in the age of quantum computing", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/05/duncan-earl-interview/view-all/", time: "10 hours ago"}, 
	{title : "Inspeqtor – Monitor your application infrastructure", site: "github.co", href: "https://github.com/mperham/inspeqtor", time: "16 hours ago"}, 
	{title : "The Books We Talk About (and Those We Don’t)", site: "nybooks.co", href: "http://www.nybooks.com/blogs/nyrblog/2014/oct/01/books-we-talk-about/", time: "1 day ago"}, 
	{title : "Untangling how cables coil", site: "mit.ed", href: "http://newsoffice.mit.edu/2014/predict-cable-coiling-1003", time: "15 hours ago"}, 
	{title : "Modernized time.h for ISO C (1998)", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~mgk25/time/c/", time: "1 day ago"}, 
	{title : "Reddit, Redditors and Self-Promotion", site: "youtube.co", href: "https://www.youtube.com/watch?v=uOtuEDgYTwI", time: "5 hours ago"}, 
	{title : "Welcome to the World of Regulatory Hackers", site: "1776dc.co", href: "http://1776dc.com/news/2014/10/03/welcome-to-the-world-of-regulatory-hackers/", time: "11 hours ago"}, 
	{title : "Storage Scalability in Docker", site: "redhat.co", href: "http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/?utm_content=buffer8a955&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer", time: "1 day ago"}, 
	{title : "Personal site, terminal style", site: "silvioporcellana.co", href: "http://silvioporcellana.com/", time: "9 hours ago"}, 
	{title : "Why haven't quadcopters been scaled up yet?", site: "stackexchange.co", href: "http://aviation.stackexchange.com/questions/3300/why-havent-quadcopters-been-scaled-up-yet", time: "1 day ago"}, 
	{title : "Show HN: Mojulo – Pixelated Math Rendering Sandbox Toy", site: "maxbittker.github.i", href: "http://maxbittker.github.io/Mojulo/", time: "1 day ago"}, 
	{title : "Linked lists with wait-free reads in C++", site: "concurrencyfreaks.blogspot.co", href: "http://concurrencyfreaks.blogspot.com/2014/10/linked-lists-with-wait-free-reads-in-c.html", time: "2 days ago"}, 
	{title : "ScoutBot: Automated network scanning, environment assessments, and more", site: "lansec.ne", href: "http://lansec.net/project/scoutbot/", time: "12 hours ago"}, 
	{title : "Daya Bay places new limit on sterile neutrinos", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/daya-bay-places-new-limit-on-sterile-neutrinos", time: "9 hours ago"}, 
	{title : "Show HN: Turning a classic gamebook into interactive fiction", site: "github.co", href: "https://github.com/cjauvin/gamebook.js", time: "11 hours ago"}, 
	{title : "The Man Who Smuggles Traders Joe’s into Canada", site: "priceonomics.co", href: "http://priceonomics.com/the-man-who-smuggles-traders-joes-into-canada/", time: "2 days ago"}, 
	{title : "How to change or build your career", site: "sivers.or", href: "http://sivers.org/career", time: "7 hours ago"}, 
	{title : "Bitcoin falls below $300, lowest in 11 months", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?below300", time: "12 hours ago"}, 
	{title : "Non-weak DSA key? oxymoronic, perhaps (2010)", site: "meyering.ne", href: "http://meyering.net/nuke-your-DSA-keys/", time: "11 hours ago"}, 
]