news8 = [
	{title : "The Ebola Patient Was Sent Home Because of Bad Software", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/10/the-ebola-patient-was-sent-home-because-of-an-electronic-health-record-problem/381087/", time: "1 day ago"}, 
	{title : "Show HN: Franc – Detect natural languages", site: "github.co", href: "https://github.com/wooorm/franc", time: "2 days ago"}, 
	{title : "Aids: Origin of pandemic 'was 1920s Kinshasa'", site: "bbc.co", href: "http://www.bbc.com/news/health-29442642", time: "2 days ago"}, 
	{title : "A survey of the current state of Golang ORMs", site: "go-steel-programmers.or", href: "http://present.go-steel-programmers.org/talk-review-orms/gsp-go-orms.slide#1", time: "20 hours ago"}, 
	{title : "Show HN: The Wide Language Index", site: "widelanguageindex.or", href: "http://widelanguageindex.org/", time: "1 day ago"}, 
	{title : "Bill Gates: Bitcoin Is 'Better Than Currency'", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/238103", time: "1 day ago"}, 
	{title : "The next generation storage engine for Couchbase Server: ForestDB", site: "couchbase.co", href: "http://blog.couchbase.com/next-generation-storage-engine-couchbase-server-and-couchbase-lite-forestdb-now-available-beta", time: "17 hours ago"}, 
	{title : "Aboard a Cargo Colossus: Maersk’s New Container Ships", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/business/international/aboard-a-cargo-colossus-maersks-new-container-ships.html?hp&action=click&pgtype=Homepage&version=HpSumSmallMediaHigh&module=second-column-region&region=top-news&WT.nav=top-news&_r=0", time: "2 days ago"}, 
	{title : "Dirty Assembly Tricks in NES Assembly (2013)", site: "andrewkelley.m", href: "http://andrewkelley.me/post/jamulator.html#dirty-assembly-tricks", time: "2 days ago"}, 
	{title : "Arduino LED Startup Counter", site: "matthack.co", href: "http://matthack.com/startup-counter/", time: "1 day ago"}, 
	{title : "A Plan to Use Survivors’ Blood for Ebola Treatment in Africa", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/health/use-of-ebola-survivors-blood-as-possible-treatment-gains-support.html?ref=science", time: "1 day ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage", time: "1 day ago"}, 
	{title : "Pace4000 hidden testing modes", site: "sodnpoo.co", href: "http://www.sodnpoo.com/posts.xml/pace4000_testing_modes.xml", time: "1 day ago"}, 
	{title : "With Dry Taps and Toilets, California Drought Turns Desperate", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/california-drought-tulare-county.html?smid=tw-share", time: "3 days ago"}, 
	{title : "To catch a gravitational wave", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/october-2014/to-catch-a-gravitational-wave", time: "1 day ago"}, 
	{title : "Bash bug: the other two RCEs, or how we chipped away at the original fix", site: "lcamtuf.blogspot.co", href: "http://lcamtuf.blogspot.com/2014/10/bash-bug-how-we-finally-cracked.html", time: "4 days ago"}, 
	{title : "The Quest to Build an Elevator into Space", site: "gizmodo.co", href: "http://gizmodo.com/the-quest-to-build-an-elevator-to-space-1638192427", time: "2 days ago"}, 
	{title : "Machine Learning is the new Algorithms", site: "nlpers.blogspot.co", href: "http://nlpers.blogspot.com/2014/10/machine-learning-is-new-algorithms.html", time: "2 days ago"}, 
	{title : "Show HN: M.py: inline and minify all CSS and JavaScript references in your HTML", site: "github.co", href: "https://github.com/nate-parrott/m.py", time: "1 day ago"}, 
	{title : "This American Life tries to turn its radio audience onto podcasting", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/this-american-life-tries-to-turn-its-radio-audience-onto-podcasting-with-its-new-show-serial/", time: "1 day ago"}, 
	{title : "Using Alchemy's semantic analysis function with Go to process Twitter data", site: "drshrey.github.i", href: "http://drshrey.github.io/jekyll/update/natural-language-processing/golang/2014/09/18/writing-my-first-nlp-app.html", time: "1 day ago"}, 
	{title : "Bang – An Atari 2600 VCS Demo", site: "xayax.ne", href: "http://xayax.net/bang!/", time: "2 days ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977", time: "2 days ago"}, 
	{title : "Lecture 1 – How to Start a Startup [video]", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec01/", time: "12 days ago"}, 
	{title : "Kimono Labs (YC W14) Hackathon This Weekend--win a BTC", site: "kimonolabs.co", href: "https://www.kimonolabs.com/hacks", time: "1 day ago"}, 
	{title : "In Colorado, a Rebranding of Pot Inc.", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/fashion/in-colorado-a-rebranding-of-pot-inc-marijuana.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "1 day ago"}, 
	{title : "Show HN: Dependency Update as a Service", site: "tachikoma.i", href: "http://tachikoma.io/", time: "1 day ago"}, 
	{title : "Best Papers vs. Top Cited Papers in Computer Science", site: "arnetminer.or", href: "http://arnetminer.org/conferencebestpapers", time: "4 days ago"}, 
]