news10 = [
	{title : "Celebs whose nude photos were stolen threaten Google with $100M lawsuit", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/celebs-whose-nude-photos-were-stolen-threaten-google-with-100m-lawsuit/", time: "2 days ago"}, 
	{title : "Show HN: Make your site faster", site: "eager.i", href: "https://eager.io/app/ZYBle8qUhKFJ?n", time: "3 days ago"}, 
	{title : "Many to Many Joins with Ecto and Elixir", site: "coffeesforclosures.co", href: "http://www.coffeesforclosures.com/many-to-many-joins-with-ecto-and-elixir/", time: "2 days ago"}, 
	{title : "The FBI Says How It ‘Legally’ Pinpointed Silk Road’s Server", site: "wired.co", href: "http://www.wired.com/2014/09/the-fbi-finally-says-how-it-legally-pinpointed-silk-roads-server/", time: "30 days ago"}, 
	{title : "Thinking about quitting your job? Go tell your boss", site: "ronsho.co", href: "http://www.ronsho.com/2014/10/quitting-job-tell-boss/", time: "18 hours ago"}, 
	{title : "Sex for the pleasure of women: The amazing heroes behind inventing the Pill", site: "salon.co", href: "http://www.salon.com/2014/10/04/sex_for_the_pleasure_of_women_the_amazing_heroes_behind_the_invention_of_the_pill/", time: "23 hours ago"}, 
	{title : "Dominus is now open source.  Multiplayer browser game made with Meteor", site: "github.co", href: "https://github.com/dan335/dominus", time: "1 day ago"}, 
	{title : "South by Southwest’s unpaid labor problem", site: "salon.co", href: "http://www.salon.com/2014/02/26/south_by_southwest%E2%80%99s_unpaid_labor_problem_why_its_risking_a_class_action_lawsuit/", time: "23 hours ago"}, 
	{title : "Yahoo Acquires Mobile Messaging App MessageMe", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/yahoo-acquires-mobile-messaging-app-messageme/", time: "2 days ago"}, 
	{title : "Watch the Navy’s Robotic Gunboats Swarm the James River", site: "medium.co", href: "https://medium.com/war-is-boring/watch-the-navys-robotic-gunboats-swarm-the-james-river-86abe382600f", time: "1 day ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage/", time: "1 day ago"}, 
	{title : "Debian Linux Wheezy OpenVPN and Squid3 How to with Transparent Proxying", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/debian-linux-wheezy-openvpn-squid3-howto-with-transparent-proxying/", time: "1 day ago"}, 
	{title : "HackCampus Internship: A programme built by students for students in the UK", site: "hackcampus.i", href: "http://hackcampus.io/internship/", time: "1 day ago"}, 
	{title : "The surprising and continuing influence of Swami Vivekananda (2012)", site: "wsj.co", href: "http://online.wsj.com/news/articles/SB10001424052702303404704577305581227233656", time: "8 days ago"}, 
	{title : "The self-made man", site: "slate.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/the_self_made_man_history_of_a_myth_from_ben_franklin_to_andrew_carnegie.html", time: "5 days ago"}, 
	{title : "Avoid OOP (Overzealous Optimization Programming)", site: "colintoh.co", href: "http://colintoh.com/blog/avoid-oop", time: "22 hours ago"}, 
	{title : "AngularJS Tutorial: a comprehensive 10,000 word guide", site: "airpair.co", href: "http://www.airpair.com/angularjs", time: "2 days ago"}, 
	{title : "How WP Engine Hijacked My Business", site: "matthewwoodward.co.u", href: "http://www.matthewwoodward.co.uk/reviews/webhost-trusted-wp-engine-hijacked-business-avoid-them/", time: "23 hours ago"}, 
	{title : "Why women leave tech: It's the culture, not because 'math is hard'", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture/", time: "2 days ago"}, 
	{title : "How the Shinkansen bullet train made Tokyo into the monster it is today", site: "theguardian.co", href: "http://www.theguardian.com/cities/2014/sep/30/-sp-shinkansen-bullet-train-tokyo-rail-japan-50-years", time: "5 days ago"}, 
	{title : "Brain Gain: the underground world of neuroenhancing drugs (2009)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2009/04/27/brain-gain?utm_source=tny&utm_campaign=generalsocial&utm_medium=facebook&mbid=social_facebook", time: "2 days ago"}, 
	{title : "NASA Eyes Crew Deep Sleep Option for Mars Mission", site: "discovery.co", href: "http://news.discovery.com/space/nasa-eyes-crew-deep-sleep-option-for-mission-to-mars-141003.htm", time: "2 days ago"}, 
	{title : "if (osName.startsWith('windows 9'))", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22%29", time: "4 days ago"}, 
	{title : "Rocket Internet Shares Fall Below Issue Price at Debut", site: "wsj.co", href: "http://online.wsj.com/articles/rocket-internet-shares-fall-below-issue-price-at-debut-1412237549", time: "3 days ago"}, 
]