news29 = [
	{title : "Show HN: QDB, a remote python debugger", site: "github.co", href: "https://github.com/quantopian/qdb", time: "4 days ago"}, 
	{title : "A Sea Story (2004)", site: "theatlantic.co", href: "http://www.theatlantic.com/magazine/archive/2004/05/a-sea-story/302940/?single_page=true#show-last-Point", time: "3 days ago"}, 
	{title : "Join the Computing for Ebola Challenge Hackathon", site: "hackerleague.or", href: "https://www.hackerleague.org/hackathons/computing-for-ebola-challenge", time: "3 days ago"}, 
	{title : "Islamic State Social Media Strangely Silent Since Strikes", site: "vice.co", href: "http://motherboard.vice.com/en_ca/read/the-islamic-state-has-been-quieter-online-after-us-air-strikes", time: "3 days ago"}, 
	{title : "Tesla to unveil D and other product on October 9th", site: "twitter.co", href: "https://twitter.com/elonmusk/status/517486950589014016", time: "4 days ago"}, 
	{title : "Open-source client scaffolds and API pricing", site: "inboxapp.co", href: "https://www.inboxapp.com/blog/clients-and-pricing", time: "4 days ago"}, 
	{title : "API Docs for URX's Deeplink Search Engine", site: "urx.co", href: "http://developers.urx.com/", time: "6 days ago"}, 
	{title : "Technical analysis of client identification mechanisms", site: "chromium.or", href: "http://www.chromium.org/Home/chromium-security/client-identification-mechanisms", time: "9 days ago"}, 
	{title : "Sile, a typesetting system inspired by TeX and InDesign", site: "sile-typesetter.or", href: "http://www.sile-typesetter.org/what-is/index.html", time: "5 days ago"}, 
	{title : "Show HN: Open source, JavaScript game", site: "veerasundar.co", href: "http://veerasundar.com/suzhi/?hn", time: "3 days ago"}, 
	{title : "Reddit Plans Cryptocurrency to Give Back to Its Users After $50M Raise", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/reddit-scoops-up-50m-series-b-from-sam-altman-a16z-sequoia-at-500m-valuation/?ncid=rss", time: "5 days ago"}, 
	{title : "Piracy at the Old Bailey", site: "publicdomainreview.or", href: "http://publicdomainreview.org/2014/10/01/piracy-at-the-old-bailey/", time: "4 days ago"}, 
	{title : "Search Funds: The quiet, dependable, risk-averse sibling to the startup", site: "slate.co", href: "http://www.slate.com/articles/business/buy_a_small_business/2014/10/search_funds_the_quiet_dependable_risk_averse_sibling_to_the_startup.html", time: "4 days ago"}, 
	{title : "Rovio Announces Redundancies", site: "rovio.co", href: "http://www.rovio.com/en/news/blog/552/towards-a-simplified-organization", time: "3 days ago"}, 
	{title : "Cloudflare experiencing upstream network issues", site: "twitter.co", href: "https://twitter.com/CloudFlareSys/status/517699118680911872", time: "3 days ago"}, 
	{title : "How Product Hunt + Hacker News fueled 300k views in 30 days", site: "medium.co", href: "https://medium.com/design-philosophies/an-overnight-success-660739c2a7e9", time: "3 days ago"}, 
	{title : "Opternative: Eye exams from the comfort of home", site: "opternative.co", href: "http://www.opternative.com/", time: "4 days ago"}, 
	{title : "Terms of Service; Didn't Read", site: "tosdr.or", href: "https://tosdr.org/", time: "4 days ago"}, 
	{title : "“Do you wear pants”: T. S. Eliot’s first magazine", site: "harvard.ed", href: "http://blogs.law.harvard.edu/houghton/2014/10/01/do-you-wear-pants-t-s-eliots-first-magazine/", time: "4 days ago"}, 
	{title : "“Gasbuggy” tests nuclear fracking in the late 1960s", site: "aoghs.or", href: "http://aoghs.org/technology/project-gasbuggy/", time: "3 days ago"}, 
	{title : "Delorean: Microsoft skips Windows 9, jumps to Windows 10 (2013)", site: "infoworld.co", href: "http://www.infoworld.com/article/2613504/microsoft-windows/microsoft-windows-microsoft-skips-too-good-windows-9-jumps-to-windows-10.html", time: "3 days ago"}, 
	{title : "Hank Green: Why am I using this shitty iPhone 4", site: "medium.co", href: "https://medium.com/@hankgreen/why-am-i-using-this-shitty-iphone-4-29c8a8514e99", time: "3 days ago"}, 
	{title : "What You Need to Know About the Ebola Outbreak", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/07/31/world/africa/ebola-virus-outbreak-qa.html", time: "5 days ago"}, 
	{title : "Proof that HubSpot CMS sites can have amazing UI/UX", site: "greenhouse.i", href: "http://www.greenhouse.io?utm_campaign=hn", time: "3 days ago"}, 
	{title : "Advanced iOS virus targeting Hong Kong protestors", site: "reuters.co", href: "http://www.reuters.com/article/2014/09/30/hongkong-china-cybersecurity-apple-idUSL2N0RV2D320140930", time: "5 days ago"}, 
	{title : "Dart and Internet Explorer", site: "uservoice.co", href: "http://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6511262-add-the-dart-vm", time: "3 days ago"}, 
	{title : "Groove Deletes Their Facebook Page", site: "groovehq.co", href: "http://www.groovehq.com/blog/focus", time: "3 days ago"}, 
]