news35 = [
	{title : "The Fake Terror Threat Used to Justify Bombing Syria", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/09/28/u-s-officials-invented-terror-group-justify-bombing-syria/", time: "6 days ago"}, 
	{title : "What Happens When We All Live to 100?", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/what-happens-when-we-all-live-to-100/379338/", time: "17 days ago"}, 
	{title : "Synergy (mouse and keyboard sharing over a network) goes from free to paid", site: "synergy-project.or", href: "http://synergy-project.org/download/", time: "11 days ago"}, 
	{title : "Recruiter: Startups Are Offering Crazy, 1999-Like Hiring Incentives", site: "businessinsider.co", href: "http://www.businessinsider.com/startups-offering-1-million-signing-bonuses-2014-9", time: "8 days ago"}, 
	{title : "Live attacks against the Norse honeypot infrastructure", site: "ipviking.co", href: "http://map.ipviking.com/", time: "58 days ago"}, 
	{title : "Entrepreneurs anonymous: People should understand how hard their lives can be", site: "economist.co", href: "http://www.economist.com/news/business/21618816-instead-romanticising-entrepreneurs-people-should-understand-how-hard-their-lives-can", time: "17 days ago"}, 
	{title : "Affinity Designer – Illustrator alternative", site: "serif.co", href: "https://affinity.serif.com/", time: "66 days ago"}, 
	{title : "The Cardinal Sin of Software Engineering", site: "theeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/cardinal-sin-of-software-engineering", time: "11 days ago"}, 
	{title : "Show HN: Socktunes, the music search engine", site: "socktunes.co", href: "http://socktunes.com", time: "8 days ago"}, 
	{title : "Using your RDBMS for messaging is totally OK", site: "jooq.or", href: "http://blog.jooq.org/2014/09/26/using-your-rdbms-for-messaging-is-totally-ok/", time: "9 days ago"}, 
	{title : "Effective Code Reviews", site: "originate.co", href: "http://blog.originate.com/blog/2014/09/29/effective-code-reviews/", time: "6 days ago"}, 
	{title : "Why startups fail (according to their founders)", site: "fortune.co", href: "http://fortune.com/2014/09/25/why-startups-fail-according-to-their-founders/", time: "10 days ago"}, 
	{title : "Tour of pyramids of Giza using Google Maps street view", site: "google.co", href: "http://www.google.com/maps/about/behind-the-scenes/streetview/treks/pyramids-of-giza/", time: "25 days ago"}, 
	{title : "Living Simply in a Dumpster", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/the-simple-life-in-a-dumpster/379947/", time: "24 days ago"}, 
	{title : "Marka: Icon transformations", site: "fian.my.i", href: "http://fian.my.id/marka/", time: "56 days ago"}, 
	{title : "An interactive exploration of Boston's subway system", site: "mbtaviz.github.i", href: "http://mbtaviz.github.io/", time: "117 days ago"}, 
	{title : "GitHub.com is officially banned in Russia by the Government", site: "twitter.co", href: "https://twitter.com/orangy/status/517714936974561280", time: "3 days ago"}, 
	{title : "Synergy FOSS: Connect your keyboard to multiple PCs", site: "synergy-project.or", href: "http://synergy-project.org/", time: "32 days ago"}, 
	{title : "ISPs in Russia are blocking GitHub", site: "amazonaws.co", href: "https://s3.amazonaws.com/kato-share/18e61a9a5fb1c6906002801197086fbbe35d531c7b64d3d5afe764823ed2f1a/Screen%20Shot%202014-10-02%20at%208.37.11%20PM.png", time: "3 days ago"}, 
	{title : "Systemd may drive Linux admins to FreeBSD", site: "infoworld.co", href: "http://www.infoworld.com/d/data-center/you-have-your-windows-in-my-linux-249483", time: "33 days ago"}, 
	{title : "Are coders worth it? (2013)", site: "aeon.c", href: "http://aeon.co/magazine/society/james-somers-web-developer-money/", time: "37 days ago"}, 
	{title : "Dug.js – A JSONP to HTML Script", site: "rog.i", href: "http://rog.ie/blog/dugjs-a-jsonp-to-html-script", time: "234 days ago"}, 
	{title : "JPEG image glitching / corruption", site: "snorpey.github.i", href: "http://snorpey.github.io/jpg-glitch/", time: "392 days ago"}, 
	{title : "What Qualities Make a Good Startup Engineer?", site: "theeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/what-qualities-make-a-good-startup-engineer", time: "88 days ago"}, 
	{title : "Programming Sucks", site: "stilldrinking.or", href: "http://stilldrinking.org/programming-sucks", time: "159 days ago"}, 
	{title : "Unsung Hero of the Nuclear Age", site: "slate.co", href: "http://www.slate.com/articles/life/the_spectator/2011/02/an_unsung_hero_of_the_nuclear_age.single.html", time: "239 days ago"}, 
	{title : "Daniel Shiffman launches 'The Nature of Code' online for free", site: "natureofcode.co", href: "http://natureofcode.com/", time: "707 days ago"}, 
	{title : "BOXEN – GitHub's configuration tool for osx", site: "github.co", href: "https://boxen.github.com/", time: "154 days ago"}, 
	{title : "Apple will buy Tesla – rumor", site: "venturebeat.co", href: "http://venturebeat.com/2014/02/16/rumor-says-apple-will-buy-tesla/", time: "231 days ago"}, 
	{title : "Fun With HTTP Headers", site: "nextthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers", time: "2062 days ago"}, 
]