news14 = [
	{title : "We need to stop pushing our kids", site: "theguardian.co", href: "http://www.theguardian.com/lifeandstyle/2014/oct/04/we-need-stop-pushing-our-kids-parents", time: "1 day ago"}, 
	{title : "The Price of Music", site: "recode.ne", href: "http://recode.net/2014/03/18/the-price-of-music/", time: "2 days ago"}, 
	{title : "As Housing Costs Soar, San Francisco Seeks Ballot Solution", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/as-housing-costs-soar-san-francisco-seeks-ballot-solution.html?contentCollection=us&action=click&module=NextInCollection&region=Footer&pgtype=article", time: "2 days ago"}, 
	{title : "Mozilla Brick", site: "mozilla.i", href: "http://brick.mozilla.io/", time: "5 days ago"}, 
	{title : "Inside Shellshock: How hackers are using it to exploit systems", site: "cloudflare.co", href: "https://blog.cloudflare.com/inside-shellshock/", time: "5 days ago"}, 
	{title : "The day of the technopath", site: "thesprawl.or", href: "http://thesprawl.org/simstim/day-technopath/", time: "3 days ago"}, 
	{title : "RethinkDB and CoreOS: Navigating Digital Ocean Together", site: "justonepixel.co", href: "http://blog.justonepixel.com/geek/2014/10/03/rethinkdb-and-coreos/", time: "2 days ago"}, 
	{title : "Yahoo Nears Investment in Snapchat", site: "wsj.co", href: "http://online.wsj.com/articles/yahoo-nears-investment-in-snapchat-1412361684", time: "2 days ago"}, 
	{title : "Prison Bankers Who Profit from the Inmates", site: "time.co", href: "http://time.com/3446372/criminal-justice-prisoners-profit/", time: "5 days ago"}, 
	{title : "Don't build pages, build modules – Rethinking front-end engineering at eBay", site: "ebaytechblog.co", href: "http://www.ebaytechblog.com/2014/10/02/dont-build-pages-build-modules/", time: "2 days ago"}, 
	{title : "Social Media as Understood by Oracle Marketing vs. Oracle Legal", site: "imgur.co", href: "http://imgur.com/BGdAvWa", time: "1 day ago"}, 
	{title : "After raising $50M, Reddit forces all remote workers to relocate to SF", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/01/after-raising-50m-reddit-forces-remote-workers-to-relocate-to-sf-or-get-fired/", time: "4 days ago"}, 
	{title : "It's time to shout stop on this war on the living world", site: "theguardian.co", href: "http://www.theguardian.com/environment/georgemonbiot/2014/oct/01/george-monbiot-war-on-the-living-world-wildlife?CMP=twt_gu", time: "1 day ago"}, 
	{title : "How does SQLite work? Part 1: Pages", site: "jvns.c", href: "http://jvns.ca/blog/2014/09/27/how-does-sqlite-work-part-1-pages/", time: "8 days ago"}, 
	{title : "Tilde Club", site: "tilde.clu", href: "http://tilde.club", time: "2 days ago"}, 
	{title : "Show HN: Peercast – Stream BitTorrent video to your Chromecast in real time", site: "github.co", href: "https://github.com/mafintosh/peercast", time: "2 days ago"}, 
	{title : "Weev comes out as neo Nazi and white supremacist", site: "breitbart.co", href: "http://www.breitbart.com/Breitbart-London/2014/10/04/Convicted-hacker-and-darling-of-the-left-weev-emerges-from-prison-a-neo-Nazi-white-supremacist", time: "1 day ago"}, 
	{title : "Ancient campfires may have aided the rise of storytelling", site: "sciencemag.or", href: "http://news.sciencemag.org/archaeology/2014/09/ancient-campfires-led-rise-storytelling", time: "3 days ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math", time: "3 days ago"}, 
	{title : "Is it legitimate to “buy” Stack Overflow reputation?", site: "stackoverflow.co", href: "http://meta.stackoverflow.com/questions/270795/is-it-legitimate-to-buy-stack-overflow-reputation", time: "1 day ago"}, 
	{title : "Introducing Modelling by Example", site: "everzet.co", href: "http://everzet.com/post/99045129766/introducing-modelling-by-example", time: "2 days ago"}, 
	{title : "New Mac OS X botnet discovered", site: "drweb.co", href: "http://news.drweb.com/show/?i=5976&lng=en", time: "2 days ago"}, 
	{title : "Hacker News comments with greatest number of upvotes, by month of posting", site: "docs.google.co", href: "https://docs.google.com/spreadsheets/d/1ZwonVX_KlDYhuhPnAAnVpdVRgu4LxldP74-c_kvOd5k/edit?usp=sharing", time: "2 days ago"}, 
	{title : "A review of free sparse sequence taggers for NLP", site: "fnl.e", href: "http://fnl.es/a-review-of-sparse-sequence-taggers.html", time: "2 days ago"}, 
	{title : "After the Quake: Earliest Known Color Photographs of San Francisco", site: "mashable.co", href: "http://mashable.com/2014/10/03/san-francisco-earthquake-color-photos/", time: "2 days ago"}, 
	{title : "SortedContainers: Pure-Python sorted containers that are as fast as C extensions", site: "grantjenks.co", href: "http://www.grantjenks.com/docs/sortedcontainers/", time: "2 days ago"}, 
	{title : "U.S. stockpiling nukes to protect Earth from asteroids", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/federal-eye/wp/2014/10/02/u-s-plan-to-save-earth-from-giant-asteroids-use-old-nukes/", time: "2 days ago"}, 
	{title : "Your Ancestors Didn't Sleep Like You – Are We Doing It Wrong?", site: "earthweareone.co", href: "http://earthweareone.com/your-ancestors-didnt-sleep-like-you-are-we-doing-it-wrong/", time: "2 days ago"}, 
]