news24 = [
	{title : "Reddit Forces Remote Workers to Live in San Francisco or Lose Job", site: "cbslocal.co", href: "http://sanfrancisco.cbslocal.com/2014/10/02/reddit-forcing-remote-workers-to-move-to-san-francisco-or-lose-job-tech-employee-fired-termination-relocate/", time: "3 days ago"}, 
	{title : "GCSS – Pure Go CSS Preprocessor", site: "github.co", href: "https://github.com/yosssi/gcss", time: "8 days ago"}, 
	{title : "How Two Men Unlocked Modern Encryption", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/09/how-two-men-unlocked-modern-encryption/380520/", time: "12 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://www.paulgraham.com/before.html", time: "3 days ago"}, 
	{title : "What I Learned from My Time in Prison", site: "dailystormer.co", href: "http://www.dailystormer.com/what-i-learned-from-my-time-in-prison/", time: "3 days ago"}, 
	{title : "Test your email server encryption", site: "ssl-tools.ne", href: "https://ssl-tools.net/mailservers/", time: "9 days ago"}, 
	{title : "Londoners give up eldest children in public Wi-Fi security horror show", site: "theguardian.co", href: "http://www.theguardian.com/technology/2014/sep/29/londoners-wi-fi-security-herod-clause", time: "6 days ago"}, 
	{title : "Gaspard, the anti-assault accessory: never be alone again", site: "mygaspard.co", href: "http://mygaspard.com/index.php?lang=en", time: "2 days ago"}, 
	{title : "What It’s Like to Fly the $23,000 Singapore Airlines Suites Class", site: "medium.co", href: "https://medium.com/travel-adventure/what-its-like-to-fly-the-23-000-singapore-airlines-suites-class-17d9f3fee0d", time: "5 days ago"}, 
	{title : "Eve Raises $2.3M to Rethink Programming", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/eve-raises-2-3m-to-rethink-programming/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29", time: "4 days ago"}, 
	{title : "What It's Like to Fly the $23,000 Singapore Airlines Suites Class", site: "dereklow.c", href: "http://dereklow.co/what-its-like-to-fly-the-23000-singapore-airlines-suites-class/", time: "5 days ago"}, 
	{title : "ACPI, kernels and contracts with firmware", site: "mjg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32369.html", time: "19 days ago"}, 
	{title : "Game about squares", site: "gameaboutsquares.co", href: "http://gameaboutsquares.com/", time: "70 days ago"}, 
	{title : "Call me maybe: Elasticsearch", site: "aphyr.co", href: "http://aphyr.com/posts/317-call-me-maybe-elasticsearch", time: "108 days ago"}, 
	{title : "Being in “flow”: the most addictive element in programming", site: "valbonneconsulting.wordpress.co", href: "http://valbonneconsulting.wordpress.com/2014/09/24/flow-the-addiction-behind-programming/", time: "10 days ago"}, 
	{title : "JPMorgan Discovers Further Cyber Security Issues", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/02/jpmorgan-discovers-further-cyber-security-issues/", time: "3 days ago"}, 
	{title : "Compressor.io – Compress and optimize your images", site: "compressor.i", href: "http://compressor.io", time: "137 days ago"}, 
	{title : "Dining Philosophers Rebooted", site: "howardhinnant.github.i", href: "http://howardhinnant.github.io/dining_philosophers.html", time: "3 days ago"}, 
	{title : "Building a block-chain database the right way", site: "coinspect.c", href: "http://blog.coinspect.co/building-block-chain-database-right-way", time: "3 days ago"}, 
	{title : "How to handle a text spammer", site: "tickld.co", href: "http://www.tickld.com/x/the-best-text-reply-ever-this-is-gold", time: "3 days ago"}, 
	{title : "Hong Kong protest: Why are pro-democracy supporters staging a sit-in?", site: "independent.co.u", href: "http://www.independent.co.uk/news/world/asia/hong-kong-protest-why-are-prodemocracy-supporters-staging-a-sitin-9760234.html", time: "7 days ago"}, 
	{title : "Miguel de Icaza's Markdown Style Guide", site: "tirania.or", href: "http://tirania.org/blog/archive/2014/Sep-30.html", time: "4 days ago"}, 
	{title : "Judge Rebukes Government, Keeps Gitmo Force-Feeding Hearing Open", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/judge-knocks-government-attempt-keep-gitmo-hearing-secret/", time: "3 days ago"}, 
	{title : "HFT in My Backyard", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/09/22/hft-in-my-backyard-part-i/", time: "12 days ago"}, 
	{title : "Elon Musk says next year's Tesla cars will be able to self-drive 90% of the time", site: "theverge.co", href: "http://www.theverge.com/2014/10/2/6894875/elon-musk-says-next-years-tesla-cars-will-be-able-to-self-drive-90-percent-of-the-time", time: "3 days ago"}, 
	{title : "The Days They Changed the Gauge (1966)", site: "railfan.ne", href: "http://southern.railfan.net/ties/1966/66-8/gauge.html", time: "9 days ago"}, 
	{title : "Recruiter Trolling on GitHub", site: "github.co", href: "https://github.com/thoughtbot/liftoff/pull/178#issuecomment-57688590", time: "3 days ago"}, 
	{title : "Lee Sedol wins historic jubango against Gu Li", site: "gogameguru.co", href: "https://gogameguru.com/lee-sedol-wins-jubango/", time: "6 days ago"}, 
]