news28 = [
	{title : "Show HN: Do you hate salesforce?", site: "ihatesalesforce.co", href: "http://ihatesalesforce.com", time: "3 days ago"}, 
	{title : "Germany plans to make sending colleagues work emails after 6pm illegal", site: "metro.co.u", href: "http://metro.co.uk/2014/10/02/germany-plans-to-make-sending-colleagues-work-emails-after-6pm-illegal-4889633/", time: "3 days ago"}, 
	{title : "Learn computer vision in a single weekend", site: "pyimagesearch.co", href: "https://www.pyimagesearch.com/practical-python-opencv/?__vid=0ebac5e0138c0132dac522000b340435&email=artolaya%40gmail.com", time: "3 days ago"}, 
	{title : "Reclining airplane seats and the endowment effect", site: "slate.co", href: "http://www.slate.com/articles/health_and_science/science/2014/09/airplane_seat_reclining_can_economics_reveal_who_deserves_the_space.single.html", time: "3 days ago"}, 
	{title : "Multiple Template Engines for Django", site: "indiegogo.co", href: "https://www.indiegogo.com/projects/multiple-template-engines-for-django", time: "4 days ago"}, 
	{title : "How EA’s jet-setting founder avoided $26M in taxes", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/how-eas-jet-setting-founder-avoided-26-million-in-taxes/", time: "3 days ago"}, 
	{title : "Rethinking the origins of the universe", site: "unc.ed", href: "http://unc.edu/spotlight/rethinking-the-origins-of-the-universe/", time: "11 days ago"}, 
	{title : "What Ever Happened to the Founders of Sierra Online?", site: "simpleprogrammer.co", href: "http://simpleprogrammer.com/2014/09/29/ever-happened-founders-sierra-online", time: "3 days ago"}, 
	{title : "On Thailand’s immigration police targeting digital nomads", site: "levels.i", href: "https://levels.io/thailands-immigration-police-targeting-digital-nomads/", time: "4 days ago"}, 
	{title : "Intel pulls equality ads in response to anti-feminist pressure", site: "theverge.co", href: "http://www.theverge.com/2014/10/2/6886747/intel-buckles-to-anti-feminist-campaign-by-pulling-ads-from-gaming", time: "3 days ago"}, 
	{title : "Reddit CEO Yishan Wong on Giving Stock to Users: “We Have a Crazy Plan.”", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/reddit-fundraising/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29&utm_content=FaceBook", time: "5 days ago"}, 
	{title : "Hipcamp Raises $2M to Get People Camping", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/hipcamp-cooks-up-2m-seed-to-get-people-camping/", time: "5 days ago"}, 
	{title : "Cosmos Browser – Connect to the Internet via SMS, no data or wifi required", site: "github.co", href: "https://github.com/ColdSauce/CosmosBrowserAndroid", time: "24 days ago"}, 
	{title : "The Coordinator pattern", site: "redbooth.co", href: "https://redbooth.com/engineering/javascript/the-coordinator-pattern", time: "4 days ago"}, 
	{title : "The Wolf", site: "randsinrepose.co", href: "http://randsinrepose.com/archives/the-wolf/", time: "34 days ago"}, 
	{title : "The Racial Dot Map: One Dot Per Person for the Entire U.S.", site: "coopercenter.or", href: "http://demographics.coopercenter.org/DotMap/index.html", time: "24 days ago"}, 
	{title : "First-Ever Expedition to Turkmenistan's “Door to Hell”", site: "nationalgeographic.co", href: "http://news.nationalgeographic.com/news/energy/2014/07/140716-door-to-hell-darvaza-crater-george-kourounis-expedition/", time: "76 days ago"}, 
	{title : "Holy Grail", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Holy_Grail_(web_design)", time: "3 days ago"}, 
	{title : "Farewell CoffeeScript", site: "github.co", href: "https://github.com/staltz/rxmarbles/commit/57e37f176e0e005abd2c4fa0253bbd8f57fe1bd9", time: "3 days ago"}, 
	{title : "OpenWrt BarrierBreaker 14.07", site: "openwrt.or", href: "https://forum.openwrt.org/viewtopic.php?pid=242292#p242292", time: "3 days ago"}, 
	{title : "Design for Assembly in KiCad", site: "rheingoldheavy.co", href: "http://rheingoldheavy.com/design-assembly-kicad/", time: "3 days ago"}, 
	{title : "C++11/14 compiler and library shootout", site: "cpprocks.co", href: "http://cpprocks.com/c1114-compiler-and-library-shootout/", time: "3 days ago"}, 
	{title : "Declassified photos from Tinian Island as the B-29 “Enola Gay” was being loaded", site: "archive.toda", href: "https://archive.today/94EKG", time: "5 days ago"}, 
	{title : "The Downtown Project Suicides", site: "recode.ne", href: "http://recode.net/2014/10/01/the-downtown-project-suicides-can-the-pursuit-of-happiness-kill-you/", time: "4 days ago"}, 
	{title : "Moscone Effect: What Dreamforce and Big Conferences Mean for Airbnb", site: "beyondpricing.co", href: "https://blog.beyondpricing.com/the-moscone-effect?rel=hn", time: "3 days ago"}, 
	{title : "Lever (YC S12) raises $10M to make hiring awesome", site: "lever.c", href: "https://blog.lever.co/the-next-chapter/", time: "3 days ago"}, 
	{title : "EC2 Maintenance Update II", site: "amazon.co", href: "http://aws.amazon.com/blogs/aws/ec2-maintenance-update-2/", time: "4 days ago"}, 
]