news34 = [
	{title : "Eleventh Grade Tech Trends", site: "medium.co", href: "https://medium.com/musings-about-text-boxes/eleventh-grade-tech-trends-aca537e9ce62", time: "18 days ago"}, 
	{title : "Universal SSL: Be just a bit more patient", site: "cloudflare.co", href: "https://blog.cloudflare.com/universal-ssl-be-just-a-bit-more-patient/", time: "5 days ago"}, 
	{title : "NerdytData patches Shellshock in a single crawl", site: "nerdydata.co", href: "http://blog.nerdydata.com/post/98906853956/nerdydata-patches-shellshock-in-a-single-crawl", time: "4 days ago"}, 
	{title : "Lecture 3: Counterintuitive Parts of Startups, and How to Have Ideas", site: "genius.co", href: "http://tech.genius.com/Paul-graham-lecture-3-counterintuitive-parts-of-startups-and-how-to-have-ideas-annotated", time: "4 days ago"}, 
	{title : "Firefox Considering Tor Integration", site: "torproject.or", href: "https://lists.torproject.org/pipermail/tor-dev/2014-September/007533.html", time: "4 days ago"}, 
	{title : "CVE-2014-7187 (yet another) Bash arbitrary execution of code", site: "redhat.co", href: "https://access.redhat.com/security/cve/CVE-2014-7187", time: "4 days ago"}, 
	{title : "Steve Wozniak on starting companies, solving problems, finding happiness", site: "fastcodesign.co", href: "http://www.fastcodesign.com/3036366/the-wisdom-of-woz", time: "5 days ago"}, 
	{title : "Show HN: Dabble Me – the open source replacement for OhLife", site: "dabble.m", href: "https://dabble.me", time: "6 days ago"}, 
	{title : "How Jerry Yang Made the Most Lucrative Bet in Tech History", site: "forbes.co", href: "http://www.forbes.com/sites/parmyolson/2014/09/30/how-jerry-yang-made-the-most-lucrative-bet-in-tech-history/", time: "5 days ago"}, 
	{title : "How 50 startups manage their code", site: "foundersgrid.co", href: "http://foundersgrid.com/code-management", time: "4 days ago"}, 
	{title : "Beating the Tinder game: 800+ Matches. I’ll probably get banned for this…", site: "medium.co", href: "https://medium.com/@blakejamieson/beating-the-tinder-game-4f08c9ec0d80", time: "4 days ago"}, 
	{title : "Show HN: Privacy – PGP Messenger", site: "medium.co", href: "https://medium.com/@krzyzanowskim/privacy-pgp-messenger-9612cd6bc08", time: "4 days ago"}, 
	{title : "Idiomatic Generics in Go", site: "bouk.c", href: "http://bouk.co/blog/idiomatic-generics-in-go/", time: "5 days ago"}, 
	{title : "Move Fast and Break Things", site: "xkcd.co", href: "http://xkcd.com/1428/", time: "4 days ago"}, 
	{title : "Compatibility tables for default local fonts", site: "fontfamily.i", href: "http://fontfamily.io/", time: "5 days ago"}, 
	{title : "What “technical” concerns do I have with systemd?", site: "lusis.or", href: "http://blog.lusis.org/blog/2014/09/23/end-of-linux/", time: "11 days ago"}, 
	{title : "What Working for Apple Is Really Like", site: "businessinsider.com.a", href: "http://www.businessinsider.com.au/these-people-are-nuts-what-working-for-apple-is-really-like-2014-10", time: "4 days ago"}, 
	{title : "Just some simple game", site: "ioxapp.co", href: "http://game.ioxapp.com/color/", time: "7 days ago"}, 
	{title : "Windows 10 is the official name for Microsoft's next version of Windows", site: "theverge.co", href: "http://www.theverge.com/2014/9/30/6868695/microsoft-windows-9-announced-official", time: "5 days ago"}, 
	{title : "Emergent – Realtime Rumor Tracker", site: "emergent.inf", href: "http://www.emergent.info/", time: "9 days ago"}, 
	{title : "Kickstarter: film photography", site: "kickstarter.co", href: "https://www.kickstarter.com/projects/filmferrania/100-more-years-of-analog-film", time: "5 days ago"}, 
	{title : "Bugging out: How rampant online piracy squashed one insect photographer", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/one-mans-endless-hopeless-struggle-to-protect-his-copyrighted-images/", time: "11 days ago"}, 
	{title : "The Design and Implementation of the FreeBSD Operating System, 2nd ed.", site: "amazon.co", href: "http://www.amazon.com/Design-Implementation-FreeBSD-Operating-Edition/dp/0321968972/ref=zg_bs_3756_28", time: "18 days ago"}, 
	{title : "Exposing Hidden Biases at Google to Improve Diversity", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/25/technology/exposing-hidden-biases-at-google-to-improve-diversity.html", time: "11 days ago"}, 
	{title : "Quick Explore of the Ello API", site: "github.co", href: "https://gist.github.com/conatus/cc665f917d5558c123bc", time: "8 days ago"}, 
	{title : "Why a Dead Alkaline Battery Bounces [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=qrGV7zKEdtU", time: "31 days ago"}, 
	{title : "Bypassing AngularJS Sandbox and winning a $5,000 Google bug bounty", site: "avlidienbrunn.s", href: "http://avlidienbrunn.se/angular.txt", time: "11 days ago"}, 
	{title : "Why can't you track periods in Apple's Health app?", site: "ntlk.ne", href: "http://ntlk.net/2014/09/26/why-cant-you-track-periods-in-apples-health-app/", time: "9 days ago"}, 
	{title : "Cons is your friend", site: "kaygun.tumblr.co", href: "http://kaygun.tumblr.com/post/96866991234/cons-is-your-friend", time: "24 days ago"}, 
]