news32 = [
	{title : "A Rare Look at Apple's Design Genius Jony Ive", site: "vogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive/", time: "4 days ago"}, 
	{title : "Anti-selfconsciousness and John Stuart Mill and Carlyle", site: "theliterarylink.co", href: "http://theliterarylink.com/anti_selfconsciousness.html", time: "4 days ago"}, 
	{title : "Universal SSL: How It Scales", site: "cloudflare.co", href: "https://blog.cloudflare.com/universal-ssl-how-it-scales/", time: "4 days ago"}, 
	{title : "Show HN: Shared reading list and bookmarks for teams", site: "readonomy.co", href: "https://www.readonomy.com/?hn", time: "4 days ago"}, 
	{title : "This Time The Bubble Will Implode", site: "arielmichaeli.co", href: "http://arielmichaeli.com/2014/09/this-time-the-bubble-will-implode/", time: "4 days ago"}, 
	{title : "Adam Sandler to star in four movies exclusively for Netflix", site: "ew.co", href: "http://insidemovies.ew.com/2014/10/02/adam-sandler-netflix-movies/", time: "3 days ago"}, 
	{title : "Webfont optimization", site: "developers.google.co", href: "https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization", time: "4 days ago"}, 
	{title : "The Effort to Bring “Habitat” Back to Life", site: "wired.co", href: "http://www.wired.com/2014/10/restoring-habitat/", time: "4 days ago"}, 
	{title : "Raising Capital: Advice We Give Our Founders", site: "a16z.co", href: "https://a16z.com/2014/09/26/valuation-this-is-the-advice-we-give-our-founders/", time: "7 days ago"}, 
	{title : "Show HN: Go channels as a C library (with Obj-C wrapper)", site: "github.co", href: "https://github.com/davekeck/eb_chan", time: "4 days ago"}, 
	{title : "Microsoft Announces Windows 10", site: "theverge.co", href: "http://live.theverge.com/microsoft-windows-9-event-live-blog/", time: "5 days ago"}, 
	{title : "Facebook Apologizes to LGBT Community and Promises Changes to Real Name Policy", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/facebook-apologizes-to-lgbt-community-and-promises-changes-to-real-name-policy/", time: "4 days ago"}, 
	{title : "Node.js Best Practices", site: "joyent.co", href: "https://www.joyent.com/developers/node/design", time: "16 days ago"}, 
	{title : "What’s a Bitcoin Look Like? The Story Behind This Popular Photograph", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/what-s-a-bitcoin-look-like-popular-photograph-has-story.html", time: "4 days ago"}, 
	{title : "The Race to the Bottom of the 3D Engines", site: "irrlicht3d.or", href: "http://www.irrlicht3d.org/pivot/entry.php?id=1440", time: "3 days ago"}, 
	{title : "Machine learning is teaching us the secret to teaching", site: "nautil.u", href: "http://nautil.us/issue/6/secret-codes/teaching-me-softly", time: "7 days ago"}, 
	{title : "Current and upcoming robots on American farms", site: "engadget.co", href: "http://www.engadget.com/2014/09/22/robot-farming-explainer/", time: "4 days ago"}, 
	{title : "Security Breach: The London Mail Rail (2011)", site: "placehacking.co.u", href: "http://www.placehacking.co.uk/2011/04/24/security-breach-london-mail-rail/", time: "4 days ago"}, 
	{title : "DevOps: From Unicorns to Horses", site: "amplifypartners.co", href: "http://www.amplifypartners.com/interviews/devops-from-unicorns-to-horses/", time: "4 days ago"}, 
	{title : "SendGrid Replaces CEO", site: "xconomy.co", href: "http://www.xconomy.com/boulder-denver/2014/09/30/franklin-out-vmlogix-and-citrix-exec-in-as-sendgrid-replaces-ceo/", time: "4 days ago"}, 
	{title : "The Man Who Fought the Synanon Cult and Won", site: "gizmodo.co", href: "http://paleofuture.gizmodo.com/the-man-who-fought-cults-and-won-1634267961", time: "7 days ago"}, 
	{title : "Mobile Web App Checklist", site: "luster.i", href: "http://www.luster.io/blog/9-29-14-mobile-web-checklist.html", time: "11 days ago"}, 
	{title : "Show HN: ScaleDrone, push messaging that makes sense", site: "scaledrone.co", href: "https://www.scaledrone.com/", time: "4 days ago"}, 
	{title : "Simple, secure cloud storage", site: "leastauthority.co", href: "https://leastauthority.com/", time: "4 days ago"}, 
	{title : "Clojure Cup 2014 Apps", site: "clojurecup.co", href: "https://clojurecup.com/#/apps", time: "6 days ago"}, 
]