news9 = [
	{title : "A State of Xen – Chaos Monkey and Cassandra", site: "netflix.co", href: "http://techblog.netflix.com/2014/10/a-state-of-xen-chaos-monkey-cassandra.html", time: "3 days ago"}, 
	{title : "Schneier on Incident Response", site: "lwn.ne", href: "http://lwn.net/Articles/612818/", time: "1 day ago"}, 
	{title : "How to get every game on STEAM for free", site: "gamasutra.co", href: "http://www.gamasutra.com/blogs/LeszekLisowski/20141001/226840/How_to_get_every_game_on_STEAM_for_free.php", time: "1 day ago"}, 
	{title : "In 1976 I discovered Ebola, now I fear an unimaginable tragedy", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/04/ebola-zaire-peter-piot-outbreak", time: "1 day ago"}, 
	{title : "Colleges Make It Easier for Students to Show, Not Tell, in Their Applications", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/28/education/college-admissions-goucher-video.html", time: "1 day ago"}, 
	{title : "Saeed Malekpour, programmer and political prisoner in Iran", site: "github.co", href: "https://github.com/saeedmalekpour", time: "1 day ago"}, 
	{title : "William Binney Explains Snowden Docs", site: "alexaobrien.co", href: "http://www.alexaobrien.com/secondsight/wb/binney.html", time: "5 days ago"}, 
	{title : "National Nurse Survey Shows Hospitals Still Not Prepared for U.S. Ebola Patients", site: "nationalnursesunited.or", href: "http://www.nationalnursesunited.org/press/entry/national-nurse-survey-shows-hospitals-still-not-prepared-for-us-ebola/", time: "1 day ago"}, 
	{title : "How the Hash Works in Ruby", site: "gotealeaf.co", href: "http://www.gotealeaf.com/blog/how-the-hash-works-in-ruby/", time: "1 day ago"}, 
	{title : "Why Not Eat Octopus?", site: "newyorker.co", href: "http://www.newyorker.com/tech/elements/eating-octopus", time: "1 day ago"}, 
	{title : "Phison USB Custom Firmware and Existing Firmware Patches", site: "github.co", href: "https://github.com/adamcaudill/Psychson", time: "2 days ago"}, 
	{title : "BAP: Binary Analysis Platform", site: "cmu.ed", href: "http://bap.ece.cmu.edu/", time: "4 days ago"}, 
	{title : "The Ambiguities of Prison Gangs", site: "theatlantic.co", href: "http://www.theatlantic.com/national/archive/2014/10/gangs-and-prisons/381034/?single_page=true", time: "2 days ago"}, 
	{title : "Can Big Data Tell Us What Clinical Trials Don’t?", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/magazine/can-big-data-tell-us-what-clinical-trials-dont.html?rref=magazine&module=Ribbon&version=context&region=Header&action=click&contentCollection=Magazine&pgtype=article", time: "1 day ago"}, 
	{title : "Supporting idea convergence through pedagogical scripts and Etherpad APIs", site: "reganmian.ne", href: "http://reganmian.net/blog/2014/10/03/supporting-idea-convergence-through-pedagogical-scripts/", time: "1 day ago"}, 
	{title : "“The Peripheral” by William Gibson (Excerpt)", site: "williamgibsonbooks.co", href: "http://williamgibsonbooks.com/books/the_peripheral_excerpt.asp", time: "1 day ago"}, 
	{title : "This is Water: a commencement speech by David Foster Wallace [pdf]", site: "purdue.ed", href: "http://web.ics.purdue.edu/~drkelly/DFWKenyonAddress2005.pdf", time: "1 day ago"}, 
	{title : "Three Years on Rikers Without Trial", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/06/law-3", time: "3 days ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29465446", time: "2 days ago"}, 
	{title : "Hackers’ Attack Cracked 10 Financial Institutions in Major Assault", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/03/hackers-attack-cracked-10-banks-in-major-assault/", time: "2 days ago"}, 
	{title : "John Carmack on Inlined Code", site: "number-none.co", href: "http://number-none.com/blow/john_carmack_on_inlined_code.html", time: "9 days ago"}, 
	{title : "New Map Exposes Previously Unseen Details of Seafloor", site: "ucsd.ed", href: "https://scripps.ucsd.edu/news/new-map-exposes-previously-unseen-details-seafloor", time: "2 days ago"}, 
	{title : "Place SSH users in Docker jails (or as replacement for docker-bash / dockersh)", site: "github.co", href: "https://github.com/clevcode/docker-cmd", time: "2 days ago"}, 
]