news31 = [
	{title : "Parallel In-Place Merge Sort", site: "drdobbs.co", href: "http://www.drdobbs.com/parallel/parallel-in-place-merge-sort/240169094", time: "4 days ago"}, 
	{title : "Mining Bitcoin with pencil and paper: 0.67 hashes per day", site: "righto.co", href: "http://www.righto.com/2014/09/mining-bitcoin-with-pencil-and-paper.html", time: "7 days ago"}, 
	{title : "On the role of GRBs on life extinction in the Universe", site: "arxiv.or", href: "http://arxiv.org/abs/1409.2506", time: "4 days ago"}, 
	{title : "Coinbase Expands to 5 More Countries and Raises Limits for European Users", site: "coinbase.co", href: "http://blog.coinbase.com/post/98952363012/coinbase-expands-to-5-more-countries-and-raises-limits", time: "3 days ago"}, 
	{title : "The New York Times’ App Plan Isn’t Working, So It’s Laying Off Staff", site: "recode.ne", href: "http://recode.net/2014/10/01/the-new-york-times-app-plan-isnt-working-so-its-laying-off-staff/", time: "4 days ago"}, 
	{title : "A DOMain of Shadows", site: "gbracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html?m=1", time: "4 days ago"}, 
	{title : "Walrus mass in vast numbers on Alaska beach as sea ice retreats", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/walrus-mass-vast-numbers-alaska-beach-sea-ice-retreats", time: "3 days ago"}, 
	{title : "On a farm in Missouri, a radical experiment in self-sufficiency (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/12/23/the-civilization-kit", time: "5 days ago"}, 
	{title : "Making a homemade metal semi-automatic rifle just got easy", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/making-a-homemade-metal-semi-automatic-rifle-just-got-crazy-easy/", time: "4 days ago"}, 
	{title : "Google Drops Compute Engine Prices by 10 Percent", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/google-drops-all-compute-engine-prices-by-10-percent/", time: "4 days ago"}, 
	{title : "Drone captures scale of Hong Kong protest [video]", site: "bbc.co", href: "http://www.bbc.com/news/world-asia-29421914", time: "4 days ago"}, 
	{title : "Sxript: Arbitrary-precision math and programming environment", site: "umass.ed", href: "http://people.umass.edu/wfbarnes/STxAxTICMathWriteup.html", time: "4 days ago"}, 
	{title : "Linear Optimization with Glop", site: "developers.google.co", href: "https://developers.google.com/optimization/docs/lp/glop", time: "4 days ago"}, 
	{title : "Show HN: HackerBracket – What are you working on?", site: "hackerbracket.co", href: "https://www.hackerbracket.com/v/2", time: "4 days ago"}, 
	{title : "Tor growth rates", site: "docs.google.co", href: "https://docs.google.com/document/d/1SaBK664SchhZOP9XBsB8KK63k4xlmMTlkhfF28f2204/pub", time: "4 days ago"}, 
	{title : "Scientific writing: the online cooperative", site: "nature.co", href: "http://www.nature.com/news/scientific-writing-the-online-cooperative-1.16039", time: "4 days ago"}, 
	{title : "Inside the Cosmonaut Survival Kit (2013)", site: "theappendix.ne", href: "http://theappendix.net/blog/2013/11/the-cosmonauts-survival-kit", time: "5 days ago"}, 
	{title : "Is Alzheimer's Type 3 Diabetes? (2012)", site: "opinionator.blogs.nytimes.co", href: "http://opinionator.blogs.nytimes.com/2012/09/25/bittman-is-alzheimers-type-3-diabetes/", time: "4 days ago"}, 
	{title : "Digital.nyc – NYC's hub for tech and startups", site: "digital.ny", href: "http://www.digital.nyc", time: "4 days ago"}, 
	{title : "Source Code Optimization (2009) [pdf]", site: "linux-kongress.or", href: "http://www.linux-kongress.org/2009/slides/compiler_survey_felix_von_leitner.pdf", time: "4 days ago"}, 
	{title : "35,000 Walruses Gathered in Alaska", site: "businessinsider.co", href: "http://www.businessinsider.com/35000-walruses-gathered-in-alaska-2014-10", time: "4 days ago"}, 
	{title : "Show HN: EBay for 3D Printing", site: "printthis4.m", href: "https://printthis4.me", time: "4 days ago"}, 
	{title : "Doctors Find Barriers to Sharing Digital Medical Records", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/01/business/digital-medical-records-become-common-but-sharing-remains-challenging.html", time: "4 days ago"}, 
	{title : "Recruiting Tech Talent in High School", site: "wsj.co", href: "http://online.wsj.com/articles/recruiting-tech-talent-in-high-school-1412220618", time: "4 days ago"}, 
	{title : "LibreSSL: More Than 30 Days Later", site: "openbsd.or", href: "http://www.openbsd.org/papers/eurobsdcon2014-libressl.html", time: "7 days ago"}, 
	{title : "Clustering of bigram frequencies", site: "gottwurfelt.co", href: "http://gottwurfelt.com/2014/10/01/clustering-of-bigram-frequencies/", time: "4 days ago"}, 
	{title : "The Future of Iced Coffee", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/08/the-future-of-iced-coffee/375114/", time: "4 days ago"}, 
	{title : "Is this why Microsoft named it Windows 10?", site: "cnet.co", href: "http://www.cnet.com/news/is-this-why-microsoft-named-it-windows-10/", time: "3 days ago"}, 
	{title : "Show HN: WeTopTen – Create top 10 of books, movies, albums and more", site: "wetopten.co", href: "http://wetopten.com", time: "4 days ago"}, 
]