news26 = [
	{title : "Mysql_real_escape_string wont solve your SQL injection security bugs", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/mysql_real_escape_string-wont-magically-solve-your-sql-injection-problems/", time: "1 day ago"}, 
	{title : "Instant.io - Massive Google Translate (built in 8 hours)", site: "instant.i", href: "http://instant.io/", time: "1237 days ago"}, 
	{title : "The Next Big Programming Language You've Never Heard of – WIRED", site: "wired.co", href: "http://www.wired.com/2014/07/d-programming-language/", time: "1 day ago"}, 
	{title : "Evercookie used by NSA to track TOR users across browsers", site: "wikipedia.or", href: "https://en.wikipedia.org/wiki/Evercookie", time: "2 days ago"}, 
	{title : "JPMorgan Employee Password Was Key in Hack Hitting 76M Homes", site: "bloomberg.co", href: "http://mobile.bloomberg.com/news/2014-10-02/jpmorgan-says-data-breach-affected-76-million-households.html", time: "2 days ago"}, 
	{title : "RIP: Rapportive.  Finally stopped working today :(", site: "rapportive.co", href: "https://rapportive.com/", time: "170 days ago"}, 
	{title : "Creepy guys inspire Seattle women to make a new dating app", site: "seattletimes.co", href: "http://seattletimes.com/html/localnews/2024665918_sirendatingappxml.html", time: "4 days ago"}, 
	{title : "Google threatened with lawsuit over nude celebrity photos", site: "theguardian.co", href: "http://www.theguardian.com/technology/2014/oct/02/google-lawsuit-nude-celebrity-photos", time: "3 days ago"}, 
	{title : "Butterfly Labs mined Bitcoins on customers’ boxes before shipping", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/feds-butterfly-labs-mined-bitcoins-on-customers-boxes-before-shipping/", time: "6 days ago"}, 
	{title : "How History Forgot Its Role in Public Debate", site: "aeon.c", href: "http://aeon.co/magazine/society/how-history-forgot-its-role-in-public-debate/", time: "3 days ago"}, 
	{title : "Raw data from rDNS scan of the whole v4 Internet (2011)", site: "archive.or", href: "https://archive.org/details/mass-rdns-2011-02", time: "3 days ago"}, 
	{title : "Ken Silverman's PND3D engine", site: "advsys.ne", href: "http://advsys.net/ken/voxlap/pnd3d.htm", time: "3 days ago"}, 
	{title : "The Evolution of Sleep: 700M Years of Melatonin", site: "nytimes.co", href: "http://nytimes.com/2014/10/02/science/the-evolution-of-sleep-700-million-years-of-melatonin.html?_r=0&referrer=", time: "3 days ago"}, 
	{title : "“A Tesla car next year will probably be 90 percent capable of autopilot.”", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/02/elon-musk-tesla-will-be-90-automated-next-year-shame-on-silicon-valley-if-were-not-the-leader/", time: "3 days ago"}, 
	{title : "Silk Road Lawyers Poke Holes in FBI’s Story", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/silk-road-lawyers-poke-holes-in-fbis-story/", time: "3 days ago"}, 
	{title : "A Danish company is building a $335M seawall around New York", site: "theverge.co", href: "http://www.theverge.com/2014/10/1/6874925/can-a-massive-seawall-save-new-york-from-flooding", time: "3 days ago"}, 
	{title : "Online Linear Regression Using a Kalman Filter", site: "thealgoengineer.co", href: "http://www.thealgoengineer.com/2014/online_linear_regression_kalman_filter/", time: "3 days ago"}, 
	{title : "Police Used a Drone to Chase Down and Arrest Four DUI Suspects in a Cornfield", site: "vice.co", href: "http://motherboard.vice.com/read/police-used-a-drone-to-chase-down-and-arrest-four-dui-suspects-in-a-cornfield", time: "3 days ago"}, 
	{title : "SyncFree Consortium / Programming Models, Part 2: QuickChecking Derflow", site: "christophermeiklejohn.co", href: "http://christophermeiklejohn.com/derflow/erlang/2014/10/01/quickchecking-derflow.html", time: "3 days ago"}, 
	{title : "Council removes Banksy artwork after complaints of racism", site: "theguardian.co", href: "http://www.theguardian.com/artanddesign/2014/oct/01/banksy-mural-clacton-racist", time: "3 days ago"}, 
	{title : "A Nomic game in Haskell", site: "nomyx.ne", href: "http://www.nomyx.net/", time: "3 days ago"}, 
	{title : "At 17, Setting Off Protests That Roil Hong Kong", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/world/asia/hong-kong-china-democracy-protests-students.html", time: "3 days ago"}, 
	{title : "MemSQL Does Oracle’s Own Demo Ten Times as Fast, Sixty Times Cheaper", site: "memsql.co", href: "http://blog.memsql.com/memsql-does-oracles-own-demo-ten-times-as-fast-sixty-times-cheaper/", time: "4 days ago"}, 
	{title : "Hopscotch: Towards User Interface Composition (2008) [pdf]", site: "bracha.or", href: "http://bracha.org/hopscotch-wasdett.pdf", time: "3 days ago"}, 
	{title : "After 31 years, Lotus-1-2-3 spreadsheet support has ended", site: "zdnet.co", href: "http://www.zdnet.com/so-farewell-then-lotus-1-2-3-spreadsheet-extraordinaire-7000034288/", time: "3 days ago"}, 
	{title : "Google reportedly tried to buy Cyanogen", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/google-reportedly-tried-to-buy-cyanogen-inc/", time: "3 days ago"}, 
	{title : "Extensible Web Resource Loading Manifesto", site: "igvita.co", href: "https://www.igvita.com/2014/10/02/extensible-web-resource-loading-manifesto/", time: "3 days ago"}, 
	{title : "Research at Facebook", site: "fb.co", href: "http://newsroom.fb.com/news/2014/10/research-at-facebook/", time: "3 days ago"}, 
]