news7 = [
	{title : "As Many as 5K .Com’s Taken Away by Sealed Court Order by Verisign", site: "thedomains.co", href: "http://www.thedomains.com/2014/10/02/as-many-as-5k-coms-taken-away-by-sealed-court-order-by-verisign-including-some-of-mine/", time: "2 days ago"}, 
	{title : "'God View': Uber Allegedly Stalked Users for Party-Goers' Viewing Pleasure", site: "forbes.co", href: "http://www.forbes.com/sites/kashmirhill/2014/10/03/god-view-uber-allegedly-stalked-users-for-party-goers-viewing-pleasure/", time: "10 hours ago"}, 
	{title : "All of IT", site: "eldelshell.co", href: "http://www.eldelshell.com/all-of-it.html", time: "16 hours ago"}, 
	{title : "Refactoring Ruby with Monads", site: "codon.co", href: "http://codon.com/refactoring-ruby-with-monads", time: "2 days ago"}, 
	{title : "Why Coconuts Could Be the Hydrogen Storage Material of the Future", site: "technologyreview.co", href: "http://www.technologyreview.com/view/531416/why-coconuts-could-be-the-hydrogen-storage-material-of-the-future/", time: "2 days ago"}, 
	{title : "Show HN: JuliusJS – Speech recognition in JavaScript", site: "github.co", href: "https://github.com/zzmp/juliusjs", time: "2 days ago"}, 
	{title : "Mistakes AngularJS Developers Make", site: "airpair.co", href: "http://www.airpair.com/angularjs/posts/top-10-mistakes-angularjs-developers-make", time: "2 days ago"}, 
	{title : "How the world’s health organizations failed to stop the Ebola disaster", site: "washingtonpost.co", href: "http://www.washingtonpost.com/sf/national/2014/10/04/how-ebola-sped-out-of-control/", time: "1 day ago"}, 
	{title : "The history of our world in 18 minutes", site: "ted.co", href: "https://www.ted.com/talks/david_christian_big_history", time: "12 hours ago"}, 
	{title : "Ello: Be ready to say goodbye", site: "zdnet.co", href: "http://www.zdnet.com/ello-be-ready-to-say-goodbye-7000034333/", time: "12 hours ago"}, 
	{title : "Pangrams on the web", site: "farside.org.u", href: "https://www.farside.org.uk/201410/pangrams_on_the_web", time: "2 days ago"}, 
	{title : "Tobacco plant may be key to Ebola drugs", site: "cnn.co", href: "http://www.cnn.com/2014/10/03/health/ebola-tobacco-plant/", time: "2 days ago"}, 
	{title : "NgMario", site: "blnight.github.i", href: "http://blnight.github.io/ngMario/#/game", time: "1 day ago"}, 
	{title : "To Find Meteorites, Listen to the Legends of Australian Aborigines", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/science-nature/find-meteorites-listen-legends-australian-aborigines-180952941/", time: "22 hours ago"}, 
	{title : "Granny Smith apples promote growth of friendly bacteria in the colon", site: "wsu.ed", href: "https://news.wsu.edu/2014/09/29/an-apple-a-day-could-keep-obesity-away/#.VCqA_GeSz94", time: "1 day ago"}, 
	{title : "Common Parts Library", site: "octopart.co", href: "http://octopart.com/common-parts-library?a=1", time: "6 days ago"}, 
	{title : "Bitcoin's Killer Apps", site: "chain.co", href: "http://blog.chain.com/post/99177371581/bitcoins-killer-apps", time: "1 day ago"}, 
	{title : "Show HN: Hackers Job Apply", site: "github.co", href: "https://github.com/lukasz-madon/hackers-job-apply", time: "1 day ago"}, 
	{title : "MiniKanren – An embedded DSL for logic programming", site: "minikanren.or", href: "http://minikanren.org/", time: "4 days ago"}, 
	{title : "A Fresh Look at Rust", site: "pocoo.or", href: "http://lucumr.pocoo.org/2014/10/1/a-fresh-look-at-rust/", time: "5 days ago"}, 
	{title : "Microsoft makes more money from Samsung than from Skype, Windows Phone, and Xbox", site: "qz.co", href: "http://qz.com/276242/microsoft-makes-more-money-from-samsung-than-from-skype-windows-phone-and-xbox-combined/", time: "14 hours ago"}, 
	{title : "Eleven awesome things you can do with csvkit", site: "opennews.or", href: "https://source.opennews.org/en-US/articles/eleven-awesome-things-you-can-do-csvkit/", time: "18 hours ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341/", time: "1 day ago"}, 
	{title : "For developers: These shirts make you look better than your code – ShirtJS", site: "shirtjs.co", href: "http://shirtjs.com/", time: "10 hours ago"}, 
	{title : "Writing a simple operating system from scratch (2010) [pdf]", site: "bham.ac.u", href: "http://www.cs.bham.ac.uk/~exr/lectures/opsys/10_11/lectures/os-dev.pdf", time: "7 days ago"}, 
]