news25 = [
	{title : "Merkle tree", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Merkle_tree", time: "16 days ago"}, 
	{title : "Neural-Network", site: "nxxcxx.github.i", href: "https://nxxcxx.github.io/Neural-Network", time: "2 days ago"}, 
	{title : "History of T", site: "paulgraham.co", href: "http://www.paulgraham.com/thist.html", time: "318 days ago"}, 
	{title : "Is Docker Ready for Production? Feedbacks of a 2 Weeks Hands On", site: "t37.ne", href: "http://t37.net/is-docker-ready-for-production-feedbacks-of-a-2-weeks-hands-on.html", time: "26 days ago"}, 
	{title : "The Art of Naming (Military) Operations", site: "army.mi", href: "http://strategicstudiesinstitute.army.mil/pubs/parameters/Articles/1995/sieminsk.htm", time: "307 days ago"}, 
	{title : "Finger Trees: A Simple General-purpose Data Structure", site: "city.ac.u", href: "http://www.soi.city.ac.uk/~ross/papers/FingerTree.html", time: "562 days ago"}, 
	{title : "The trajectory of a software engineer… and where it all goes wrong.", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "197 days ago"}, 
	{title : "Bitcoin back at 600$", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd", time: "128 days ago"}, 
	{title : "LÖVE (2D Game Engine) 0.9 is out", site: "love2d.or", href: "http://love2d.org/", time: "295 days ago"}, 
	{title : "NetBSD Kernel Drivers Compiled to Javascript and Run in Browser", site: "netbsd.or", href: "http://blog.netbsd.org/tnf/entry/kernel_drivers_compiled_to_javascript", time: "697 days ago"}, 
	{title : "Watch someone else code and learn", site: "thecodeplayer.co", href: "http://thecodeplayer.com/", time: "879 days ago"}, 
	{title : "Please write shorter emails", site: "sentenc.e", href: "http://five.sentenc.es/", time: "1447 days ago"}, 
	{title : "How Chris McCandless Died (2013)", site: "newyorker.co", href: "http://www.newyorker.com/books/page-turner/how-chris-mccandless-died", time: "9 days ago"}, 
	{title : "The Cult of Done Manifesto", site: "brepettis.co", href: "http://www.brepettis.com/blog/2009/3/3/the-cult-of-done-manifesto.html", time: "1963 days ago"}, 
	{title : "HNWatcher: track keywords and follow users on Hacker News", site: "hnwatcher.co", href: "https://www.hnwatcher.com/", time: "438 days ago"}, 
	{title : "TIOBE: Objective-C on its way to become 'language of the year' again", site: "tiobe.co", href: "http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html", time: "670 days ago"}, 
	{title : "Church: A probabilistic Lisp", site: "mit.ed", href: "http://projects.csail.mit.edu/church/wiki/Church", time: "1067 days ago"}, 
	{title : "Are you Living in a Computer Simulation?", site: "simulation-argument.co", href: "http://www.simulation-argument.com/simulation.html", time: "1391 days ago"}, 
	{title : "Find your color scheme", site: "colourco.d", href: "http://colourco.de/", time: "212 days ago"}, 
	{title : "CouchDB 'joins'. Some NoSQL design considerations", site: "cmlenz.ne", href: "http://www.cmlenz.net/archives/2007/10/couchdb-joins", time: "1674 days ago"}, 
	{title : "Understanding scam victims: seven principles for systems security. [pdf]", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-754.pdf", time: "1770 days ago"}, 
	{title : "The Brain That Changed Everything", site: "esquire.co", href: "http://www.esquire.com/print-this/henry-molaison-brain-1110?page=all", time: "1434 days ago"}, 
	{title : "Bjarne Stroustrup: “I did it for you all” (1998)", site: "cat-v.or", href: "http://harmful.cat-v.org/software/c++/I_did_it_for_you_all", time: "1 day ago"}, 
	{title : "How Would the FDA Respond If We Had a Drug to Cure Aging?", site: "kolber.typepad.co", href: "http://kolber.typepad.com/ethics_law_blog/2014/09/how-would-the-fda-respond-if-we-had-a-drug-to-cure-aging-guest-post-by-kira-peikoff.html", time: "34 minutes ago"}, 
	{title : "Came across this site that lists products with a lifetime warranty", site: "lastmealifetime.co", href: "http://lastmealifetime.com/", time: "1 day ago"}, 
]