news23 = [
	{title : "New material steals oxygen from the air", site: "sciencedaily.co", href: "http://www.sciencedaily.com/releases/2014/09/140930113254.htm", time: "3 days ago"}, 
	{title : "C# 6 Cuts", site: "trelford.co", href: "http://www.trelford.com/blog/post/austerity.aspx", time: "3 days ago"}, 
	{title : "Backer News: fresh crowdfunding projects", site: "backernews.co", href: "http://backernews.com/", time: "3 days ago"}, 
	{title : "Douglas Model 671/684: The X-15’s Shadow (2012)", site: "falsesteps.wordpress.co", href: "http://falsesteps.wordpress.com/2012/08/11/douglas-model-671684-the-x-15s-shadow/", time: "3 days ago"}, 
	{title : "The New and Improved C# 6.0", site: "microsoft.co", href: "http://msdn.microsoft.com/en-us/magazine/dn802602.aspx", time: "3 days ago"}, 
	{title : "U.S. Law Enforcement Seeks to Halt Apple-Google Encryption of Mobile Data", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/u-s-seeks-to-reverse-apple-android-data-locking-decision.html", time: "5 days ago"}, 
	{title : "Modules in C99", site: "snaipe.m", href: "http://snaipe.me/c/modules-in-c99/", time: "3 days ago"}, 
	{title : "The story of the longest-held American POW", site: "slate.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/john_t_downey_cia_agent_captured_by_china_during_the_korean_war_the_story.single.html", time: "4 days ago"}, 
	{title : "An iconic phone before the iPhone", site: "juxtapoz.co", href: "http://www.juxtapoz.com/design/an-iconic-phone-before-the-iphone", time: "4 days ago"}, 
	{title : "Containers [pdf]", site: "usenix.or", href: "https://www.usenix.org/system/files/login/articles/login_1410_02-bottomley.pdf", time: "4 days ago"}, 
	{title : "RamanPi – The 3D Printable Raspberry Pi Raman Spectrometer", site: "publiclab.or", href: "http://publiclab.org/notes/flatCat/08-29-2014/ramanpi-the-3d-printable-raspberry-pi-raman-spectrometer", time: "4 days ago"}, 
	{title : "Information age tarot deck", site: "nettarot.ne", href: "http://nettarot.net", time: "3 days ago"}, 
	{title : "iCarus – Raspberry Pi-Powered Head Unit for Cars", site: "i-carus.co", href: "http://i-carus.com", time: "3 days ago"}, 
	{title : "California Cracks Down on Farmers Market Cheaters", site: "npr.or", href: "http://www.npr.org/blogs/thesalt/2014/10/02/352979875/california-cracks-down-on-farmers-market-cheaters?sc=tw", time: "3 days ago"}, 
	{title : "This payload is currently being distributed using the Shellshock vulnerability", site: "github.co", href: "https://gist.github.com/jacquerie/0569a4a192b06f25d764", time: "3 days ago"}, 
	{title : "U.S. v. Ross Ulbricht: Declaration of Joshua J. Horowitz [pdf]", site: "antilop.c", href: "http://antilop.cc/sr/files/2014_10_01_Declaration_of_Josh_Horowitz_defense_attorney.pdf", time: "3 days ago"}, 
	{title : "Why are hash functions one way?", site: "stackexchange.co", href: "http://security.stackexchange.com/questions/11717/why-are-hash-functions-one-way-if-i-know-the-algorithm-why-cant-i-calculate-t", time: "2 days ago"}, 
	{title : "Shell Unshock?", site: "bash.s", href: "http://bash.sh/shell-unshock/", time: "3 days ago"}, 
	{title : "The Last Days of an Ancient Sword", site: "roadsandkingdoms.co", href: "http://roadsandkingdoms.com/2014/the-last-days-of-an-ancient-sword/", time: "3 days ago"}, 
	{title : "List of Words Google considers curse words", site: "github.co", href: "https://github.com/jakesyl/WDYL-Curse/blob/master/output.txt", time: "3 days ago"}, 
	{title : "The Betamax vs. VHS Format War", site: "mediacollege.co", href: "http://www.mediacollege.com/video/format/compare/betamax-vhs.html", time: "3 days ago"}, 
	{title : "Re: MemSQL the “world's fastest database”? (2012)", site: "postgresql.or", href: "http://www.postgresql.org/message-id/4FE8A2DE.5050806@agliodbs.com", time: "4 days ago"}, 
	{title : "A beginners guide to writing documentation", site: "writethedocs.or", href: "http://docs.writethedocs.org/writing/beginners-guide-to-docs/", time: "3 days ago"}, 
	{title : "How to Stop Time", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/28/opinion/sunday/how-to-stop-time.html", time: "7 days ago"}, 
	{title : "Drop Caps Are Beautiful", site: "adobe.co", href: "http://blogs.adobe.com/webplatform/2014/10/02/drop-caps-are-beautiful/", time: "3 days ago"}, 
	{title : "USB has a huge security problem that could take years to fix", site: "theverge.co", href: "http://www.theverge.com/2014/10/2/6896095/this-published-hack-could-be-the-beginning-of-the-end-for-usb", time: "3 days ago"}, 
	{title : "The Fallacy of Premature Optimization (2009)", site: "acm.or", href: "http://ubiquity.acm.org/article.cfm?id=1513451", time: "4 days ago"}, 
	{title : "Optimizing the restaurant sales receipt for maximum tips", site: "maxsavin.co", href: "http://maxsavin.com/posts/receipt.html", time: "3 days ago"}, 
]