news2 = [
	{title : "Maps attributed to Marco Polo sketch what looks like the coast of Alaska", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/history/did-marco-polo-discover-america-180952765/", time: "11 hours ago"}, 
	{title : "Massive electrode array will do first large-scale recording of brain activity", site: "kurzweilai.ne", href: "http://www.kurzweilai.net/massive-electrode-array-system-will-do-first-large-scale-network-recording-of-brain-activity", time: "15 hours ago"}, 
	{title : "Terrestriality", site: "theappendix.ne", href: "http://theappendix.net/issues/2014/4/terrestriality", time: "8 hours ago"}, 
	{title : "Hacked Screenshots Show Friend-To-Friend Payments Feature in Facebook Messenger", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/pay-with-facebook-messenger/", time: "10 hours ago"}, 
	{title : "The Star7 PDA Prototype, Genesis of Java [video] (1992)", site: "youtube.co", href: "https://www.youtube.com/watch?v=Ahg8OBYixL0", time: "19 hours ago"}, 
	{title : "Throw Out the College Application System", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/opinion/sunday/throw-out-the-college-application-system.html", time: "10 hours ago"}, 
	{title : "Rockwool vs. Perlite vs. Hydroton vs. Soil", site: "hydronerd.co", href: "http://hydronerd.com/2014/10/rockwool-vs-perlite-vs-hydroton-vs-soil/", time: "10 hours ago"}, 
	{title : "Graphite-News: Keeping up to speed with whats new in your monitoring tool", site: "jilles.ne", href: "http://www.jilles.net/perma/2014/10/03/introducing-graphite-news/", time: "8 hours ago"}, 
	{title : "1041uuu Pixel Art", site: "1041uuu.tumblr.co", href: "http://1041uuu.tumblr.com/", time: "11 hours ago"}, 
	{title : "Bitcoin trader floods market with $300 orders, causing price to flatline", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?flatine", time: "1 hour ago"}, 
	{title : "The Greatest Ancient Picture Gallery", site: "nybooks.co", href: "http://www.nybooks.com/articles/archives/2014/oct/23/greatest-ancient-picture-gallery/", time: "12 hours ago"}, 
	{title : "Why can't Apple decrypt your iPhone?", site: "cryptographyengineering.co", href: "http://blog.cryptographyengineering.com/2014/10/why-cant-apple-decrypt-your-iphone.html", time: "1 day ago"}, 
	{title : "Is Google Making Students Stupid?", site: "theatlantic.co", href: "http://www.theatlantic.com/education/archive/2014/09/is-google-making-students-stupid/380944/", time: "3 hours ago"}, 
	{title : "Why do roots of polynomials tend to have absolute value 1?", site: "mathoverflow.ne", href: "http://mathoverflow.net/questions/182412/why-do-roots-of-polynomials-tend-to-have-absolute-value-1", time: "23 hours ago"}, 
	{title : "Naive Bayes and Text Classification I – Introduction and Theory", site: "sebastianraschka.co", href: "http://sebastianraschka.com/Articles/2014_naive_bayes_1.html", time: "1 day ago"}, 
	{title : "English Proficiency Index", site: "ef.co", href: "http://www.ef.com/epi", time: "16 hours ago"}, 
	{title : "‘The Innovators’ by Walter Isaacson", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/books/review/the-innovators-by-walter-isaacson.html", time: "11 hours ago"}, 
	{title : "In 1888, one man patented a machine for vending “healthy” electric shocks", site: "arstechnica.co", href: "http://arstechnica.com/science/2014/10/a-look-at-the-1888-patent-for-an-electric-shock-vending-machine", time: "11 hours ago"}, 
	{title : "Hiker Discovers an Abandoned Town Inside Tennessee's Great Smoky Mountains", site: "huffingtonpost.co", href: "http://www.huffingtonpost.com/roadtrippers/hiker-discovers-an-abando_b_5927164.html", time: "1 hour ago"}, 
	{title : "Vim blowfish encryption", site: "dgl.c", href: "https://dgl.cx/2014/10/vim-blowfish", time: "15 hours ago"}, 
	{title : "Machine Learning with Knowledge Graphs [video]", site: "nzhiltsov.blogspot.co", href: "http://nzhiltsov.blogspot.com/2014/10/machine-learning-with-knowledge-graphs.html", time: "12 hours ago"}, 
	{title : "Big robot fleet takes to UK waters", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29464273", time: "22 hours ago"}, 
	{title : "The Immaturity and Arrogance of Uber", site: "medium.co", href: "https://medium.com/@petersimsie/the-immaturity-and-arrogance-of-uber-eea64bcfa5bf", time: "2 hours ago"}, 
	{title : "Show HN: Poll – Voting done simply in real time", site: "lab.i", href: "http://poll.lab.io", time: "19 hours ago"}, 
	{title : "Some ideas for native Bitcoin apps", site: "cdixon.or", href: "http://cdixon.org/2014/10/04/some-ideas-for-native-bitcoin-apps/", time: "1 day ago"}, 
	{title : "Statistical Flaw Punctuates Brain Research in Elite Journals", site: "scientificamerican.co", href: "http://blogs.scientificamerican.com/talking-back/2014/03/27/statistical-flaw-punctuates-brain-research-in-elite-journals/", time: "16 hours ago"}, 
	{title : "Exploring Change Blindness", site: "learnforeverlearn.co", href: "http://learnforeverlearn.com/changeblindness/", time: "11 hours ago"}, 
	{title : "Navy: Self-guided unmanned patrol boats make debut", site: "myfoxal.co", href: "http://www.myfoxal.com/story/26706962/navy-self-guided-unmanned-patrol-boats-make-debut", time: "20 hours ago"}, 
]