news30 = [
	{title : "Fedora Workstation Progress Report (Wayland and More)", site: "gnome.or", href: "http://blogs.gnome.org/uraeus/2014/10/02/fedora-workstation-progress-report-wayland-and-more/", time: "3 days ago"}, 
	{title : "EBay to Spin Off PayPal", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/09/30/ebay-to-spin-off-paypal-adopting-strategy-backed-by-icahn/", time: "5 days ago"}, 
	{title : "Man allegedly shoots down neighbor’s drone with shotgun", site: "digitaltrends.co", href: "http://www.digitaltrends.com/cool-tech/new-jersey-man-allegedly-shoots-neighbors-drone/?utm_source=o1&utm_medium=cpc&utm_campaign=o1", time: "3 days ago"}, 
	{title : "Parallel scheduling of task trees with limited memory [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1410.0329.pdf", time: "3 days ago"}, 
	{title : "How to Deploy Play Framework on AWS OpsWorks", site: "originate.co", href: "http://blog.originate.com/blog/2014/10/02/how-to-deploy-play-framework-on-aws-opsworks/", time: "3 days ago"}, 
	{title : "Hound Reviews JavaScript for Style Violations", site: "thoughtbot.co", href: "http://robots.thoughtbot.com/hound-reviews-javascript-for-style-violations", time: "3 days ago"}, 
	{title : "Cloudflare is down", site: "twitter.co", href: "https://twitter.com/search?f=realtime&q=cloudflare", time: "3 days ago"}, 
	{title : "Three years later, Pentagon unit still hides Internet voting test results", site: "mcclatchydc.co", href: "http://www.mcclatchydc.com/2014/10/01/241746_three-years-later-pentagon-unit.html", time: "3 days ago"}, 
	{title : "Clock Edge Detection in Excel", site: "drdobbs.co", href: "http://www.drdobbs.com/embedded-systems/clock-edge-detectionin-excel/240169084", time: "4 days ago"}, 
	{title : "NearlyFreeSpeech.NET now supports persistent processes", site: "nearlyfreespeech.ne", href: "https://blog.nearlyfreespeech.net/2014/09/24/more-power-more-control-more-insight-less-cost/", time: "4 days ago"}, 
	{title : "Show HN: Open-Source extensible personal assistant on your desktop", site: "github.co", href: "https://github.com/29decibel/assistant", time: "4 days ago"}, 
	{title : "Lies, Damn Lies and Version Numbers", site: "telerik.co", href: "http://developer.telerik.com/featured/lies-damn-lies-version-numbers/", time: "3 days ago"}, 
	{title : "Emotional Intelligence is Overrated", site: "linkedin.co", href: "https://www.linkedin.com/pulse/article/20140930125543-69244073-emotional-intelligence-is-overrated", time: "5 days ago"}, 
	{title : "Google Classroom", site: "google.co", href: "https://www.google.com/edu/classroom/", time: "6 days ago"}, 
	{title : "Using Intel VTune to Tune Software on the 4th Generation (Haswell) Processor [pdf]", site: "intel.co", href: "https://software.intel.com/sites/default/files/article/394181/using-intel-vtune-amplifier-xe-on-4th-generation-intel-core-processors.pdf", time: "4 days ago"}, 
	{title : "Show HN: DART – Quickly search and discover startup engineering jobs", site: "dart.rock", href: "http://www.dart.rocks/", time: "4 days ago"}, 
	{title : "A Field Guide to Design by Pros at Media Temple, Marvel, GA Dash and Product Hunt", site: "mention.co", href: "http://blog.mention.com/a-field-guide-to-design-where-to-begin/", time: "3 days ago"}, 
	{title : "Peter Thiel's Zero to One Might Be the Best Business Book I've Read", site: "theatlantic.co", href: "http://www.theatlantic.com/business/archive/2014/09/peter-thiel-zero-to-one-review/380738/?single_page=true", time: "7 days ago"}, 
	{title : "Atom: Editor window startup is slow", site: "github.co", href: "https://www.github.com/atom/atom/issues/2654", time: "4 days ago"}, 
	{title : "ComputerCOP: Dubious 'Internet Safety Software' Police Distributed to Families", site: "eff.or", href: "https://www.eff.org/deeplinks/2014/09/computercop-dangerous-internet-safety-software-hundreds-police-agencies", time: "4 days ago"}, 
	{title : "Could Uber be held liable for driver hammer attack?", site: "forbes.co", href: "http://www.forbes.com/sites/ellenhuet/2014/09/30/uber-driver-hammer-attack-liability/", time: "3 days ago"}, 
	{title : "Clarifai: Advanced Image Recognition", site: "clarifai.co", href: "http://www.clarifai.com/", time: "4 days ago"}, 
	{title : "MiniZinc, the medium-level constraint modelling language", site: "minizinc.or", href: "http://www.minizinc.org/index.html", time: "4 days ago"}, 
	{title : "The Medium Is the Message, 50 Years Later", site: "psmag.co", href: "http://www.psmag.com/navigation/nature-and-technology/medium-message-50-years-later-91552/", time: "5 days ago"}, 
	{title : "StoreDot Charges Up with $42M for Its Fast-Charging Bio-Organic Batteries", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/storedot-series-b/", time: "3 days ago"}, 
	{title : "Mobile Malware: Small Numbers, but Growing", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/technology/personaltech/mobile-malware-small-numbers-but-growing.html?ref=personaltech", time: "3 days ago"}, 
	{title : "Against Concentrations", site: "harry-lewis.blogspot.co", href: "http://harry-lewis.blogspot.com/2014/09/against-concentrations.html", time: "4 days ago"}, 
	{title : "J-expressions (2012)", site: "sriku.or", href: "http://sriku.org/blog/2012/04/15/j-expressions/", time: "4 days ago"}, 
	{title : "OnionTip – Donate to volunteers who are running Tor relays", site: "oniontip.co", href: "https://oniontip.com", time: "5 days ago"}, 
]