news37 = [
	{title : "Realtime Lyft Surge Prices", site: "konscript.ne", href: "http://lyft.konscript.net", time: "4 days ago"}, 
	{title : "U.S. Takes Asteroid Threat Seriously, Saves Nukes", site: "wsj.co", href: "http://online.wsj.com/articles/u-s-takes-asteroid-threat-seriously-1412119610", time: "4 days ago"}, 
	{title : "Reddit to force relocation of remote workers", site: "twitter.co", href: "https://twitter.com/yishan/status/517364923320385536", time: "4 days ago"}, 
	{title : "End of an era – No more pics from Trading Floor", site: "marketwatch.co", href: "http://www.marketwatch.com/story/this-is-the-last-photo-well-ever-run-of-the-nyse-trading-floor-2014-10-01?dist=countdown", time: "4 days ago"}, 
	{title : "Tony Hsieh Steps Down from Lead Role at Las Vegas Downtown Project", site: "recode.ne", href: "http://recode.net/2014/09/30/tony-hsieh-steps-down-from-lead-role-at-las-vegas-downtown-project/", time: "5 days ago"}, 
	{title : "Command-line file sharing", site: "transfer.s", href: "https://transfer.sh/", time: "5 days ago"}, 
	{title : "Scriptable Operating Systems with Lua [pdf]", site: "netbsd.or", href: "http://www.netbsd.org/~lneto/dls14.pdf", time: "5 days ago"}, 
	{title : "Click on the tile that has a different color", site: "ioxapp.co", href: "http://game.ioxapp.com/color/?", time: "5 days ago"}, 
	{title : "The Internet of Furbies", site: "memsql.co", href: "http://blog.memsql.com/the-internet-of-furbies/", time: "4 days ago"}, 
	{title : "What one engineer learned when he stopped taking photos and started drawing", site: "fastcompany.co", href: "http://www.fastcompany.com/3036378/my-creative-life/slowgrams-what-one-silicon-valley-engineer-learned-when-he-stopped-taking-p", time: "5 days ago"}, 
	{title : "Ellison: Sparc M7 is Oracle's most important silicon EVER", site: "theregister.co.u", href: "http://www.theregister.co.uk/2014/09/29/ellison_sparc_m7/", time: "4 days ago"}, 
	{title : "Tree-based Seekable Sequential Key Generators", site: "iacr.or", href: "https://eprint.iacr.org/2014/479", time: "5 days ago"}, 
	{title : "A strange green organism has spread, clogging up the world's rivers", site: "bbc.co", href: "http://www.bbc.com/earth/story/20140922-green-snot-takes-over-worlds-rivers?OCID=fbindia", time: "5 days ago"}, 
	{title : "T – a command-line power tool for Twitter", site: "sferik.github.i", href: "http://sferik.github.io/t/", time: "6 days ago"}, 
	{title : "Are Ivy League schools overrated?", site: "andrewgelman.co", href: "http://andrewgelman.com/2014/09/30/23581/", time: "4 days ago"}, 
	{title : "Is My Shift Key on or Not", site: "ismyshiftkeyonornot.co", href: "http://ismyshiftkeyonornot.com/", time: "4 days ago"}, 
	{title : "Under Rainier’s crater, a natural laboratory like no other", site: "seattletimes.co", href: "http://seattletimes.com/html/localnews/2024638286_rainiercavesxml.html", time: "6 days ago"}, 
	{title : "Houzz Raises $165M, Launches Online Store", site: "recode.ne", href: "http://recode.net/2014/10/01/houzz-raises-165-million-launches-online-store/", time: "4 days ago"}, 
	{title : "10% price cuts on Google Compute Engine", site: "googlecloudplatform.blogspot.co", href: "http://googlecloudplatform.blogspot.com/2014/10/Announcing-across-the-board-price-cuts-on-Compute-Engine.html", time: "4 days ago"}, 
	{title : "LinkedIn releases undergraduate university ratings", site: "linkedin.co", href: "https://www.linkedin.com/edu/rankings/us/undergraduate-software-engineering", time: "4 days ago"}, 
	{title : "My $300 Home Cloud Server", site: "acm.or", href: "http://xrds.acm.org/blog/2014/09/my-300-home-cloud-server-a-story-of-blood-sweat-and-ebay/", time: "9 days ago"}, 
	{title : "What we learned from YC S14 (even though we weren't accepted)", site: "medium.co", href: "https://medium.com/@Open_Listings/what-we-learned-from-yc-summer-2014-a419e7ffb55c", time: "4 days ago"}, 
	{title : "Taboola: The Internet firm at the forefront of 'click-bait'", site: "bbc.co", href: "http://www.bbc.com/news/business-29322578", time: "5 days ago"}, 
	{title : "The economics of a web-based book", site: "practicaltypography.co", href: "http://practicaltypography.com/economics-year-one.html", time: "9 days ago"}, 
	{title : "New experimental console features in Windows “Threshold”", site: "withinrafael.co", href: "http://withinrafael.com/new-experimental-console-features-in-windows-threshold/", time: "5 days ago"}, 
	{title : "The Most Expensive One-byte Mistake (2011)", site: "acm.or", href: "http://queue.acm.org/detail.cfm?id=2010365", time: "6 days ago"}, 
	{title : "The Evolution of Storm at Yahoo and Apache", site: "yahoohadoop.tumblr.co", href: "http://yahoohadoop.tumblr.com/post/98751512631/the-evolution-of-storm-at-yahoo-and-apache", time: "5 days ago"}, 
	{title : "Self-Destructing SSDs Will Nuke Themselves If You Text Them a Code Word", site: "gizmodo.co", href: "http://gizmodo.com/self-destructing-ssds-will-nuke-themselves-if-you-text-1640733628", time: "4 days ago"}, 
]