news6 = [
	{title : "Aboard Amtrak", site: "spnzr.co", href: "http://spnzr.com/aboard-amtrak", time: "2 days ago"}, 
	{title : "Journey into information theory", site: "khanacademy.or", href: "https://www.khanacademy.org/computing/computer-science/informationtheory", time: "17 hours ago"}, 
	{title : "Germany’s great tuition fees U-turn", site: "timeshighereducation.co.u", href: "http://www.timeshighereducation.co.uk/features/feature-germanys-great-tuition-fees-u-turn/2011168.fullarticle", time: "4 days ago"}, 
	{title : "Libsqlfs: A POSIX-style file system on top of an SQLite database", site: "github.co", href: "https://github.com/guardianproject/libsqlfs", time: "2 days ago"}, 
	{title : "Haskell, Monads and Purity", site: "jelv.i", href: "http://jelv.is/blog/Haskell-Monads-and-Purity/", time: "2 days ago"}, 
	{title : "What do the top 1% of software engineers do?", site: "quora.co", href: "http://www.quora.com/What-do-the-top-1-of-software-engineers-do-that-the-other-99-do-not", time: "6 hours ago"}, 
	{title : "The badge of ignorance", site: "medium.co", href: "https://medium.com/@emilepetrone/the-badge-of-ignorance-185c85ac9a30", time: "12 hours ago"}, 
	{title : "Keynote: Dries Buytaert. Scaling open source projects", site: "drupal.or", href: "https://amsterdam2014.drupal.org/keynote-dries-buytaert", time: "12 hours ago"}, 
	{title : "Uber Improves Life, Economists Agree", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/01/upshot/uber-improves-life-economists-agree.html", time: "16 hours ago"}, 
	{title : "Postgres 9.5 feature highlight: row-level security and policies", site: "otacoo.co", href: "http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-row-level-security/", time: "2 days ago"}, 
	{title : "India, U.S. Agree to Joint Exploration of Mars", site: "wsj.co", href: "http://blogs.wsj.com/indiarealtime/2014/10/01/india-u-s-to-agree-to-joint-exploration-of-mars", time: "3 days ago"}, 
	{title : "HackCampus Internship Programme", site: "hackcampus.i", href: "http://hackcampus.io/internship/#hero", time: "9 hours ago"}, 
	{title : "Caesium: A brief history of timekeeping", site: "bbc.co", href: "http://www.bbc.com/news/magazine-29476893", time: "1 day ago"}, 
	{title : "Windows 95 on Android Smartwatch", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6910791/least-useful-hack-ever-puts-windows-95-on-your-smartwatch", time: "8 hours ago"}, 
	{title : "CDC confirms first Ebola case diagnosed in US", site: "cnbc.co", href: "http://www.cnbc.com/id/102037055", time: "5 days ago"}, 
	{title : "ForestDb – A Fast Key-Value Storage Engine Based on Hierarchical B+-Tree Trie", site: "github.co", href: "https://github.com/couchbaselabs/forestdb", time: "1 day ago"}, 
	{title : "Shapecatcher: Draw the Unicode character you want", site: "shapecatcher.co", href: "http://shapecatcher.com", time: "3 days ago"}, 
	{title : "Analyzing AngelList Job Postings, Part 2: Salary and Equity Benchmarks", site: "codingvc.co", href: "http://codingvc.com/analyzing-angellist-job-postings-part-2-salary-and-equity-benchmarks", time: "2 days ago"}, 
	{title : "An Analysis of Shell Shock Malware", site: "erenyagdiran.github.i", href: "http://erenyagdiran.github.io/An-Analysis-of-Shell-shock-malware/", time: "1 day ago"}, 
	{title : "Marriott Hotels fined $600,000 by FCC for jamming Wi-Fi hotspots [pdf]", site: "fcc.go", href: "http://transition.fcc.gov/Daily_Releases/Daily_Business/2014/db1003/DA-14-1444A1.pdf", time: "2 days ago"}, 
	{title : "Sourcery (YC W13) Raises $2.5M to Connect Kitchens and Local Food Suppliers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/sourcery-raises-2-5m-to-connect-kitchens-and-local-food-suppliers/", time: "2 days ago"}, 
	{title : "Usaddress – Python library for parsing unstructured address strings with NLP", site: "rtfd.or", href: "http://usaddress.rtfd.org/", time: "2 days ago"}, 
	{title : "Windows 95 on Android Wear [video]", site: "youtube.co", href: "http://youtube.com/watch?v=GZx-LJH5J_I", time: "12 hours ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341", time: "1 day ago"}, 
	{title : "TXR: A Programming Language for Convenient Data Munging", site: "nongnu.or", href: "http://www.nongnu.org/txr", time: "1 day ago"}, 
	{title : "We Got Accepted into Techstars and Turned Them Down", site: "talkroute.co", href: "http://talkroute.com/got-accepted-into-techstars-turned-it-down/", time: "3 days ago"}, 
	{title : "Reading the Silk Road configuration", site: "erratasec.co", href: "http://blog.erratasec.com/2014/10/reading-silk-road-configuration.html", time: "2 days ago"}, 
	{title : "Consider the Lobster (2004)", site: "gourmet.co", href: "http://www.gourmet.com/magazine/2000s/2004/08/consider_the_lobster?printable=true", time: "2 days ago"}, 
	{title : "Why is 0x00400000 the default base address for an executable?", site: "msdn.co", href: "http://blogs.msdn.com/b/oldnewthing/archive/2014/10/03/10562176.aspx", time: "2 days ago"}, 
]