news27 = [
	{title : "The Quiet Zone: No wifi or cell phone service for 13,000 sq. miles", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/United_States_National_Radio_Quiet_Zone", time: "3 days ago"}, 
	{title : "Texas Contacts 100, Citing Possible Links to Ebola Patient", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/dallas-ebola-case-thomas-duncan-contacts.html?_r=0", time: "3 days ago"}, 
	{title : "Systems of Logic Based on Ordinals (1938) [pdf]", site: "princeton.ed", href: "https://webspace.princeton.edu/users/jedwards/Turing%20Centennial%202012/Mudd%20Archive%20files/12285_AC100_Turing_1938.pdf", time: "4 days ago"}, 
	{title : "Show HN: All available three letter .io domains", site: "edward.i", href: "http://edward.io/io", time: "3 days ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "youtube.co", href: "https://www.youtube.com/watch?v=yP176MBG9Tk", time: "3 days ago"}, 
	{title : "Zentail.com (YC S12) Now Accepts Bitcoin", site: "reddit.co", href: "http://www.reddit.com/r/Bitcoin/comments/2i3ssd/zentailcom_now_accepts_bitcoin/", time: "3 days ago"}, 
	{title : "Elon Musk: Tesla 90% autonomous in 2015", site: "youtube.co", href: "https://www.youtube.com/watch?v=EJmhpgW0Dmc", time: "3 days ago"}, 
	{title : "Losing the sense of smell predicts death within five years", site: "theguardian.co", href: "http://www.theguardian.com/science/neurophilosophy/2014/oct/01/your-nose-knows-death-is-imminent", time: "3 days ago"}, 
	{title : "Joshua Wong: the teenager who is the public face of the Hong Kong protests", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/joshua-wong-teenager-public-face-hong-kong-protests", time: "3 days ago"}, 
	{title : "Cassini Watches Mysterious Feature Evolve in Titan Sea", site: "nasa.go", href: "http://www.nasa.gov/jpl/cassini/cassini-watches-mysterious-feature-evolve-in-titan-sea/", time: "5 days ago"}, 
	{title : "Cyanogen refuses Google's money in an effort to keep Android 'open'", site: "engadget.co", href: "http://www.engadget.com/2014/10/02/cyanogen-refuses-google/", time: "3 days ago"}, 
	{title : "Show HN: TypeWonder – Test web fonts on any site on the fly", site: "typewonder.co", href: "http://typewonder.com/", time: "4 days ago"}, 
	{title : "Facebook Promises a Deeper Review of Its User Research", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/technology/facebook-promises-a-deeper-review-of-its-user-research.html", time: "3 days ago"}, 
	{title : "Google Project Zero: More Mac OS X and iPhone Sandbox Escapes", site: "googleprojectzero.blogspot.co", href: "http://googleprojectzero.blogspot.com/2014/10/more-mac-os-x-and-iphone-sandbox.html", time: "4 days ago"}, 
	{title : "Matchstick Brings Firefox OS to Your HDTV", site: "mozilla.or", href: "https://hacks.mozilla.org/2014/09/matchstick-brings-firefox-os-to-your-hdtv-be-the-first-to-get-a-developer-stick/", time: "5 days ago"}, 
	{title : "NASA found a mysterious rectangular shape on the moon", site: "sciencemag.or", href: "http://news.sciencemag.org/space/2014/10/ancient-magma-plumbing-found-buried-below-moons-largest-dark-spot", time: "3 days ago"}, 
	{title : "Parenting as a Gen Xer: The 1st generation of parents in the age of iEverything", site: "washingtonpost.co", href: "http://www.washingtonpost.com/news/parenting/wp/2014/09/29/parenting-as-a-gen-xer-what-its-like-to-be-the-first-generation-of-parents-in-the-age-of-ieverything/", time: "3 days ago"}, 
	{title : "Visualizing and Understanding Convolutional Networks", site: "arxiv.or", href: "http://arxiv.org/abs/1311.2901", time: "4 days ago"}, 
	{title : "J.P. Morgan Says About 76M Households Affected by Cyber Breach", site: "marketwatch.co", href: "http://www.marketwatch.com/story/jp-morgan-says-about-76-million-households-affected-by-cyber-breach-2014-10-02-17103316", time: "3 days ago"}, 
	{title : "Show HN: Crowdsourced Summaries of Facebook's Human-Subjects Research", site: "sauvik.m", href: "https://experiment.sauvik.me/", time: "4 days ago"}, 
	{title : "AT", site: "acker invoices Justice Dept. for time spent in federal pri", href: "http://rt.com/usa/160216-weev-invoice-fed-bitcoin/", time: "3 days ago"}, 
	{title : "JPMorgan Data Break", site: "mashable.co", href: "http://mashable.com/2014/10/02/jp-morgan-chase-breach/?utm_campaign=Feed%3A+Mashable+%28Mashable%29&utm_cid=Mash-Prod-RSS-Feedburner-All-Partial&utm_medium=feed&utm_source=feedburner", time: "3 days ago"}, 
	{title : "Sense of smell 'may predict lifespan'", site: "bbc.co", href: "http://www.bbc.com/news/health-29441323", time: "4 days ago"}, 
	{title : "Startup Burn Rates: A Game of High Stakes Poker", site: "medium.co", href: "https://medium.com/@clarencewooten/startup-burn-rates-a0a36f2375c9", time: "3 days ago"}, 
	{title : "Spotify on their Engineering Culture", site: "arcticstartup.co", href: "http://www.arcticstartup.com/2014/10/02/video-spotify-on-their-engineering-culture", time: "3 days ago"}, 
	{title : "The Mythology of Dog Years", site: "priceonomics.co", href: "http://priceonomics.com/the-mythology-of-dog-years/", time: "4 days ago"}, 
	{title : "Dmitry Grishin: “Robotics Has Too Many Dreamers, Needs More Practical People”", site: "ieee.or", href: "http://spectrum.ieee.org/automaton/robotics/home-robots/dmitry-grishin-robotics#.VCr0s3T1v2w.hackernews", time: "5 days ago"}, 
	{title : "Ebola Overwhelming West Africa Communities", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/world/africa/ebola-spreading-in-west-africa.html", time: "4 days ago"}, 
	{title : "Elon Musk argues that putting a million people on Mars ensures humanity's future", site: "aeon.c", href: "http://aeon.co/magazine/technology/the-elon-musk-interview-on-mars/", time: "5 days ago"}, 
]