news1 = [
	{title : "Square Raises $150M at a $6B Valuation", site: "bits.blogs.nytimes.co", href: "http://bits.blogs.nytimes.com/2014/10/05/square-raises-150-million-at-a-6-billion-valuation/", time: "2 hours ago"}, 
	{title : "Apple Expected to Consume 25% of All DRAM in 2015", site: "hothardware.co", href: "http://hothardware.com/m/News/Apple-Expected-To-Consume-25-Of-All-DRAM-In-2015-Impact-Industry-Trends/default.aspx", time: "2 hours ago"}, 
	{title : "A look at the Apple ‘Skankphone’, built before the original iPhone release", site: "thenextweb.co", href: "http://thenextweb.com/apple/2014/10/05/apple-skankphone-built-original-iphone-release/", time: "1 hour ago"}, 
	{title : "Microsoft’s ‘RoomAlive’ transforms any room into a giant Xbox game", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6912979/microsoft-roomalive-research-projector-system", time: "3 hours ago"}, 
	{title : "Live Coding in VR with Oculus Rift, Firefox WebVR, JavaScript, Three.js [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=db-7J5OaSag", time: "22 hours ago"}, 
	{title : "Stop Australia's Data Retention Bill", site: "stopthespies.or", href: "https://stopthespies.org/?live", time: "3 hours ago"}, 
	{title : "Firechat and nearby communication", site: "breizh-entropy.or", href: "http://breizh-entropy.org/~nameless/random/posts/firechat_and_nearby_communication/", time: "9 hours ago"}, 
	{title : "Autothysis SSD drives impede unauthorised access", site: "securedrives.co.u", href: "http://securedrives.co.uk/index.php?route=product/category&path=73_75", time: "9 hours ago"}, 
	{title : "How does a computer chip work?", site: "quora.co", href: "http://www.quora.com/Computer-Science/How-does-a-computer-chip-work/answer/Subhasis-Das?share=1", time: "11 hours ago"}, 
	{title : "Why Apple's iPhone encryption won't stop NSA", site: "siliconexposed.blogspot.co", href: "http://siliconexposed.blogspot.com/2014/10/why-apples-iphone-encryption-wont-stop.html", time: "11 hours ago"}, 
	{title : "Hewlett-Packard Plans to Break in Two", site: "wsj.co", href: "http://online.wsj.com/articles/hewlett-packard-plans-to-break-in-two-1412530028?mod=djemalertTECH", time: "11 hours ago"}, 
	{title : "How fast is fscanf?", site: "github.co", href: "https://github.com/alexflint/fscanf-speed", time: "3 hours ago"}, 
	{title : "How the Z80's registers are implemented", site: "righto.co", href: "http://www.righto.com/2014/10/how-z80s-registers-are-implemented-down.html", time: "12 hours ago"}, 
	{title : "Kurt Vonnegut, the Art of Fiction No. 64 (1977)", site: "theparisreview.or", href: "http://www.theparisreview.org/interviews/3605/the-art-of-fiction-no-64-kurt-vonnegut", time: "7 hours ago"}, 
	{title : "Our Understanding of Giraffes Does Not Measure Up", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/science/our-understanding-of-giraffes-does-not-measure-up.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "9 hours ago"}, 
	{title : "How feminism helped me solve one of file systems’ oldest conundrums", site: "valerieaurora.or", href: "http://blog.valerieaurora.org/2014/10/03/operating-systems-war-story-how-feminism-helped-me-solve-one-of-file-systems-oldest-conundrums/", time: "1 hour ago"}, 
	{title : "Somewhere in the Philippines, there are roads named after countries", site: "nicluo.co", href: "http://nicluo.com/somewhere-in-the-philippines-theres-roads-of-every-country-in-the-world/", time: "2 hours ago"}, 
	{title : "Show HN: Simple email rendering tool to handle multi-language email content", site: "github.co", href: "https://github.com/KeepSafe/ks-email-parser", time: "1 hour ago"}, 
	{title : "OpenBSD 5.6: What will be there", site: "openbsd.or", href: "http://www.openbsd.org/56.html", time: "10 hours ago"}, 
	{title : "Cheap Beer and the Psychology of PlayStation Now Pricing", site: "psychologyofgames.co", href: "http://www.psychologyofgames.com/2014/08/cheep-beer-and-the-psychology-of-playstation-now-pricing/", time: "10 hours ago"}, 
	{title : "Building a testable Go web app", site: "sourcegraph.co", href: "https://sourcegraph.com/blog/building-a-testable-webapp", time: "8 hours ago"}, 
	{title : "On the Computational Complexity of MapReduce", site: "jeremykun.co", href: "http://jeremykun.com/2014/10/05/on-the-computational-complexity-of-mapreduce/", time: "13 hours ago"}, 
	{title : "Dealer’s Hand: Why are so many people paying so much money for art? (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/12/02/dealers-hand", time: "8 hours ago"}, 
	{title : "Startups Spend with Abandon, Flush with Capital", site: "wsj.co", href: "http://online.wsj.com/articles/startups-spend-with-abandon-flush-with-capital-1412549853", time: "2 hours ago"}, 
	{title : "Show HN: Generate interactive heatmaps from your Google Location History data", site: "theopolisme.github.i", href: "http://theopolisme.github.io/location-history-visualizer/", time: "14 hours ago"}, 
	{title : "Zen Buddhism and Alan Watts", site: "aeon.c", href: "http://aeon.co/magazine/philosophy/tim-lott-zen-buddhism-alan-watts/", time: "20 hours ago"}, 
	{title : "HexLogic – Logic gates in a hexagon grid", site: "anubiann00b.github.i", href: "http://anubiann00b.github.io/HexLogic/", time: "10 hours ago"}, 
	{title : "Breaking the Waves", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/02/10/breaking-the-waves-2", time: "6 hours ago"}, 
	{title : "Google to Make Security Guards Employees, Rather Than Contractors", site: "wsj.co", href: "http://blogs.wsj.com/digits/2014/10/03/google-to-make-security-guards-as-employees-rather-than-contractors/", time: "1 day ago"}, 
	{title : "What is probabilistic programming?", site: "pl-enthusiast.ne", href: "http://www.pl-enthusiast.net/2014/09/08/probabilistic-programming/", time: "14 hours ago"}, 
]