news16 = [
	{title : "US top cop decries encryption, demands backdoors", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/us-top-cop-decries-encryption-demands-backdoors/", time: "4 days ago"}, 
	{title : "Bridging Algorithms and Programming Languages", site: "pl-enthusiast.ne", href: "http://www.pl-enthusiast.net/2014/09/25/algorithms-and-programming-languages/", time: "6 days ago"}, 
	{title : "Humans Need Not Apply", site: "youtube.co", href: "https://www.youtube.com/watch?feature=youtu.be&v=7Pq-S557XQU", time: "3 hours ago"}, 
	{title : "The Dropbox terabyte conundrum", site: "sixcolors.co", href: "http://sixcolors.com/post/2014/09/the-dropbox-terabyte-conundrum/", time: "12 days ago"}, 
	{title : "Ello, goodbye", site: "aralbalkan.co", href: "https://aralbalkan.com/notes/ello-goodbye/", time: "9 days ago"}, 
	{title : "Angry Birds maker Rovio lays off 130 staff and tries to 'reignite growth'", site: "theguardian.co", href: "http://www.theguardian.com/technology/2014/oct/02/angry-birds-rovio-layoffs-growth", time: "3 days ago"}, 
	{title : "Ideas about a new programming language for games [video] [Jonathan Blow]", site: "youtube.co", href: "https://www.youtube.com/watch?v=TH9VCN6UkyQ", time: "16 days ago"}, 
	{title : "Peter Thiel and David Graeber Debate Technology’s Future", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/22/arts/peter-thiel-and-david-graeber-debate-technologys-future.html", time: "13 days ago"}, 
	{title : "Use Salt to manage and deploy Docker containers", site: "jacksoncage.s", href: "http://jacksoncage.se/posts/2014/10/01/use-salt-to-manage-and-deploy-docker-containers/", time: "4 days ago"}, 
	{title : "The Kerning of Neil DeGrasse Tyson, Fearless Denier Killer", site: "rawstory.co", href: "http://www.rawstory.com/rs/2014/10/the-kerning-of-neil-degrasse-tyson-fearless-denier-killer/", time: "1 day ago"}, 
	{title : "Amazon Launches WriteOn to Compete Against Crowd-Writing Sites Like Wattpad", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/amazon-launches-writeon-to-compete-against-crowd-writing-sites-like-wattpad", time: "2 days ago"}, 
	{title : "Early Digital Research CP/M Source Code", site: "computerhistory.or", href: "http://www.computerhistory.org/_static/atchm/early-digital-research-cpm-source-code/", time: "4 days ago"}, 
	{title : "Heat- and booze-tolerant yeast make more biofuels", site: "arstechnica.co", href: "http://arstechnica.com/science/2014/10/heat-booze-tolerant-yeast-make-more-biofuels/", time: "2 days ago"}, 
	{title : "Understanding sources of unfairness in data driven decision making", site: "medium.co", href: "https://medium.com/@mrtz/how-big-data-is-unfair-9aa544d739de", time: "2 days ago"}, 
	{title : "A re-enactment of a 1967 animal movement simulator", site: "etiennebenson.co", href: "http://www.etiennebenson.com/simplot/", time: "3 days ago"}, 
	{title : "Soil Doctors Hit Pay Dirt in Manhattan's Central Park", site: "npr.or", href: "http://www.npr.org/2014/10/02/353066730/soil-doctors-hit-pay-dirt-in-manhattans-central-park&sa=U&ei=tAouVLHXHsGryATlo4KoDw&ved=0CA4QqQIwAA&usg=AFQjCNGQKtdiodU8GxwPdl8ed7hFAeedSQ", time: "2 days ago"}, 
	{title : "How RAM Scrapers Work: The Tool Behind the Latest Credit Card Hacks", site: "wired.co", href: "http://www.wired.com/2014/09/ram-scrapers-how-they-work/", time: "5 days ago"}, 
	{title : "Hackers Are Controling 17,000 Apple Computers", site: "yahoo.co", href: "http://finance.yahoo.com/news/hackers-found-flaw-macs-using-121808264.html", time: "2 days ago"}, 
	{title : "The Mirrorball", site: "textfiles.co", href: "http://ascii.textfiles.com/archives/4395", time: "2 days ago"}, 
	{title : "Marriott Pays $600,000 Fine for Blocking Guests' Wi-Fi Hotspots", site: "skift.co", href: "http://skift.com/2014/10/03/marriott-pays-600000-fine-for-blocking-guests-wi-fi-hotspots/", time: "2 days ago"}, 
	{title : "Jobless Rate in U.S. Falls Below 6% as Hiring Picks Up", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/economy/monthly-jobs-report-september.html", time: "2 days ago"}, 
	{title : "ELI5: Why are there so many MEAN stacks?", site: "stackoverflow.co", href: "http://stackoverflow.com/questions/23199392/difference-between-mean-js-and-mean-io", time: "2 days ago"}, 
	{title : "The 10,000 Hour Rule for deliberate practice is wrong", site: "slate.co", href: "http://www.slate.com/articles/health_and_science/science/2014/09/malcolm_gladwell_s_10_000_hour_rule_for_deliberate_practice_is_wrong_genes.single.html", time: "4 days ago"}, 
	{title : "Hong Kong protesters beaten and bloodied as thugs attack sit-in", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/03/hong-kong-protestesters-democracy-occupy", time: "2 days ago"}, 
	{title : "Fullstack Academy: Come craft the CS education you would have wanted (NYC)", site: "fullstackacademy.co", href: "http://www.fullstackacademy.com/careers/positions", time: "ookmar"}, 
]