news19 = [
	{title : "Using Machine Learning and Node.js to detect the gender of Instagram Users", site: "totems.c", href: "http://totems.co/?p=11084", time: "8 days ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341", time: "3 days ago"}, 
	{title : "Benchmarking Tableau's S-1: How Key SaaS Metrics Stack Up", site: "tomtunguz.co", href: "http://tomtunguz.com/tableau-s-1/", time: "8 days ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math", time: "5 days ago"}, 
	{title : "The anatomy of a door-to-door Taobao delivery", site: "theanthill.or", href: "http://theanthill.org/taobao-delivery", time: "12 days ago"}, 
	{title : "Facebook's Bus Drivers Seek Union", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/business/facebooks-bus-drivers-seek-union.html", time: "1 day ago"}, 
	{title : "The Evils of Open Source", site: "xavierriley.co.u", href: "http://xavierriley.co.uk/the-evils-of-open-source/", time: "1 day ago"}, 
	{title : "Show HN: ShirtJS – Sexy JavaScript MVC Tees -AngularJS -Node.js", site: "shirtjs.co", href: "http://shirtjs.com", time: "2 days ago"}, 
	{title : "Marriott Hotels fined $600,000 by FCC for jamming Wi-Fi hotspots [pdf]", site: "fcc.go", href: "http://transition.fcc.gov/Daily_Releases/Daily_Business/2014/db1003/DA-14-1444A1.pdf", time: "4 days ago"}, 
	{title : "Shadow Internet That’s 100 Times Faster Than Google Fiber", site: "wired.co", href: "http://www.wired.com/2014/06/esnet", time: "2 days ago"}, 
	{title : "Monit issues takedown request for Inspeqtor (both open source monitoring tools)", site: "twitter.co", href: "https://twitter.com/mperham/status/518796150733033472", time: "1 day ago"}, 
	{title : "The Greatest Ancient Picture Gallery", site: "nybooks.co", href: "http://www.nybooks.com/articles/archives/2014/oct/23/greatest-ancient-picture-gallery/", time: "2 days ago"}, 
	{title : "Tuples in Swift: How to Create, Read, and Return Them", site: "codingexplorer.co", href: "http://www.codingexplorer.com/tuples-in-swift-create-read-and-return/", time: "1 day ago"}, 
	{title : "Installing Nvidia CUDA on Ubuntu 14.04 for Linux GPU Computing", site: "quantstart.co", href: "http://www.quantstart.com/articles/Installing-Nvidia-CUDA-on-Ubuntu-14-04-for-Linux-GPU-Computing", time: "1 day ago"}, 
	{title : "Apple Sapphire Glass Supplier, GT Advanced, Files for Bankruptcy", site: "businessinsider.co", href: "http://www.businessinsider.com/gt-advanced-files-for-bankruptcy-2014-10", time: "1 day ago"}, 
	{title : "Animating Images with CSS", site: "pencilscoop.co", href: "http://www.pencilscoop.com/2014/04/animating-images-with-css-keyframes/", time: "1 day ago"}, 
	{title : "A new type of software helps researchers decide what they should be looking for", site: "economist.co", href: "http://www.economist.com/news/science-and-technology/21621704-new-type-software-helps-researchers-decide-what-they-should-be-looking", time: "3 days ago"}, 
	{title : "Glut of postdoc researchers stirs quiet crisis in science", site: "bostonglobe.co", href: "http://www.bostonglobe.com/metro/2014/10/04/glut-postdoc-researchers-stirs-quiet-crisis-science/HWxyErx9RNIW17khv0MWTN/story.html", time: "1 day ago"}, 
	{title : "Consider the Lobster (2004)", site: "gourmet.co", href: "http://www.gourmet.com/magazine/2000s/2004/08/consider_the_lobster?printable=true", time: "4 days ago"}, 
	{title : "1041uuu Pixel Art", site: "1041uuu.tumblr.co", href: "http://1041uuu.tumblr.com/", time: "2 days ago"}, 
	{title : "Bugzilla Zero-Day Exposes Zero-Day Bugs", site: "krebsonsecurity.co", href: "https://krebsonsecurity.com/2014/10/bugzilla-zero-day-exposes-zero-day-bugs/", time: "1 day ago"}, 
	{title : "Geena Davis' Two Easy Steps to Make Hollywood Less Sexist (Guest Column) (2013)", site: "hollywoodreporter.co", href: "http://www.hollywoodreporter.com/news/geena-davis-two-easy-steps-664573", time: "1 day ago"}, 
	{title : "Google+ is hurting the Internet. Europeans have the power to stop it", site: "focusontheuser.e", href: "http://focusontheuser.eu/", time: "1 day ago"}, 
	{title : "Bruce Byfield: LibreOffice, OpenOffice, and Rumors of Unification", site: "linuxpromagazine.co", href: "http://www.linuxpromagazine.com/Online/Blogs/Off-the-Beat-Bruce-Byfield-s-Blog/LibreOffice-OpenOffice-and-rumors-of-unification", time: "1 day ago"}, 
	{title : "The slaying of bearwhale. 30k BTC sell order being chewed through", site: "youtube.co", href: "http://www.youtube.com/watch?v=-uX_bB_4VJk", time: "1 day ago"}, 
	{title : "How We Drove 10K Unique Visitors to a New Product in a Month", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/237922", time: "1 day ago"}, 
	{title : "Attack code for 'unpatchable' USB flaw released", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/technology-29475566", time: "1 day ago"}, 
	{title : "What It's Like to Build a Startup in Gaza", site: "wired.co", href: "http://www.wired.com/2014/10/like-build-startup-gaza-strip-bombs-drop/", time: "4 days ago"}, 
	{title : "ComputerCOP: Dubious 'Internet Safety Software' Police Distributed to Families", site: "eff.or", href: "https://www.eff.org/deeplinks/2014/09/computercop-dangerous-internet-safety-software-hundreds-police-agencies", time: "6 days ago"}, 
]