news5 = [
	{title : "Real-Time Biometric Attendance of Indian Government Employees", site: "attendance.gov.i", href: "http://attendance.gov.in", time: "11 hours ago"}, 
	{title : "Former Infosys recruiter says he was told not to hire U.S. workers", site: "computerworld.co", href: "http://www.computerworld.com/article/2692372/former-infosys-recruiter-says-he-was-told-not-to-hire-us-workers.html", time: "7 hours ago"}, 
	{title : "Meeting the New Indian Prime Minister – Bill Gates", site: "gatesnotes.co", href: "http://www.gatesnotes.com/Development/Meeting-Indias-New-Prime-Minister?WT.mc_id=10_03_2014_IndiaTrip_fb&WT.tsrc=Facebook", time: "5 hours ago"}, 
	{title : "BlackBerry may have finally hit rock bottom in U.S. market share", site: "geekwire.co", href: "http://www.geekwire.com/2014/blackberry-may-finally-hit-rock-bottom-u-s-market-share/", time: "6 hours ago"}, 
	{title : "Yahoo just sacked nearly all of its engineers in India", site: "qz.co", href: "http://qz.com/277371/yahoo-just-sacked-nearly-all-of-its-engineers-in-india/", time: "6 hours ago"}, 
	{title : "Why You Must Lie on Job Interviews and What You Must Lie About", site: "linkedin.co", href: "https://www.linkedin.com/pulse/article/20141006125226-10136502-why-you-must-lie-on-job-interviews-and-what-you-must-lie-about", time: "6 hours ago"}, 
	{title : "Missing Maps: a human genome project for cities", site: "theguardian.co", href: "http://www.theguardian.com/cities/2014/oct/06/missing-maps-human-genome-project-unmapped-cities", time: "1 day ago"}, 
	{title : "'Open Source is awful in many ways, and people should be aware of this'", site: "plus.google.co", href: "https://plus.google.com/app/basic/stream/z13rdjryqyn1xlt3522sxpugoz3gujbhh04", time: "1 day ago"}, 
	{title : "Wednesday's lunar eclipse will be special", site: "csmonitor.co", href: "http://www.csmonitor.com/Science/2014/1006/Why-Wednesday-s-lunar-eclipse-will-be-so-special-video", time: "1 day ago"}, 
	{title : "Seven Deadly Sins of Talking About Types", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~srk31/blog/2014/10/07/", time: "17 hours ago"}, 
	{title : "Man-Computer Symbiosis (1960)", site: "mit.ed", href: "http://groups.csail.mit.edu/medg/people/psz/Licklider.html", time: "1 day ago"}, 
	{title : "Why can't Apple decrypt your iPhone?", site: "cryptographyengineering.co", href: "http://blog.cryptographyengineering.com/2014/10/why-cant-apple-decrypt-your-iphone.html", time: "3 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://paulgraham.com/before.html", time: "6 days ago"}, 
	{title : "What's Wrong with the Amazon Fire Phone?", site: "pcmag.co", href: "http://www.pcmag.com/article2/0,2817,2469066,00.asp", time: "8 hours ago"}, 
	{title : "The NSA and Me", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/the-nsa-and-me/", time: "5 days ago"}, 
	{title : "Peter Thiel and Silicon Valley's Obsession with Superficial Thinking", site: "institutionalinvestor.co", href: "http://www.institutionalinvestor.com/inside-edge/3387493/peter-thiel-and-silicon-valleys-obsession-with-superficial-thinking.html", time: "7 hours ago"}, 
	{title : "Test your JavaScript with Jasmine", site: "rainforestqa.co", href: "https://blog.rainforestqa.com/2014-10-06-test-your-javascript-with-jasmine-part-2/", time: "8 hours ago"}, 
	{title : "MakeMeASandwich.js", site: "github.co", href: "https://github.com/travist/makemeasandwich.js", time: "12 hours ago"}, 
	{title : "People care more about convenience than privacy online", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/the-switch/wp/2014/10/07/people-care-more-about-convenience-than-privacy-online/", time: "9 hours ago"}, 
	{title : "Show HN: ScreenSlicer – Automatic, zero-config web scraping", site: "github.co", href: "https://github.com/MachinePublishers/ScreenSlicer", time: "1 day ago"}, 
	{title : "Meteor Acquires FathomDb", site: "meteor.co", href: "https://www.meteor.com/blog/2014/10/07/fathomdb-joining-meteor", time: "11 hours ago"}, 
	{title : "Turndownforwhat.JS", site: "nthitz.github.i", href: "https://nthitz.github.io/turndownforwhatjs/", time: "6 hours ago"}, 
	{title : "BattleBots may be coming back in 2015", site: "kickstarter.co", href: "https://www.kickstarter.com/projects/1555995549/bring-robot-combat-back-to-your-screen", time: "8 hours ago"}, 
	{title : "NASA Study Finds Earth's Ocean Abyss Has Not Warmed", site: "nasa.go", href: "http://www.jpl.nasa.gov/news/news.php?feature=4321", time: "10 hours ago"}, 
	{title : "Building Your First Swift App Video", site: "apple.co", href: "https://developer.apple.com/swift/blog/?id=16", time: "10 hours ago"}, 
	{title : "Heathkit", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Heathkit", time: "1 day ago"}, 
	{title : "Choosing a Web Framework: Django, Flask, or Pyramid", site: "airpair.co", href: "https://www.airpair.com/python/posts/django-flask-pyramid", time: "14 hours ago"}, 
]