news1 = [
	{title : "Hacker News API", site: "ycombinator.co", href: "http://blog.ycombinator.com/hacker-news-api", time: "11 hours ago"}, 
	{title : "Adobe Spyware Reveals Again the Price of DRM: Your Privacy and Security", site: "eff.or", href: "https://www.eff.org/deeplinks/2014/10/adobe-spyware-reveals-again-price-drm-your-privacy-and-security", time: "4 hours ago"}, 
	{title : "San Francisco Legalizes, Regulates Airbnb with 7-4 Vote, Lots of Amendments", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/san-francisco-airbnb/", time: "1 hour ago"}, 
	{title : "GitHub Student Developer Pack", site: "github.co", href: "https://education.github.com/pack", time: "12 hours ago"}, 
	{title : "Plastc Card", site: "plastc.co", href: "https://www.plastc.com/#", time: "10 hours ago"}, 
	{title : "Show HN: Speeding up PostgreSQL through vectorized execution", site: "github.co", href: "https://github.com/citusdata/postgres_vectorization_test", time: "8 hours ago"}, 
	{title : "Failed Startup Post-Mortems", site: "gitbooks.i", href: "http://3things.gitbooks.io/77-failed-startup-post-mortems/", time: "6 hours ago"}, 
	{title : "Twitter sues U.S. government over ability to disclose surveillance orders", site: "washingtonpost.co", href: "http://www.washingtonpost.com/world/national-security/twitter-sues-us-government-over-limits-on-ability-to-disclose-surveillance-orders/2014/10/07/5cc39ba0-4dd4-11e4-babe-e91da079cb8a_story.html", time: "11 hours ago"}, 
	{title : "Solar sends energy prices below zero in middle of day", site: "reneweconomy.com.a", href: "http://reneweconomy.com.au/2014/solar-sends-energy-prices-below-zero-in-middle-of-day-63767", time: "6 hours ago"}, 
	{title : "Lecture 5, How to Start a Startup: Peter Thiel", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec05/", time: "7 hours ago"}, 
	{title : "What we did about expired links on HN", site: "pastebin.co", href: "http://pastebin.com/bSW5dfRQ", time: "6 hours ago"}, 
	{title : "The amazing progress of LEDs", site: "vox.co", href: "http://www.vox.com/2014/10/7/6936361/the-amazing-progress-of-leds-in-one-chart", time: "6 hours ago"}, 
	{title : "Rust means never having to close a socket", site: "skylight.i", href: "http://blog.skylight.io/rust-means-never-having-to-close-a-socket/", time: "12 hours ago"}, 
	{title : "SQLite 3.8.7 is 50% faster than 3.7.17", site: "gmane.or", href: "http://permalink.gmane.org/gmane.comp.db.sqlite.general/90549", time: "19 hours ago"}, 
	{title : "The Extropian Roots of Bitcoin", site: "cryptocoinsnews.co", href: "https://www.cryptocoinsnews.com/extropian-roots-bitcoin/", time: "9 hours ago"}, 
	{title : "Show HN: ReadMe.io – Beautiful Documentation Made Easy", site: "readme.i", href: "http://readme.io/home", time: "11 hours ago"}, 
	{title : "The Limits of Friendship", site: "newyorker.co", href: "http://www.newyorker.com/science/maria-konnikova/social-media-affect-math-dunbar-number-friendships", time: "11 hours ago"}, 
	{title : "Show HN: Hacker News implemented using the new API", site: "firebaseapp.co", href: "https://realtimehackernews.firebaseapp.com/", time: "8 hours ago"}, 
	{title : "A replacement for JavaScript's “alert”", site: "github.co", href: "https://github.com/t4t5/sweetalert", time: "15 hours ago"}, 
	{title : "Automatizing rewards for solving hard problems with Bitcoin", site: "blogchain.f", href: "http://blogchain.fr/programmarket-en/", time: "6 hours ago"}, 
	{title : "A Flurry of Copycats on PubMed", site: "thegrandlocus.co", href: "http://blog.thegrandlocus.com/2014/10/a-flurry-of-copycats-on-pubmed", time: "4 hours ago"}, 
	{title : "Interview with Brad Cox, the Man Behind Objective-C", site: "mactech.co", href: "http://www.mactech.com/articles/mactech/Vol.25/25.07/2507RoadtoCode-BradCoxInterview/index.html", time: "11 hours ago"}, 
	{title : "LED Inventor and Employer Settle for $8.1M (2005)", site: "nytimes.co", href: "http://www.nytimes.com/2005/01/12/business/worldbusiness/12light.html?_r=1&", time: "6 hours ago"}, 
	{title : "Talking about “types”", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~srk31/blog/2014/10/07", time: "13 hours ago"}, 
	{title : "Online ads roll the dice", site: "ftc.go", href: "http://www.ftc.gov/news-events/blogs/techftc/2014/09/online-ads-roll-dice", time: "7 hours ago"}, 
	{title : "Finding a Video Poker Bug Made These Guys Rich", site: "wired.co", href: "http://www.wired.com/2014/10/cheating-video-poker/", time: "13 hours ago"}, 
	{title : "The 2014 Nobel Prize in Physics", site: "nobelprize.or", href: "http://www.nobelprize.org/nobel_prizes/physics/laureates/2014/press.html", time: "19 hours ago"}, 
	{title : "Show HN: JavaScript Battle – A daily artificial intelligence battle", site: "javascriptbattle.co", href: "http://www.javascriptbattle.com/", time: "13 hours ago"}, 
	{title : "The LED's Dark Secret (2009)", site: "ieee.or", href: "http://spectrum.ieee.org/semiconductors/optoelectronics/the-leds-dark-secret", time: "14 hours ago"}, 
]