news23 = [
	{title : "In 1976 I discovered Ebola, now I fear an unimaginable tragedy", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/04/ebola-zaire-peter-piot-outbreak", time: "3 days ago"}, 
	{title : "Biggest patent win ever? Microsoft's billion dollar a year Samsung deal", site: "zdnet.co", href: "http://www.zdnet.com/biggest-patent-win-ever-microsofts-billion-dollar-a-year-samsung-deal-7000034353/", time: "2 days ago"}, 
	{title : "How Would the FDA Respond If We Had a Drug to Cure Aging?", site: "kolber.typepad.co", href: "http://kolber.typepad.com/ethics_law_blog/2014/09/how-would-the-fda-respond-if-we-had-a-drug-to-cure-aging-guest-post-by-kira-peikoff.html", time: "2 days ago"}, 
	{title : "U.S. Navy Tests Robot Boat Swarm to Overwhelm Enemies", site: "ieee.or", href: "http://spectrum.ieee.org/automaton/robotics/military-robots/us-navy-robot-boat-swarm", time: "2 days ago"}, 
	{title : "After raising $50M, Reddit forces all remote workers to relocate to SF", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/01/after-raising-50m-reddit-forces-remote-workers-to-relocate-to-sf-or-get-fired/", time: "6 days ago"}, 
	{title : "Bezier.js, for doing bezier curve things", site: "pomax.github.i", href: "http://pomax.github.io/bezierjs/", time: "2 days ago"}, 
	{title : "India, U.S. Agree to Joint Exploration of Mars", site: "wsj.co", href: "http://blogs.wsj.com/indiarealtime/2014/10/01/india-u-s-to-agree-to-joint-exploration-of-mars", time: "5 days ago"}, 
	{title : "The Aral Sea was once the fourth largest lake in the world. Watch it dry up", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/capital-weather-gang/wp/2014/09/30/the-aral-sea-was-once-the-fourth-largest-lake-in-the-world-watch-it-dry-up/", time: "7 days ago"}, 
	{title : "if (osName.startsWith('windows 9'))", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22%29", time: "6 days ago"}, 
	{title : "Talkray (YC W12), an under-the-radar messaging app, takes off overseas", site: "fortune.co", href: "http://fortune.com/2014/09/23/talkray-messaging-app-series-b/", time: "10 days ago"}, 
	{title : "Bitcoin's Killer Apps", site: "chain.co", href: "http://blog.chain.com/post/99177371581/bitcoins-killer-apps", time: "3 days ago"}, 
	{title : "What do the top 1% of software engineers do?", site: "quora.co", href: "http://www.quora.com/What-do-the-top-1-of-software-engineers-do-that-the-other-99-do-not", time: "2 days ago"}, 
	{title : "A table of electric clay (2013) [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lvtfD_rJ2hE", time: "2 days ago"}, 
	{title : "Which Flavor of Tokenization Is Used by Apple Pay", site: "pomcor.co", href: "http://pomcor.com/2014/10/05/which-flavor-of-tokenization-is-used-by-apple-pay/", time: "2 days ago"}, 
	{title : "What Venture Capitalists will not tell you", site: "linkedin.co", href: "https://www.linkedin.com/today/post/article/20141005202543-140792-what-venture-capitalists-will-not-tell-you", time: "2 days ago"}, 
	{title : "Nereus deep sea sub 'implodes' 10km-down", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-27374326", time: "2 days ago"}, 
	{title : "BDD anti patterns", site: "jcowie.co.u", href: "http://jcowie.co.uk/articles/BDD-Antipatterns/", time: "2 days ago"}, 
	{title : "Dirty Assembly Tricks in NES Assembly (2013)", site: "andrewkelley.m", href: "http://andrewkelley.me/post/jamulator.html#dirty-assembly-tricks", time: "4 days ago"}, 
	{title : "Online JavaScript minifier", site: "javascriptcompress.herokuapp.co", href: "http://javascriptcompress.herokuapp.com/", time: "2 days ago"}, 
	{title : "C++ and the Perils of Double-Checked Locking (2004) [pdf]", site: "aristeia.co", href: "http://www.aristeia.com/Papers/DDJ_Jul_Aug_2004_revised.pdf", time: "3 days ago"}, 
	{title : "Digital revolution has yet to fulfil its promise of productivity and better jobs", site: "economist.co", href: "http://www.economist.com/news/special-report/21621237-digital-revolution-has-yet-fulfil-its-promise-higher-productivity-and-better", time: "4 days ago"}, 
	{title : "How Exercise May Protect Against Depression", site: "well.blogs.nytimes.co", href: "http://well.blogs.nytimes.com/2014/10/01/how-exercise-may-protect-against-depression/?src=me", time: "5 days ago"}, 
	{title : "Dollar a Day", site: "dollaraday.c", href: "https://dollaraday.co/", time: "6 days ago"}, 
	{title : "NFL Bans Beats Headphones on Camera", site: "recode.ne", href: "http://recode.net/2014/10/04/nfl-bans-beats-headphones-on-camera/", time: "2 days ago"}, 
	{title : "The Quest to Build an Elevator into Space", site: "gizmodo.co", href: "http://gizmodo.com/the-quest-to-build-an-elevator-to-space-1638192427", time: "4 days ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977", time: "4 days ago"}, 
	{title : "Early Digital Research CP/M Source Code", site: "computerhistory.or", href: "http://www.computerhistory.org/_static/atchm/early-digital-research-cpm-source-code/", time: "6 days ago"}, 
	{title : "How feminism helped me solve one of file systems’ oldest conundrums", site: "valerieaurora.or", href: "http://blog.valerieaurora.org/2014/10/03/operating-systems-war-story-how-feminism-helped-me-solve-one-of-file-systems-oldest-conundrums/", time: "2 days ago"}, 
	{title : "AngularJS Tutorial: a comprehensive 10,000 word guide", site: "airpair.co", href: "http://www.airpair.com/angularjs", time: "4 days ago"}, 
]