news17 = [
	{title : "The Man Who Smuggles Traders Joe’s into Canada", site: "priceonomics.co", href: "http://priceonomics.com/the-man-who-smuggles-traders-joes-into-canada/", time: "4 days ago"}, 
	{title : "Autothysis SSD drives impede unauthorised access", site: "securedrives.co.u", href: "http://securedrives.co.uk/index.php?route=product/category&path=73_75", time: "2 days ago"}, 
	{title : "Shielding Applications from an Untrusted Cloud with Haven [pdf]", site: "usenix.or", href: "https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-baumann.pdf", time: "1 day ago"}, 
	{title : "“Not” Neutrality?", site: "level3.co", href: "http://blog.level3.com/open-internet/not-neutrality/", time: "6 days ago"}, 
	{title : "Do Deep Nets Really Need to be Deep? [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1312.6184v5.pdf", time: "4 days ago"}, 
	{title : "Same-Sex Marriage Is Now Legal for a Majority of the USA", site: "fivethirtyeight.co", href: "http://fivethirtyeight.com/datalab/same-sex-marriage-is-now-legal-for-a-majority-of-the-u-s/", time: "1 day ago"}, 
	{title : "Hacked Screenshots Show Friend-To-Friend Payments Feature in Facebook Messenger", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/pay-with-facebook-messenger/", time: "2 days ago"}, 
	{title : "Managing Issues and Pull Requests Across Repositories", site: "github.co", href: "https://github.com/blog/1901-managing-issues-and-pull-requests-across-repositories", time: "1 day ago"}, 
	{title : "Learn JavaScript by adventuring around in the terminal", site: "github.co", href: "https://github.com/sethvincent/javascripting", time: "1 day ago"}, 
	{title : "On the Computational Complexity of MapReduce", site: "jeremykun.co", href: "http://jeremykun.com/2014/10/05/on-the-computational-complexity-of-mapreduce/", time: "2 days ago"}, 
	{title : "How to Work Quietly", site: "idonethis.co", href: "http://blog.idonethis.com/quiet-work/", time: "1 day ago"}, 
	{title : "Azalead Ends Cold Calls by Telling You Which Company Visited Your Site", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/06/azalead-ends-cold-calls-by-telling-you-which-company-visited-your-site/", time: "1 day ago"}, 
	{title : "Somewhere in the Philippines, there are roads named after countries", site: "nicluo.co", href: "http://nicluo.com/somewhere-in-the-philippines-theres-roads-of-every-country-in-the-world/", time: "2 days ago"}, 
	{title : "Show HN: Mojulo – Pixelated Math Rendering Sandbox Toy", site: "maxbittker.github.i", href: "http://maxbittker.github.io/Mojulo/", time: "3 days ago"}, 
	{title : "NPR's Fresh Air interviews Walter Isaacson, author of 'The Innovators'", site: "npr.or", href: "http://www.npr.org/2014/10/06/353269811/how-the-cold-war-and-george-orwell-helped-make-the-internet-what-it-is", time: "1 day ago"}, 
	{title : "This Is What Common Core Looks Like", site: "erickerickson.or", href: "http://www.erickerickson.org/blog/2014/09/30/this-is-what-common-core-looks-like/", time: "1 day ago"}, 
	{title : "Google to Make Security Guards Employees, Rather Than Contractors", site: "wsj.co", href: "http://blogs.wsj.com/digits/2014/10/03/google-to-make-security-guards-as-employees-rather-than-contractors/", time: "3 days ago"}, 
	{title : "How a Trillion-Dollar Market Remains Hidden in Plain Sight", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/05/how-a-trillion-dollar-market-remains-hidden-in-plain-sight/", time: "2 days ago"}, 
	{title : "FBI director says Chinese hackers are like a “drunk burglar”", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/fbi-director-says-chinese-hackers-are-like-a-drunk-burglar/", time: "1 day ago"}, 
	{title : "What is probabilistic programming?", site: "pl-enthusiast.ne", href: "http://www.pl-enthusiast.net/2014/09/08/probabilistic-programming/", time: "2 days ago"}, 
	{title : "Bugzilla Zero-Day Exposes Zero-Day Bugs", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/bugzilla-zero-day-exposes-zero-day-bugs", time: "1 day ago"}, 
	{title : "Why the Scroll Event Change in iOS 8 Is a Big Deal", site: "telerik.co", href: "http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/", time: "1 day ago"}, 
	{title : "Freedom from Food", site: "aeon.c", href: "http://aeon.co/magazine/health/would-we-opt-out-of-food-if-given-the-chance/", time: "1 day ago"}, 
	{title : "Hewlett-Packard Announces Breakup Plan", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/business/hewlett-packard-announces-breakup-plan.html?src=busln&_r=0", time: "1 day ago"}, 
	{title : "[iOS8 Tutorial] Interactive Notifications with Notification Actions", site: "thinkandbuild.i", href: "http://www.thinkandbuild.it/interactive-notifications-with-notification-actions/", time: "1 day ago"}, 
	{title : "Uber Hires Former Lyft COO VanderZanden", site: "recode.ne", href: "http://recode.net/2014/10/06/uber-hires-former-lyft-coo-vanderzanden-to-spur-international-growth/", time: "1 day ago"}, 
	{title : "Adobe and Microsoft Partner at Adobe MAX", site: "youtube.co", href: "http://www.youtube.com/watch?v=tR5JPw4HiTY&feature=youtu.be", time: "1 day ago"}, 
	{title : "Breaking the Waves", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/02/10/breaking-the-waves-2", time: "2 days ago"}, 
]