news8 = [
	{title : "Plastc: rewritable payment card with e-ink touchscreen", site: "plastc.co", href: "https://www.plastc.com/card", time: "15 hours ago"}, 
	{title : "Some Ebola experts worry virus may spread more easily than assumed", site: "latimes.co", href: "http://www.latimes.com/nation/la-na-ebola-questions-20141007-story.html", time: "14 hours ago"}, 
	{title : "Autodesk offers it's products for free to Students, Teachers and Schools", site: "autodesk.co", href: "http://www.autodesk.com/education/home", time: "12 hours ago"}, 
	{title : "Show HN: Causemap – Crowdsourced Causality", site: "causemap.or", href: "http://www.causemap.org", time: "12 hours ago"}, 
	{title : "Nature – The easiest way to analyze your data", site: "nature42.co", href: "http://www.nature42.com/", time: "10 hours ago"}, 
	{title : "BeerThink: infinite scrolling in a mobile app with Ionic, Node.js, and RethinkDB", site: "rethinkdb.co", href: "http://rethinkdb.com/blog/beerthink/", time: "11 hours ago"}, 
	{title : "Pediff – tools for visually comparing web pages", site: "github.co", href: "https://github.com/Schibsted-Tech-Polska/stp.pediff", time: "1 day ago"}, 
	{title : "Twitter – Taking the fight for transparency to court", site: "blog.twitter.co", href: "https://blog.twitter.com/2014/taking-the-fight-for-transparency-to-court", time: "11 hours ago"}, 
	{title : "Floodwatch – A collective ad monitoring tool", site: "o-c-r.or", href: "http://floodwatch.o-c-r.org/", time: "13 hours ago"}, 
	{title : "Chart of the Day: Overweight Teenagers Earn Less as Adults", site: "motherjones.co", href: "http://www.motherjones.com/kevin-drum/2014/10/chart-day-overweight-teenagers-earn-less-adults", time: "10 hours ago"}, 
	{title : "Canadian startups bring big data to inefficient industries", site: "theglobeandmail.co", href: "http://www.theglobeandmail.com/report-on-business/small-business/sb-growth/day-to-day/farms-factories-and-film-sets-startups-bring-big-data-to-inefficient-industries/article20574000/", time: "1 day ago"}, 
	{title : "Zen Buddhism and Alan Watts", site: "aeon.c", href: "http://aeon.co/magazine/philosophy/tim-lott-zen-buddhism-alan-watts/", time: "2 days ago"}, 
	{title : "Quadrotor Pod Racing", site: "hackaday.co", href: "http://hackaday.com/2014/10/06/quadrotor-pod-racing/", time: "9 hours ago"}, 
	{title : "Amazon Warehouse Workers Head to Supreme Court Over Unpaid Theft Screenings", site: "huffingtonpost.co", href: "http://www.huffingtonpost.com/2014/10/07/amazon-warehouse-supreme-_n_5946464.html", time: "10 hours ago"}, 
	{title : "Gaming Player Motivation in Diablo 3", site: "all-things-andy-gavin.co", href: "http://all-things-andy-gavin.com/2014/10/06/diablo-3-from-good-to-great/", time: "10 hours ago"}, 
	{title : "5700+ Games, 50+ Systems.Complete Nintendo and Sega Sets", site: "ebay.co", href: "http://www.ebay.com/itm/5700-Games-50-Systems-Complete-Nintendo-Sega-Sets-and-more-Huge-Collection-/221564569633", time: "11 hours ago"}, 
	{title : "Servers for Hackers eBook", site: "serversforhackers.co", href: "https://book.serversforhackers.com/?", time: "11 hours ago"}, 
	{title : "The Forgotten Female Programmers Who Created Modern Tech", site: "npr.or", href: "http://www.npr.org/blogs/alltechconsidered/2014/10/06/345799830/the-forgotten-female-programmers-who-created-modern-tech", time: "1 day ago"}, 
	{title : "How Apple caused our iPhone app to crash for 3 days", site: "breefield.co", href: "http://www.breefield.com/essays/critical-app-review", time: "11 hours ago"}, 
	{title : "20 years of blogging", site: "scripting.co", href: "http://scripting.com/2014/10/07/20YearsOfBlogging.html", time: "14 hours ago"}, 
	{title : "What's wrong with Angular.js", site: "medium.co", href: "https://medium.com/@steida/whats-wrong-with-angular-js-97b0a787f903", time: "15 hours ago"}, 
	{title : "Pharocloud – hosting for Smalltalk web-applications", site: "pharocloud.co", href: "http://pharocloud.com/", time: "1 day ago"}, 
	{title : "How Seriously Does Your Cloud Hosting Provider Take Redundancy?", site: "upcloud.co", href: "http://en.upcloud.com/blog/how-seriously-does-your-cloud-hosting-provider-take-redundancy/", time: "16 hours ago"}, 
	{title : "Spotify Is Powered by Linux and Open Source", site: "linux.co", href: "http://www.linux.com/news/enterprise/case-studies/790458-spotify-is-powered-by-linux-and-open-source", time: "12 hours ago"}, 
	{title : "HTTP Requests are Hard", site: "mobify.co", href: "http://www.mobify.com/blog/http-requests-are-hard/", time: "12 hours ago"}, 
	{title : "Adobe Is Spying on Users, Collecting Data on Their EBook Libraries", site: "the-digital-reader.co", href: "http://the-digital-reader.com/2014/10/06/adobe-spying-users-collecting-data-ebook-libraries/#.VDPSl-fk-SU", time: "17 hours ago"}, 
	{title : "GitHub Gives Free Access to Developer Tools (Stripe, UnrealEngine, DigitalOcean)", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/github-partners-with-digital-ocean-unreal-engine-and-others-to-give-students-free-access-to-developer-tools/", time: "12 hours ago"}, 
	{title : "Docker Acquires Koality to Accelerate Development of Docker Hub Enterprise", site: "businesswire.co", href: "http://www.businesswire.com/news/home/20141007005035/en/Docker-Acquires-Koality-Accelerate-Development-Docker-Hub", time: "15 hours ago"}, 
]