news26 = [
	{title : "The Fourth Skull: A Tale of Authenticity and Fraud (2013)", site: "theappendix.ne", href: "http://theappendix.net/issues/2013/4/the-fourth-skull-a-tale-of-authenticity-and-fraud", time: "3 days ago"}, 
	{title : "HFT in my backyard – III", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/02/hft-in-my-backyard-iii/", time: "5 days ago"}, 
	{title : "Most People with Addiction Simply Grow Out of It", site: "substance.co", href: "http://www.substance.com/most-people-with-addiction-simply-grow-out-of-it-why-is-this-widely-denied/13017/", time: "6 days ago"}, 
	{title : "Journey into information theory", site: "khanacademy.or", href: "https://www.khanacademy.org/computing/computer-science/informationtheory", time: "2 days ago"}, 
	{title : "Libsqlfs: A POSIX-style file system on top of an SQLite database", site: "github.co", href: "https://github.com/guardianproject/libsqlfs", time: "4 days ago"}, 
	{title : "Universal SSL", site: "cloudflare.co", href: "https://blog.cloudflare.com/introducing-universal-ssl/", time: "8 days ago"}, 
	{title : "John Carmack on Inlined Code", site: "number-none.co", href: "http://number-none.com/blow/john_carmack_on_inlined_code.html", time: "11 days ago"}, 
	{title : "Bill Gates: Bitcoin Is 'Better Than Currency'", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/238103", time: "3 days ago"}, 
	{title : "Keynote: Dries Buytaert. Scaling open source projects", site: "drupal.or", href: "https://amsterdam2014.drupal.org/keynote-dries-buytaert", time: "2 days ago"}, 
	{title : "Uber Improves Life, Economists Agree", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/01/upshot/uber-improves-life-economists-agree.html", time: "2 days ago"}, 
	{title : "Shellshock will happen again", site: "mecheye.ne", href: "http://blog.mecheye.net/2014/10/shellshock-will-happen-again/", time: "2 days ago"}, 
	{title : "HackCampus Internship Programme", site: "hackcampus.i", href: "http://hackcampus.io/internship/#hero", time: "2 days ago"}, 
	{title : "CDC confirms first Ebola case diagnosed in US", site: "cnbc.co", href: "http://www.cnbc.com/id/102037055", time: "7 days ago"}, 
	{title : "ForestDb – A Fast Key-Value Storage Engine Based on Hierarchical B+-Tree Trie", site: "github.co", href: "https://github.com/couchbaselabs/forestdb", time: "3 days ago"}, 
	{title : "Shapecatcher: Draw the Unicode character you want", site: "shapecatcher.co", href: "http://shapecatcher.com", time: "5 days ago"}, 
	{title : "Analyzing AngelList Job Postings, Part 2: Salary and Equity Benchmarks", site: "codingvc.co", href: "http://codingvc.com/analyzing-angellist-job-postings-part-2-salary-and-equity-benchmarks", time: "4 days ago"}, 
	{title : "An Analysis of Shell Shock Malware", site: "erenyagdiran.github.i", href: "http://erenyagdiran.github.io/An-Analysis-of-Shell-shock-malware/", time: "3 days ago"}, 
	{title : "Sourcery (YC W13) Raises $2.5M to Connect Kitchens and Local Food Suppliers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/sourcery-raises-2-5m-to-connect-kitchens-and-local-food-suppliers/", time: "4 days ago"}, 
	{title : "Windows 95 on Android Wear [video]", site: "youtube.co", href: "http://youtube.com/watch?v=GZx-LJH5J_I", time: "2 days ago"}, 
	{title : "Forty Portraits in Forty Years", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/03/magazine/01-brown-sisters-forty-years.html", time: "4 days ago"}, 
	{title : "Google Project Zero: More Mac OS X and iPhone Sandbox Escapes", site: "googleprojectzero.blogspot.co", href: "http://googleprojectzero.blogspot.com/2014/10/more-mac-os-x-and-iphone-sandbox.html", time: "6 days ago"}, 
	{title : "Lever (YC S12) raises $10M to make hiring awesome", site: "lever.c", href: "https://blog.lever.co/the-next-chapter/", time: "5 days ago"}, 
	{title : "Reddit/Hacker News clone using the MEAN stack", site: "thinkster.i", href: "https://thinkster.io/angulartutorial/mean-stack-tutorial/", time: "5 days ago"}, 
	{title : "Show HN: GifBook – Animated GIFs as paper flip books", site: "gifbook.i", href: "https://gifbook.io/?hn", time: "4 days ago"}, 
	{title : "Great books about mathematics", site: "kjro.s", href: "http://wp.kjro.se/2013/12/27/5-insanely-great-books-about-mathematics-you-should-read/", time: "284 days ago"}, 
	{title : "Ebola Infects Spanish Nurse, a First in West", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/world/europe/spain-reports-first-case-of-ebola-contracted-outside-west-africa.html", time: "1 day ago"}, 
	{title : "Tesla's trump card: Used cars", site: "autonews.co", href: "http://www.autonews.com/article/20141006/RETAIL04/310069963/teslas-trump-card-used-cars", time: "1 day ago"}, 
]