news22 = [
	{title : "Statistical Flaw Punctuates Brain Research in Elite Journals", site: "scientificamerican.co", href: "http://blogs.scientificamerican.com/talking-back/2014/03/27/statistical-flaw-punctuates-brain-research-in-elite-journals/", time: "2 days ago"}, 
	{title : "Bitcoin falls below $300, lowest in 11 months", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?below300", time: "2 days ago"}, 
	{title : "Postgres 9.5 feature highlight: row-level security and policies", site: "otacoo.co", href: "http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-row-level-security/", time: "4 days ago"}, 
	{title : "Usaddress – Python library for parsing unstructured address strings with NLP", site: "rtfd.or", href: "http://usaddress.rtfd.org/", time: "4 days ago"}, 
	{title : "Caesium: A brief history of timekeeping", site: "bbc.co", href: "http://www.bbc.com/news/magazine-29476893", time: "3 days ago"}, 
	{title : "Exploring Change Blindness", site: "learnforeverlearn.co", href: "http://learnforeverlearn.com/changeblindness/", time: "2 days ago"}, 
	{title : "Is Google Making Students Stupid?", site: "theatlantic.co", href: "http://www.theatlantic.com/education/archive/2014/09/is-google-making-students-stupid/380944/", time: "2 days ago"}, 
	{title : "Throw Out the College Application System", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/opinion/sunday/throw-out-the-college-application-system.html", time: "2 days ago"}, 
	{title : "Show HN: Open-Source, Free, Agile Project Management Tool", site: "taiga.i", href: "http://www.taiga.io", time: "6 days ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec04/#", time: "5 days ago"}, 
	{title : "The USSR used a nuclear charge to stop a gas well fire in 1966", site: "coal-seam-gas.co", href: "http://www.coal-seam-gas.com/accidents/ussr.htm", time: "6 days ago"}, 
	{title : "Novena Update", site: "bunniestudios.co", href: "http://www.bunniestudios.com/blog/?p=4146", time: "4 days ago"}, 
	{title : "Personal site, terminal style", site: "silvioporcellana.co", href: "http://silvioporcellana.com/", time: "2 days ago"}, 
	{title : "Lilblue Linux: Adventures Beyond the Land of Posix", site: "gentoo.or", href: "http://blogs.gentoo.org/blueness/2014/10/04/lilblue-linux-release-20140925-adventures-beyond-the-land-of-posix/", time: "3 days ago"}, 
	{title : "Comparisons among Java-based CSV parsers", site: "github.co", href: "https://github.com/uniVocity/csv-parsers-comparison", time: "2 days ago"}, 
	{title : "Colonizing the Solar System Is Humankind’s Insurance Policy Against Extinction", site: "singularityhub.co", href: "http://singularityhub.com/2014/10/05/elon-musk-is-right-colonizing-the-solar-system-is-humankinds-insurance-policy-against-extinction/", time: "1 day ago"}, 
	{title : "Yahoo Acquires Mobile Messaging App MessageMe", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/yahoo-acquires-mobile-messaging-app-messageme/", time: "4 days ago"}, 
	{title : "Qubitekk offers hope for protecting computers in the age of quantum computing", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/05/duncan-earl-interview/view-all/", time: "2 days ago"}, 
	{title : "I come to bury IAmCarbonatedMilk.com, not to praise it (2002)", site: "salon.co", href: "http://www.salon.com/2002/08/03/deleteddomains/", time: "3 days ago"}, 
	{title : "Welcome to the World of Regulatory Hackers", site: "1776dc.co", href: "http://1776dc.com/news/2014/10/03/welcome-to-the-world-of-regulatory-hackers/", time: "2 days ago"}, 
	{title : "Sthttpd: Tiny and fast http server with a mature codebase", site: "github.co", href: "https://github.com/rmdir/sthttpd", time: "3 days ago"}, 
	{title : "Two birds and a liar’s game", site: "thatgeoguy.c", href: "https://thatgeoguy.ca/blog/2014/10/04/two-birds-and-a-liars-game/", time: "3 days ago"}, 
	{title : "Why the U.S. Military Is into Bee Brain Surgery", site: "nautil.u", href: "http://nautil.us/issue/11/light/why-the-us-military-is-into-bee-brain-surgery", time: "2 days ago"}, 
	{title : "Non-weak DSA key? oxymoronic, perhaps (2010)", site: "meyering.ne", href: "http://meyering.net/nuke-your-DSA-keys/", time: "2 days ago"}, 
	{title : "Daya Bay places new limit on sterile neutrinos", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/daya-bay-places-new-limit-on-sterile-neutrinos", time: "2 days ago"}, 
	{title : "Hiker Discovers an Abandoned Town Inside Tennessee's Great Smoky Mountains", site: "huffingtonpost.co", href: "http://www.huffingtonpost.com/roadtrippers/hiker-discovers-an-abando_b_5927164.html", time: "2 days ago"}, 
	{title : "Reddit, Redditors and Self-Promotion", site: "youtube.co", href: "https://www.youtube.com/watch?v=uOtuEDgYTwI", time: "2 days ago"}, 
	{title : "A Virologist Takes You Inside the Ebola Protective Suit", site: "npr.or", href: "http://www.npr.org/blogs/goatsandsoda/2014/10/04/352804648/a-virologist-takes-you-inside-the-ebola-protective-suit", time: "2 days ago"}, 
]