news16 = [
	{title : "Saeed Malekpour, programmer and political prisoner in Iran", site: "github.co", href: "https://github.com/saeedmalekpour", time: "3 days ago"}, 
	{title : "Shell Shock Exploitation Vectors", site: "dfranke.u", href: "https://www.dfranke.us/posts/2014-09-27-shell-shock-exploitation-vectors.html", time: "10 days ago"}, 
	{title : "Major Update to Elasticsearch Kibana (Kibana 4)", site: "elasticsearch.or", href: "http://www.elasticsearch.org/blog/kibana-4-beta-1-released/", time: "1 day ago"}, 
	{title : "Facebook plots first steps into healthcare", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/03/us-facebook-health-idUSKCN0HS09720141003", time: "4 days ago"}, 
	{title : "Windows 95 on Android Smartwatch", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6910791/least-useful-hack-ever-puts-windows-95-on-your-smartwatch", time: "2 days ago"}, 
	{title : "Isomorphic JavaScript", site: "isomorphic.ne", href: "http://isomorphic.net/", time: "1 day ago"}, 
	{title : "SweetAlert – a beautiful replacement for JavaScript's alert()", site: "tristanedwards.m", href: "http://tristanedwards.me/sweetalert", time: "6 days ago"}, 
	{title : "Learning much JavaScript from one line of code", site: "arqex.co", href: "http://arqex.com/939/learning-much-javascript-one-line-code", time: "1 day ago"}, 
	{title : "Following Sony, Samsung has stopped sales of its laptops in Europe", site: "pcadvisor.co.u", href: "http://www.pcadvisor.co.uk/news/laptop/3573470/samsung-exits-laptop-market-including-chromebooks/", time: "13 days ago"}, 
	{title : "Show HN: Furtive – A forward-thinking, CSS micro-framework", site: "furtive.c", href: "http://furtive.co/", time: "7 days ago"}, 
	{title : "The source of bad writing: curse of knowledge", site: "wsj.co", href: "http://online.wsj.com/articles/the-cause-of-bad-writing-1411660188", time: "12 days ago"}, 
	{title : "For developers: These shirts make you look better than your code – ShirtJS", site: "shirtjs.co", href: "http://shirtjs.com/", time: "2 days ago"}, 
	{title : "SwiftOnSecurity: A story about Jessica", site: "swiftonsecurity.tumblr.co", href: "http://swiftonsecurity.tumblr.com/post/98675308034/a-story-about-jessica", time: "7 days ago"}, 
	{title : "Blockchain Is Latest Bitcoin Startup to Lure Big Investment", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/06/blockchain-is-latest-bitcoin-start-up-to-lure-big-investment", time: "1 day ago"}, 
	{title : "An Arts Major codes a website, becomes a CEO", site: "hackerrank.co", href: "http://blog.hackerrank.com/arts-major-codes-becomes-ceo/", time: "6 days ago"}, 
	{title : "Getting Started with tmux", site: "packtpub.co", href: "https://www.packtpub.com/application-development/getting-started-tmux", time: "12 days ago"}, 
	{title : "Java is Cool", site: "javais.coo", href: "http://www.javais.cool/", time: "22 days ago"}, 
	{title : "Code is not Literature", site: "gigamonkeys.co", href: "http://www.gigamonkeys.com/code-reading/", time: "260 days ago"}, 
	{title : "DEC64: Decimal Floating Point", site: "dec64.co", href: "http://dec64.com/", time: "213 days ago"}, 
	{title : "Modern art was CIA 'weapon'", site: "independent.co.u", href: "http://www.independent.co.uk/news/world/modern-art-was-cia-weapon-1578808.html", time: "119 days ago"}, 
	{title : "Bug reporting  for the internet", site: "webcompat.co", href: "http://webcompat.com/", time: "119 days ago"}, 
	{title : "Y Combinator Company List", site: "yclist.co", href: "http://yclist.com/", time: "158 days ago"}, 
	{title : "Udacity's Sebastian Thrun, Godfather Of Free Online Education, Changes Course ", site: "fastcompany.co", href: "http://www.fastcompany.com/3021473/udacity-sebastian-thrun-uphill-climb", time: "271 days ago"}, 
	{title : "Paris syndrome", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Paris_syndrome", time: "217 days ago"}, 
	{title : "Preserving technical knowledge", site: "thomasleecopeland.co", href: "http://thomasleecopeland.com/2014/10/01/preserving-technical-knowledge.html", time: "1 day ago"}, 
	{title : "Magnetic items in an MRI machine [video]", site: "iflscience.co", href: "http://www.iflscience.com/health-and-medicine/how-dangerous-are-magnetic-items-near-mri-machine", time: "1 day ago"}, 
]