news27 = [
	{title : "iPhone 6 prototype turns up on eBay", site: "ebay.co", href: "http://www.ebay.com/itm/Brand-New-Rare-Apple-iPhone-6-Prototype-64gb-/171483815097?", time: "1 day ago"}, 
	{title : "Why women leave tech: It's the culture", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture", time: "3 days ago"}, 
	{title : "TXR: A Programming Language for Convenient Data Munging", site: "nongnu.or", href: "http://www.nongnu.org/txr", time: "3 days ago"}, 
	{title : "We Got Accepted into Techstars and Turned Them Down", site: "talkroute.co", href: "http://talkroute.com/got-accepted-into-techstars-turned-it-down/", time: "5 days ago"}, 
	{title : "Why is 0x00400000 the default base address for an executable?", site: "msdn.co", href: "http://blogs.msdn.com/b/oldnewthing/archive/2014/10/03/10562176.aspx", time: "4 days ago"}, 
	{title : "'God View': Uber Allegedly Stalked Users for Party-Goers' Viewing Pleasure", site: "forbes.co", href: "http://www.forbes.com/sites/kashmirhill/2014/10/03/god-view-uber-allegedly-stalked-users-for-party-goers-viewing-pleasure/", time: "2 days ago"}, 
	{title : "Why Coconuts Could Be the Hydrogen Storage Material of the Future", site: "technologyreview.co", href: "http://www.technologyreview.com/view/531416/why-coconuts-could-be-the-hydrogen-storage-material-of-the-future/", time: "4 days ago"}, 
	{title : "How the world’s health organizations failed to stop the Ebola disaster", site: "washingtonpost.co", href: "http://www.washingtonpost.com/sf/national/2014/10/04/how-ebola-sped-out-of-control/", time: "3 days ago"}, 
	{title : "The history of our world in 18 minutes", site: "ted.co", href: "https://www.ted.com/talks/david_christian_big_history", time: "2 days ago"}, 
	{title : "Ello: Be ready to say goodbye", site: "zdnet.co", href: "http://www.zdnet.com/ello-be-ready-to-say-goodbye-7000034333/", time: "2 days ago"}, 
	{title : "Pangrams on the web", site: "farside.org.u", href: "https://www.farside.org.uk/201410/pangrams_on_the_web", time: "4 days ago"}, 
	{title : "Tobacco plant may be key to Ebola drugs", site: "cnn.co", href: "http://www.cnn.com/2014/10/03/health/ebola-tobacco-plant/", time: "4 days ago"}, 
	{title : "NgMario", site: "blnight.github.i", href: "http://blnight.github.io/ngMario/#/game", time: "4 days ago"}, 
	{title : "To Find Meteorites, Listen to the Legends of Australian Aborigines", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/science-nature/find-meteorites-listen-legends-australian-aborigines-180952941/", time: "2 days ago"}, 
	{title : "Granny Smith apples promote growth of friendly bacteria in the colon", site: "wsu.ed", href: "https://news.wsu.edu/2014/09/29/an-apple-a-day-could-keep-obesity-away/#.VCqA_GeSz94", time: "3 days ago"}, 
	{title : "Common Parts Library", site: "octopart.co", href: "http://octopart.com/common-parts-library?a=1", time: "8 days ago"}, 
	{title : "Show HN: Hackers Job Apply", site: "github.co", href: "https://github.com/lukasz-madon/hackers-job-apply", time: "3 days ago"}, 
	{title : "C++11/14 compiler and library shootout", site: "cpprocks.co", href: "http://cpprocks.com/c1114-compiler-and-library-shootout/", time: "5 days ago"}, 
	{title : "MiniKanren – An embedded DSL for logic programming", site: "minikanren.or", href: "http://minikanren.org/", time: "6 days ago"}, 
	{title : "A Fresh Look at Rust", site: "pocoo.or", href: "http://lucumr.pocoo.org/2014/10/1/a-fresh-look-at-rust/", time: "7 days ago"}, 
	{title : "Microsoft makes more money from Samsung than from Skype, Windows Phone, and Xbox", site: "qz.co", href: "http://qz.com/276242/microsoft-makes-more-money-from-samsung-than-from-skype-windows-phone-and-xbox-combined/", time: "2 days ago"}, 
	{title : "Eleven awesome things you can do with csvkit", site: "opennews.or", href: "https://source.opennews.org/en-US/articles/eleven-awesome-things-you-can-do-csvkit/", time: "2 days ago"}, 
	{title : "Fraud possible in Brazil's e-voting system", site: "zdnet.co", href: "http://www.zdnet.com/fraud-possible-in-brazils-e-voting-system-7000034341/", time: "3 days ago"}, 
	{title : "The Downtown Project Suicides", site: "recode.ne", href: "http://recode.net/2014/10/01/the-downtown-project-suicides-can-the-pursuit-of-happiness-kill-you/", time: "6 days ago"}, 
	{title : "Issue #3 – Better Late Than Never", site: "neovim.or", href: "http://neovim.org/news/2014/sept/", time: "28 days ago"}, 
	{title : "Writing a simple operating system from scratch (2010) [pdf]", site: "bham.ac.u", href: "http://www.cs.bham.ac.uk/~exr/lectures/opsys/10_11/lectures/os-dev.pdf", time: "9 days ago"}, 
	{title : "The Ebola Patient Was Sent Home Because of Bad Software", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/10/the-ebola-patient-was-sent-home-because-of-an-electronic-health-record-problem/381087/", time: "3 days ago"}, 
]