news3 = [
	{title : "AIs are now re-writing history", site: "robertelliottsmith.co", href: "http://www.robertelliottsmith.com/?p=530", time: "12 hours ago"}, 
	{title : "A Week Drinking the Black Blood of the Earth, the Gnarliest Coffee on the Market", site: "vice.co", href: "http://motherboard.vice.com/read/a-week-drinking-the-black-blood-of-the-earth-the-gnarliest-coffee-on-the-market", time: "47 minutes ago"}, 
	{title : "Making the HTTPd run 20% faster with qrintf-gcc; a sprintf-optimizing compiler", site: "kazuhooku.co", href: "http://blog.kazuhooku.com/2014/10/announcing-qrintf-and-qrintf-gcc.html", time: "7 hours ago"}, 
	{title : "Docker Acquires Koality in Engineering Talent Grab", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/docker-acquires-koality-in-engineering-talent-grab/", time: "14 hours ago"}, 
	{title : "Flipkart, Amazon of India, has sales of $100M in one day", site: "livemint.co", href: "http://www.livemint.com/Industry/TM8tDvrv3OfeYjeXkEPXZI/Flipkart-hits-100-million-sales-target-in-10-hours.html", time: "1 day ago"}, 
	{title : "LambdaNative – A cross-platform development environment written in Scheme", site: "github.co", href: "https://github.com/part-cw/lambdanative/wiki", time: "1 day ago"}, 
	{title : "The Empire of Edge", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/13/empire-edge", time: "1 day ago"}, 
	{title : "Show HN: Team – Coroutines and async semantics for C++", site: "s4y.u", href: "http://team.s4y.us", time: "14 hours ago"}, 
	{title : "Live Coding in VR with Oculus Rift, Firefox WebVR, JavaScript, Three.js [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=db-7J5OaSag", time: "2 days ago"}, 
	{title : "Robotic Surgery Brings Higher Costs, More Complications, Study Shows", site: "wsj.co", href: "http://m.wsj.com/articles/robotic-surgery-brings-higher-costs-more-complications-study-shows-1412715786", time: "4 hours ago"}, 
	{title : "Sublime Text Power User Book", site: "sublimetextbook.co", href: "https://sublimetextbook.com/", time: "6 hours ago"}, 
	{title : "History of Apache Storm and Lessons Learned", site: "nathanmarz.co", href: "http://nathanmarz.com/blog/history-of-apache-storm-and-lessons-learned.html", time: "1 day ago"}, 
	{title : "Life of an HTTP request, as seen by my toy web server", site: "tia.mat.b", href: "http://tia.mat.br/blog/html/2014/10/06/life_of_a_http_request.html", time: "1 day ago"}, 
	{title : "There Is No Maker Movement in China", site: "ello.c", href: "https://ello.co/cshirky/post/FQKBh4QMjfaqBM1C4XYnjw", time: "1 day ago"}, 
	{title : "Steve Ciarcia Buys Back Circuit Cellar Ink Magazine", site: "avrfreaks.ne", href: "http://www.avrfreaks.net/forum/steve-ciarcia-buys-back-circuit-cellar-magazine", time: "5 hours ago"}, 
	{title : "Blue Chip – Shuji Nakamura beat the titans to blue LEDs and laser (2000)", site: "scientificamerican.co", href: "http://www.scientificamerican.com/article/blue-chip-2000-07-05/", time: "13 hours ago"}, 
	{title : "Reston's Ebola Hot Zone ─ 20 Years Later (2010)", site: "ispub.co", href: "http://ispub.com/IJPRM/2/1/12768", time: "13 hours ago"}, 
	{title : "A neighborhood garbageman explains modern Egypt", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/13/tales-trash", time: "15 hours ago"}, 
	{title : "Overstock.com Assembles Coders to Create a Bitcoin-Like Stock Market", site: "wired.co", href: "http://www.wired.com/2014/10/overstock-com-assembles-coders-build-bitcoin-like-stock-market/", time: "1 day ago"}, 
	{title : "Samsung Electronics forecasts 60% fall in quarterly profit", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/business-29516806", time: "1 day ago"}, 
	{title : "Polanyi’s Paradox and the Shape of Employment Growth", site: "mit.ed", href: "http://economics.mit.edu/files/9835", time: "13 hours ago"}, 
	{title : "Brain makes its own version of Valium, scientists discover (2013)", site: "stanford.ed", href: "http://med.stanford.edu/news/all-news/2013/05/brain-makes-its-own-version-of-valium-scientists-discover.html", time: "7 hours ago"}, 
	{title : "State of the Lua Ecosystem (2013)", site: "speakerdeck.co", href: "https://speakerdeck.com/catwell/state-of-the-lua-ecosystem", time: "1 day ago"}, 
	{title : "Do-Not-Track and the Economics of Third-Party Advertising", site: "ssrn.co", href: "http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2505643", time: "5 hours ago"}, 
	{title : "Show HN: Workboard – Team goal sharing and achievement", site: "workboard.co", href: "http://www.workboard.com", time: "5 hours ago"}, 
	{title : "Turing's bombe pips Concorde in mechanical engineers' poll", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/uk-england-beds-bucks-herts-29512623", time: "18 hours ago"}, 
	{title : "Celebrity-Endorsed Startups That Bombed", site: "techcrunch.co", href: "http://techcrunch.com/gallery/7-celebrity-endorsed-startups-that-totally-bombed/", time: "6 hours ago"}, 
	{title : "Tyupkin: Manipulating ATM Machines with Malware", site: "securelist.co", href: "http://securelist.com/blog/research/66988/tyupkin-manipulating-atm-machines-with-malware/", time: "13 hours ago"}, 
	{title : "Unfinished game – learn by practice", site: "github.co", href: "https://github.com/rezoner/unfinished-asteroids", time: "1 day ago"}, 
]