news9 = [
	{title : "In the medical response to Ebola, Cuba is punching above its weight", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/worldviews/wp/2014/10/04/in-the-medical-response-to-ebola-cuba-is-punching-far-above-its-weight/", time: "1 day ago"}, 
	{title : "Shdr – Online GLSL shader editor and validator with live preview", site: "bkcore.co", href: "http://bkcore.com/blog/3d/shdr-online-glsl-shader-editor-viewer-validator.html", time: "1 day ago"}, 
	{title : "Benchmarking Unity performance in WebGL", site: "unity3d.co", href: "http://blogs.unity3d.com/2014/10/07/benchmarking-unity-performance-in-webgl/", time: "13 hours ago"}, 
	{title : "IMF says economic growth may never return to pre-crisis levels", site: "theguardian.co", href: "http://www.theguardian.com/business/2014/oct/07/imf-economic-growth-forecasts-downgraded-crisis", time: "12 hours ago"}, 
	{title : "2 Japanese and 1 American Share Nobel Prize in Physics for Work on LED Lights", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/08/science/isamu-akasaki-hiroshi-amano-and-shuji-nakamura-awarded-the-nobel-prize-in-physics.html", time: "15 hours ago"}, 
	{title : "Scientists discover cancer-fighting berry on tree that grows in Queensland", site: "abc.net.a", href: "http://www.abc.net.au/news/2014-10-07/queensland-scientists-discover-cancer-fighting-berry/5796106/", time: "11 hours ago"}, 
	{title : "Mailgun forwarding can result in your domain being treated as spam", site: "rajivm.co", href: "https://blog.rajivm.com/mailgun-forwarding-spam.html", time: "1 day ago"}, 
	{title : "Expressjs update: fixed issues, Jade to Markdown and what's next", site: "strongloop.co", href: "http://strongloop.com/strongblog/express-update-doc-improvements-plus-markdown-powered-community-content/", time: "12 hours ago"}, 
	{title : "Show HN: Exist – understand your life through data", site: "exist.i", href: "https://exist.io/", time: "1 day ago"}, 
	{title : "Bitcoin: The Tech Based Solution to Oppressive Government", site: "coinprices.i", href: "https://www.coinprices.io/articles/analysis/the-tech-based-solution-to-oppressive-government", time: "15 hours ago"}, 
	{title : "First Teleportation of Multiple Quantum Properties of a Single Photon", site: "medium.co", href: "https://medium.com/the-physics-arxiv-blog/first-teleportation-of-multiple-quantum-properties-of-a-single-photon-7c1e61598565", time: "12 hours ago"}, 
	{title : "Why Ebola Is Amazon.com, Not Instagram", site: "thinkhardly.co", href: "http://www.thinkhardly.com/think-hardly/ebola-for-entrepreneurs", time: "13 hours ago"}, 
	{title : "Stamplay: IFTTT for developers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/06/stamplay-is-ifttt-for-back-end-development/", time: "1 day ago"}, 
	{title : "The 2014 Nobel Prize in Physiology or Medicine", site: "nobelprize.or", href: "http://www.nobelprize.org/nobel_prizes/medicine/laureates/2014/press.html", time: "1 day ago"}, 
	{title : "FinFisher Malware Analysis – Part 2", site: "codeandsec.co", href: "https://www.codeandsec.com/FinFisher-Malware-Analysis-Part-2", time: "1 day ago"}, 
	{title : "Show HN: Clojure in the Open – simple tasks from open-source projects", site: "longstorm.or", href: "http://www.longstorm.org/weekly/cito/1/", time: "1 day ago"}, 
	{title : "Here’s Why Founders Should Care about Happiness", site: "firstround.co", href: "http://firstround.com/article/Heres-Why-Founders-Should-Care-about-Happiness", time: "12 hours ago"}, 
	{title : "Student makes changing classes now clear as a bell", site: "whig.co", href: "http://www.whig.com/story/26692842/e-husar-qjhs-student-makes-changing-classes-now-clear-as-a-bell", time: "1 day ago"}, 
	{title : "Show HN: GetMetrics – Metrics and Notifications for Stripe", site: "getmetrics.i", href: "https://getmetrics.io", time: "1 day ago"}, 
	{title : "Scientists discover cancer-fighting berry in Far North Queensland", site: "abc.net.a", href: "http://www.abc.net.au/news/2014-10-07/queensland-scientists-discover-cancer-fighting-berry/5796106", time: "15 hours ago"}, 
	{title : "Microsoft's Elop was no Trojan horse, just a terrible boss", site: "yle.f", href: "http://yle.fi/uutiset/new_finnish_book_microsofts_elop_was_no_trojan_horse_just_a_terrible_boss/7515214", time: "13 hours ago"}, 
	{title : "US says it can hack into foreign-based servers without warrants", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/us-says-it-can-hack-into-foreign-based-servers-without-warrants/", time: "13 hours ago"}, 
	{title : "New cracks in Hunterston reactor", site: "bbc.co", href: "http://bbc.com/news/science-environment-29481481", time: "21 hours ago"}, 
	{title : "'A Terrible Slaughter Is Coming' – The Atlantic", site: "theatlantic.co", href: "http://www.theatlantic.com/international/archive/2014/10/a-terrible-slaughter-is-coming/381157/", time: "15 hours ago"}, 
	{title : "The Bacon Boom Was Not an Accident", site: "businessweek.co", href: "http://www.businessweek.com/articles/2014-10-06/bacon-why-americas-favorite-food-mania-happened?google_editors_picks=true", time: "1 day ago"}, 
	{title : "A Toast Story", site: "psmag.co", href: "http://www.psmag.com/navigation/health-and-behavior/toast-story-latest-artisanal-food-craze-72676/", time: "1 day ago"}, 
	{title : "Gaming on Linux Shuts Down, Plagurism and Hate to Blame", site: "thepowerbase.co", href: "http://www.thepowerbase.com/2014/10/gaming-linux-shuts-plagurism-hate-blame/", time: "15 hours ago"}, 
	{title : "Marijuana and Your Health: What 20 Years of Research Reveals", site: "yahoo.co", href: "http://news.yahoo.com/marijuana-health-20-years-research-reveals-102605139.html", time: "14 hours ago"}, 
	{title : "What brings Y Combinator to Europe? We caught up with Kirsty Nathoo to find out", site: "tech.e", href: "http://tech.eu/features/2821/y-combinator-europe-kirsty-nathoo-video/", time: "15 hours ago"}, 
]