news6 = [
	{title : "The Most Ambitious Environmental Lawsuit Ever", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/02/magazine/mag-oil-lawsuit.html", time: "2 days ago"}, 
	{title : "Testing a $35 Firefox OS phone–how bad could it be?", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/testing-a-35-firefox-os-phone-how-bad-could-it-be/", time: "1 day ago"}, 
	{title : "What’s wrong with Angular.js", site: "medium.co", href: "https://medium.com/este-js-framework/whats-wrong-with-angular-js-97b0a787f903", time: "17 hours ago"}, 
	{title : "Startups Spend with Abandon, Flush with Capital", site: "wsj.co", href: "http://online.wsj.com/articles/startups-spend-with-abandon-flush-with-capital-1412549853", time: "2 days ago"}, 
	{title : "Shen Under BSD", site: "shenlanguage.or", href: "http://www.shenlanguage.org/shenbsd.htm", time: "2 days ago"}, 
	{title : "The Quality, Popularity, and Negativity of 5.6M Hacker News Comments", site: "minimaxir.co", href: "http://minimaxir.com/2014/10/hn-comments-about-comments/", time: "1 day ago"}, 
	{title : "“How to Start a Startup” Audio Files", site: "github.co", href: "https://github.com/NathanEpstein/How_To_Start_A_Startup.git", time: "4 days ago"}, 
	{title : "How to Start a Startup: Fall 2014", site: "samaltman.co", href: "http://startupclass.samaltman.com/", time: "21 days ago"}, 
	{title : "Apple will face $350M trial over iPod DRM", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/apple-will-face-350m-trial-over-ipod-drm/", time: "4 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://www.paulgraham.com/before.html", time: "5 days ago"}, 
	{title : "Snapchat Effect: How LA Startups Are Snatching Silicon Valley's Tech Talent", site: "fastcompany.co", href: "http://www.fastcompany.com/3036552/then-and-now/the-snapchat-effect-how-los-angeles-startups-are-snatching-silicon-valley-talen", time: "4 days ago"}, 
	{title : "Exclusive: Yahoo India Is Laying Off Everybody in India. Everybody", site: "nextbigwhat.co", href: "http://www.nextbigwhat.com/yahoo-india-layoff-297/", time: "17 hours ago"}, 
	{title : "Introducing Carrot", site: "introducingcarrot.co", href: "http://www.introducingcarrot.com/", time: "16 hours ago"}, 
	{title : "Spurious Correlations", site: "tylervigen.co", href: "http://www.tylervigen.com/", time: "149 days ago"}, 
	{title : "The Contrarians on Stress: It Can Be Good for You", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/your-money/the-contrarians-on-stress-it-can-be-good-for-you-.html?smid=fb-nytimes&smtyp=cur&bicmp=AD&bicmlukp=WT.mc_id&bicmst=1409232722000&bicmet=1419773522000&_r=0", time: "1 day ago"}, 
	{title : "Adobe Is Spying on Users, Collecting Data on Their EBook Libraries", site: "the-digital-reader.co", href: "http://the-digital-reader.com/2014/10/06/adobe-spying-users-collecting-data-ebook-libraries/#.VDPfmaZXfCQ", time: "16 hours ago"}, 
	{title : "iOS 8 Adoption Stalls at 47% of Users After Three Weeks", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/ios-8-adoption-stalls-at-47-of-users-after-three-weeks/", time: "14 hours ago"}, 
	{title : "A Complete Understanding Is No Longer Possible", site: "dadgum.co", href: "http://prog21.dadgum.com/129.html", time: "16 hours ago"}, 
	{title : "Anita Sarkeesian, Feminist Frequency – XOXO Festival (2014)", site: "youtube.co", href: "https://www.youtube.com/watch?v=ah8mhDW6Shs", time: "8 hours ago"}, 
	{title : "Apologies from Flipkart for #BigBillionDay sale mess", site: "flipkart.co", href: "http://blog.flipkart.com/apologies-from-flipkart/", time: "13 hours ago"}, 
	{title : "Vim blowfish encryption", site: "dgl.c", href: "https://dgl.cx/2014/10/vim-blowfish", time: "2 days ago"}, 
	{title : "Adobe is spying on users and sending the data to its servers – in clear text", site: "the-digital-reader.co", href: "http://the-digital-reader.com/2014/10/06/adobe-spying-users-collecting-data-ebook-libraries/", time: "1 day ago"}, 
	{title : "Show HN: Ng-eocities – A library of retro Angular directives", site: "github.co", href: "https://github.com/KatzInHatz/ng-eocities", time: "15 hours ago"}, 
	{title : "Yahoo Close to Investing in Snapchat at $10B Value", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-03/yahoo-said-close-to-investing-in-snapchat-at-10b-value.html", time: "14 hours ago"}, 
	{title : "Announcing TypeScript 1.1 CTP", site: "msdn.co", href: "http://blogs.msdn.com/b/typescript/archive/2014/10/06/announcing-typescript-1-1-ctp.aspx", time: "1 day ago"}, 
	{title : "Not a Manifesto", site: "antipope.or", href: "http://www.antipope.org/charlie/blog-static/2014/10/not-a-manifesto.html", time: "13 hours ago"}, 
	{title : "Being Mindful Can Help Guide a Decision", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/29/your-money/being-mindful-can-help-guide-a-decision.html?contentCollection=your-money&action=click&module=NextInCollection&region=Footer&pgtype=article&_r=0", time: "22 hours ago"}, 
]