news11 = [
	{title : "Starflight: Near-Term Prospects", site: "centauri-dreams.or", href: "http://www.centauri-dreams.org/?p=31676", time: "1 day ago"}, 
	{title : "Small solar powered printer that doesn't require the use of ink cartridges", site: "tranqila.co", href: "http://www.tranqila.com/2014/10/amazing-tanning-printer.html", time: "21 hours ago"}, 
	{title : "A transparency model for all Governments", site: "attendance.gov.i", href: "http://attendance.gov.in/", time: "23 hours ago"}, 
	{title : "Hint of life after death in scientific study", site: "telegraph.co.u", href: "http://www.telegraph.co.uk/science/science-news/11144442/First-hint-of-life-after-death-in-biggest-ever-scientific-study.html", time: "16 hours ago"}, 
	{title : "Rolls-Royce RB211", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Rolls-Royce_RB211", time: "18 hours ago"}, 
	{title : "Venture capital and the great big Silicon Valley asshole game", site: "pando.co", href: "http://pando.com/2014/10/06/venture-capital-and-the-great-big-silicon-valley-asshole-game/", time: "1 day ago"}, 
	{title : "Does It Help to Know History?", site: "newyorker.co", href: "http://www.newyorker.com/news/daily-comment/help-know-history", time: "1 day ago"}, 
	{title : "It’s time to be honest: Netflix is parasitic", site: "theglobeandmail.co", href: "http://www.theglobeandmail.com/arts/television/its-time-to-be-honest-netflix-is-parasitic/article20918687/", time: "1 day ago"}, 
	{title : "Reddit CEO Calls Out Former Reddit Employee on Reddit", site: "reddit.co", href: "https://np.reddit.com/r/IAmA/comments/2iea97/i_am_a_former_reddit_employee_ama/cl1ygat?context=3", time: "1 day ago"}, 
	{title : "Tech World Vexed by Slow Progress on Batteries", site: "wsj.co", href: "http://online.wsj.com/news/article_email/tech-world-vexed-by-slow-progress-on-batteries-1412552377-lMyQjAxMTE0MjAzNjUwNjY3Wj", time: "1 day ago"}, 
	{title : "Go 1.4 now supports Android", site: "code.google.co", href: "https://code.google.com/p/go/issues/detail?id=8020", time: "1 day ago"}, 
	{title : "How does a computer chip work?", site: "quora.co", href: "http://www.quora.com/Computer-Science/How-does-a-computer-chip-work/answer/Subhasis-Das?share=1", time: "2 days ago"}, 
	{title : "Automated Debian Packages with Bricklayer and Docker", site: "orelhas.i", href: "http://orelhas.in/bricklayer-docker.html", time: "14 hours ago"}, 
	{title : "Second Seed Rounds: How They Impact a Startup's Ability to Raise a Series A", site: "tomtunguz.co", href: "http://tomtunguz.com/second-seeds", time: "1 day ago"}, 
	{title : "Monit Team Widthdraws Inspeqtor Takedown", site: "github.co", href: "https://github.com/github/dmca/blob/master/2014-10-06-tildeslash-retraction.md", time: "1 day ago"}, 
	{title : "Microsoft’s ‘RoomAlive’ transforms any room into a giant Xbox game", site: "theverge.co", href: "http://www.theverge.com/2014/10/5/6912979/microsoft-roomalive-research-projector-system", time: "2 days ago"}, 
	{title : "Crypto Museum", site: "cryptomuseum.co", href: "http://www.cryptomuseum.com/index.htm", time: "1 day ago"}, 
	{title : "Hundreds of Devices Hidden Inside New York City Phone Booths", site: "buzzfeed.co", href: "http://www.buzzfeed.com/josephbernstein/exclusive-hundreds-of-devices-hidden-inside-new-york-city-ph", time: "1 day ago"}, 
	{title : "Tango: Distributed Data Structures Over a Shared Log", site: "muratbuffalo.blogspot.co", href: "http://muratbuffalo.blogspot.com/2014/09/paper-summary-tango-distributed-data.html", time: "1 day ago"}, 
	{title : "Microsoft-backed F# functional language surges in popularity", site: "infoworld.co", href: "http://www.infoworld.com/article/2610183/microsoft-net/article.html?share", time: "17 hours ago"}, 
	{title : "Show HN: Tempmail.de – Temporary, disposable, anonymous email address", site: "tempmail.d", href: "http://tempmail.de", time: "1 day ago"}, 
	{title : "Engineering management lessons", site: "defmacro.or", href: "http://www.defmacro.org/2014/10/03/engman.html", time: "4 days ago"}, 
	{title : "Real problems people want solved", site: "reddit.co", href: "http://www.reddit.com/r/SomebodyMakeThis/", time: "1 day ago"}, 
	{title : "New tool helps debug Java exceptions faster", site: "excepterror.co", href: "http://www.excepterror.com", time: "3 days ago"}, 
	{title : "Cheap Beer and the Psychology of PlayStation Now Pricing", site: "psychologyofgames.co", href: "http://www.psychologyofgames.com/2014/08/cheep-beer-and-the-psychology-of-playstation-now-pricing/", time: "2 days ago"}, 
	{title : "How mozzarella became the perfect pizza cheese", site: "bbc.co", href: "http://www.bbc.com/future/story/20141006-the-secrets-of-perfect-pizza", time: "1 day ago"}, 
	{title : "Petitioning Google, Inc  Stop Killing Small Business", site: "change.or", href: "https://www.change.org/p/google-stop-killing-small-business", time: "22 hours ago"}, 
]