news14 = [
	{title : "iPhone Encryption and the Return of the Crypto Wars", site: "schneier.co", href: "https://www.schneier.com/blog/archives/2014/10/iphone_encrypti_1.html", time: "1 day ago"}, 
	{title : "JSON Web Tokens", site: "jwt.i", href: "http://jwt.io/?", time: "30 days ago"}, 
	{title : "We should all just decide on JS and solve the interesting problems instead", site: "peterevjan.co", href: "http://peterevjan.com/posts/we-should-all-just-decide-on-javascript-and-solve-the-interesting-problems-instead", time: "1 day ago"}, 
	{title : "Dubai police to use Google Glass for facial recognition", site: "networkworld.co", href: "http://www.networkworld.com/article/2690791/opensource-subnet/dubai-police-to-use-google-glass-for-facial-recognition.html", time: "1 day ago"}, 
	{title : "Why women leave tech: It's the culture, not because 'math is hard'", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture/", time: "4 days ago"}, 
	{title : "Elon Musk argues that putting a million people on Mars ensures humanity's future", site: "aeon.c", href: "http://aeon.co/magazine/technology/the-elon-musk-interview-on-mars/", time: "7 days ago"}, 
	{title : "I want problems, not solutions", site: "medium.co", href: "https://medium.com/@MrJamesFisher/i-want-problems-not-solutions-284b8d5b651", time: "1 day ago"}, 
	{title : "Adaptive Path and the Death Rattle of the Web 2.0 Era", site: "wired.co", href: "http://www.wired.com/2014/10/adaptive-path-end-of-the-web-2-0-era/", time: "4 days ago"}, 
	{title : "New Class of Vulnerability in Perl Web Applications", site: "gerv.ne", href: "http://blog.gerv.net/2014/10/new-class-of-vulnerability-in-perl-web-applications/", time: "1 day ago"}, 
	{title : "Nine years later, Citibank’s fraud department is still self-defeating", site: "jcole.u", href: "http://blog.jcole.us/2014/10/06/nine-years-later-citibanks-fraud-department-is-still-self-defeating/", time: "1 day ago"}, 
	{title : "Surveillance drives South Koreans to encrypted messaging apps", site: "theverge.co", href: "http://www.theverge.com/2014/10/6/6926205/surveillance-drives-south-koreans-to-encrypted-messaging-apps", time: "1 day ago"}, 
	{title : "Haskell, Monads and Purity", site: "jelv.i", href: "http://jelv.is/blog/Haskell-Monads-and-Purity/", time: "4 days ago"}, 
	{title : "YouTube's joke of a fair-use appeal process", site: "jwz.or", href: "http://www.jwz.org/blog/2014/10/youtubes-joke-of-a-fair-use-appeal-process/", time: "1 day ago"}, 
	{title : "Teaching CS in K12 – Using easy assignments to introduce deep concepts", site: "cestlaz.github.i", href: "http://cestlaz.github.io/2014/10/05/easy-assignments.html#.VDLZUPdw474.hackernews", time: "1 day ago"}, 
	{title : "Mono 3.10.0", site: "mono-project.co", href: "http://www.mono-project.com/docs/about-mono/releases/3.10.0/", time: "1 day ago"}, 
	{title : "Roll your own autocomplete solution using Tries (2012)", site: "vivekn.co", href: "http://vivekn.com/blog/2012/02/25/roll-your-own-autocomplete-solution-using-tries/", time: "1 day ago"}, 
	{title : "Open Explorer: Follow expeditions around the world", site: "openexplorer.co", href: "https://openexplorer.com", time: "1 day ago"}, 
	{title : "What you don't know can hurt you", site: "coverclock.blogspot.co", href: "http://coverclock.blogspot.com/2014/09/what-you-dont-know-can-hurt-you.html", time: "1 day ago"}, 
	{title : "YouTube Shut Down One of the Best Hacking Videotutorial Channel", site: "plus.google.co", href: "https://plus.google.com/u/1/+ChrisHaralson/posts/U5mq8THHhgP", time: "1 day ago"}, 
	{title : "Nurse in Spain tests positive for Ebola in first infection outside west Africa", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/06/nurse-spain-tests-positive-ebola", time: "1 day ago"}, 
	{title : "Quantitative Analysis of Pooled Ridesharing", site: "telegraphresearch.co", href: "http://www.telegraphresearch.com/ridesharing/", time: "1 day ago"}, 
	{title : "One in three Jobs will be taken by software or robots by 2025", site: "computerworld.co", href: "http://www.computerworld.com/article/2691607/one-in-three-jobs-will-be-taken-by-software-or-robots-by-2025.html", time: "1 day ago"}, 
	{title : "Show HN: JuliusJS – Speech recognition in JavaScript", site: "github.co", href: "https://github.com/zzmp/juliusjs", time: "4 days ago"}, 
	{title : "As Many as 5K .Com’s Taken Away by Sealed Court Order by Verisign", site: "thedomains.co", href: "http://www.thedomains.com/2014/10/02/as-many-as-5k-coms-taken-away-by-sealed-court-order-by-verisign-including-some-of-mine/", time: "4 days ago"}, 
	{title : "A Walking Tour Through the Living Wreckage of Penn Station", site: "theawl.co", href: "http://www.theawl.com/2014/10/a-walking-tour-through-the-living-wreckage-of-penn-station", time: "1 day ago"}, 
	{title : "Spain is trying to get rid of Uber: drivers will face fines up to €18K", site: "novobrief.co", href: "http://novobrief.com/spain-trying-push-uber-country-drivers-will-face-fines-e18000/", time: "1 day ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd", time: "5 days ago"}, 
	{title : "The Immaturity and Arrogance of Uber", site: "medium.co", href: "https://medium.com/@petersimsie/the-immaturity-and-arrogance-of-uber-eea64bcfa5bf", time: "2 days ago"}, 
]