news29 = [
	{title : "How the Hash Works in Ruby", site: "gotealeaf.co", href: "http://www.gotealeaf.com/blog/how-the-hash-works-in-ruby/", time: "3 days ago"}, 
	{title : "Why Not Eat Octopus?", site: "newyorker.co", href: "http://www.newyorker.com/tech/elements/eating-octopus", time: "3 days ago"}, 
	{title : "Phison USB Custom Firmware and Existing Firmware Patches", site: "github.co", href: "https://github.com/adamcaudill/Psychson", time: "4 days ago"}, 
	{title : "BAP: Binary Analysis Platform", site: "cmu.ed", href: "http://bap.ece.cmu.edu/", time: "6 days ago"}, 
	{title : "The Ambiguities of Prison Gangs", site: "theatlantic.co", href: "http://www.theatlantic.com/national/archive/2014/10/gangs-and-prisons/381034/?single_page=true", time: "4 days ago"}, 
	{title : "Can Big Data Tell Us What Clinical Trials Don’t?", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/magazine/can-big-data-tell-us-what-clinical-trials-dont.html?rref=magazine&module=Ribbon&version=context&region=Header&action=click&contentCollection=Magazine&pgtype=article", time: "3 days ago"}, 
	{title : "Supporting idea convergence through pedagogical scripts and Etherpad APIs", site: "reganmian.ne", href: "http://reganmian.net/blog/2014/10/03/supporting-idea-convergence-through-pedagogical-scripts/", time: "3 days ago"}, 
	{title : "“The Peripheral” by William Gibson (Excerpt)", site: "williamgibsonbooks.co", href: "http://williamgibsonbooks.com/books/the_peripheral_excerpt.asp", time: "3 days ago"}, 
	{title : "This is Water: a commencement speech by David Foster Wallace [pdf]", site: "purdue.ed", href: "http://web.ics.purdue.edu/~drkelly/DFWKenyonAddress2005.pdf", time: "3 days ago"}, 
	{title : "Three Years on Rikers Without Trial", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/06/law-3", time: "5 days ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29465446", time: "4 days ago"}, 
	{title : "Hackers’ Attack Cracked 10 Financial Institutions in Major Assault", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/03/hackers-attack-cracked-10-banks-in-major-assault/", time: "4 days ago"}, 
	{title : "New Map Exposes Previously Unseen Details of Seafloor", site: "ucsd.ed", href: "https://scripps.ucsd.edu/news/new-map-exposes-previously-unseen-details-seafloor", time: "4 days ago"}, 
	{title : "Place SSH users in Docker jails (or as replacement for docker-bash / dockersh)", site: "github.co", href: "https://github.com/clevcode/docker-cmd", time: "4 days ago"}, 
	{title : "How the Shinkansen bullet train made Tokyo into the monster it is today", site: "theguardian.co", href: "http://www.theguardian.com/cities/2014/sep/30/-sp-shinkansen-bullet-train-tokyo-rail-japan-50-years", time: "7 days ago"}, 
	{title : "Brain Gain: the underground world of neuroenhancing drugs (2009)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2009/04/27/brain-gain?utm_source=tny&utm_campaign=generalsocial&utm_medium=facebook&mbid=social_facebook", time: "4 days ago"}, 
	{title : "NASA Eyes Crew Deep Sleep Option for Mars Mission", site: "discovery.co", href: "http://news.discovery.com/space/nasa-eyes-crew-deep-sleep-option-for-mission-to-mars-141003.htm", time: "4 days ago"}, 
	{title : "Rocket Internet Shares Fall Below Issue Price at Debut", site: "wsj.co", href: "http://online.wsj.com/articles/rocket-internet-shares-fall-below-issue-price-at-debut-1412237549", time: "5 days ago"}, 
	{title : "Celebs whose nude photos were stolen threaten Google with $100M lawsuit", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/celebs-whose-nude-photos-were-stolen-threaten-google-with-100m-lawsuit/", time: "4 days ago"}, 
	{title : "Building a Better Build: Our Transition from Ant to SBT", site: "codeascraft.co", href: "http://codeascraft.com/2014/09/30/building-a-better-build-our-transition-from-ant-to-sbt/", time: "6 days ago"}, 
	{title : "Show HN: Make your site faster", site: "eager.i", href: "https://eager.io/app/ZYBle8qUhKFJ?n", time: "5 days ago"}, 
	{title : "Many to Many Joins with Ecto and Elixir", site: "coffeesforclosures.co", href: "http://www.coffeesforclosures.com/many-to-many-joins-with-ecto-and-elixir/", time: "4 days ago"}, 
	{title : "The FBI Says How It ‘Legally’ Pinpointed Silk Road’s Server", site: "wired.co", href: "http://www.wired.com/2014/09/the-fbi-finally-says-how-it-legally-pinpointed-silk-roads-server/", time: "32 days ago"}, 
]