news25 = [
	{title : "Integer to string conversion", site: "tia.mat.b", href: "http://tia.mat.br/blog/html/2014/06/23/integer_to_string_conversion.html", time: "106 days ago"}, 
	{title : "Mysterious Mac and PC malware that jumps airgaps?", site: "arstechnica.co", href: "http://arstechnica.com/security/2013/10/meet-badbios-the-mysterious-mac-and-pc-malware-that-jumps-airgaps/", time: "341 days ago"}, 
	{title : "Startpage Search Engine: The world's most private search", site: "startpage.co", href: "https://www.startpage.com/", time: "298 days ago"}, 
	{title : "Colorsublime", site: "colorsublime.co", href: "http://colorsublime.com/", time: "367 days ago"}, 
	{title : "15 Sorting Algorithms in 6 Minutes", site: "youtube.co", href: "https://www.youtube.com/watch?v=kPRA0W1kECg", time: "312 days ago"}, 
	{title : "Jewish Nobel Laureates", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/List_of_Jewish_Nobel_laureates", time: "361 days ago"}, 
	{title : "Designing In The Open", site: "bradfrostweb.co", href: "http://bradfrostweb.com/blog/post/designing-in-the-open/", time: "379 days ago"}, 
	{title : " headache relief for programmers: regular expression generator", site: "txt2re.co", href: "http://txt2re.com", time: "911 days ago"}, 
	{title : "Education in Finland", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Education_in_Finland", time: "427 days ago"}, 
	{title : "How facebook managed growth from 30 to 200 engineers", site: "algeri-wong.co", href: "http://algeri-wong.com/yishan/engineering-management.html", time: "1479 days ago"}, 
	{title : "Hal Finney being cryopreserved now", site: "extropy.or", href: "http://lists.extropy.org/pipermail/extropy-chat/2014-August/082585.html", time: "40 days ago"}, 
	{title : "Germany’s great tuition fees U-turn", site: "timeshighereducation.co.u", href: "http://www.timeshighereducation.co.uk/features/feature-germanys-great-tuition-fees-u-turn/2011168.fullarticle", time: "6 days ago"}, 
	{title : "Machine Learning is the new Algorithms", site: "nlpers.blogspot.co", href: "http://nlpers.blogspot.com/2014/10/machine-learning-is-new-algorithms.html", time: "4 days ago"}, 
	{title : "Learning Online", site: "christinacacioppo.co", href: "http://christinacacioppo.com/blog/learning-online", time: "8 days ago"}, 
	{title : "All of IT", site: "eldelshell.co", href: "http://www.eldelshell.com/all-of-it.html", time: "2 days ago"}, 
	{title : "Linux Challenge Blackbox #1", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/linux-challenge-blackbox-1/", time: "2 days ago"}, 
	{title : "The badge of ignorance", site: "medium.co", href: "https://medium.com/@emilepetrone/the-badge-of-ignorance-185c85ac9a30", time: "2 days ago"}, 
	{title : "Let's Talk about Reddit and Self Promotion", site: "reddit.co", href: "http://www.reddit.com/r/videos/comments/2idhxn/lets_talk_about_reddit_and_selfpromotion/", time: "2 days ago"}, 
	{title : "HTTP/2 Frequently Asked Questions", site: "http2.github.i", href: "http://http2.github.io/faq/", time: "4 days ago"}, 
	{title : "Content Security Policy (CSP) for the web we have", site: "mozilla.or", href: "https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/", time: "3 days ago"}, 
	{title : "Show HN: GoldenLayout – JavaScript Layout Manager", site: "golden-layout.co", href: "https://golden-layout.com/", time: "5 days ago"}, 
	{title : "How Archerfish Hunt With Their Spit (2013)", site: "wired.co", href: "http://www.wired.com/2013/11/archerfish-physics/", time: "3 days ago"}, 
	{title : "An Australian researcher has worked out how to store 1000TB on a CD", site: "sciencealert.com.a", href: "http://www.sciencealert.com.au/news/20140309-26116.html", time: "5 days ago"}, 
	{title : "Sway: A new presentation application from Microsoft", site: "sway.co", href: "https://sway.com/", time: "6 days ago"}, 
	{title : "The Sound So Loud That It Circled the Earth Four Times", site: "nautil.u", href: "http://nautil.us/blog/the-sound-so-loud-that-it-circled-the-earth-four-times", time: "8 days ago"}, 
	{title : "Show HN: Star Wars GUI / MultiTouch UI", site: "chrisgannon.wordpress.co", href: "http://chrisgannon.wordpress.com/2014/09/24/star-wars-guimultitouch-ui-controls-again/", time: "3 days ago"}, 
	{title : "WebSharper: Make web apps in F#", site: "websharper.co", href: "http://websharper.com/", time: "4 days ago"}, 
	{title : "Stampede – Texas Advanced Computing Center", site: "utexas.ed", href: "https://www.tacc.utexas.edu/stampede/", time: "3 days ago"}, 
	{title : "A mixed bag on apps: What the NY Times learned with NYT Opinion and NYT Now", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/a-mixed-bag-on-apps-what-the-new-york-times-learned-with-nyt-opinion-and-nyt-now/", time: "3 days ago"}, 
	{title : "Contact Lost with Planes One by One as FAA Fire Spread", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/contact-lost-with-planes-one-by-one-as-faa-center-fire-spread.html", time: "5 days ago"}, 
]