news10 = [
	{title : "Government Set Up a Fake Facebook Page in This Woman’s Name", site: "buzzfeed.co", href: "http://www.buzzfeed.com/chrishamby/government-says-federal-agents-can-impersonate-woman-online?utm_term=3bgq1fs&s=mobile#20dxu96", time: "19 hours ago"}, 
	{title : "Ranges in C++: Counted Iterables and Efficiency", site: "ericniebler.co", href: "http://ericniebler.com/2014/10/06/counted-ranges-and-efficiency/", time: "1 day ago"}, 
	{title : "Docker acquires Koality", site: "gigaom.co", href: "https://gigaom.com/2014/10/07/docker-acquires-testing-centric-startup-koality-as-it-continues-to-build-out-its-paid-services/", time: "14 hours ago"}, 
	{title : "Show HN: Pod – Organize your clubs, causes, and teams", site: "joinpod.co", href: "https://www.joinpod.com/", time: "15 hours ago"}, 
	{title : "CppCon 2014: Data-Oriented Design and C++ [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=rX0ItVEVjHc", time: "14 hours ago"}, 
	{title : "Monit's DMCA takedown notice for Inspeqtor", site: "github.co", href: "https://github.com/github/dmca/blob/master/2014-10-05-tildeslash.md", time: "1 day ago"}, 
	{title : "A Fresh Take on Error Logging: Introducing Annotated Stacktraces", site: "opbeat.co", href: "https://opbeat.com/", time: "15 hours ago"}, 
	{title : "Apologies, from Flipkart", site: "github.co", href: "https://gist.github.com/anonymous/dfda56b2ab6e412ee2f4", time: "16 hours ago"}, 
	{title : "The Complete Guide to Treadmill Desk Walking While Working", site: "simpleprogrammer.co", href: "http://simpleprogrammer.com/2014/10/07/treadmill-desk-walking/", time: "14 hours ago"}, 
	{title : "We moved our company 795 miles and nobody noticed", site: "workweekabroad.co", href: "http://www.workweekabroad.com/moved-company-795-miles-nobody-noticed/", time: "16 hours ago"}, 
	{title : "Boiling Sous-Vide Eggs Using Clojure's Transducers", site: "eikeland.s", href: "http://blog.eikeland.se/2014/10/06/pid-transducer/", time: "1 day ago"}, 
	{title : "Work Practices and Challenges in Pull-Based Development [pdf]", site: "tudelft.n", href: "http://swerl.tudelft.nl/twiki/pub/Main/TechnicalReports/TUD-SERG-2014-013.pdf", time: "1 day ago"}, 
	{title : "Procedural colors for video games", site: "noctua-software.co", href: "http://blog.noctua-software.com/procedural-colors-for-game.html", time: "1 day ago"}, 
	{title : "A look at the Apple ‘Skankphone’, built before the original iPhone release", site: "thenextweb.co", href: "http://thenextweb.com/apple/2014/10/05/apple-skankphone-built-original-iphone-release/", time: "2 days ago"}, 
	{title : "Project Cybersyn and the origins of the Big Data nation", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/13/planning-machine", time: "1 day ago"}, 
	{title : "Revisiting Android disk encryption", site: "nelenkov.blogspot.co", href: "http://nelenkov.blogspot.com/2014/10/revisiting-android-disk-encryption.html", time: "1 day ago"}, 
	{title : "A Scalability Roadmap", site: "bitcoinfoundation.or", href: "https://bitcoinfoundation.org/2014/10/a-scalability-roadmap/", time: "1 day ago"}, 
	{title : "AngularJS Tutorial: A Comprehensive 10,000 Word Guide", site: "airpair.co", href: "http://www.airpair.com/angularjs?ti=#MxkrVCfYlQfeQLBy.99", time: "1 day ago"}, 
	{title : "Tesla wants to sell you a used Model S", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/06/tesla-wants-to-sell-you-a-used-model-s/", time: "1 day ago"}, 
	{title : "Help improve gcc", site: "gnu.or", href: "https://gcc.gnu.org/ml/gcc/2014-10/msg00040.html", time: "1 day ago"}, 
	{title : "PHP Framework CodeIgniter Has a New Home", site: "ellislab.co", href: "https://ellislab.com/blog/entry/your-favorite-php-framework-codeigniter-has-a-new-home", time: "1 day ago"}, 
	{title : "YouTube shuts down popular pen testing channel", site: "plus.google.co", href: "https://plus.google.com/app/basic/stream/z12ag1qzcvyjshxh104cj5y4bsnnfxmoxdk", time: "22 hours ago"}, 
	{title : "Radioactivity in Norway's reindeers hits high", site: "thelocal.n", href: "http://m.thelocal.no//20141006/radioactive-reindeer-found-in-norway", time: "1 day ago"}, 
	{title : "Neil Sloane: the man who loved only integer sequences", site: "theguardian.co", href: "http://www.theguardian.com/science/alexs-adventures-in-numberland/2014/oct/07/neil-sloane-the-man-who-loved-only-integer-sequences", time: "15 hours ago"}, 
	{title : "Portugal released a webpage to see number of deaths", site: "min-saude.p", href: "https://servicos.min-saude.pt/sico/faces/statistics.jsp", time: "21 hours ago"}, 
	{title : "Starflight: Near-Term Prospects", site: "centauri-dreams.or", href: "http://www.centauri-dreams.org/?p=31676", time: "1 day ago"}, 
	{title : "DNSSEC: An Introduction (from CloudFlare)", site: "cloudflare.co", href: "http://blog.cloudflare.com/dnssec-an-introduction/", time: "15 hours ago"}, 
	{title : "Servers for Hackers eBook", site: "serversforhackers.co", href: "https://book.serversforhackers.com/", time: "12 hours ago"}, 
	{title : "The Magic CmdLine and how I got it back", site: "ntua.g", href: "http://users.softlab.ece.ntua.gr/~ttsiod/bashheimer.html", time: "4 days ago"}, 
]