news18 = [
	{title : "NASA may get astronauts to Mars using deep sleep and intravenous drips", site: "geek.co", href: "http://www.geek.com/science/nasa-may-get-astronauts-to-mars-using-deep-sleep-and-intravenous-drips-1606052/", time: "1 day ago"}, 
	{title : "Attack code for 'unpatchable' USB flaw released", site: "bbc.co", href: "http://www.bbc.com/news/technology-29475566", time: "1 day ago"}, 
	{title : "Programming and Computer Science: an imminent divorce?", site: "txus.i", href: "http://blog.txus.io/2014/10/programming-and-computer-science-an-imminent-divorce/", time: "1 day ago"}, 
	{title : "Building an iOS8 Today widget – the good/bad/ugly", site: "medium.co", href: "https://medium.com/ios-os-x-development/learnings-from-building-a-today-view-extension-in-ios-8-710d5f481594", time: "1 day ago"}, 
	{title : "Why Ello Needs Craig Newmark(?)", site: "dentthefuture.co", href: "http://blog.dentthefuture.com/2014/why-ello-needs-craig-newmark/", time: "1 day ago"}, 
	{title : "Beautiful Chemistry", site: "beautifulchemistry.ne", href: "http://beautifulchemistry.net/", time: "5 days ago"}, 
	{title : "Stress Gives You Daughters, Sons Make You Liberal", site: "nautil.u", href: "http://nautil.us/issue/13/symmetry/stress-gives-you-daughters-sons-make-you-liberal", time: "1 day ago"}, 
	{title : "A Warning to the Tech Community on Abusive Journalists", site: "zdziarski.co", href: "http://www.zdziarski.com/blog/?p=3958", time: "1 day ago"}, 
	{title : "Make your smartwatch even less useful by installing Windows 95", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/make-your-smartwatch-even-less-useful-by-installing-windows-95/", time: "1 day ago"}, 
	{title : "Show HN: Generate interactive heatmaps from your Google Location History data", site: "theopolisme.github.i", href: "http://theopolisme.github.io/location-history-visualizer/", time: "2 days ago"}, 
	{title : "'You Have the Right to Remain Silent.' or Do You?", site: "npr.or", href: "http://www.npr.org/2014/10/05/353893046/you-have-the-right-to-remain-silent-or-do-you?utm_campaign=storyshare&utm_source=facebook.com&utm_medium=social", time: "1 day ago"}, 
	{title : "Car sharing: A cheaper alternative to owning a car in Japan", site: "japantimes.co.j", href: "http://www.japantimes.co.jp/news/2014/10/06/reference/car-sharing-cheaper-alternative-owning-car-city/", time: "1 day ago"}, 
	{title : "Apple sapphire crystal supplier GT Advanced files for bankruptcy", site: "9to5mac.co", href: "http://9to5mac.com/2014/10/06/gtat-sapphire-apple-bankrupt/", time: "1 day ago"}, 
	{title : "John Oliver Explores the Sad Reality of Civil Forfeitures – Rolling Stone", site: "rollingstone.co", href: "http://www.rollingstone.com/tv/videos/john-oliver-amplifies-the-absurdity-of-civil-forfeitures-20141006", time: "1 day ago"}, 
	{title : "Terrestriality", site: "theappendix.ne", href: "http://theappendix.net/issues/2014/4/terrestriality", time: "2 days ago"}, 
	{title : "How con artists trick your mind", site: "bbc.co", href: "http://www.bbc.com/future/story/20141003-the-mind-tricks-of-scammers", time: "3 days ago"}, 
	{title : "Latest Ebola Statistics", site: "ebolastats.inf", href: "http://ebolastats.info/", time: "1 day ago"}, 
	{title : "Linux Software Releases, September 2014", site: "linuxsoftnews.wordpress.co", href: "http://linuxsoftnews.wordpress.com/2014/09/19/linux-software-release-september-2014/", time: "1 day ago"}, 
	{title : "IRIS+", site: "3drobotics.co", href: "http://3drobotics.com/iris-plus/", time: "4 days ago"}, 
	{title : "Researchers see signature of “Majorana particles” inside superconducting iron", site: "scientificamerican.co", href: "http://www.scientificamerican.com/article/majorana-particle-matter-and-antimatter/", time: "4 days ago"}, 
	{title : "Bugzilla 0-day exposes 0-days", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/bugzilla-zero-day-exposes-zero-day-bugs/", time: "1 day ago"}, 
	{title : "Aboard Amtrak", site: "spnzr.co", href: "http://spnzr.com/aboard-amtrak", time: "4 days ago"}, 
	{title : "Ebola virus outbreak timeline", site: "abc.net.a", href: "http://www.abc.net.au/news/2014-07-31/ebola-timeline-deadliest-outbreak/5639060", time: "1 day ago"}, 
	{title : "Stop Australia's Data Retention Bill", site: "stopthespies.or", href: "https://stopthespies.org/?live", time: "2 days ago"}, 
	{title : "OpenBSD 5.6: What will be there", site: "openbsd.or", href: "http://www.openbsd.org/56.html", time: "2 days ago"}, 
	{title : "HexLogic – Logic gates in a hexagon grid", site: "anubiann00b.github.i", href: "http://anubiann00b.github.io/HexLogic/", time: "2 days ago"}, 
	{title : "Why Facebook Was So Aggressive About Migrating Users Over to Messenger", site: "fastcompany.co", href: "http://www.fastcompany.com/3036695/fast-feed/this-is-why-facebook-was-so-aggressive-about-migrating-users-over-to-messenger", time: "1 day ago"}, 
	{title : "First womb-transplant baby born", site: "bbc.co", href: "http://www.bbc.com/news/health-29485996", time: "3 days ago"}, 
]