news13 = [
	{title : "Nobel laureates call for a revolutionary shift in how humans use resources", site: "theguardian.co", href: "http://www.theguardian.com/science/2014/oct/07/nobel-laureates-call-for-a-revolutionary-shift-in-how-humans-use-resources", time: "20 hours ago"}, 
	{title : "The cookie is dead. Here’s how Facebook, Google, and Apple are tracking you now", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/06/the-cookie-is-dead-heres-how-facebook-google-and-apple-are-tracking-you-now/", time: "1 day ago"}, 
	{title : "Doctor Who Discovered Ebola in 1976 Fears “Unimaginable Tragedy”", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/04/ebola-zaire-peter-piot-outbreak?CMP=twt_gu", time: "20 hours ago"}, 
	{title : "Show HN: Pykov – a tiny Python module on finite regular Markov chains", site: "github.co", href: "https://github.com/riccardoscalco/Pykov", time: "1 day ago"}, 
	{title : "Kurt Vonnegut, the Art of Fiction No. 64 (1977)", site: "theparisreview.or", href: "http://www.theparisreview.org/interviews/3605/the-art-of-fiction-no-64-kurt-vonnegut", time: "2 days ago"}, 
	{title : "Unintentionally in YC", site: "medium.co", href: "https://medium.com/@andrewjiang/unintentionally-in-yc-9dd0ccbaeb44", time: "1 day ago"}, 
	{title : "Emotional Renovations: How your brain twists together emotion and place", site: "nautil.u", href: "http://nautil.us/issue/8/home/emotional-renovations", time: "1 day ago"}, 
	{title : "EBay Opens Fine Art Live-Auction Sites, for Second Time", site: "bits.blogs.nytimes.co", href: "http://bits.blogs.nytimes.com/2014/10/06/ebay-opens-fine-art-live-auction-sites-for-second-time/", time: "1 day ago"}, 
	{title : "Clocks Make Workers Less Creative and Less Happy", site: "theatlantic.co", href: "http://www.theatlantic.com/business/archive/2014/10/clocks-make-workers-less-creative/381064/", time: "1 day ago"}, 
	{title : "Ebola, Beyond the Headlines", site: "gatesnotes.co", href: "http://www.gatesnotes.com/Health/Ebola-Beyond-the-Headlines", time: "1 day ago"}, 
	{title : "The Archipelago of Weird (2005)", site: "siderea.livejournal.co", href: "http://siderea.livejournal.com/201206.html", time: "1 day ago"}, 
	{title : "Mary Shaw Will Receive National Medal of Technology and Innovation", site: "cmu.ed", href: "http://www.cmu.edu/news/stories/archives/2014/october/october3_shawwinsnationalmedal.html", time: "1 day ago"}, 
	{title : "IKEA is finally selling a sit/stand desk in the US for less than $500", site: "ikea.co", href: "http://www.ikea.com/us/en/catalog/products/S99022526/", time: "23 hours ago"}, 
	{title : "Battle Over Use of Word ‘How’ as Trademark", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/business/chobani-and-dov-seidman-wrestle-over-use-of-how-trademark.html?partner=rss&emc=rss&smid=tw-nytimes&_r=1", time: "1 day ago"}, 
	{title : "Graph of the routed autonomous systems", site: "polzunov.co", href: "http://as-graph.polzunov.com/", time: "1 day ago"}, 
	{title : "An exchange on capital, debt, and the future", site: "thebaffler.co", href: "http://www.thebaffler.com/odds-and-ends/soak-the-rich", time: "1 day ago"}, 
	{title : "Fast Resettable Flag Vector", site: "upcoder.co", href: "http://upcoder.com/9/fast-resettable-flag-vector/", time: "1 day ago"}, 
	{title : "Getting A+ on SSLLabs with Nginx and StartSSL", site: "mijndertstuij.n", href: "https://mijndertstuij.nl/getting-a-on-ssllabs-with-nginx-startssl/", time: "21 hours ago"}, 
	{title : "GNU Bash commit messages", site: "gnu.or", href: "http://git.savannah.gnu.org/cgit/bash.git/log/", time: "1 day ago"}, 
	{title : "I'm Agile but My Contract Isn't", site: "stridenyc.co", href: "http://www.stridenyc.com/blog/2014/10/3/im-agile-but-my-contract-isnt-how-to-align-contracts-with-agile-software-development-teams", time: "1 day ago"}, 
	{title : "Refold cardboard standing desk changes the way you work", site: "designboom.co", href: "http://www.designboom.com/design/refold-cardboard-standing-desk-new-zealand-10-07-2014/", time: "22 hours ago"}, 
	{title : "Coyote Creek is a foul wasteland minutes from mega-rich Silicon Valley", site: "mirror.co.u", href: "http://www.mirror.co.uk/news/world-news/welcome-jungle-coyote-creek-foul-4392415", time: "1 day ago"}, 
	{title : "Andreessen on Finance: ‘We Can Reinvent the Entire Thing’", site: "businessweek.co", href: "http://www.businessweek.com/news/2014-10-07/andreessen-on-finance-we-can-reinvent-the-entire-thing", time: "22 hours ago"}, 
	{title : "Show HN: AhhLife, a free replacement for OhLife", site: "ahhlife.co", href: "http://ahhlife.com", time: "1 day ago"}, 
	{title : "SpaceX launching Seattle-area office, recruiting Microsoft engineers", site: "geekwire.co", href: "http://www.geekwire.com/2014/spacex-launching-seattle-area-office-recruiting-squadrons-microsoft-engineers/", time: "1 day ago"}, 
	{title : "According to Apple, people have all but stopped upgrading to iOS 8", site: "9to5mac.co", href: "http://9to5mac.com/2014/10/06/ios8-market-share-stagnated/", time: "23 hours ago"}, 
]