news20 = [
	{title : "Microsoft imagines an incredible transparent smart cover for Surface tablets", site: "theverge.co", href: "http://www.theverge.com/2014/10/6/6918753/microsoft-flexsense-transparent-smart-cover-research-project", time: "1 day ago"}, 
	{title : "Haskell's Prelude is adding Foldable/Traversable", site: "yesodweb.co", href: "http://www.yesodweb.com/blog/2014/10/classy-base-prelude", time: "1 day ago"}, 
	{title : "Dealer’s Hand: Why are so many people paying so much money for art? (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/12/02/dealers-hand", time: "2 days ago"}, 
	{title : "Maps attributed to Marco Polo sketch what looks like the coast of Alaska", site: "smithsonianmag.co", href: "http://www.smithsonianmag.com/history/did-marco-polo-discover-america-180952765/", time: "2 days ago"}, 
	{title : "Naive Bayes and Text Classification I – Introduction and Theory", site: "sebastianraschka.co", href: "http://sebastianraschka.com/Articles/2014_naive_bayes_1.html", time: "3 days ago"}, 
	{title : "Massive electrode array will do first large-scale recording of brain activity", site: "kurzweilai.ne", href: "http://www.kurzweilai.net/massive-electrode-array-system-will-do-first-large-scale-network-recording-of-brain-activity", time: "2 days ago"}, 
	{title : "Why do roots of polynomials tend to have absolute value 1?", site: "mathoverflow.ne", href: "http://mathoverflow.net/questions/182412/why-do-roots-of-polynomials-tend-to-have-absolute-value-1", time: "2 days ago"}, 
	{title : "The Power of Interoperability: Why Objects Are Inevitable (2013) [pdf]", site: "cmu.ed", href: "http://www.cs.cmu.edu/~aldrich/papers/objects-essay.pdf", time: "3 days ago"}, 
	{title : "How I deploy node apps on Linux, 2014 edition", site: "medium.co", href: "https://medium.com/@mikemaccana/how-i-deploy-node-apps-on-linux-2014-edition-309d606219ca", time: "1 day ago"}, 
	{title : "Show HN: Turning a classic gamebook into interactive fiction", site: "github.co", href: "https://github.com/cjauvin/gamebook.js", time: "2 days ago"}, 
	{title : "Visual Revolution of the Vanishing of Ethan Carter", site: "theastronauts.co", href: "http://www.theastronauts.com/2014/03/visual-revolution-vanishing-ethan-carter/", time: "7 days ago"}, 
	{title : "A survey of the current state of Golang ORMs", site: "go-steel-programmers.or", href: "http://present.go-steel-programmers.org/talk-review-orms/gsp-go-orms.slide#1", time: "2 days ago"}, 
	{title : "Hacker's Guide to Setting Up Your Mac", site: "lapwinglabs.co", href: "http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac", time: "5 days ago"}, 
	{title : "ScoutBot: Automated network scanning, environment assessments, and more", site: "lansec.ne", href: "http://lansec.net/project/scoutbot/", time: "2 days ago"}, 
	{title : "Learn Swift for Free (expires Oct. 31)", site: "udemy.co", href: "https://www.udemy.com/learn-swift/?couponCode=LEARN_SWIFT_HACKERNEWS", time: "1 day ago"}, 
	{title : "Cool-retro-term: A terminal emulator which mimics the old cathode display", site: "github.co", href: "https://github.com/Swordfish90/cool-retro-term", time: "6 days ago"}, 
	{title : "This is the last photo we’ll ever run of the NYSE trading floor", site: "marketwatch.co", href: "http://www.marketwatch.com/story/this-is-the-last-photo-well-ever-run-of-the-nyse-trading-floor-2014-10-01", time: "1 day ago"}, 
	{title : "Saving Cyla", site: "theglobeandmail.co", href: "http://www.theglobeandmail.com/life/health-and-fitness/health/video-saving-cyla-inside-the-operating-room-as-a-young-ontario-woman-undergoes-brain-surgery-while-awake/article20895176/", time: "2 days ago"}, 
	{title : "New web privacy system could revolutionise the safety of surfing", site: "ucl.ac.u", href: "http://www.ucl.ac.uk/news/news-articles/1014/061014_COWL", time: "1 day ago"}, 
	{title : "Viomba: A/B test your website and measure your design with eye tracking", site: "viomba.co", href: "http://www.viomba.com", time: "2 days ago"}, 
	{title : "The Potential Power of Networked Community Building", site: "thefnf.or", href: "https://lists.thefnf.org/pipermail/discuss/2014-October/001932.html", time: "2 days ago"}, 
	{title : "What the Hell Was Megadeth, Arizona?", site: "medium.co", href: "https://medium.com/cuepoint/what-the-hell-was-megadeth-arizona-3519a751149d", time: "1 day ago"}, 
	{title : "Oxygen absorbing material may allow us to breathe underwater", site: "gizmag.co", href: "http://www.gizmag.com/crystalline-material-absorb-oxygen-denmark/34064/", time: "1 day ago"}, 
	{title : "Show HN: PixelTool – a tool for overlaying designs for pixel perfect front-end", site: "spencer-walden.co", href: "http://www.spencer-walden.com/pixeltool/", time: "2 days ago"}, 
	{title : "To Reach China, LinkedIn Plays by Local Rules", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/06/technology/to-reach-china-linkedin-plays-by-local-rules.html", time: "2 days ago"}, 
	{title : "Untangling how cables coil", site: "mit.ed", href: "http://newsoffice.mit.edu/2014/predict-cable-coiling-1003", time: "2 days ago"}, 
	{title : "How to change or build your career", site: "sivers.or", href: "http://sivers.org/career", time: "2 days ago"}, 
	{title : "My Approach to Life Logging. Meet Nomie", site: "icorbin.co", href: "http://blog.icorbin.com/my-take-on-life-tracking-meet-nomie/", time: "1 day ago"}, 
	{title : "English Proficiency Index", site: "ef.co", href: "http://www.ef.com/epi", time: "2 days ago"}, 
]