news21 = [
	{title : "‘The Innovators’ by Walter Isaacson", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/books/review/the-innovators-by-walter-isaacson.html", time: "2 days ago"}, 
	{title : "The Physical Web", site: "github.co", href: "https://github.com/google/physical-web", time: "5 days ago"}, 
	{title : "Refactoring Ruby with Monads", site: "codon.co", href: "http://codon.com/refactoring-ruby-with-monads", time: "4 days ago"}, 
	{title : "Rockwool vs. Perlite vs. Hydroton vs. Soil", site: "hydronerd.co", href: "http://hydronerd.com/2014/10/rockwool-vs-perlite-vs-hydroton-vs-soil/", time: "2 days ago"}, 
	{title : "The Star7 PDA Prototype, Genesis of Java [video] (1992)", site: "youtube.co", href: "https://www.youtube.com/watch?v=Ahg8OBYixL0", time: "2 days ago"}, 
	{title : "Graphite-News: Keeping up to speed with whats new in your monitoring tool", site: "jilles.ne", href: "http://www.jilles.net/perma/2014/10/03/introducing-graphite-news/", time: "2 days ago"}, 
	{title : "Why haven't quadcopters been scaled up yet?", site: "stackexchange.co", href: "http://aviation.stackexchange.com/questions/3300/why-havent-quadcopters-been-scaled-up-yet", time: "3 days ago"}, 
	{title : "Inspeqtor – Monitor your application infrastructure", site: "github.co", href: "https://github.com/mperham/inspeqtor", time: "2 days ago"}, 
	{title : "Show HN: Simple email rendering tool to handle multi-language email content", site: "github.co", href: "https://github.com/KeepSafe/ks-email-parser", time: "2 days ago"}, 
	{title : "Where the Printf Rubber Meets the Road (2010)", site: "hostilefork.co", href: "http://blog.hostilefork.com/where-printf-rubber-meets-road/", time: "3 days ago"}, 
	{title : "Big robot fleet takes to UK waters", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29464273", time: "2 days ago"}, 
	{title : "Times Articles Removed from Google Results in Europe", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/media/times-articles-removed-from-google-results-in-europe.html", time: "3 days ago"}, 
	{title : "Machine Learning with Knowledge Graphs [video]", site: "nzhiltsov.blogspot.co", href: "http://nzhiltsov.blogspot.com/2014/10/machine-learning-with-knowledge-graphs.html", time: "2 days ago"}, 
	{title : "Apple Expected to Consume 25% of All DRAM in 2015", site: "hothardware.co", href: "http://hothardware.com/m/News/Apple-Expected-To-Consume-25-Of-All-DRAM-In-2015-Impact-Industry-Trends/default.aspx", time: "2 days ago"}, 
	{title : "Navy: Self-guided unmanned patrol boats make debut", site: "myfoxal.co", href: "http://www.myfoxal.com/story/26706962/navy-self-guided-unmanned-patrol-boats-make-debut", time: "2 days ago"}, 
	{title : "In 1888, one man patented a machine for vending “healthy” electric shocks", site: "arstechnica.co", href: "http://arstechnica.com/science/2014/10/a-look-at-the-1888-patent-for-an-electric-shock-vending-machine", time: "2 days ago"}, 
	{title : "When 911 calls fail", site: "theverge.co", href: "http://www.theverge.com/2014/10/3/6414949/911-call-failures-fcc", time: "4 days ago"}, 
	{title : "CERN turns 60", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/cern-turns-60", time: "3 days ago"}, 
	{title : "Bitcoin trader floods market with $300 orders, causing price to flatline", site: "bitcoinwisdom.co", href: "https://bitcoinwisdom.com/markets/bitstamp/btcusd?flatine", time: "2 days ago"}, 
	{title : "Reading the Silk Road configuration", site: "erratasec.co", href: "http://blog.erratasec.com/2014/10/reading-silk-road-configuration.html", time: "4 days ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://m.bbc.com/news/science-environment-29465446", time: "3 days ago"}, 
	{title : "Code Browser – A Folding Text Editor", site: "tibleiz.ne", href: "http://tibleiz.net/code-browser/index.html", time: "3 days ago"}, 
	{title : "When is a recursive function not a recursive function?", site: "russet.org.u", href: "http://www.russet.org.uk/blog/3015", time: "2 days ago"}, 
	{title : "The Books We Talk About (and Those We Don’t)", site: "nybooks.co", href: "http://www.nybooks.com/blogs/nyrblog/2014/oct/01/books-we-talk-about/", time: "3 days ago"}, 
	{title : "Modernized time.h for ISO C (1998)", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~mgk25/time/c/", time: "3 days ago"}, 
	{title : "Storage Scalability in Docker", site: "redhat.co", href: "http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/?utm_content=buffer8a955&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer", time: "3 days ago"}, 
	{title : "Dubai detectives to get Google Glass", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/02/us-emirates-dubai-google-police-idUSKCN0HR0W320141002", time: "2 days ago"}, 
	{title : "Linked lists with wait-free reads in C++", site: "concurrencyfreaks.blogspot.co", href: "http://concurrencyfreaks.blogspot.com/2014/10/linked-lists-with-wait-free-reads-in-c.html", time: "4 days ago"}, 
]