news30 = [
	{title : "Thinking about quitting your job? Go tell your boss", site: "ronsho.co", href: "http://www.ronsho.com/2014/10/quitting-job-tell-boss/", time: "2 days ago"}, 
	{title : "Dominus is now open source.  Multiplayer browser game made with Meteor", site: "github.co", href: "https://github.com/dan335/dominus", time: "3 days ago"}, 
	{title : "South by Southwest’s unpaid labor problem", site: "salon.co", href: "http://www.salon.com/2014/02/26/south_by_southwest%E2%80%99s_unpaid_labor_problem_why_its_risking_a_class_action_lawsuit/", time: "2 days ago"}, 
	{title : "Watch the Navy’s Robotic Gunboats Swarm the James River", site: "medium.co", href: "https://medium.com/war-is-boring/watch-the-navys-robotic-gunboats-swarm-the-james-river-86abe382600f", time: "3 days ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage/", time: "3 days ago"}, 
	{title : "Debian Linux Wheezy OpenVPN and Squid3 How to with Transparent Proxying", site: "iodigitalsec.co", href: "http://www.iodigitalsec.com/debian-linux-wheezy-openvpn-squid3-howto-with-transparent-proxying/", time: "3 days ago"}, 
	{title : "HackCampus Internship: A programme built by students for students in the UK", site: "hackcampus.i", href: "http://hackcampus.io/internship/", time: "3 days ago"}, 
	{title : "The surprising and continuing influence of Swami Vivekananda (2012)", site: "wsj.co", href: "http://online.wsj.com/news/articles/SB10001424052702303404704577305581227233656", time: "10 days ago"}, 
	{title : "The self-made man", site: "slate.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/the_self_made_man_history_of_a_myth_from_ben_franklin_to_andrew_carnegie.html", time: "8 days ago"}, 
	{title : "Avoid OOP (Overzealous Optimization Programming)", site: "colintoh.co", href: "http://colintoh.com/blog/avoid-oop", time: "2 days ago"}, 
	{title : "How WP Engine Hijacked My Business", site: "matthewwoodward.co.u", href: "http://www.matthewwoodward.co.uk/reviews/webhost-trusted-wp-engine-hijacked-business-avoid-them/", time: "3 days ago"}, 
	{title : "Japan's groundbreaking bullet train is 50 years old", site: "businessinsider.co", href: "http://www.businessinsider.com/shinkansen-bullet-train-now-50-years-old-2014-10?op=1", time: "3 days ago"}, 
	{title : "Good looking addresses – solving the “Berlin, Berlin” bug", site: "opencagedata.co", href: "http://blog.opencagedata.com/post/99059889253/good-looking-addresses-solving-the-berlin-berlin", time: "4 days ago"}, 
	{title : "Finally, a 2nd Ave. Subway [video]", site: "nytimes.co", href: "http://www.nytimes.com/video/nyregion/100000003149427/living-city-finally-a-2nd-ave-subway.html?src=vidm", time: "3 days ago"}, 
	{title : "Desktop PCs aren’t going anywhere–because they’re cheap (2011)", site: "jseliger.wordpress.co", href: "https://jseliger.wordpress.com/2011/10/09/desktop-pcs-arent-going-anywhere-despite-the-growth-of-phones-and-tablets%E2%80%94because-theyre-cheap", time: "3 days ago"}, 
	{title : "The very laws of physics imply that artificial intelligence must be possible", site: "aeon.c", href: "http://aeon.co/magazine/technology/david-deutsch-artificial-intelligence/", time: "7 days ago"}, 
	{title : "Rise of the Robots: On Peter Thiel's argument about robots and low wages", site: "project-syndicate.or", href: "http://www.project-syndicate.org/commentary/j--bradford-delong-questions-paypal-co-founder-peter-thiel-s-argument-that-robots-will-save-us-from-a-low-wage-future", time: "3 days ago"}, 
	{title : "Sweden to become first EU country to officially recognize State of Palestine", site: "rt.co", href: "http://rt.com/news/192904-sweden-to-recognize-palestine/", time: "2 days ago"}, 
	{title : "N.C.A.A. Fan Map: How the Country Roots for College Football", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/03/upshot/ncaa-football-fan-map.html", time: "4 days ago"}, 
	{title : "Etsy’s Trying to Fix Tech’s Women Problem. Why Aren’t You?", site: "medium.co", href: "https://medium.com/matter/this-is-the-last-thing-youll-ever-need-to-read-about-sexism-in-tech-56b9a3a77af0", time: "5 days ago"}, 
	{title : "Ebola: The tolling bell", site: "stanford.ed", href: "http://stanfordlawyer.law.stanford.edu/2014/10/ebola-the-tolling-bell/", time: "4 days ago"}, 
	{title : "Unpatchable Malware That Infects USBs", site: "wired.co", href: "http://www.wired.com/2014/10/code-published-for-unfixable-usb-attack/", time: "5 days ago"}, 
	{title : "Introducing the World’s Most Precise Clock", site: "ieee.or", href: "http://spectrum.ieee.org/aerospace/satellites/introducing-the-worlds-most-precise-clock", time: "4 days ago"}, 
	{title : "Decoding Nature's Soundtrack", site: "nautil.u", href: "http://nautil.us/issue/12/feedback/decoding-natures-soundtrack?utm_source=tss&utm_medium=desktop&utm_campaign=linkfrom", time: "3 days ago"}, 
	{title : "Roller Coaster Tycoon was written in x86 Assembly by one guy", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/RollerCoaster_Tycoon#Development", time: "3 days ago"}, 
	{title : "Labour is steadily losing out to capital", site: "economist.co", href: "http://www.economist.com/news/special-report/21621160-labour-steadily-losing-out-capital-those-have-shall-be-given", time: "4 days ago"}, 
	{title : "Inside McLaren's 650S supercar factory", site: "cnet.co", href: "http://www.cnet.com/pictures/inside-mclaren/", time: "3 days ago"}, 
]