news31 = [
	{title : "Soylent and It's Side Effects", site: "ethanglover.bi", href: "http://ethanglover.biz/blog/soylent-side-effects.php", time: "3 days ago"}, 
	{title : "Privacy Statements for Windows 10 Technical Preview", site: "microsoft.co", href: "http://windows.microsoft.com/en-gb/windows/preview-privacy-statement", time: "3 days ago"}, 
	{title : "Installing Apple CarPlay and Taking It for a Spin", site: "consumerreports.or", href: "http://www.consumerreports.org/cro/news/2014/10/installing-apple-carplay-on-pioneer-stereo-and-taking-it-for-spin/index.htm", time: "4 days ago"}, 
	{title : "Show HN: Create Your Own Startup Metrics Dashboard", site: "pubnub.co", href: "http://www.pubnub.com/developers/demos/startup-metrics-dashboard/", time: "4 days ago"}, 
	{title : "Isomorphic JavaScript: Angular.js is not the answer", site: "berzniz.co", href: "http://berzniz.com/post/99158163051/isomorphic-javascript-angular-js-is-not-the-answer", time: "3 days ago"}, 
	{title : "How Computers Boot Up (2008)", site: "duartes.or", href: "http://duartes.org/gustavo/blog/post/how-computers-boot-up/", time: "3 days ago"}, 
	{title : "Is Docker ready for production? Feedbacks of a 2 weeks hands on", site: "t37.ne", href: "https://t37.net/is-docker-ready-for-production-feedbacks-of-a-2-weeks-hands-on.html", time: "4 days ago"}, 
	{title : "Python REPL with syntax highlighting, autocomplete and multiline editing", site: "github.co", href: "https://github.com/jonathanslenders/python-prompt-toolkit", time: "8 days ago"}, 
	{title : "Why I took on building a better way to frame any poster, print or photo", site: "medium.co", href: "https://medium.com/@jhubball/custom-framing-is-a-racket-61461b12278d", time: "5 days ago"}, 
	{title : "Show HN: HelloBitcoin. A “Hello World” of Bitcoin, Written in Go", site: "github.co", href: "https://github.com/prettymuchbryce/hellobitcoin", time: "5 days ago"}, 
	{title : "How I hit my first $100 month on Udemy.com", site: "dennisjsmith.co", href: "http://dennisjsmith.com/how-i-hit-my-first-100-month-on-udemy-com/", time: "3 days ago"}, 
	{title : "Booking.com donates $60000 to Perl development", site: "perlfoundation.or", href: "http://news.perlfoundation.org/2014/10/bookingcom-donates-60000-to-pe.html", time: "4 days ago"}, 
	{title : "Power Up Your Team with Nonviolent Communication Principles", site: "firstround.co", href: "http://firstround.com/article/power-up-your-team-with-nonviolent-communication-principles", time: "3 days ago"}, 
	{title : "Major Updates to Firebase User Authentication", site: "firebase.co", href: "https://www.firebase.com/blog/2014-10-03-major-updates-to-firebase-user-auth.html", time: "4 days ago"}, 
	{title : "Apple allows hot code push for JS downloaded and run by WebKit", site: "meteor.co", href: "https://www.meteor.com/blog/2014/10/02/Apple-hot-code-push-mobile", time: "5 days ago"}, 
	{title : "Creating your own Heroku on EC2", site: "clearbit.c", href: "http://blog.clearbit.co/ec2-heroku?hn", time: "4 days ago"}, 
	{title : "Three months at Y Combinator: what it’s like and how to get in", site: "frontapp.co", href: "http://blog.frontapp.com/three-months-at-y-combinator-what-its-like-and-how-to-get-in/", time: "5 days ago"}, 
	{title : "Adventures in 19th-century photography", site: "mortalmuses.co", href: "http://mortalmuses.com/2014/10/03/adventures-in-19th-century-photography/", time: "4 days ago"}, 
	{title : "Drug recommended to help cut drink dependence", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/uk-29468885", time: "4 days ago"}, 
	{title : "Geometric Madness: Implementation of computational geometry algorithms [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=fu-uW7CQkVo", time: "5 days ago"}, 
	{title : "The origins of language are not what inherited disorders seemed to suggest", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/the-family-that-couldnt-say-hippopotamus?utm_source=RSS_Feed&utm_medium=RSS&utm_campaign=RSS_Syndication", time: "4 days ago"}, 
	{title : "Study suggests that memory loss in Alzheimer's patients may be reversed", site: "neurosciencenews.co", href: "http://neurosciencenews.com/alzheimers-memory-loss-reversal-1377/", time: "5 days ago"}, 
	{title : "Data science: How mood and tempo can influence artist discovery?", site: "apassant.ne", href: "http://apassant.net/2014/10/03/how-mood-and-tempo-can-influence-artist-discovery/", time: "3 days ago"}, 
	{title : "BookKeeper: High-availability scalable distributed logging", site: "muratbuffalo.blogspot.co", href: "http://muratbuffalo.blogspot.com/2014/09/paper-summary-high-availability.html", time: "4 days ago"}, 
	{title : "Elusive Form of Evolution Seen in Spiders", site: "simonsfoundation.or", href: "http://www.simonsfoundation.org/quanta/20141002-in-social-spiders-evidence-that-groups-evolve/", time: "5 days ago"}, 
	{title : "Jank Free: Let's Make the Web Silky Smooth", site: "jankfree.or", href: "http://jankfree.org/", time: "4 days ago"}, 
	{title : "SAT solving – An alternative to brute force Bitcoin mining (2013)", site: "jheusser.github.i", href: "https://jheusser.github.io/2013/02/03/satcoin.html", time: "5 days ago"}, 
]