news2 = [
	{title : "Yahoo Hacked", site: "googleusercontent.co", href: "http://webcache.googleusercontent.com/search?q=cache:I8s8KmZhwXMJ:www.futuresouth.us/yahoo_hacked.html+&cd=1&hl=en&ct=clnk&client=firefox-a", time: "1 day ago"}, 
	{title : "Show HN: Virtjs, an ES6 emulation library", site: "virtjs.co", href: "http://virtjs.com", time: "10 hours ago"}, 
	{title : "Travel planning software: The most common bad startup idea (2012)", site: "garrytan.co", href: "http://blog.garrytan.com/travel-planning-software-the-most-common-bad", time: "1 day ago"}, 
	{title : "Meteor Acquires YC Alum FathomDB for Its Development Platform", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/meteor-acquires-yc-alum-fathomdb-for-its-web-development-platform/", time: "10 hours ago"}, 
	{title : "Reverse engineering the binary data format for Star Wars: Yoda Stories", site: "zachtronics.co", href: "http://www.zachtronics.com/yoda-stories/", time: "1 day ago"}, 
	{title : "Stealth, Countermeasures, and ELINT, 1960-1975", site: "cia.go", href: "http://www.foia.cia.gov/sites/default/files/DOC_0006122549.pdf", time: "9 hours ago"}, 
	{title : "800 year old Magna Carta manuscript reveals its secrets", site: "britishlibrary.typepad.co.u", href: "http://britishlibrary.typepad.co.uk/collectioncare/2014/10/800-year-old-magna-carta-manuscript-reveals-its-secrets.html", time: "13 hours ago"}, 
	{title : "Become Estonia’s e-resident", site: "e-estonia.co", href: "http://e-estonia.com/e-residents/become-e-resident/", time: "1 day ago"}, 
	{title : "Interana (YC W13) promises Facebook-style analytics for everyone", site: "gigaom.co", href: "https://gigaom.com/2014/10/07/interana-promises-facebook-style-analytics-for-everyone/", time: "13 hours ago"}, 
	{title : "Show HN: Nightmare – Simple browser automation", site: "nightmarejs.or", href: "http://www.nightmarejs.org/", time: "1 day ago"}, 
	{title : "Mouse Speedometer", site: "ocks.or", href: "http://bl.ocks.org/jlaurito/raw/d2f172c58b6ee07cf3d4/", time: "7 hours ago"}, 
	{title : "HyperLogLog and HyperLogLog++ implementation in Go", site: "github.co", href: "https://github.com/clarkduvall/hyperloglog", time: "13 hours ago"}, 
	{title : "Video Digest of “How to Start a Startup”", site: "berkeley.ed", href: "http://vis.berkeley.edu/videodigests/view/Lecture-1-How-to-Start-a-Startup-FuX-7RX", time: "8 hours ago"}, 
	{title : "King of click: the story of the greatest keyboard ever made", site: "theverge.co", href: "http://www.theverge.com/2014/10/7/6882427/king-of-keys", time: "7 hours ago"}, 
	{title : "Design is Expensive", site: "dadgum.co", href: "http://prog21.dadgum.com/199.html", time: "13 hours ago"}, 
	{title : "What We Learned About Scaling with Apache Storm", site: "loggly.co", href: "https://www.loggly.com/blog/what-we-learned-about-scaling-with-apache-storm/", time: "9 hours ago"}, 
	{title : "SPHINCS: practical stateless hash-based signatures", site: "yp.t", href: "http://sphincs.cr.yp.to/index.html", time: "14 hours ago"}, 
	{title : "Designer's Guide to DPI", site: "sebastien-gabriel.co", href: "http://sebastien-gabriel.com/designers-guide-to-dpi/home?oops", time: "2 hours ago"}, 
	{title : "The Placebo Effect Doesn’t Apply Just to Pills", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/upshot/the-placebo-effect-doesnt-apply-just-to-pills.html?partner=rss&emc=rss&abt=0002&abg=1&_r=0", time: "13 hours ago"}, 
	{title : "Torturing Databases for Fun and Profit [pdf]", site: "usenix.or", href: "https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-zheng_mai.pdf", time: "7 hours ago"}, 
	{title : "How Did English Become the Language of Science?", site: "pri.or", href: "http://www.pri.org/stories/2014-10-06/how-did-english-become-language-science", time: "11 hours ago"}, 
	{title : "NCR ATM API Documentation Available on Baidu", site: "f-secure.co", href: "http://www.f-secure.com/weblog/archives/00002751.html", time: "6 hours ago"}, 
	{title : "Up All Night: The Science of Sleeplessness (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/03/11/up-all-night-2?currentPage=all", time: "1 day ago"}, 
	{title : "Slfsrv – Create simple, cross-platform GUI applications", site: "github.co", href: "https://github.com/BrentNoorda/slfsrv", time: "6 hours ago"}, 
	{title : "SAT Scores and Income Inequality: How Wealthier Kids Rank Higher", site: "wsj.co", href: "http://blogs.wsj.com/economics/2014/10/07/sat-scores-and-income-inequality-how-wealthier-kids-rank-higher", time: "6 hours ago"}, 
	{title : "Needle: ASCII-fied arrow notation", site: "scrambledeggsontoast.github.i", href: "http://scrambledeggsontoast.github.io/2014/09/28/needle-announce/", time: "14 hours ago"}, 
	{title : "The force vectors on a skateboard during an Ollie", site: "wired.co", href: "http://www.wired.com/2014/10/skateboard-physics-empzeal/", time: "1 day ago"}, 
	{title : "Yahoo Lays Off 400 Employees In India", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/07/yahoo-lays-off-employees-in-india-reportedly-up-to-2000-affected/", time: "15 hours ago"}, 
	{title : "A Young Chemist Explains How Legal Highs Work", site: "vice.co", href: "http://www.vice.com/read/research-drugs-and-the-grey-market", time: "8 hours ago"}, 
]