news12 = [
	{title : "Why I'm Building Volley", site: "medium.co", href: "https://medium.com/volley-works/why-were-making-volley-b7e382da8ead", time: "17 hours ago"}, 
	{title : "Peru: The Future of Gastronomy", site: "cntraveler.co", href: "http://www.cntraveler.com/stories/2014-09-23/peru-the-future-of-gastronomy", time: "1 day ago"}, 
	{title : "Square Raises $150M at a $6B Valuation", site: "bits.blogs.nytimes.co", href: "http://bits.blogs.nytimes.com/2014/10/05/square-raises-150-million-at-a-6-billion-valuation/", time: "2 days ago"}, 
	{title : "FlexSense: A Transparent Self-Sensing Deformable Surface [video]", site: "microsoft.co", href: "http://research.microsoft.com/apps/video/default.aspx?id=230399", time: "1 day ago"}, 
	{title : "Firechat and nearby communication", site: "breizh-entropy.or", href: "http://breizh-entropy.org/~nameless/random/posts/firechat_and_nearby_communication/", time: "2 days ago"}, 
	{title : "Soft Errors Are Hard Problems (2009)", site: "geekhold.co", href: "http://codingrelic.geekhold.com/2009/09/soft-errors-are-hard-problems.html", time: "1 day ago"}, 
	{title : "How the Z80's registers are implemented", site: "righto.co", href: "http://www.righto.com/2014/10/how-z80s-registers-are-implemented-down.html", time: "2 days ago"}, 
	{title : "Glut of postdoc researchers stirs quiet crisis in science", site: "bostonglobe.co", href: "https://www.bostonglobe.com/metro/2014/10/04/glut-postdoc-researchers-stirs-quiet-crisis-science/HWxyErx9RNIW17khv0MWTN/story.html", time: "2 days ago"}, 
	{title : "Why Apple's iPhone encryption won't stop NSA", site: "siliconexposed.blogspot.co", href: "http://siliconexposed.blogspot.com/2014/10/why-apples-iphone-encryption-wont-stop.html", time: "2 days ago"}, 
	{title : "Go at Google I/O and Gopher SummerFest", site: "golang.or", href: "http://blog.golang.org/io2014", time: "1 day ago"}, 
	{title : "Beginnings of Science Fiction", site: "wewanttolearn.wordpress.co", href: "http://wewanttolearn.wordpress.com/2014/10/05/beginnings-of-sf/", time: "1 day ago"}, 
	{title : "PayPal's Incentive Problem", site: "stratechery.co", href: "http://stratechery.com/2014/paypals-incentive-problem/", time: "1 day ago"}, 
	{title : "Reddit", site: "samaltman.co", href: "http://blog.samaltman.com/reddit", time: "7 days ago"}, 
	{title : "Building packages at scale", site: "perkin.org.u", href: "http://www.perkin.org.uk/posts/building-packages-at-scale.html", time: "1 day ago"}, 
	{title : "Hewlett-Packard Plans to Break in Two", site: "wsj.co", href: "http://online.wsj.com/articles/hewlett-packard-plans-to-break-in-two-1412530028?mod=djemalertTECH", time: "2 days ago"}, 
	{title : "Hooknook: Like GitHub Pages for Your Server", site: "washington.ed", href: "http://homes.cs.washington.edu/~asampson/blog/hooknook.html", time: "1 day ago"}, 
	{title : "Show HN: Aiveo – Free issue tracking tool", site: "aiveo.c", href: "http://aiveo.ca", time: "1 day ago"}, 
	{title : "How fast is fscanf?", site: "github.co", href: "https://github.com/alexflint/fscanf-speed", time: "2 days ago"}, 
	{title : "Our Understanding of Giraffes Does Not Measure Up", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/science/our-understanding-of-giraffes-does-not-measure-up.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "2 days ago"}, 
	{title : "HFT in my backyard – More on piracy", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/06/hft-in-my-backyard-more-on-piracy", time: "1 day ago"}, 
	{title : "Avoiding the Top Security Flaws", site: "ieee.or", href: "http://cybersecurity.ieee.org/center-for-secure-design/avoiding-the-top-10-security-flaws.html", time: "1 day ago"}, 
	{title : "Feet-on with RocketSkates", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/feet-on-with-rocketskates-which-are-exactly-what-they-sound-like/", time: "1 day ago"}, 
	{title : "Building a testable Go web app", site: "sourcegraph.co", href: "https://sourcegraph.com/blog/building-a-testable-webapp", time: "2 days ago"}, 
	{title : "Meg Whitman Finds a Vision for HP", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/07/technology/meg-whitman-finds-a-vision-for-hp.html?hp&action=click&pgtype=Homepage&version=HpSum&module=first-column-region&region=top-news&WT.nav=top-news", time: "1 day ago"}, 
	{title : "New npm documentation", site: "npmjs.co", href: "https://docs.npmjs.com/", time: "1 day ago"}, 
	{title : "Some ideas for native Bitcoin apps", site: "cdixon.or", href: "http://cdixon.org/2014/10/04/some-ideas-for-native-bitcoin-apps/", time: "3 days ago"}, 
	{title : "Lecture 3: How to Start a Startup", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec03/", time: "7 days ago"}, 
	{title : "Mistakes AngularJS Developers Make", site: "airpair.co", href: "http://www.airpair.com/angularjs/posts/top-10-mistakes-angularjs-developers-make", time: "4 days ago"}, 
	{title : "Show HN: VidFall – Pay with time, not your wallet", site: "vidfall.co", href: "http://vidfall.com/", time: "16 hours ago"}, 
]