news7 = [
	{title : "Accidental release of 45L of polio virus solution into the environment – Belgium", site: "europa.e", href: "http://www.ecdc.europa.eu/en/press/news/_layouts/forms/News_DispForm.aspx?List=8db7286c-fe2d-476c-9133-18ff4cb1b568&ID=1065", time: "4 days ago"}, 
	{title : "Object Oriented Programming is an expensive disaster which must end", site: "smashcompany.co", href: "http://www.smashcompany.com/technology/object-oriented-programming-is-an-expensive-disaster-which-must-end", time: "21 hours ago"}, 
	{title : "Marc Andreessen on Finance: ‘We Can Reinvent the Entire Thing’", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-07/andreessen-on-finance-we-can-reinvent-the-entire-thing-.html", time: "16 hours ago"}, 
	{title : "Newtonsoft.Json NuGet abuses install scripts to earn ad impression/revenue", site: "github.co", href: "https://github.com/JamesNK/Newtonsoft.Json/pull/387#issuecomment-58133201", time: "21 hours ago"}, 
	{title : "Tech hiring, poker, and (not) playing to win. – Michael O. Church", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2014/10/06/tech-hiring-poker-and-not-playing-to-win/", time: "1 day ago"}, 
	{title : "Offline-first is people-first", site: "nolanlawson.co", href: "http://nolanlawson.com/2014/10/03/offline-first-is-people-first/", time: "4 days ago"}, 
	{title : "Chickens have gotten ridiculously large since the 1950s", site: "vox.co", href: "http://www.vox.com/xpress/2014/10/2/6875031/chickens-breeding-farming-boilers-giant", time: "4 days ago"}, 
	{title : "Rust for functional programmers", site: "poss.nam", href: "http://science.raphael.poss.name/rust-for-functional-programmers.html", time: "86 days ago"}, 
	{title : "Digital Ocean gives away t-shirts for commiting to public GitHub repo in October", site: "digitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/", time: "5 days ago"}, 
	{title : "A Designers Guide to DPI", site: "sebastien-gabriel.co", href: "http://sebastien-gabriel.com/designers-guide-to-dpi/home", time: "53 days ago"}, 
	{title : "VEST: A Sensory Substitution Neuroscience Project", site: "kickstarter.co", href: "https://www.kickstarter.com/projects/324375300/vest-a-sensory-substitution-neuroscience-project", time: "29 days ago"}, 
	{title : "Data-Processing Frameworks Benchmark: Redshift, Hive, Shark, Impala", site: "berkeley.ed", href: "https://amplab.cs.berkeley.edu/benchmark/", time: "373 days ago"}, 
	{title : "Large-scale analysis  of neural data", site: "thefreemanlab.co", href: "http://thefreemanlab.com/thunder/", time: "71 days ago"}, 
	{title : "The Best Languages For Getting Into Functional Programming", site: "forbes.co", href: "http://www.forbes.com/sites/quora/2014/08/08/the-best-languages-for-getting-into-functional-programming/", time: "53 days ago"}, 
	{title : "How to Retain Engineering Talent", site: "tascit.co", href: "http://tascit.com/how-to-make-sure-your-engineers-dont-leave-you/", time: "7 hours ago"}, 
	{title : "Ideas about a new programming language for games", site: "youtu.b", href: "http://youtu.be/TH9VCN6UkyQ", time: "7 hours ago"}, 
	{title : "Blockchain Is Latest Bitcoin Start-Up to Lure Big Investment", site: "nytimes.co", href: "http://mobile.nytimes.com/blogs/dealbook/2014/10/06/blockchain-is-latest-bitcoin-start-up-to-lure-big-investment/", time: "23 hours ago"}, 
	{title : "The survival of filoviruses in liquids and solid substrates (2010) [pdf]", site: "wiley.co", href: "http://onlinelibrary.wiley.com/store/10.1111/j.1365-2672.2010.04778.x/asset/j.1365-2672.2010.04778.x.pdf?v=1&t=i0zca0zk&s=53088f66e93770545aa22e10843fe9bcc6bbf12c", time: "14 hours ago"}, 
	{title : "Not on a Social Network? You’ve Still Got a Privacy Problem", site: "wired.co", href: "http://www.wired.com/2014/10/privacy-friendster/", time: "1 day ago"}, 
	{title : "Why Bitcoin's price is irrelevant to its success", site: "startupmanagement.or", href: "http://startupmanagement.org/2014/10/07/why-bitcoins-price-is-irrelevant-to-its-success/", time: "8 hours ago"}, 
	{title : "Google military surveillance complex", site: "livemint.co", href: "http://www.livemint.com/Opinion/zY2dAXaXFXbXrrhHJqVX2I/WikiLeaks-and-the-Googlemilitarysurveillance-complex.html", time: "9 hours ago"}, 
	{title : "Adobe's e-book reader sends your reading logs back to Adobe-in plain text", site: "arstechnica.co", href: "http://arstechnica.com/security/2014/10/adobes-e-book-reader-sends-your-reading-logs-back-to-adobe-in-plain-text/", time: "10 hours ago"}, 
	{title : "France stages monumental cyber-attack as ‘Snowden syndrome’ takes hold", site: "vancouversun.co", href: "http://www.vancouversun.com/business/technology/France+stages+monumental+cyber+attack+Snowden/10266797/story.html?__federated=1", time: "12 hours ago"}, 
	{title : "Experience Plastc", site: "plastc.co", href: "https://www.plastc.com/", time: "14 hours ago"}, 
	{title : "Cassandra at Instagram 2014", site: "slideshare.ne", href: "http://www.slideshare.net/planetcassandra/cassandra-summit-2014-cassandra-at-instagram-2014", time: "13 hours ago"}, 
	{title : "Plastc: rewritable payment card with e-ink touchscreen", site: "plastc.co", href: "https://www.plastc.com/card", time: "15 hours ago"}, 
]