news15 = [
	{title : "Why I decided to finally give up on Google", site: "medium.co", href: "https://medium.com/@raghunayyar/why-i-decided-to-finally-give-up-on-google-3b876777040f", time: "2 days ago"}, 
	{title : "HP to split into two companies", site: "cnn.co", href: "http://money.cnn.com/2014/10/05/technology/hp-restructuring-split/index.html", time: "2 days ago"}, 
	{title : "Why nerd culture must die", site: "petewarden.co", href: "http://petewarden.com/2014/10/05/why-nerd-culture-must-die/", time: "3 days ago"}, 
	{title : "A curated list of awesome command-line frameworks, toolkits, guides and gizmos", site: "github.co", href: "https://github.com/alebcay/awesome-shell?utm_campaign=explore-email&utm_medium=email&utm_source=newsletter&utm_term=weekly", time: "7 days ago"}, 
	{title : "Real Life MMO FPS", site: "father.i", href: "http://father.io/", time: "7 days ago"}, 
	{title : "readme.io: Beautiful Documentation Made Easy", site: "readme.i", href: "http://readme.io", time: "8 days ago"}, 
	{title : "Lennart Poettering on the state of open source communities", site: "plus.google.co", href: "https://plus.google.com/+LennartPoetteringTheOneAndOnly/posts/J2TZrTvu7vd", time: "1 day ago"}, 
	{title : "10 common mistakes companies make when hiring in IT", site: "jobbox.i", href: "http://blog.jobbox.io/10-common-mistakes-companies-make-when-hiring-techies/", time: "11 days ago"}, 
	{title : "npm@2.0.0", site: "npmjs.or", href: "http://blog.npmjs.org/post/98131109725/npm-2-0-0", time: "15 days ago"}, 
	{title : "Artificial General Intelligence that plays video games: How did DeepMind do it?", site: "robohub.or", href: "http://robohub.org/artificial-general-intelligence-that-plays-atari-video-games-how-did-deepmind-do-it/", time: "12 days ago"}, 
	{title : "Square Cash", site: "square.co", href: "https://square.com/cash", time: "357 days ago"}, 
	{title : "How to Succeed in Silicon Valley Without Really Trying (YC S12)", site: "newrepublic.co", href: "http://www.newrepublic.com/article/119350/amicus-app-how-tech-investors-are-failing-due-diligence", time: "29 days ago"}, 
	{title : "GifBook – Animated GIFs as Flip Books", site: "gifbook.i", href: "https://gifbook.io", time: "1 day ago"}, 
	{title : "Humans Need Not Apply", site: "youtube.co", href: "https://www.youtube.com/watch?feature=youtu.be&v=7Pq-S557XQU", time: "2 days ago"}, 
	{title : "Learn Vim Progressively", site: "yannesposito.co", href: "http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/", time: "1135 days ago"}, 
	{title : "Uber will eventually replace all its drivers with self-driving cars", site: "theverge.co", href: "http://www.theverge.com/2014/5/28/5758734/uber-will-eventually-replace-all-its-drivers-with-self-driving-cars", time: "131 days ago"}, 
	{title : "Krugman on Bitcoin", site: "nytimes.co", href: "http://mobile.nytimes.com/blogs/krugman/2014/10/04/the-long-cryptocon/", time: "1 day ago"}, 
	{title : "Ebola in Spain: Nurse 'infected in Madrid'", site: "bbc.co", href: "http://www.bbc.com/news/world-europe-29514920", time: "1 day ago"}, 
	{title : "U.S. Law Enforcement Seeks to Halt Apple-Google Encryption of Mobile Data", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/u-s-seeks-to-reverse-apple-android-data-locking-decision.html", time: "7 days ago"}, 
	{title : "Show HN: Qbox Releases QES Elasticsearch Connector for Magento", site: "qbox.i", href: "http://blog.qbox.io/qbox-releases-qes-elasticsearch-connector-for-magento", time: "1 day ago"}, 
	{title : "HTTP Considered Unethical", site: "alexgaynor.ne", href: "https://alexgaynor.net/2014/oct/06/http-considered-unethical/", time: "1 day ago"}, 
	{title : "Show HN: Offline-docs", site: "github.co", href: "https://github.com/vvo/offline-docs", time: "1 day ago"}, 
	{title : "Understanding XOR: it's just a diff", site: "biesnecker.co", href: "http://biesnecker.com/2014/10/06/swapping-variables-with-xor/", time: "1 day ago"}, 
	{title : "Show HN: Poll – Voting done simply in real time", site: "lab.i", href: "http://poll.lab.io", time: "2 days ago"}, 
	{title : "Modern art was CIA 'weapon' in the cultural Cold War", site: "independent.co.u", href: "http://www.independent.co.uk/news/world/modern-art-was-cia-weapon-1578808.html", time: "1 day ago"}, 
	{title : "Google Is Inventing Screens That Snap Together Like Lego", site: "fastcodesign.co", href: "http://www.fastcodesign.com/3036692/fast-feed/google-is-inventing-screens-that-snap-together-like-lego?utm_source=facebook", time: "1 day ago"}, 
	{title : "New York Quickly Nixes Cellphone Tracking Devices in Phone Booths", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/06/phone-booths-get-new-life-tracking-cellphone/", time: "1 day ago"}, 
	{title : "How Facebook’s Shifting ‘Real Names’ Policy Threatens Free Expression", site: "psmag.co", href: "http://www.psmag.com/navigation/nature-and-technology/problem-facebooks-shifting-policy-using-legal-names-91723/", time: "1 day ago"}, 
]