news4 = [
	{title : "Unfinished game – learn by practice", site: "github.co", href: "https://github.com/rezoner/unfinished-asteroids", time: "1 day ago"}, 
	{title : "Detecting Algorithmically Generated Domain Names", site: "ipython.or", href: "http://nbviewer.ipython.org/github/ClickSecurity/data_hacking/blob/master/dga_detection/DGA_Domain_Detection.ipynb", time: "23 hours ago"}, 
	{title : "Node-Red, a tool for wiring together hardware devices, APIs and online services", site: "nodered.or", href: "http://nodered.org/", time: "21 hours ago"}, 
	{title : "This Holacracy Thing", site: "caswenson.co", href: "http://www.caswenson.com/2014_10_05_this_holacracy_thing", time: "5 hours ago"}, 
	{title : "A Bedtime Story", site: "stanford.ed", href: "https://alumni.stanford.edu/get/page/magazine/article/?article_id=72890", time: "21 hours ago"}, 
	{title : "MIT Economist David Autor on the Future of Work and Polanyi's Paradox", site: "econtalk.or", href: "http://www.econtalk.org/archives/2014/10/david_autor_on.html", time: "1 day ago"}, 
	{title : "The 1920 British air bombing campaign in Iraq", site: "bbc.co", href: "http://www.bbc.com/news/magazine-29441383", time: "23 hours ago"}, 
	{title : "Show HN: Rect Rangle – simple multi-player browser-based game", site: "rectrangle.co", href: "http://rectrangle.com", time: "12 hours ago"}, 
	{title : "Mnesia and CAP", site: "medium.co", href: "https://medium.com/@jlouis666/mnesia-and-cap-d2673a92850", time: "23 hours ago"}, 
	{title : "Blockchain Lands Biggest Ever Venture Funding Round in Bitcoin Industry", site: "wsj.co", href: "http://online.wsj.com/articles/blockchain-lands-biggest-ever-venture-funding-round-in-bitcoin-industry-1412687156?tesla=y", time: "15 hours ago"}, 
	{title : "The Genius ISMs", site: "genius.co", href: "http://meta.genius.com/Genius-the-genius-isms-annotated", time: "10 hours ago"}, 
	{title : "Reddit Gives Remote Employees Until End of Year to Relocate to San Francisco", site: "fastcompany.co", href: "http://www.fastcompany.com/3036660/fast-feed/reddit-gives-remote-employees-until-end-of-year-to-relocate-to-san-francisco", time: "3 hours ago"}, 
	{title : "The Buried: Excavating the Egyptian Revolution (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/11/18/the-buried", time: "8 hours ago"}, 
	{title : "MONIAC Computer", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/MONIAC_Computer", time: "10 hours ago"}, 
	{title : "Homebrew dome projector for planetarium using two stock lenses", site: "astrosurf.co", href: "http://www.astrosurf.com/lhoumeau/planetariums/en/", time: "8 hours ago"}, 
	{title : "The Man Who Was Buried Twice", site: "theappendix.ne", href: "http://theappendix.net/issues/2014/10/the-man-who-was-buried-twice", time: "13 hours ago"}, 
	{title : "On-Line Man-Computer Communication (1962) [pdf]", site: "msjc.ed", href: "http://cis.msjc.edu/courses/internet_authoring/CSIS103/resources/ON-LINE%20MAN-COMPUTER%20COMMUNICATION.pdf", time: "14 hours ago"}, 
	{title : "BuildZoom (YC W13) crunches data to pick home improvement contractors", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/06/with-a-fresh-2-15m-buildzoom-crunches-data-to-pick-the-best-home-improvement-contractors/", time: "11 hours ago"}, 
	{title : "Slow is not a dirty word", site: "jamesvandyne.co", href: "http://www.jamesvandyne.com/slow-is-not-a-dirty-word/", time: "15 hours ago"}, 
	{title : "Why the “Big Billion Day” might be the worst mistake that Flipkart has committed", site: "aawaara.co", href: "http://aawaara.com/post/99437174657/why-the-big-billion-day-might-be-the-worst-mistake", time: "6 hours ago"}, 
	{title : "Drug cheats in sport could benefit 'for decades', scientists find", site: "bbc.co", href: "http://www.bbc.com/sport/0/athletics/29510575", time: "22 hours ago"}, 
	{title : "Big Banks Face Another Round of U.S. Charges", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/06/big-banks-face-another-round-of-u-s-charges/?_php=true&_type=blogs&_r=0", time: "13 hours ago"}, 
	{title : "Bitcoin is not compatible with the State", site: "oleganza.co", href: "http://blog.oleganza.com/post/93767945708/bitcoin-is-not-compatible-with-the-state", time: "2 hours ago"}, 
	{title : "Massive Moniker.com Breach, Valuable Domains Stolen", site: "dotweekly.co", href: "http://dotweekly.com/massive-moniker-com-breach-valuable-domains-stolen/", time: "16 hours ago"}, 
	{title : "Privacy vs. User Experience", site: "dcurt.i", href: "http://dcurt.is/privacy-vs-user-experience", time: "6 hours ago"}, 
	{title : "Scala – The good, the bad and the very ugly", site: "slideshare.ne", href: "http://www.slideshare.net/Bozho/scala-the-good-the-bad-and-the-very-ugly", time: "20 hours ago"}, 
	{title : "Why do we keep repeating the Milgram experiments?", site: "aeon.c", href: "http://aeon.co/magazine/psychology/why-do-we-keep-repeating-the-milgram-experiments", time: "19 hours ago"}, 
	{title : "Show HN: Tamper – Devtools extension. Edit remote files locally", site: "dutzi.github.i", href: "http://dutzi.github.io/tamper/", time: "11 hours ago"}, 
	{title : "Let's Build Google Alerts for HN on the New API, Together", site: "assembly.co", href: "https://assembly.com/hn-monitor", time: "9 hours ago"}, 
]