news24 = [
	{title : "Sex for the pleasure of women: The amazing heroes behind inventing the Pill", site: "salon.co", href: "http://www.salon.com/2014/10/04/sex_for_the_pleasure_of_women_the_amazing_heroes_behind_the_invention_of_the_pill/", time: "2 days ago"}, 
	{title : "The Bézier Game", site: "method.a", href: "http://bezier.method.ac/", time: "22 days ago"}, 
	{title : "Dispatch from Worldcon", site: "nplusonemag.co", href: "https://nplusonemag.com/online-only/online-only/dispatch-from-worldcon/", time: "6 days ago"}, 
	{title : "Idiomatic Generics in Go", site: "bouk.c", href: "http://bouk.co/blog/idiomatic-generics-in-go/", time: "7 days ago"}, 
	{title : "Introducing the Gartner Programming Language Index for 2014", site: "gartner.co", href: "http://blogs.gartner.com/mark_driver/2014/10/02/gartner-programming-language-index-for-2014/", time: "3 days ago"}, 
	{title : "Hiring a Startup Lawyer", site: "adlervermillion.co", href: "http://adlervermillion.com/tech-law-link-list-hiring-lawyers/", time: "21 days ago"}, 
	{title : "THANKS HN! How Hacker News + Product Hunt Fueled 300,000 Views in 30 Days", site: "medium.co", href: "https://medium.com/@jadlimcaco/an-overnight-success-660739c2a7e9", time: "4 days ago"}, 
	{title : "Y Combinator and the Negative Externalities of Hackernews", site: "danilocampos.co", href: "http://danilocampos.com/2014/09/y-combinator-and-the-negative-externalities-of-hacker-news/", time: "7 days ago"}, 
	{title : "Three Words Entrepreneurs (and VC’s) Should Take to Heart", site: "bothsidesofthetable.co", href: "http://www.bothsidesofthetable.com/2014/10/05/three-words-every-entrepreneur-and-vc-should-take-to-heart/", time: "2 days ago"}, 
	{title : "What I Learned from My Time in Prison", site: "dailystormer.co", href: "http://www.dailystormer.com/what-i-learned-from-my-time-in-prison/", time: "5 days ago"}, 
	{title : "FinFisher Malware Dropper Analysis", site: "codeandsec.co", href: "https://www.codeandsec.com/FinFisher-Malware-Dropper-Analysis", time: "17 days ago"}, 
	{title : "Monit issues DMCA takedown against Mike Perham's open source Inspeqtor project", site: "github.co", href: "https://github.com/github/dmca/commit/e8e7a27dd17ad6fe8d53fbb8f6084b560b2d3a29", time: "1 day ago"}, 
	{title : "Toshi – An Open Source Bitcoin Node for Developers", site: "coinbase.co", href: "http://blog.coinbase.com/post/97671295752/introducing-toshi-an-open-source-bitcoin-node-for", time: "21 days ago"}, 
	{title : "Is Overleaf the Wordpress for LaTeX?", site: "writelatex.co", href: "https://www.writelatex.com/overleaf", time: "5 days ago"}, 
	{title : "The Eudyptula Challenge", site: "eudyptula-challenge.or", href: "http://eudyptula-challenge.org", time: "1 day ago"}, 
	{title : "How do project owners use pull requests on GitHub?", site: "gousios.g", href: "http://www.gousios.gr/blog/How-do-project-owners-use-pull-requests-on-Github/", time: "4 days ago"}, 
	{title : "Ello, goodbye", site: "aralbalkan.co", href: "https://aralbalkan.com/notes/ello-goodbye/", time: "11 days ago"}, 
	{title : "Tilde.club", site: "tilde.clu", href: "http://tilde.club/", time: "4 days ago"}, 
	{title : "Microservices for the Grumpy Neckbeard", site: "chrisstucchio.co", href: "http://www.chrisstucchio.com/blog/2014/microservices_for_the_grumpy_neckbeard.html", time: "42 days ago"}, 
	{title : "Nobel Prize for the brain's GPS discovery", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/health-29504761", time: "1 day ago"}, 
	{title : "Ban travelers from Ebola-ravaged countries?", site: "washingtonpost.co", href: "http://www.washingtonpost.com/news/to-your-health/wp/2014/10/01/why-hasnt-the-u-s-closed-its-airports-to-travelers-from-ebola-ravaged-countries/", time: "6 days ago"}, 
	{title : "The Crow and the Cave Dweller", site: "medium.co", href: "https://medium.com/@aaronmentele/the-crow-and-the-cave-dweller-b230cc750694", time: "5 days ago"}, 
	{title : "The end of neighbours", site: "macleans.c", href: "http://www.macleans.ca/society/the-end-of-neighbours/", time: "57 days ago"}, 
	{title : "Bill Gates's Favorite Business Book", site: "wsj.co", href: "http://online.wsj.com/articles/bill-gatess-favorite-business-book-1405088228", time: "88 days ago"}, 
	{title : "Reddit’s crappy ultimatum to remote workers and offices", site: "shortlogic.tumblr.co", href: "http://shortlogic.tumblr.com/post/99014759324/reddits-crappy-ultimatum", time: "5 days ago"}, 
	{title : "Productising a Service Business (Part 1)", site: "theprocedurepeople.co", href: "http://www.theprocedurepeople.com/blog/2014/09/22/productising-a-service-business-part-one-separating-capabilities-from-products/", time: "15 days ago"}, 
	{title : "Stop the Spies – Campaign against mass surveillance down under (Australia)", site: "stopthespies.or", href: "https://stopthespies.org", time: "41 days ago"}, 
	{title : "Learn Lua in 15 Minutes", site: "tylerneylon.co", href: "http://tylerneylon.com/a/learn-lua/", time: "470 days ago"}, 
	{title : "A war game that actually feels like being in a war", site: "polygon.co", href: "http://www.polygon.com/2014/9/3/6098005/this-war-of-mine-actually-feels-like-being-in-a-war", time: "34 days ago"}, 
	{title : "PyCA's Cryptography library", site: "cryptography.i", href: "https://cryptography.io/en/latest/", time: "102 days ago"}, 
]