news28 = [
	{title : "With Dry Taps and Toilets, California Drought Turns Desperate", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/california-drought-tulare-county.html?smid=tw-share", time: "5 days ago"}, 
	{title : "To catch a gravitational wave", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/october-2014/to-catch-a-gravitational-wave", time: "3 days ago"}, 
	{title : "Bash bug: the other two RCEs, or how we chipped away at the original fix", site: "lcamtuf.blogspot.co", href: "http://lcamtuf.blogspot.com/2014/10/bash-bug-how-we-finally-cracked.html", time: "6 days ago"}, 
	{title : "Show HN: M.py: inline and minify all CSS and JavaScript references in your HTML", site: "github.co", href: "https://github.com/nate-parrott/m.py", time: "3 days ago"}, 
	{title : "This American Life tries to turn its radio audience onto podcasting", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/this-american-life-tries-to-turn-its-radio-audience-onto-podcasting-with-its-new-show-serial/", time: "3 days ago"}, 
	{title : "Using Alchemy's semantic analysis function with Go to process Twitter data", site: "drshrey.github.i", href: "http://drshrey.github.io/jekyll/update/natural-language-processing/golang/2014/09/18/writing-my-first-nlp-app.html", time: "3 days ago"}, 
	{title : "Bang – An Atari 2600 VCS Demo", site: "xayax.ne", href: "http://xayax.net/bang!/", time: "4 days ago"}, 
	{title : "Lecture 1 – How to Start a Startup [video]", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec01/", time: "14 days ago"}, 
	{title : "Kimono Labs (YC W14) Hackathon This Weekend--win a BTC", site: "kimonolabs.co", href: "https://www.kimonolabs.com/hacks", time: "3 days ago"}, 
	{title : "In Colorado, a Rebranding of Pot Inc.", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/fashion/in-colorado-a-rebranding-of-pot-inc-marijuana.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "3 days ago"}, 
	{title : "Show HN: Dependency Update as a Service", site: "tachikoma.i", href: "http://tachikoma.io/", time: "3 days ago"}, 
	{title : "Best Papers vs. Top Cited Papers in Computer Science", site: "arnetminer.or", href: "http://arnetminer.org/conferencebestpapers", time: "6 days ago"}, 
	{title : "A State of Xen – Chaos Monkey and Cassandra", site: "netflix.co", href: "http://techblog.netflix.com/2014/10/a-state-of-xen-chaos-monkey-cassandra.html", time: "5 days ago"}, 
	{title : "Schneier on Incident Response", site: "lwn.ne", href: "http://lwn.net/Articles/612818/", time: "3 days ago"}, 
	{title : "How to get every game on STEAM for free", site: "gamasutra.co", href: "http://www.gamasutra.com/blogs/LeszekLisowski/20141001/226840/How_to_get_every_game_on_STEAM_for_free.php", time: "3 days ago"}, 
	{title : "Colleges Make It Easier for Students to Show, Not Tell, in Their Applications", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/28/education/college-admissions-goucher-video.html", time: "3 days ago"}, 
	{title : "William Binney Explains Snowden Docs", site: "alexaobrien.co", href: "http://www.alexaobrien.com/secondsight/wb/binney.html", time: "7 days ago"}, 
	{title : "National Nurse Survey Shows Hospitals Still Not Prepared for U.S. Ebola Patients", site: "nationalnursesunited.or", href: "http://www.nationalnursesunited.org/press/entry/national-nurse-survey-shows-hospitals-still-not-prepared-for-us-ebola/", time: "3 days ago"}, 
	{title : "Show HN: Franc – Detect natural languages", site: "github.co", href: "https://github.com/wooorm/franc", time: "4 days ago"}, 
	{title : "Aids: Origin of pandemic 'was 1920s Kinshasa'", site: "bbc.co", href: "http://www.bbc.com/news/health-29442642", time: "4 days ago"}, 
	{title : "Show HN: The Wide Language Index", site: "widelanguageindex.or", href: "http://widelanguageindex.org/", time: "3 days ago"}, 
	{title : "The next generation storage engine for Couchbase Server: ForestDB", site: "couchbase.co", href: "http://blog.couchbase.com/next-generation-storage-engine-couchbase-server-and-couchbase-lite-forestdb-now-available-beta", time: "2 days ago"}, 
	{title : "Aboard a Cargo Colossus: Maersk’s New Container Ships", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/business/international/aboard-a-cargo-colossus-maersks-new-container-ships.html?hp&action=click&pgtype=Homepage&version=HpSumSmallMediaHigh&module=second-column-region&region=top-news&WT.nav=top-news&_r=0", time: "4 days ago"}, 
	{title : "Arduino LED Startup Counter", site: "matthack.co", href: "http://matthack.com/startup-counter/", time: "3 days ago"}, 
	{title : "A Plan to Use Survivors’ Blood for Ebola Treatment in Africa", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/health/use-of-ebola-survivors-blood-as-possible-treatment-gains-support.html?ref=science", time: "3 days ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage", time: "3 days ago"}, 
	{title : "Pace4000 hidden testing modes", site: "sodnpoo.co", href: "http://www.sodnpoo.com/posts.xml/pace4000_testing_modes.xml", time: "3 days ago"}, 
]