news9 = [
	{title : "Texas Contacts 100, Citing Possible Links to Ebola Patient", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/03/us/dallas-ebola-case-thomas-duncan-contacts.html?_r=0", time: "20 hours ago"}, 
	{title : "Systems of Logic Based on Ordinals (1938) [pdf]", site: "rinceton.ed", href: "https://webspace.princeton.edu/users/jedwards/Turing%20Centennial%202012/Mudd%20Archive%20files/12285_AC100_Turing_1938.pdf", time: "2 days ago"}, 
	{title : "A Path to Full-time Open Source", site: "ikeperham.co", href: "http://www.mikeperham.com/2014/10/01/the-path-to-full-time-open-source/", time: "2 days ago"}, 
	{title : "Show HN: All available three letter .io domains", site: "dward.i", href: "http://edward.io/io", time: "1 day ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "outube.co", href: "https://www.youtube.com/watch?v=yP176MBG9Tk", time: "17 hours ago"}, 
	{title : "Zentail.com (YC S12) Now Accepts Bitcoin", site: "eddit.co", href: "http://www.reddit.com/r/Bitcoin/comments/2i3ssd/zentailcom_now_accepts_bitcoin/", time: "22 hours ago"}, 
	{title : "Elon Musk: Tesla 90% autonomous in 2015", site: "outube.co", href: "https://www.youtube.com/watch?v=EJmhpgW0Dmc", time: "19 hours ago"}, 
	{title : "Losing the sense of smell predicts death within five years", site: "heguardian.co", href: "http://www.theguardian.com/science/neurophilosophy/2014/oct/01/your-nose-knows-death-is-imminent", time: "1 day ago"}, 
	{title : "‘The Innovators’ by Walter Isaacson: How Women Shaped Technology", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/02/fashion/the-innovators-by-walter-isaacson-how-women-shaped-technology.html?_r=1", time: "1 day ago"}, 
	{title : "Joshua Wong: the teenager who is the public face of the Hong Kong protests", site: "heguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/joshua-wong-teenager-public-face-hong-kong-protests", time: "17 hours ago"}, 
	{title : "Cassini Watches Mysterious Feature Evolve in Titan Sea", site: "asa.go", href: "http://www.nasa.gov/jpl/cassini/cassini-watches-mysterious-feature-evolve-in-titan-sea/", time: "2 days ago"}, 
	{title : "Cyanogen refuses Google's money in an effort to keep Android 'open'", site: "ngadget.co", href: "http://www.engadget.com/2014/10/02/cyanogen-refuses-google/", time: "17 hours ago"}, 
	{title : "Show HN: TypeWonder – Test web fonts on any site on the fly", site: "ypewonder.co", href: "http://typewonder.com/", time: "2 days ago"}, 
	{title : "Facebook Promises a Deeper Review of Its User Research", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/03/technology/facebook-promises-a-deeper-review-of-its-user-research.html", time: "21 hours ago"}, 
	{title : "Google Project Zero: More Mac OS X and iPhone Sandbox Escapes", site: "oogleprojectzero.blogspot.co", href: "http://googleprojectzero.blogspot.com/2014/10/more-mac-os-x-and-iphone-sandbox.html", time: "1 day ago"}, 
	{title : "Drop Caps Are Beautiful", site: "dobe.co", href: "http://blogs.adobe.com/webplatform/2014/10/02/drop-caps-are-beautiful/", time: "19 hours ago"}, 
	{title : "Matchstick Brings Firefox OS to Your HDTV", site: "ozilla.or", href: "https://hacks.mozilla.org/2014/09/matchstick-brings-firefox-os-to-your-hdtv-be-the-first-to-get-a-developer-stick/", time: "3 days ago"}, 
	{title : "NASA found a mysterious rectangular shape on the moon", site: "ciencemag.or", href: "http://news.sciencemag.org/space/2014/10/ancient-magma-plumbing-found-buried-below-moons-largest-dark-spot", time: "18 hours ago"}, 
	{title : "Parenting as a Gen Xer: The 1st generation of parents in the age of iEverything", site: "ashingtonpost.co", href: "http://www.washingtonpost.com/news/parenting/wp/2014/09/29/parenting-as-a-gen-xer-what-its-like-to-be-the-first-generation-of-parents-in-the-age-of-ieverything/", time: "20 hours ago"}, 
	{title : "Visualizing and Understanding Convolutional Networks", site: "rxiv.or", href: "http://arxiv.org/abs/1311.2901", time: "1 day ago"}, 
	{title : "J.P. Morgan Says About 76M Households Affected by Cyber Breach", site: "arketwatch.co", href: "http://www.marketwatch.com/story/jp-morgan-says-about-76-million-households-affected-by-cyber-breach-2014-10-02-17103316", time: "18 hours ago"}, 
	{title : "Recruiter Trolling on GitHub", site: "ithub.co", href: "https://github.com/thoughtbot/liftoff/pull/178#issuecomment-57688590", time: "18 hours ago"}, 
	{title : "Show HN: Crowdsourced Summaries of Facebook's Human-Subjects Research", site: "auvik.m", href: "https://experiment.sauvik.me/", time: "1 day ago"}, 
	{title : "AT", site: "cker invoices Justice Dept. for time spent in federal pri", href: "http://rt.com/usa/160216-weev-invoice-fed-bitcoin/", time: "20 hours ago"}, 
	{title : "Moving to Sublime 3 after 15 yrs with TextPad – reasons, comparisons, and tips", site: "literalmind.wordpress.co", href: "http://aliteralmind.wordpress.com/2014/10/02/textpad_to_sublime/", time: "21 hours ago"}, 
	{title : "JPMorgan Data Break", site: "ashable.co", href: "http://mashable.com/2014/10/02/jp-morgan-chase-breach/?utm_campaign=Feed%3A+Mashable+%28Mashable%29&utm_cid=Mash-Prod-RSS-Feedburner-All-Partial&utm_medium=feed&utm_source=feedburner", time: "18 hours ago"}, 
	{title : "Sense of smell 'may predict lifespan'", site: "bc.co", href: "http://www.bbc.com/news/health-29441323", time: "1 day ago"}, 
	{title : "How We Use AWS, Ansible, and Packer to Make Deployment Awesome", site: "ranchmetrics.i", href: "http://branchmetrics.io/blog/2014/09/19/how-we-deploy/", time: "1 day ago"}, 
	{title : "Elon Musk says next year's Tesla cars will be able to self-drive 90% of the time", site: "heverge.co", href: "http://www.theverge.com/2014/10/2/6894875/elon-musk-says-next-years-tesla-cars-will-be-able-to-self-drive-90-percent-of-the-time", time: "20 hours ago"}, 
	{title : "Startup Burn Rates: A Game of High Stakes Poker", site: "edium.co", href: "https://medium.com/@clarencewooten/startup-burn-rates-a0a36f2375c9", time: "21 hours ago"}, 
]