news8 = [
	{title : "History of T", site: "aulgraham.co", href: "http://www.paulgraham.com/thist.html", time: "315 days ago"}, 
	{title : "The trajectory of a software engineer… and where it all goes wrong.", site: "ichaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "194 days ago"}, 
	{title : "The Cult of Done Manifesto", site: "repettis.co", href: "http://www.brepettis.com/blog/2009/3/3/the-cult-of-done-manifesto.html", time: "1960 days ago"}, 
	{title : "Google threatened with lawsuit over nude celebrity photos", site: "heguardian.co", href: "http://www.theguardian.com/technology/2014/oct/02/google-lawsuit-nude-celebrity-photos", time: "18 hours ago"}, 
	{title : "Reddit Forces Remote Workers to Live in San Francisco or Lose Job", site: "bslocal.co", href: "http://sanfrancisco.cbslocal.com/2014/10/02/reddit-forcing-remote-workers-to-move-to-san-francisco-or-lose-job-tech-employee-fired-termination-relocate/", time: "13 hours ago"}, 
	{title : "Butterfly Labs mined Bitcoins on customers’ boxes before shipping", site: "rstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/feds-butterfly-labs-mined-bitcoins-on-customers-boxes-before-shipping/", time: "3 days ago"}, 
	{title : "How History Forgot Its Role in Public Debate", site: "eon.c", href: "http://aeon.co/magazine/society/how-history-forgot-its-role-in-public-debate/", time: "23 hours ago"}, 
	{title : "Python REPL with syntax highlighting, autocomplete and multiline editing", site: "ithub.co", href: "https://github.com/jonathanslenders/python-prompt-toolkit", time: "3 days ago"}, 
	{title : "Raw data from rDNS scan of the whole v4 Internet (2011)", site: "rchive.or", href: "https://archive.org/details/mass-rdns-2011-02", time: "22 hours ago"}, 
	{title : "Ken Silverman's PND3D engine", site: "dvsys.ne", href: "http://advsys.net/ken/voxlap/pnd3d.htm", time: "1 day ago"}, 
	{title : "The Evolution of Sleep: 700M Years of Melatonin", site: "ytimes.co", href: "http://nytimes.com/2014/10/02/science/the-evolution-of-sleep-700-million-years-of-melatonin.html?_r=0&referrer=", time: "20 hours ago"}, 
	{title : "“A Tesla car next year will probably be 90 percent capable of autopilot.”", site: "enturebeat.co", href: "http://venturebeat.com/2014/10/02/elon-musk-tesla-will-be-90-automated-next-year-shame-on-silicon-valley-if-were-not-the-leader/", time: "18 hours ago"}, 
	{title : "Silk Road Lawyers Poke Holes in FBI’s Story", site: "rebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/silk-road-lawyers-poke-holes-in-fbis-story/", time: "16 hours ago"}, 
	{title : "A Danish company is building a $335M seawall around New York", site: "heverge.co", href: "http://www.theverge.com/2014/10/1/6874925/can-a-massive-seawall-save-new-york-from-flooding", time: "1 day ago"}, 
	{title : "Online Linear Regression Using a Kalman Filter", site: "healgoengineer.co", href: "http://www.thealgoengineer.com/2014/online_linear_regression_kalman_filter/", time: "23 hours ago"}, 
	{title : "Police Used a Drone to Chase Down and Arrest Four DUI Suspects in a Cornfield", site: "ice.co", href: "http://motherboard.vice.com/read/police-used-a-drone-to-chase-down-and-arrest-four-dui-suspects-in-a-cornfield", time: "21 hours ago"}, 
	{title : "SyncFree Consortium / Programming Models, Part 2: QuickChecking Derflow", site: "hristophermeiklejohn.co", href: "http://christophermeiklejohn.com/derflow/erlang/2014/10/01/quickchecking-derflow.html", time: "1 day ago"}, 
	{title : "Council removes Banksy artwork after complaints of racism", site: "heguardian.co", href: "http://www.theguardian.com/artanddesign/2014/oct/01/banksy-mural-clacton-racist", time: "12 hours ago"}, 
	{title : "A Nomic game in Haskell", site: "omyx.ne", href: "http://www.nomyx.net/", time: "1 day ago"}, 
	{title : "At 17, Setting Off Protests That Roil Hong Kong", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/02/world/asia/hong-kong-china-democracy-protests-students.html", time: "23 hours ago"}, 
	{title : "MemSQL Does Oracle’s Own Demo Ten Times as Fast, Sixty Times Cheaper", site: "emsql.co", href: "http://blog.memsql.com/memsql-does-oracles-own-demo-ten-times-as-fast-sixty-times-cheaper/", time: "1 day ago"}, 
	{title : "Hopscotch: Towards User Interface Composition (2008) [pdf]", site: "racha.or", href: "http://bracha.org/hopscotch-wasdett.pdf", time: "21 hours ago"}, 
	{title : "Ello Says You're Not a Product, but You Are – The Atlantic", site: "heatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/09/ello-says-youre-not-a-product-but-you-are/380809/", time: "15 hours ago"}, 
	{title : "After 31 years, Lotus-1-2-3 spreadsheet support has ended", site: "dnet.co", href: "http://www.zdnet.com/so-farewell-then-lotus-1-2-3-spreadsheet-extraordinaire-7000034288/", time: "16 hours ago"}, 
	{title : "Google reportedly tried to buy Cyanogen", site: "rstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/google-reportedly-tried-to-buy-cyanogen-inc/", time: "17 hours ago"}, 
	{title : "Extensible Web Resource Loading Manifesto", site: "gvita.co", href: "https://www.igvita.com/2014/10/02/extensible-web-resource-loading-manifesto/", time: "21 hours ago"}, 
	{title : "Research at Facebook", site: "b.co", href: "http://newsroom.fb.com/news/2014/10/research-at-facebook/", time: "22 hours ago"}, 
	{title : "The Quiet Zone: No wifi or cell phone service for 13,000 sq. miles", site: "ikipedia.or", href: "http://en.wikipedia.org/wiki/United_States_National_Radio_Quiet_Zone", time: "16 hours ago"}, 
]