news11 = [
	{title : "Holy Grail", site: "ikipedia.or", href: "http://en.wikipedia.org/wiki/Holy_Grail_(web_design)", time: "17 hours ago"}, 
	{title : "Farewell CoffeeScript", site: "ithub.co", href: "https://github.com/staltz/rxmarbles/commit/57e37f176e0e005abd2c4fa0253bbd8f57fe1bd9", time: "1 day ago"}, 
	{title : "Adaptive Path: Where We’re Going Next", site: "daptivepath.co", href: "http://www.adaptivepath.com/ideas/adaptive-path-where-were-going-next/", time: "20 hours ago"}, 
	{title : "OpenWrt BarrierBreaker 14.07", site: "penwrt.or", href: "https://forum.openwrt.org/viewtopic.php?pid=242292#p242292", time: "1 day ago"}, 
	{title : "Bash bug: the other two RCEs, or how we chipped away at the original fix", site: "camtuf.blogspot.co", href: "http://lcamtuf.blogspot.com/2014/10/bash-bug-how-we-finally-cracked.html", time: "2 days ago"}, 
	{title : "Design for Assembly in KiCad", site: "heingoldheavy.co", href: "http://rheingoldheavy.com/design-assembly-kicad/", time: "1 day ago"}, 
	{title : "C++11/14 compiler and library shootout", site: "pprocks.co", href: "http://cpprocks.com/c1114-compiler-and-library-shootout/", time: "1 day ago"}, 
	{title : "Declassified photos from Tinian Island as the B-29 “Enola Gay” was being loaded", site: "rchive.toda", href: "https://archive.today/94EKG", time: "3 days ago"}, 
	{title : "The Downtown Project Suicides", site: "ecode.ne", href: "http://recode.net/2014/10/01/the-downtown-project-suicides-can-the-pursuit-of-happiness-kill-you/", time: "1 day ago"}, 
	{title : "Moscone Effect: What Dreamforce and Big Conferences Mean for Airbnb", site: "eyondpricing.co", href: "https://blog.beyondpricing.com/the-moscone-effect?rel=hn", time: "22 hours ago"}, 
	{title : "Lever (YC S12) raises $10M to make hiring awesome", site: "ever.c", href: "https://blog.lever.co/the-next-chapter/", time: "22 hours ago"}, 
	{title : "EC2 Maintenance Update II", site: "mazon.co", href: "http://aws.amazon.com/blogs/aws/ec2-maintenance-update-2/", time: "2 days ago"}, 
	{title : "Dart and Internet Explorer", site: "servoice.co", href: "http://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6511262-add-the-dart-vm", time: "21 hours ago"}, 
	{title : "Groove Deletes Their Facebook Page", site: "roovehq.co", href: "http://www.groovehq.com/blog/focus", time: "1 day ago"}, 
	{title : "Show HN: QDB, a remote python debugger", site: "ithub.co", href: "https://github.com/quantopian/qdb", time: "2 days ago"}, 
	{title : "Work Habits at Apple", site: "leb.ne", href: "http://oleb.net/blog/2014/09/work-habits-at-apple/", time: "2 days ago"}, 
	{title : "A Sea Story (2004)", site: "heatlantic.co", href: "http://www.theatlantic.com/magazine/archive/2004/05/a-sea-story/302940/?single_page=true#show-last-Point", time: "1 day ago"}, 
	{title : "Join the Computing for Ebola Challenge Hackathon", site: "ackerleague.or", href: "https://www.hackerleague.org/hackathons/computing-for-ebola-challenge", time: "1 day ago"}, 
	{title : "Islamic State Social Media Strangely Silent Since Strikes", site: "ice.co", href: "http://motherboard.vice.com/en_ca/read/the-islamic-state-has-been-quieter-online-after-us-air-strikes", time: "1 day ago"}, 
	{title : "Tesla to unveil D and other product on October 9th", site: "witter.co", href: "https://twitter.com/elonmusk/status/517486950589014016", time: "1 day ago"}, 
	{title : "Open-source client scaffolds and API pricing", site: "nboxapp.co", href: "https://www.inboxapp.com/blog/clients-and-pricing", time: "2 days ago"}, 
	{title : "API Docs for URX's Deeplink Search Engine", site: "rx.co", href: "http://developers.urx.com/", time: "3 days ago"}, 
	{title : "Technical analysis of client identification mechanisms", site: "hromium.or", href: "http://www.chromium.org/Home/chromium-security/client-identification-mechanisms", time: "6 days ago"}, 
	{title : "Sile, a typesetting system inspired by TeX and InDesign", site: "ile-typesetter.or", href: "http://www.sile-typesetter.org/what-is/index.html", time: "2 days ago"}, 
	{title : "Show HN: Open source, JavaScript game", site: "eerasundar.co", href: "http://veerasundar.com/suzhi/?hn", time: "23 hours ago"}, 
	{title : "The Sound So Loud That It Circled the Earth Four Times", site: "autil.u", href: "http://nautil.us/blog/the-sound-so-loud-that-it-circled-the-earth-four-times", time: "4 days ago"}, 
	{title : "Inside Shellshock: How hackers are using it to exploit systems", site: "loudflare.co", href: "https://blog.cloudflare.com/inside-shellshock/", time: "2 days ago"}, 
	{title : "Reddit Plans Cryptocurrency to Give Back to Its Users After $50M Raise", site: "echcrunch.co", href: "http://techcrunch.com/2014/09/30/reddit-scoops-up-50m-series-b-from-sam-altman-a16z-sequoia-at-500m-valuation/?ncid=rss", time: "2 days ago"}, 
]