news3 = [
	{title : "“Not” Neutrality?", site: "evel3.co", href: "http://blog.level3.com/open-internet/not-neutrality/", time: "1 day ago"}, 
	{title : "How does SQLite work? Part 2: disk seeks are slow don't do them", site: "vns.c", href: "http://jvns.ca/blog/2014/10/02/how-does-sqlite-work-part-2-btrees/", time: "12 hours ago"}, 
	{title : "Against Empathy", site: "ostonreview.ne", href: "http://bostonreview.net/forum/paul-bloom-against-empathy", time: "1 day ago"}, 
	{title : "Facebook plots first steps into healthcare", site: "euters.co", href: "http://www.reuters.com/article/2014/10/03/us-facebook-health-idUSKCN0HS09720141003", time: "9 hours ago"}, 
	{title : "A possible future for PHP", site: "arlitschek.d", href: "http://karlitschek.de/2014/10/a-possible-future-for-php/", time: "1 day ago"}, 
	{title : "Reddit requiring remote office, WFH employees to move to SF or lose their jobs", site: "bcbayarea.co", href: "http://www.nbcbayarea.com/news/local/Reddit-Criticized-On-Reddit-For-Requiring-Workers-To-Move-to-SF--277930941.html", time: "1 hour ago"}, 
	{title : "Seen a font in use and want to know what it is?", site: "yfonts.co", href: "https://www.myfonts.com/WhatTheFont/?", time: "21 hours ago"}, 
	{title : "Making Fast-Paced Multiplayer Networked Games Is Hard", site: "amasutra.co", href: "http://www.gamasutra.com/blogs/MarkMennell/20140929/226628/Making_FastPaced_Multiplayer_Networked_Games_is_Hard.php", time: "1 day ago"}, 
	{title : "Inspeqtor: easy application infrastructure monitoring", site: "ikeperham.co", href: "http://www.mikeperham.com/2014/10/02/introducing-inspeqtor/", time: "1 day ago"}, 
	{title : "Apple Pay: An in-depth look at what's behind the secure payment system", site: "uaw.co", href: "http://www.tuaw.com/2014/10/02/apple-pay-an-in-depth-look-at-whats-behind-the-secure-payment/", time: "20 hours ago"}, 
	{title : "Why They Called It the Manhattan Project (2007)", site: "ytimes.co", href: "http://www.nytimes.com/2007/10/30/science/30manh.html?pagewanted=all", time: "1 day ago"}, 
	{title : "Founder Suicides", site: "eld.co", href: "http://www.feld.com/archives/2014/10/founder-suicides.html", time: "12 hours ago"}, 
	{title : "Logstalgia: website access log visualization", site: "ode.google.co", href: "https://code.google.com/p/logstalgia/", time: "1 day ago"}, 
	{title : "Looking for help improving performance of GNU Make", site: "nu.or", href: "http://lists.gnu.org/archive/html/help-make/2014-10/msg00000.html", time: "1 day ago"}, 
	{title : "SSHARK – DNS-based expiration and revocation of SSH client keys", site: "shark.or", href: "http://www.sshark.org/", time: "17 hours ago"}, 
	{title : "Cumulus Linux – first impressions", site: "acketlife.ne", href: "http://packetlife.net/blog/2014/oct/1/cumulus-linux-first-impressions/", time: "1 day ago"}, 
	{title : "XSA-108 Advisory", site: "en.or", href: "http://xenbits.xen.org/xsa/advisory-108.html", time: "2 days ago"}, 
	{title : "Three Years on Rikers Without Trial", site: "ewyorker.co", href: "http://www.newyorker.com/magazine/2014/10/06/law-3", time: "17 hours ago"}, 
	{title : "Tarana Wireless: connecting the last-mile with non-line-of-sight wireless", site: "aranawireless.co", href: "http://www.taranawireless.com", time: "22 hours ago"}, 
	{title : "A re-enactment of a 1967 animal movement simulator", site: "tiennebenson.co", href: "http://www.etiennebenson.com/simplot/", time: "11 hours ago"}, 
	{title : "Korea begins commercialized LTE service based on IPv6", site: "howired.co", href: "http://www.whowired.com/news/articleView.html?idxno=404401", time: "1 day ago"}, 
	{title : "Reducing Infrustration: smooth delivery with immutable infrastructure", site: "adify.i", href: "http://radify.io/blog/reducing-infrustration", time: "2 hours ago"}, 
	{title : "Germany’s great tuition fees U-turn", site: "imeshighereducation.co.u", href: "http://www.timeshighereducation.co.uk/features/feature-germanys-great-tuition-fees-u-turn/2011168.fullarticle", time: "2 days ago"}, 
	{title : "Chickens have gotten ridiculously large since the 1950s", site: "ox.co", href: "http://www.vox.com/xpress/2014/10/2/6875031/chickens-breeding-farming-boilers-giant", time: "2 hours ago"}, 
	{title : "Bye Bye JavaScript Promises", site: "riku.or", href: "http://sriku.org/blog/2014/02/11/bye-bye-js-promises/", time: "1 day ago"}, 
	{title : "The Researcher's Bible (1985)", site: "d.ac.u", href: "http://homepages.inf.ed.ac.uk/bundy/how-tos/resbible.html", time: "1 day ago"}, 
	{title : "Maaxi app aims to help black cabs counter rise of Uber", site: "bc.co.u", href: "http://www.bbc.co.uk/news/technology-29458897", time: "8 hours ago"}, 
	{title : "An Overview of General Performance Metrics of Binary Classifier Systems [pdf]", site: "ebastianraschka.co", href: "http://sebastianraschka.com/PDFs/articles/performance_metrics.pdf", time: "14 hours ago"}, 
	{title : "Reddit", site: "amaltman.co", href: "http://blog.samaltman.com/reddit", time: "2 days ago"}, 
]