news16 = [
	{title : "The very laws of physics imply that artificial intelligence must be possible", site: "eon.c", href: "http://aeon.co/magazine/technology/david-deutsch-artificial-intelligence/", time: "2 days ago"}, 
	{title : "Show HN: A Google Calendar Door Sign", site: "ewfangled.m", href: "http://newfangled.me/door-sign/", time: "4 days ago"}, 
	{title : "Your Agile, Free and Open Source Project Management Tool", site: "aiga.i", href: "https://taiga.io/", time: "1 day ago"}, 
	{title : "Hacktoberfest", site: "igitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/#comment-1615829197", time: "1 day ago"}, 
	{title : "Apple Says iPhone 6 and 6 Plus Bending Complaints Number Less Than 10", site: "echcrunch.co", href: "http://techcrunch.com/2014/09/25/apple-says-iphone-6-and-6-plus-bending-complaints-number-less-than-10/?ncid=rss&cps=gravity", time: "1 day ago"}, 
	{title : "Microsoft developer explains why Windows 10 is called Windows 10", site: "eddit.co", href: "http://www.reddit.com/r/technology/comments/2hwlrk/new_windows_version_will_be_called_windows_10/ckwq83x", time: "1 day ago"}, 
	{title : "How American parenting is killing the American marriage", site: "z.co", href: "http://qz.com/273255/how-american-parenting-is-killing-the-american-marriage/", time: "1 day ago"}, 
	{title : "Make in India", site: "akeinindia.co", href: "http://makeinindia.com/sectors/", time: "8 days ago"}, 
	{title : "Rails is great! Thank you", site: "ithub.co", href: "https://github.com/rails/rails/issues/16731", time: "2 days ago"}, 
	{title : "Gilad Bracha: A DOMain of Shadows", site: "bracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html", time: "3 days ago"}, 
	{title : "Students are cash cows, and schools the predators", site: "alon.co", href: "http://www.salon.com/2014/10/01/college_is_ripping_you_off_students_are_cash_cows_and_schools_the_predators/?", time: "1 day ago"}, 
	{title : "COGNITIVE SLAVES (aka Crowdslaving)", site: "lobalguerrillas.typepad.co", href: "http://globalguerrillas.typepad.com/globalguerrillas/2010/09/cognitive-slaves.html", time: "1 day ago"}, 
	{title : "US top cop decries encryption, demands backdoors", site: "rstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/us-top-cop-decries-encryption-demands-backdoors/", time: "1 day ago"}, 
	{title : "Show HN: Airtable, a real-time spreadsheet-database hybrid", site: "irtable.co", href: "https://airtable.com/invite/a3sz9t7b", time: "6 days ago"}, 
	{title : "Vogue magazine interview with Jony Ive", site: "ogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive", time: "1 day ago"}, 
	{title : "React Apps Using Flux and Backbone: A How To", site: "optal.co", href: "http://www.toptal.com/front-end/simple-data-flow-in-react-applications-using-flux-and-backbone", time: "1 day ago"}, 
	{title : "Google execs have ideas on how to run your business", site: "echnologyreview.co", href: "http://www.technologyreview.com/news/531056/google-execs-have-ideas-on-how-to-run-your-business/", time: "3 days ago"}, 
	{title : "10x: Architecture at Clay.io", site: "olmeister.co", href: "http://zolmeister.com/2014/10/10x-architecture-at-clay-io.html", time: "2 days ago"}, 
	{title : "Microsoft developer explains on Reddit why Windows 10 is called Windows 10", site: "mgur.co", href: "https://i.imgur.com/SeH6xiI.png", time: "1 day ago"}, 
	{title : "Literary Lions Unite in Protest Over Amazon’s E-Book Tactics", site: "ytimes.co", href: "http://www.nytimes.com/2014/09/29/business/literary-lions-unite-in-protest-over-amazons-e-book-tactics.html", time: "4 days ago"}, 
	{title : "UK Legalizes CD Ripping and Cloud Backups Today", site: "orrentfreak.co", href: "http://torrentfreak.com/uk-government-legalizes-cd-ripping-cloud-backups-today-141001/", time: "2 days ago"}, 
	{title : "Google announces 10% price cut for all Compute Engine instances", site: "henextweb.co", href: "http://thenextweb.com/google/2014/10/01/google-announces-10-price-cut-compute-engine-instances-google-drive-passed-240m-active-users/", time: "1 day ago"}, 
	{title : "Show HN: NIH-DB fork it and write your own", site: "ithub.co", href: "https://github.com/tjake/nih-db", time: "1 day ago"}, 
	{title : "Eleventh Grade Tech Trends", site: "edium.co", href: "https://medium.com/musings-about-text-boxes/eleventh-grade-tech-trends-aca537e9ce62", time: "16 days ago"}, 
	{title : "Universal SSL: Be just a bit more patient", site: "loudflare.co", href: "https://blog.cloudflare.com/universal-ssl-be-just-a-bit-more-patient/", time: "3 days ago"}, 
	{title : "NerdytData patches Shellshock in a single crawl", site: "erdydata.co", href: "http://blog.nerdydata.com/post/98906853956/nerdydata-patches-shellshock-in-a-single-crawl", time: "1 day ago"}, 
	{title : "Lecture 3: Counterintuitive Parts of Startups, and How to Have Ideas", site: "enius.co", href: "http://tech.genius.com/Paul-graham-lecture-3-counterintuitive-parts-of-startups-and-how-to-have-ideas-annotated", time: "2 days ago"}, 
	{title : "Firefox Considering Tor Integration", site: "orproject.or", href: "https://lists.torproject.org/pipermail/tor-dev/2014-September/007533.html", time: "1 day ago"}, 
]