news10 = [
	{title : "Learn computer vision in a single weekend", site: "yimagesearch.co", href: "https://www.pyimagesearch.com/practical-python-opencv/?__vid=0ebac5e0138c0132dac522000b340435&email=artolaya%40gmail.com", time: "1 day ago"}, 
	{title : "Reclining airplane seats and the endowment effect", site: "late.co", href: "http://www.slate.com/articles/health_and_science/science/2014/09/airplane_seat_reclining_can_economics_reveal_who_deserves_the_space.single.html", time: "21 hours ago"}, 
	{title : "Multiple Template Engines for Django", site: "ndiegogo.co", href: "https://www.indiegogo.com/projects/multiple-template-engines-for-django", time: "1 day ago"}, 
	{title : "How EA’s jet-setting founder avoided $26M in taxes", site: "rstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/how-eas-jet-setting-founder-avoided-26-million-in-taxes/", time: "23 hours ago"}, 
	{title : "Rethinking the origins of the universe", site: "nc.ed", href: "http://unc.edu/spotlight/rethinking-the-origins-of-the-universe/", time: "8 days ago"}, 
	{title : "What Ever Happened to the Founders of Sierra Online?", site: "impleprogrammer.co", href: "http://simpleprogrammer.com/2014/09/29/ever-happened-founders-sierra-online", time: "21 hours ago"}, 
	{title : "On Thailand’s immigration police targeting digital nomads", site: "evels.i", href: "https://levels.io/thailands-immigration-police-targeting-digital-nomads/", time: "2 days ago"}, 
	{title : "Intel pulls equality ads in response to anti-feminist pressure", site: "heverge.co", href: "http://www.theverge.com/2014/10/2/6886747/intel-buckles-to-anti-feminist-campaign-by-pulling-ads-from-gaming", time: "20 hours ago"}, 
	{title : "Reddit CEO Yishan Wong on Giving Stock to Users: “We Have a Crazy Plan.”", site: "echcrunch.co", href: "http://techcrunch.com/2014/09/30/reddit-fundraising/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29&utm_content=FaceBook", time: "2 days ago"}, 
	{title : "Hipcamp Raises $2M to Get People Camping", site: "echcrunch.co", href: "http://techcrunch.com/2014/09/30/hipcamp-cooks-up-2m-seed-to-get-people-camping/", time: "2 days ago"}, 
	{title : "Cosmos Browser – Connect to the Internet via SMS, no data or wifi required", site: "ithub.co", href: "https://github.com/ColdSauce/CosmosBrowserAndroid", time: "21 days ago"}, 
	{title : "Y Combinator and the Negative Externalities of Hackernews", site: "anilocampos.co", href: "http://danilocampos.com/2014/09/y-combinator-and-the-negative-externalities-of-hacker-news/", time: "2 days ago"}, 
	{title : "The Coordinator pattern", site: "edbooth.co", href: "https://redbooth.com/engineering/javascript/the-coordinator-pattern", time: "1 day ago"}, 
	{title : "The FBI Says How It ‘Legally’ Pinpointed Silk Road’s Server", site: "ired.co", href: "http://www.wired.com/2014/09/the-fbi-finally-says-how-it-legally-pinpointed-silk-roads-server/", time: "27 days ago"}, 
	{title : "The Wolf", site: "andsinrepose.co", href: "http://randsinrepose.com/archives/the-wolf/", time: "31 days ago"}, 
	{title : "The Racial Dot Map: One Dot Per Person for the Entire U.S.", site: "oopercenter.or", href: "http://demographics.coopercenter.org/DotMap/index.html", time: "22 days ago"}, 
	{title : "First-Ever Expedition to Turkmenistan's “Door to Hell”", site: "ationalgeographic.co", href: "http://news.nationalgeographic.com/news/energy/2014/07/140716-door-to-hell-darvaza-crater-george-kourounis-expedition/", time: "74 days ago"}, 
	{title : "Spotify on their Engineering Culture", site: "rcticstartup.co", href: "http://www.arcticstartup.com/2014/10/02/video-spotify-on-their-engineering-culture", time: "22 hours ago"}, 
	{title : "The Mythology of Dog Years", site: "riceonomics.co", href: "http://priceonomics.com/the-mythology-of-dog-years/", time: "1 day ago"}, 
	{title : "Dmitry Grishin: “Robotics Has Too Many Dreamers, Needs More Practical People”", site: "eee.or", href: "http://spectrum.ieee.org/automaton/robotics/home-robots/dmitry-grishin-robotics#.VCr0s3T1v2w.hackernews", time: "2 days ago"}, 
	{title : "Ebola Overwhelming West Africa Communities", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/02/world/africa/ebola-spreading-in-west-africa.html", time: "1 day ago"}, 
	{title : "Elon Musk argues that putting a million people on Mars ensures humanity's future", site: "eon.c", href: "http://aeon.co/magazine/technology/the-elon-musk-interview-on-mars/", time: "3 days ago"}, 
	{title : "Show HN: Do you hate salesforce?", site: "hatesalesforce.co", href: "http://ihatesalesforce.com", time: "21 hours ago"}, 
	{title : "Germany plans to make sending colleagues work emails after 6pm illegal", site: "etro.co.u", href: "http://metro.co.uk/2014/10/02/germany-plans-to-make-sending-colleagues-work-emails-after-6pm-illegal-4889633/", time: "23 hours ago"}, 
]