news14 = [
	{title : "The 10,000 Hour Rule for deliberate practice is wrong", site: "late.co", href: "http://www.slate.com/articles/health_and_science/science/2014/09/malcolm_gladwell_s_10_000_hour_rule_for_deliberate_practice_is_wrong_genes.single.html", time: "1 day ago"}, 
	{title : "The Effort to Bring “Habitat” Back to Life", site: "ired.co", href: "http://www.wired.com/2014/10/restoring-habitat/", time: "1 day ago"}, 
	{title : "Linear Optimization with Glop", site: "evelopers.google.co", href: "https://developers.google.com/optimization/docs/lp/glop", time: "2 days ago"}, 
	{title : "Show HN: HackerBracket – What are you working on?", site: "ackerbracket.co", href: "https://www.hackerbracket.com/v/2", time: "1 day ago"}, 
	{title : "Tor growth rates", site: "ocs.google.co", href: "https://docs.google.com/document/d/1SaBK664SchhZOP9XBsB8KK63k4xlmMTlkhfF28f2204/pub", time: "1 day ago"}, 
	{title : "Scientific writing: the online cooperative", site: "ature.co", href: "http://www.nature.com/news/scientific-writing-the-online-cooperative-1.16039", time: "1 day ago"}, 
	{title : "Inside the Cosmonaut Survival Kit (2013)", site: "heappendix.ne", href: "http://theappendix.net/blog/2013/11/the-cosmonauts-survival-kit", time: "2 days ago"}, 
	{title : "Is Alzheimer's Type 3 Diabetes? (2012)", site: "pinionator.blogs.nytimes.co", href: "http://opinionator.blogs.nytimes.com/2012/09/25/bittman-is-alzheimers-type-3-diabetes/", time: "1 day ago"}, 
	{title : "Digital.nyc – NYC's hub for tech and startups", site: "igital.ny", href: "http://www.digital.nyc", time: "1 day ago"}, 
	{title : "Source Code Optimization (2009) [pdf]", site: "inux-kongress.or", href: "http://www.linux-kongress.org/2009/slides/compiler_survey_felix_von_leitner.pdf", time: "2 days ago"}, 
	{title : "Trends in the Silk Road 2.0", site: "au.i", href: "http://lau.im/articles/analyzing-silk-road-2-0-part-1/", time: "3 days ago"}, 
	{title : "35,000 Walruses Gathered in Alaska", site: "usinessinsider.co", href: "http://www.businessinsider.com/35000-walruses-gathered-in-alaska-2014-10", time: "1 day ago"}, 
	{title : "Show HN: EBay for 3D Printing", site: "rintthis4.m", href: "https://printthis4.me", time: "1 day ago"}, 
	{title : "Doctors Find Barriers to Sharing Digital Medical Records", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/01/business/digital-medical-records-become-common-but-sharing-remains-challenging.html", time: "1 day ago"}, 
	{title : "Recruiting Tech Talent in High School", site: "sj.co", href: "http://online.wsj.com/articles/recruiting-tech-talent-in-high-school-1412220618", time: "1 day ago"}, 
	{title : "LibreSSL: More Than 30 Days Later", site: "penbsd.or", href: "http://www.openbsd.org/papers/eurobsdcon2014-libressl.html", time: "5 days ago"}, 
	{title : "Clustering of bigram frequencies", site: "ottwurfelt.co", href: "http://gottwurfelt.com/2014/10/01/clustering-of-bigram-frequencies/", time: "1 day ago"}, 
	{title : "The Future of Iced Coffee", site: "heatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/08/the-future-of-iced-coffee/375114/", time: "2 days ago"}, 
	{title : "Is this why Microsoft named it Windows 10?", site: "net.co", href: "http://www.cnet.com/news/is-this-why-microsoft-named-it-windows-10/", time: "1 day ago"}, 
	{title : "Show HN: WeTopTen – Create top 10 of books, movies, albums and more", site: "etopten.co", href: "http://wetopten.com", time: "1 day ago"}, 
	{title : "A Rare Look at Apple's Design Genius Jony Ive", site: "ogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive/", time: "2 days ago"}, 
	{title : "Anti-selfconsciousness and John Stuart Mill and Carlyle", site: "heliterarylink.co", href: "http://theliterarylink.com/anti_selfconsciousness.html", time: "1 day ago"}, 
	{title : "Universal SSL: How It Scales", site: "loudflare.co", href: "https://blog.cloudflare.com/universal-ssl-how-it-scales/", time: "1 day ago"}, 
	{title : "Show HN: Shared reading list and bookmarks for teams", site: "eadonomy.co", href: "https://www.readonomy.com/?hn", time: "2 days ago"}, 
	{title : "This Time The Bubble Will Implode", site: "rielmichaeli.co", href: "http://arielmichaeli.com/2014/09/this-time-the-bubble-will-implode/", time: "1 day ago"}, 
	{title : "Adam Sandler to star in four movies exclusively for Netflix", site: "w.co", href: "http://insidemovies.ew.com/2014/10/02/adam-sandler-netflix-movies/", time: "1 day ago"}, 
	{title : "Webfont optimization", site: "evelopers.google.co", href: "https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization", time: "2 days ago"}, 
]