news2 = [
	{title : "An Australian researcher has worked out how to store 1000TB on a CD", site: "ciencealert.com.a", href: "http://www.sciencealert.com.au/news/20140309-26116.html", time: "23 hours ago"}, 
	{title : "Unpatchable Malware That Infects USBs", site: "ired.co", href: "http://www.wired.com/2014/10/code-published-for-unfixable-usb-attack/", time: "1 day ago"}, 
	{title : "Show HN: GoldenLayout – JavaScript Layout Manager", site: "olden-layout.co", href: "https://golden-layout.com/", time: "1 day ago"}, 
	{title : "Why I took on building a better way to frame any poster, print or photo", site: "edium.co", href: "https://medium.com/@jhubball/custom-framing-is-a-racket-61461b12278d", time: "1 day ago"}, 
	{title : "Building an alternative Silicon Valley", site: "ustingrandt.co", href: "http://austingrandt.com/building-alternative-silicon-valley/", time: "2 hours ago"}, 
	{title : "Apple allows hot code push for JS downloaded and run by WebKit", site: "eteor.co", href: "https://www.meteor.com/blog/2014/10/02/Apple-hot-code-push-mobile", time: "21 hours ago"}, 
	{title : "With Dry Taps and Toilets, California Drought Turns Desperate", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/03/us/california-drought-tulare-county.html?smid=tw-share", time: "16 hours ago"}, 
	{title : "Growth, efficiency, and yield of commercial broilers from 1957, 1978, and 2005", site: "xfordjournals.or", href: "http://ps.oxfordjournals.org/content/early/2014/09/26/ps.2014-04291.abstract", time: "2 hours ago"}, 
	{title : "Lyft Drivers Are Burning Their Pink Mustaches", site: "ice.co", href: "http://www.vice.com/read/burning-mustaches-with-angry-lift-drivers-103", time: "33 minutes ago"}, 
	{title : "Study suggests that memory loss in Alzheimer's patients may be reversed", site: "eurosciencenews.co", href: "http://neurosciencenews.com/alzheimers-memory-loss-reversal-1377/", time: "1 day ago"}, 
	{title : "Route leak incident on October 2, 2014", site: "loudflare.co", href: "https://blog.cloudflare.com/route-leak-incident-on-october-2-2014/", time: "22 hours ago"}, 
	{title : "Cool-retro-term: A terminal emulator which mimics the old cathode display", site: "ithub.co", href: "https://github.com/Swordfish90/cool-retro-term", time: "1 day ago"}, 
	{title : "Orleans – Distributed Virtual Actors for Programmability and Scalability", site: "icrosoft.co", href: "http://research.microsoft.com/en-us/projects/orleans/", time: "16 hours ago"}, 
	{title : "The Magic CmdLine – and how I got it back", site: "tua.g", href: "http://users.softlab.ece.ntua.gr/~ttsiod/bashheimer.html", time: "2 hours ago"}, 
	{title : "Three months at Y Combinator: what it’s like and how to get in", site: "rontapp.co", href: "http://blog.frontapp.com/three-months-at-y-combinator-what-its-like-and-how-to-get-in/", time: "23 hours ago"}, 
	{title : "The USSR used a nuclear charge to stop a gas well fire in 1966", site: "oal-seam-gas.co", href: "http://www.coal-seam-gas.com/accidents/ussr.htm", time: "1 day ago"}, 
	{title : "Show HN: Open-Source, Free, Agile Project Management Tool", site: "aiga.i", href: "http://www.taiga.io", time: "1 day ago"}, 
	{title : "Ericsson open-sources OpenWebRTC, rival to Google’s WebRTC implementation", site: "igaom.co", href: "https://gigaom.com/2014/10/02/ericsson-open-sources-openwebrtc-to-provide-alternative-to-googles-webrtc-implementation/", time: "1 day ago"}, 
	{title : "Dollar a Day", site: "ollaraday.c", href: "https://dollaraday.co/", time: "1 day ago"}, 
	{title : "Elusive Form of Evolution Seen in Spiders", site: "imonsfoundation.or", href: "http://www.simonsfoundation.org/quanta/20141002-in-social-spiders-evidence-that-groups-evolve/", time: "22 hours ago"}, 
	{title : "Show HN: Franc – Detect 168 natural languages", site: "ithub.co", href: "https://github.com/wooorm/franc", time: "5 hours ago"}, 
	{title : "Beautiful Chemistry", site: "eautifulchemistry.ne", href: "http://beautifulchemistry.net/", time: "1 day ago"}, 
	{title : "SAT solving – An alternative to brute force Bitcoin mining (2013)", site: "heusser.github.i", href: "https://jheusser.github.io/2013/02/03/satcoin.html", time: "1 day ago"}, 
	{title : "CUPS 2.0", site: "ups.or", href: "https://www.cups.org/documentation.php/doc-2.0/relnotes.html", time: "1 day ago"}, 
	{title : "Sway: A new presentation application from Microsoft", site: "way.co", href: "https://sway.com/", time: "1 day ago"}, 
	{title : "Fly offspring can resemble mother's previous sexual partner", site: "mh.com.a", href: "http://www.smh.com.au/technology/sci-tech/ghosts-of-mothers-sexual-past-show-up-in-fly-offspring-study-shows-20141001-10onn3.html", time: "20 hours ago"}, 
	{title : "Most People with Addiction Simply Grow Out of It", site: "ubstance.co", href: "http://www.substance.com/most-people-with-addiction-simply-grow-out-of-it-why-is-this-widely-denied/13017/", time: "1 day ago"}, 
]