news19 = [
	{title : "Microbiome researcher does fecal transplant from African hunger-gatherer", site: "umanfoodproject.co", href: "http://humanfoodproject.com/rebecoming-human-happened-day-replaced-99-genes-body-hunter-gatherer/", time: "1 day ago"}, 
	{title : "If You Have Unlimited Vacation, Will You Take It?", site: "p-talk.blogs.nytimes.co", href: "http://op-talk.blogs.nytimes.com/2014/09/30/if-you-have-unlimited-vacation-will-you-take-it/", time: "1 day ago"}, 
	{title : "Simple Language Implementation Techniques for the 21st Century", site: "tefan-marr.d", href: "http://stefan-marr.de/papers/ieee-soft-marr-et-al-are-we-there-yet/", time: "3 days ago"}, 
	{title : "Show HN: Invoicerb, a simple, command line invoice tool", site: "ithub.co", href: "https://github.com/emson/invoicerb", time: "2 days ago"}, 
	{title : "New brain implants can restore autonomy to damaged minds", site: "eon.c", href: "http://aeon.co/magazine/psychology/how-new-brain-implants-affect-free-will/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+AeonMagazineEssays+%28Aeon+Magazine+Essays%29", time: "2 days ago"}, 
	{title : "Dispatch from Worldcon", site: "plusonemag.co", href: "https://nplusonemag.com/online-only/online-only/dispatch-from-worldcon/", time: "2 days ago"}, 
	{title : "Drop-a-Brick in your Toilet campaign aims to fight West Coast drought", site: "ndiegogo.co", href: "https://www.indiegogo.com/projects/drop-a-brick-in-your-toilet/x/6550456", time: "1 day ago"}, 
	{title : "Chrysler 200 Factory [video]", site: "hrysler200factory.co", href: "http://www.chrysler200factory.com/", time: "1 day ago"}, 
	{title : "Startup Community the Film – A Documentary About Startups in Kitchener-Waterloo", site: "outube.co", href: "https://www.youtube.com/watch?v=Q4EzYAB8Q4A", time: "1 day ago"}, 
	{title : "Holder urges tech companies to leave device backdoors open for police", site: "ashingtonpost.co", href: "http://www.washingtonpost.com/blogs/the-switch/wp/2014/09/30/holder-urges-tech-companies-to-leave-device-backdoors-open-for-police/", time: "2 days ago"}, 
	{title : "Incredible Close-Up Drone Video of an Erupting Volcano in Iceland", site: "ired.co", href: "http://www.wired.com/2014/10/drone-video-iceland-eruption-bardarbunga-volcano", time: "1 day ago"}, 
	{title : "Sikuli Script", site: "ikuli.or", href: "http://www.sikuli.org/", time: "2 days ago"}, 
	{title : "Benefits of Writing a DSL in Ruby", site: "enpayroll.co", href: "http://engineering.zenpayroll.com/benefits-of-writing-a-dsl/", time: "2 days ago"}, 
	{title : "Prison Bankers Who Profit from the Inmates", site: "ime.co", href: "http://time.com/3446372/criminal-justice-prisoners-profit/", time: "2 days ago"}, 
	{title : "Mozilla Brick", site: "ozilla.i", href: "http://brick.mozilla.io/", time: "3 days ago"}, 
	{title : "Download Windows Technical 10 Preview", site: "icrosoft.co", href: "http://windows.microsoft.com/en-us/windows/preview-download?ocid=tp_site_downloadpage", time: "1 day ago"}, 
	{title : "Maze Generation In Thirteen Bytes", site: "ldskool.or", href: "http://trixter.oldskool.org/2012/12/17/maze-generation-in-thirteen-bytes/", time: "654 days ago"}, 
	{title : "Find your color scheme", site: "olourco.d", href: "http://colourco.de/", time: "210 days ago"}, 
	{title : "Normalizing a CSV file using MySQL", site: "angoldin.co", href: "http://dangoldin.com/2014/10/01/normalizing-a-csv-file-using-mysql/", time: "1 day ago"}, 
	{title : "Tesla to Unveil the “D” on October 9th", site: "witter.co", href: "https://twitter.com/elonmusk/status/517486950589014016/photo/1", time: "1 day ago"}, 
	{title : "The commit Russia uses as an excuse to block GitHub", site: "ranslate.google.co", href: "https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fgithub.com%2Famdf%2Fobjidlib%2Fcommit%2Fe9c31e97c0ca7863516fa6e21c9f6441453d9149&edit-text=", time: "22 hours ago"}, 
	{title : "I Hate Commander Chris Hadfield", site: "mazon.co", href: "http://www.amazon.com/review/R6L2EVLMPPEQS", time: "1 day ago"}, 
	{title : "MIT launches Laboratory for Social Machines", site: "it.ed", href: "http://newsoffice.mit.edu/2014/twitter-funds-mit-media-lab-program-1001", time: "1 day ago"}, 
	{title : "Notation as a Tool of Thought (1979) [pdf]", site: "oronto.ed", href: "http://www.eecg.toronto.edu/~jzhu/csc326/readings/iverson.pdf", time: "2 days ago"}, 
	{title : "Denmark tackles youth unemployment with university cuts", site: "est-info.e", href: "http://www.west-info.eu/denmark-tackles-youth-unemployment-with-university-cuts/", time: "2 days ago"}, 
	{title : "Houzz Raises $165M Series D Funding Round Led by Sequoia", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/01/houzz-raises-165m-series-d-led-by-sequoia-to-fuel-international-expansion/", time: "1 day ago"}, 
	{title : "The most important chart about the American economy you'll see this year", site: "ox.co", href: "http://www.vox.com/xpress/2014/9/25/6843509/income-distribution-recoveries-pavlina-tcherneva", time: "1 day ago"}, 
	{title : "Lunchtime Hack: Decoding LocationHistory", site: "shift.ne", href: "http://www.lshift.net/blog/2014/09/30/lunchtime-hack-decoding-locationhistory/", time: "2 days ago"}, 
	{title : "Byte: The Smalltalk Issue (1981) [pdf]", site: "rchive.or", href: "https://ia601506.us.archive.org/12/items/byte-magazine-1981-08/1981_08_BYTE_06-08_Smalltalk.pdf", time: "2 days ago"}, 
]