news5 = [
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "autil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math", time: "1 day ago"}, 
	{title : "C# 6 Cuts", site: "relford.co", href: "http://www.trelford.com/blog/post/austerity.aspx", time: "1 day ago"}, 
	{title : "MiniKanren – An embedded DSL for logic programming", site: "inikanren.or", href: "http://minikanren.org/", time: "2 days ago"}, 
	{title : "Backer News: fresh crowdfunding projects", site: "ackernews.co", href: "http://backernews.com/", time: "1 day ago"}, 
	{title : "Douglas Model 671/684: The X-15’s Shadow (2012)", site: "alsesteps.wordpress.co", href: "http://falsesteps.wordpress.com/2012/08/11/douglas-model-671684-the-x-15s-shadow/", time: "1 day ago"}, 
	{title : "The New and Improved C# 6.0", site: "icrosoft.co", href: "http://msdn.microsoft.com/en-us/magazine/dn802602.aspx", time: "1 day ago"}, 
	{title : "U.S. Law Enforcement Seeks to Halt Apple-Google Encryption of Mobile Data", site: "loomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/u-s-seeks-to-reverse-apple-android-data-locking-decision.html", time: "2 days ago"}, 
	{title : "Modules in C99", site: "naipe.m", href: "http://snaipe.me/c/modules-in-c99/", time: "23 hours ago"}, 
	{title : "Early Digital Research CP/M Source Code", site: "omputerhistory.or", href: "http://www.computerhistory.org/_static/atchm/early-digital-research-cpm-source-code/", time: "1 day ago"}, 
	{title : "The story of the longest-held American POW", site: "late.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/john_t_downey_cia_agent_captured_by_china_during_the_korean_war_the_story.single.html", time: "1 day ago"}, 
	{title : "An iconic phone before the iPhone", site: "uxtapoz.co", href: "http://www.juxtapoz.com/design/an-iconic-phone-before-the-iphone", time: "1 day ago"}, 
	{title : "Containers [pdf]", site: "senix.or", href: "https://www.usenix.org/system/files/login/articles/login_1410_02-bottomley.pdf", time: "1 day ago"}, 
	{title : "How Hong Kong Protesters Are Connecting, Without Cell or Wi-Fi Networks", site: "pr.or", href: "http://www.npr.org/blogs/alltechconsidered/2014/09/29/352476454/how-hong-kong-protesters-are-connecting-without-cell-or-wi-fi-networks", time: "3 days ago"}, 
	{title : "Redesigning the OpenDNS DNS database for low latency", site: "pendns.co", href: "http://labs.opendns.com/2014/10/01/redesigning-dns-database-low-latency/", time: "1 day ago"}, 
	{title : "First Blood Test to Diagnose Depression in Adults?", site: "orthwestern.ed", href: "http://www.northwestern.edu/newscenter/stories/2014/09/first-blood-test-to-diagnose-depression-in-adults.html", time: "1 day ago"}, 
	{title : "Ancient campfires may have aided the rise of storytelling", site: "ciencemag.or", href: "http://news.sciencemag.org/archaeology/2014/09/ancient-campfires-led-rise-storytelling", time: "1 day ago"}, 
	{title : "Algolia (YC W14) debuts free plan, opens West Coast data center", site: "enturebeat.co", href: "http://venturebeat.com/2014/10/01/search-as-a-service-provider-algolia-debuts-free-plan-opens-west-coast-data-center", time: "21 hours ago"}, 
	{title : "Atlantic.net launches $0.99 SSD-based VPS servers", site: "echcrunch.co", href: "http://techcrunch.com/2014/09/30/atlantic-net-launches-0-99month-ssd-based-vps-hosting-service/", time: "2 days ago"}, 
	{title : "C for Rubyists", site: "mniref.co", href: "https://www.omniref.com/ruby/2.1.2/files/ruby.c#annotation=4029392&line=1", time: "2 days ago"}, 
	{title : "The Source of Bad Writing", site: "sj.co", href: "http://online.wsj.com/articles/the-cause-of-bad-writing-1411660188", time: "12 hours ago"}, 
	{title : "My data is bigger than your data", site: "intool.github.i", href: "http://lintool.github.io/my-data-is-bigger-than-your-data/", time: "22 hours ago"}, 
	{title : "Learning Online", site: "hristinacacioppo.co", href: "http://christinacacioppo.com/blog/learning-online", time: "3 days ago"}, 
	{title : "Universal SSL", site: "loudflare.co", href: "https://blog.cloudflare.com/introducing-universal-ssl/", time: "4 days ago"}, 
	{title : "Show HN: OrderCircle – Wholesale ordering software for small businesses", site: "rdercircle.co", href: "http://ordercircle.com", time: "1 day ago"}, 
	{title : "Why Scrum Should Basically Just Die in a Fire", site: "ilesbowkett.blogspot.co", href: "http://gilesbowkett.blogspot.com/2014/09/why-scrum-should-basically-just-die-in.html", time: "5 hours ago"}, 
	{title : "Synergy (GPL'd Software KVM) switches to paid downloads", site: "ynergy-project.or", href: "http://synergy-project.org/download/?paid", time: "18 hours ago"}, 
	{title : "New material steals oxygen from the air", site: "ciencedaily.co", href: "http://www.sciencedaily.com/releases/2014/09/140930113254.htm", time: "22 hours ago"}, 
	{title : "Ham radio exams, algorithms, and scaling on the fly", site: "obbe.u", href: "http://grant.dobbe.us/2014/10/ham-radio-exams-algorithms-and-scaling-on-the-fly/", time: "1 day ago"}, 
]