news18 = [
	{title : "Synergy (mouse and keyboard sharing over a network) goes from free to paid", site: "ynergy-project.or", href: "http://synergy-project.org/download/", time: "9 days ago"}, 
	{title : "Recruiter: Startups Are Offering Crazy, 1999-Like Hiring Incentives", site: "usinessinsider.co", href: "http://www.businessinsider.com/startups-offering-1-million-signing-bonuses-2014-9", time: "5 days ago"}, 
	{title : "Live attacks against the Norse honeypot infrastructure", site: "pviking.co", href: "http://map.ipviking.com/", time: "55 days ago"}, 
	{title : "Entrepreneurs anonymous: People should understand how hard their lives can be", site: "conomist.co", href: "http://www.economist.com/news/business/21618816-instead-romanticising-entrepreneurs-people-should-understand-how-hard-their-lives-can", time: "14 days ago"}, 
	{title : "Affinity Designer – Illustrator alternative", site: "erif.co", href: "https://affinity.serif.com/", time: "63 days ago"}, 
	{title : "The Cardinal Sin of Software Engineering", site: "heeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/cardinal-sin-of-software-engineering", time: "8 days ago"}, 
	{title : "Show HN: Socktunes, the music search engine", site: "ocktunes.co", href: "http://socktunes.com", time: "5 days ago"}, 
	{title : "Using your RDBMS for messaging is totally OK", site: "ooq.or", href: "http://blog.jooq.org/2014/09/26/using-your-rdbms-for-messaging-is-totally-ok/", time: "6 days ago"}, 
	{title : "Effective Code Reviews", site: "riginate.co", href: "http://blog.originate.com/blog/2014/09/29/effective-code-reviews/", time: "3 days ago"}, 
	{title : "Why startups fail (according to their founders)", site: "ortune.co", href: "http://fortune.com/2014/09/25/why-startups-fail-according-to-their-founders/", time: "7 days ago"}, 
	{title : "Tour of pyramids of Giza using Google Maps street view", site: "oogle.co", href: "http://www.google.com/maps/about/behind-the-scenes/streetview/treks/pyramids-of-giza/", time: "23 days ago"}, 
	{title : "Living Simply in a Dumpster", site: "heatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/the-simple-life-in-a-dumpster/379947/", time: "22 days ago"}, 
	{title : "Marka: Icon transformations", site: "ian.my.i", href: "http://fian.my.id/marka/", time: "54 days ago"}, 
	{title : "An interactive exploration of Boston's subway system", site: "btaviz.github.i", href: "http://mbtaviz.github.io/", time: "115 days ago"}, 
	{title : "GitHub.com is officially banned in Russia by the Government", site: "witter.co", href: "https://twitter.com/orangy/status/517714936974561280", time: "23 hours ago"}, 
	{title : "Synergy FOSS: Connect your keyboard to multiple PCs", site: "ynergy-project.or", href: "http://synergy-project.org/", time: "30 days ago"}, 
	{title : "ISPs in Russia are blocking GitHub", site: "mazonaws.co", href: "https://s3.amazonaws.com/kato-share/18e61a9a5fb1c6906002801197086fbbe35d531c7b64d3d5afe764823ed2f1a/Screen%20Shot%202014-10-02%20at%208.37.11%20PM.png", time: "23 hours ago"}, 
	{title : "Systemd may drive Linux admins to FreeBSD", site: "nfoworld.co", href: "http://www.infoworld.com/d/data-center/you-have-your-windows-in-my-linux-249483", time: "30 days ago"}, 
	{title : "Are coders worth it? (2013)", site: "eon.c", href: "http://aeon.co/magazine/society/james-somers-web-developer-money/", time: "35 days ago"}, 
	{title : "Dug.js – A JSONP to HTML Script", site: "og.i", href: "http://rog.ie/blog/dugjs-a-jsonp-to-html-script", time: "232 days ago"}, 
	{title : "JPEG image glitching / corruption", site: "norpey.github.i", href: "http://snorpey.github.io/jpg-glitch/", time: "389 days ago"}, 
	{title : "What Qualities Make a Good Startup Engineer?", site: "heeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/what-qualities-make-a-good-startup-engineer", time: "85 days ago"}, 
	{title : "Programming Sucks", site: "tilldrinking.or", href: "http://stilldrinking.org/programming-sucks", time: "157 days ago"}, 
	{title : "Unsung Hero of the Nuclear Age", site: "late.co", href: "http://www.slate.com/articles/life/the_spectator/2011/02/an_unsung_hero_of_the_nuclear_age.single.html", time: "236 days ago"}, 
	{title : "Daniel Shiffman launches "The Nature of Code" online for free", site: "atureofcode.co", href: "http://natureofcode.com/", time: "704 days ago"}, 
	{title : "BOXEN – GitHub's configuration tool for osx", site: "ithub.co", href: "https://boxen.github.com/", time: "152 days ago"}, 
	{title : "Apple will buy Tesla – rumor", site: "enturebeat.co", href: "http://venturebeat.com/2014/02/16/rumor-says-apple-will-buy-tesla/", time: "228 days ago"}, 
	{title : "Fun With HTTP Headers", site: "extthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers", time: "2060 days ago"}, 
	{title : "Simplify Decisions by Computing How Much Your Time Is Worth", site: "heeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/how-much-is-your-time-worth", time: "156 days ago"}, 
	{title : "The Y Combinator (Slight Return) (2008)", site: "vanier.livejournal.co", href: "http://mvanier.livejournal.com/2897.html", time: "491 days ago"}, 
]