news1 = [
	{title : "Postgres 9.5 feature highlight: row-level security and policies", site: "tacoo.co", href: "http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-row-level-security/", time: "1 hour ago"}, 
	{title : "Marriott Hotels fined $600,000 by FCC for jamming Wi-Fi hotspots [pdf]", site: "cc.go", href: "http://transition.fcc.gov/Daily_Releases/Daily_Business/2014/db1003/DA-14-1444A1.pdf", time: "11 minutes ago"}, 
	{title : "Show HN: JuliusJS – speech recognition in JavaScript", site: "ithub.co", href: "https://github.com/zzmp/juliusjs", time: "2 hours ago"}, 
	{title : "New Particle Is Both Matter and Antimatter", site: "cientificamerican.co", href: "http://www.scientificamerican.com/article/majorana-particle-matter-and-antimatter/", time: "4 hours ago"}, 
	{title : "Silk Road Lawyers Poke Holes in FBI’s Story", site: "rebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/silk-road-lawyers-poke-holes-in-fbis-story/", time: "9 hours ago"}, 
	{title : "Aboard Amtrak", site: "pnzr.co", href: "http://spnzr.com/aboard-amtrak", time: "8 hours ago"}, 
	{title : "Phison USB Custom Firmware and Existing Firmware Patches", site: "ithub.co", href: "https://github.com/adamcaudill/Psychson", time: "2 hours ago"}, 
	{title : "The tourist map of laptops", site: "nod.co", href: "http://things.gnod.com/laptops/", time: "4 hours ago"}, 
	{title : "HTTP/2 Frequently Asked Questions", site: "ttp2.github.i", href: "http://http2.github.io/faq/", time: "8 hours ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "autil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd", time: "19 hours ago"}, 
	{title : "We Got Accepted into Techstars and Turned Them Down", site: "alkroute.co", href: "http://talkroute.com/got-accepted-into-techstars-turned-it-down/", time: "17 hours ago"}, 
	{title : "A State of Xen – Chaos Monkey and Cassandra", site: "etflix.co", href: "http://techblog.netflix.com/2014/10/a-state-of-xen-chaos-monkey-cassandra.html", time: "12 hours ago"}, 
	{title : "Shapecatcher: Draw the Unicode character you want", site: "hapecatcher.co", href: "http://shapecatcher.com", time: "18 hours ago"}, 
	{title : "Hacker's Guide to Setting Up Your Mac", site: "apwinglabs.co", href: "http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac", time: "21 hours ago"}, 
	{title : "JPMorgan Says Data Breach Affected 76M Households", site: "loomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/jpmorgan-says-data-breach-affected-76-million-households.html", time: "17 hours ago"}, 
	{title : "India, U.S. Agree to Joint Exploration of Mars", site: "sj.co", href: "http://blogs.wsj.com/indiarealtime/2014/10/01/india-u-s-to-agree-to-joint-exploration-of-mars", time: "1 day ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "amaltman.co", href: "http://startupclass.samaltman.com/courses/lec04/#", time: "17 hours ago"}, 
	{title : "What It's Like to Build a Startup in Gaza", site: "ired.co", href: "http://www.wired.com/2014/10/like-build-startup-gaza-strip-bombs-drop/", time: "10 hours ago"}, 
	{title : "Before the Startup", site: "aulgraham.co", href: "http://paulgraham.com/before.html", time: "1 day ago"}, 
	{title : "Introducing Modelling by Example", site: "verzet.co", href: "http://everzet.com/post/99045129766/introducing-modelling-by-example", time: "4 hours ago"}, 
	{title : "Show HN: HelloBitcoin. A “Hello World” of Bitcoin, Written in Go", site: "ithub.co", href: "https://github.com/prettymuchbryce/hellobitcoin", time: "12 hours ago"}, 
	{title : "How Exercise May Protect Against Depression", site: "ell.blogs.nytimes.co", href: "http://well.blogs.nytimes.com/2014/10/01/how-exercise-may-protect-against-depression/?src=me", time: "21 hours ago"}, 
	{title : "The origins of language are not what inherited disorders seemed to suggest", site: "autil.u", href: "http://nautil.us/issue/17/big-bangs/the-family-that-couldnt-say-hippopotamus?utm_source=RSS_Feed&utm_medium=RSS&utm_campaign=RSS_Syndication", time: "8 hours ago"}, 
	{title : "Contact Lost with Planes One by One as FAA Fire Spread", site: "loomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/contact-lost-with-planes-one-by-one-as-faa-center-fire-spread.html", time: "20 hours ago"}, 
	{title : "Geometric Madness: Implementation of computational geometry algorithms [video]", site: "outube.co", href: "https://www.youtube.com/watch?v=fu-uW7CQkVo", time: "13 hours ago"}, 
	{title : "The NSA and Me", site: "irstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/the-nsa-and-me/", time: "21 hours ago"}, 
	{title : "The Physical Web", site: "ithub.co", href: "https://github.com/google/physical-web", time: "1 day ago"}, 
	{title : "HFT in my backyard – III", site: "niperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/02/hft-in-my-backyard-iii/", time: "1 day ago"}, 
	{title : "The day of the technopath", site: "hesprawl.or", href: "http://thesprawl.org/simstim/day-technopath/", time: "19 hours ago"}, 
]