news4 = [
	{title : "FloppyNerd – WebGL/Three.js datacenter game", site: "loppynerd.s", href: "http://floppynerd.se", time: "4 hours ago"}, 
	{title : "Run Your Startup Like a Cult", site: "ired.co", href: "http://www.wired.com/2014/09/run-startup-like-cult-heres/", time: "1 day ago"}, 
	{title : "Google planning to launch own mobile messaging app similar to WhatsApp", site: "conomictimes.co", href: "http://m.economictimes.com/tech/internet/google-planning-to-launch-own-mobile-messaging-app-similar-to-whatsapp/articleshow/44141070.cms", time: "8 hours ago"}, 
	{title : "Booking.com donates $60000 to Perl development", site: "erlfoundation.or", href: "http://news.perlfoundation.org/2014/10/bookingcom-donates-60000-to-pe.html", time: "7 hours ago"}, 
	{title : "1 Year development plan for Straight, a Bitcoin payment processor", site: "omansnitko.co", href: "http://straight.romansnitko.com/1yeardevplan.html", time: "5 hours ago"}, 
	{title : "A Visual Tour of Erlang (2012) [video]", site: "outube.co", href: "https://www.youtube.com/watch?v=lHoWfeNuAN8", time: "1 day ago"}, 
	{title : "Best Papers vs. Top Cited Papers in Computer Science", site: "rnetminer.or", href: "http://arnetminer.org/conferencebestpapers", time: "1 day ago"}, 
	{title : "A Lua interpreter written in C#", site: "oonsharp.or", href: "http://www.moonsharp.org/", time: "1 day ago"}, 
	{title : "Disassembling an attempted Shellshock exploit", site: "interactive.co", href: "http://iinteractive.com/notebook/2014/10/02/shellshock.html", time: "18 hours ago"}, 
	{title : "Aerodrums", site: "erodrums.co", href: "http://aerodrums.com/aerodrums/", time: "1 day ago"}, 
	{title : "Lever (YC S12) Raises $10M to Build a Human Resources and Hiring Platform", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/02/lever/", time: "15 hours ago"}, 
	{title : "BAP: Binary Analysis Platform", site: "mu.ed", href: "http://bap.ece.cmu.edu/", time: "1 day ago"}, 
	{title : "How to find growing files on Linux", site: "arvik.d", href: "http://aarvik.dk/how-to-find-growing-files-on-linux/", time: "3 hours ago"}, 
	{title : "Lecture 3: How to Start a Startup", site: "amaltman.co", href: "http://startupclass.samaltman.com/courses/lec03/", time: "2 days ago"}, 
	{title : "A Fresh Look at Rust", site: "ocoo.or", href: "http://lucumr.pocoo.org/2014/10/1/a-fresh-look-at-rust/", time: "2 days ago"}, 
	{title : "What if AWS goes pop, runs out of cash?", site: "hannelregister.co.u", href: "http://www.channelregister.co.uk/2014/09/25/public_iaas_crisis/", time: "4 hours ago"}, 
	{title : "Scientists twist radio beams to send data at 32 Gb/sec (x30 faster than LTE)", site: "btimes.co.u", href: "http://www.ibtimes.co.uk/scientists-twist-radio-beams-to-send-data-at-32-gigabits-per-second-30-times-faster-than-4g-lte-1465957", time: "4 hours ago"}, 
	{title : "15 years of whois client", site: "ofh.i", href: "http://blog.bofh.it/debian/id_452", time: "10 hours ago"}, 
	{title : "CVE-2014-7284: Lack of randomness in Linux kernel network secrets", site: "econdlookforensics.co", href: "http://secondlookforensics.com/ngro-linux-kernel-bug/", time: "1 day ago"}, 
	{title : "Show HN: Gmail Extension to track and secure docs you send", site: "treak.co", href: "https://www.streak.com/docsend", time: "19 hours ago"}, 
	{title : "Uncharted ocean mountains, trenches and ridges revealed by satellite map", site: "heguardian.co", href: "http://www.theguardian.com/science/2014/oct/03/uncharted-mountains-underwater-scars-revealed-satellite-map", time: "12 hours ago"}, 
	{title : "Turn an Android smartphone into a cosmic ray telescope", site: "isc.ed", href: "http://wipac.wisc.edu/news/view/262", time: "14 hours ago"}, 
	{title : "How to do research at the MIT AI Lab (1988) [pdf]", site: "mass.ed", href: "https://people.cs.umass.edu/~emery/misc/how-to.pdf", time: "1 day ago"}, 
	{title : "Show HN: Duckling – Open-source datetime expression parsing", site: "uckling-lib.or", href: "http://duckling-lib.org/", time: "1 day ago"}, 
	{title : "William Binney Explains Snowden Docs", site: "lexaobrien.co", href: "http://www.alexaobrien.com/secondsight/wb/binney.html", time: "2 days ago"}, 
	{title : "The State of C (1988)", site: "rdobbs.co", href: "http://www.drdobbs.com/cpp/the-state-of-c/223000089", time: "23 hours ago"}, 
	{title : "Whats Wrong with Markdown", site: "damhyde.ne", href: "http://www.adamhyde.net/whats-wrong-with-markdown/", time: "16 hours ago"}, 
]