news15 = [
	{title : "Computers are made of metal, not category theory", site: "hrisstucchio.co", href: "http://www.chrisstucchio.com/blog/2014/computers_are_made_of_metal.html", time: "2 days ago"}, 
	{title : "Raising Capital: Advice We Give Our Founders", site: "16z.co", href: "https://a16z.com/2014/09/26/valuation-this-is-the-advice-we-give-our-founders/", time: "5 days ago"}, 
	{title : "Show HN: Go channels as a C library (with Obj-C wrapper)", site: "ithub.co", href: "https://github.com/davekeck/eb_chan", time: "1 day ago"}, 
	{title : "Microsoft Announces Windows 10", site: "heverge.co", href: "http://live.theverge.com/microsoft-windows-9-event-live-blog/", time: "2 days ago"}, 
	{title : "Facebook Apologizes to LGBT Community and Promises Changes to Real Name Policy", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/01/facebook-apologizes-to-lgbt-community-and-promises-changes-to-real-name-policy/", time: "1 day ago"}, 
	{title : "Node.js Best Practices", site: "oyent.co", href: "https://www.joyent.com/developers/node/design", time: "13 days ago"}, 
	{title : "What’s a Bitcoin Look Like? The Story Behind This Popular Photograph", site: "loomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/what-s-a-bitcoin-look-like-popular-photograph-has-story.html", time: "1 day ago"}, 
	{title : "The Race to the Bottom of the 3D Engines", site: "rrlicht3d.or", href: "http://www.irrlicht3d.org/pivot/entry.php?id=1440", time: "1 day ago"}, 
	{title : "Machine learning is teaching us the secret to teaching", site: "autil.u", href: "http://nautil.us/issue/6/secret-codes/teaching-me-softly", time: "5 days ago"}, 
	{title : "Current and upcoming robots on American farms", site: "ngadget.co", href: "http://www.engadget.com/2014/09/22/robot-farming-explainer/", time: "1 day ago"}, 
	{title : "Security Breach: The London Mail Rail (2011)", site: "lacehacking.co.u", href: "http://www.placehacking.co.uk/2011/04/24/security-breach-london-mail-rail/", time: "2 days ago"}, 
	{title : "DevOps: From Unicorns to Horses", site: "mplifypartners.co", href: "http://www.amplifypartners.com/interviews/devops-from-unicorns-to-horses/", time: "1 day ago"}, 
	{title : "SendGrid Replaces CEO", site: "conomy.co", href: "http://www.xconomy.com/boulder-denver/2014/09/30/franklin-out-vmlogix-and-citrix-exec-in-as-sendgrid-replaces-ceo/", time: "1 day ago"}, 
	{title : "The Man Who Fought the Synanon Cult and Won", site: "izmodo.co", href: "http://paleofuture.gizmodo.com/the-man-who-fought-cults-and-won-1634267961", time: "4 days ago"}, 
	{title : "Mobile Web App Checklist", site: "uster.i", href: "http://www.luster.io/blog/9-29-14-mobile-web-checklist.html", time: "8 days ago"}, 
	{title : "Show HN: ScaleDrone, push messaging that makes sense", site: "caledrone.co", href: "https://www.scaledrone.com/", time: "2 days ago"}, 
	{title : "Simple, secure cloud storage", site: "eastauthority.co", href: "https://leastauthority.com/", time: "2 days ago"}, 
	{title : "Clojure Cup 2014 Apps", site: "lojurecup.co", href: "https://clojurecup.com/#/apps", time: "3 days ago"}, 
	{title : "Visual Revolution of the Vanishing of Ethan Carter", site: "heastronauts.co", href: "http://www.theastronauts.com/2014/03/visual-revolution-vanishing-ethan-carter/", time: "3 days ago"}, 
	{title : "Reddit source code", site: "ithub.co", href: "https://github.com/reddit/reddit/", time: "2 days ago"}, 
	{title : "Reddit disallows remote work after $50MM investment round", site: "witter.co", href: "https://twitter.com/dhh/status/517372782976696321", time: "1 day ago"}, 
	{title : "Building OS X Apps with JavaScript", site: "ylergaw.co", href: "http://tylergaw.com/articles/building-osx-apps-with-js", time: "5 days ago"}, 
	{title : "Why Windows 9 is Windows 10", site: "mgur.co", href: "http://i.imgur.com/p7eQQK3.png", time: "1 day ago"}, 
	{title : "It Just Works", site: "ustyshelf.or", href: "http://rustyshelf.org/2014/10/01/it-just-works/", time: "2 days ago"}, 
	{title : "Digital Ocean gives away t-shirts for commiting to public GitHub repo in October", site: "igitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/", time: "1 day ago"}, 
	{title : "Gauged – Fast, append-only storage layer for numeric data that changes over time", site: "ithub.co", href: "https://github.com/chriso/gauged", time: "1 day ago"}, 
	{title : "Immigration Crackdown on Digital Nomads in Chiang Mai, Thailand", site: "ohnnyfd.co", href: "http://www.johnnyfd.com/2014/09/live-updates-immigration-crackdown-in.html", time: "2 days ago"}, 
]