news7 = [
	{title : "Optimizing the restaurant sales receipt for maximum tips", site: "axsavin.co", href: "http://maxsavin.com/posts/receipt.html", time: "16 hours ago"}, 
	{title : "Dining Philosophers Rebooted", site: "owardhinnant.github.i", href: "http://howardhinnant.github.io/dining_philosophers.html", time: "1 day ago"}, 
	{title : "Fun with HTTP Headers (2005)", site: "extthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers?Cneonction=close", time: "1 day ago"}, 
	{title : "Building a block-chain database the right way", site: "oinspect.c", href: "http://blog.coinspect.co/building-block-chain-database-right-way", time: "21 hours ago"}, 
	{title : "How to handle a text spammer", site: "ickld.co", href: "http://www.tickld.com/x/the-best-text-reply-ever-this-is-gold", time: "11 hours ago"}, 
	{title : "Hong Kong protest: Why are pro-democracy supporters staging a sit-in?", site: "ndependent.co.u", href: "http://www.independent.co.uk/news/world/asia/hong-kong-protest-why-are-prodemocracy-supporters-staging-a-sitin-9760234.html", time: "4 days ago"}, 
	{title : "Judge Rebukes Government, Keeps Gitmo Force-Feeding Hearing Open", site: "irstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/judge-knocks-government-attempt-keep-gitmo-hearing-secret/", time: "16 hours ago"}, 
	{title : "Why Docker and containerization is a boon to web software startups", site: "ell.co", href: "http://eir.dell.com/docker-containerization-boon-web-software-startups/", time: "18 hours ago"}, 
	{title : "Simple is Fucking Hard", site: "edium.co", href: "https://medium.com/@kyle_ohara/simple-is-ing-hard-91730cf72301", time: "21 hours ago"}, 
	{title : "HFT in My Backyard", site: "niperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/09/22/hft-in-my-backyard-part-i/", time: "10 days ago"}, 
	{title : "Mou 1.0 coming early 2015", site: "ndiegogo.co", href: "https://www.indiegogo.com/projects/mou-1-0-markdown-editor-on-os-x-for-you/x/8756561", time: "14 hours ago"}, 
	{title : "Gaspard, the anti-assault accessory: never be alone again", site: "ygaspard.co", href: "http://mygaspard.com/index.php?lang=en", time: "2 hours ago"}, 
	{title : "What It’s Like to Fly the $23,000 Singapore Airlines Suites Class", site: "edium.co", href: "https://medium.com/travel-adventure/what-its-like-to-fly-the-23-000-singapore-airlines-suites-class-17d9f3fee0d", time: "2 days ago"}, 
	{title : "Eve Raises $2.3M to Rethink Programming", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/01/eve-raises-2-3m-to-rethink-programming/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29", time: "1 day ago"}, 
	{title : "What I Learned from My Time in Prison", site: "ailystormer.co", href: "http://www.dailystormer.com/what-i-learned-from-my-time-in-prison/", time: "20 hours ago"}, 
	{title : "What It's Like to Fly the $23,000 Singapore Airlines Suites Class", site: "ereklow.c", href: "http://dereklow.co/what-its-like-to-fly-the-23000-singapore-airlines-suites-class/", time: "3 days ago"}, 
	{title : "Reddit’s crappy ultimatum to remote workers and offices", site: "hortlogic.tumblr.co", href: "http://shortlogic.tumblr.com/post/99014759324/reddits-crappy-ultimatum", time: "14 hours ago"}, 
	{title : "ACPI, kernels and contracts with firmware", site: "jg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32369.html", time: "16 days ago"}, 
	{title : "JPMorgan Discovers Further Cyber Security Issues", site: "ytimes.co", href: "http://dealbook.nytimes.com/2014/10/02/jpmorgan-discovers-further-cyber-security-issues/", time: "19 hours ago"}, 
	{title : "Game about squares", site: "ameaboutsquares.co", href: "http://gameaboutsquares.com/", time: "68 days ago"}, 
	{title : "Neural-Network", site: "xxcxx.github.i", href: "https://nxxcxx.github.io/Neural-Network", time: "9 hours ago"}, 
	{title : "Choosing a Web Framework/Language Combo – Ruby on Rails", site: "acquesmattheij.co", href: "http://jacquesmattheij.com/choosing-web-framework-language-combo-srs-ruby-on-rails", time: "36 days ago"}, 
]