news13 = [
	{title : "Google Classroom", site: "oogle.co", href: "https://www.google.com/edu/classroom/", time: "4 days ago"}, 
	{title : "Using Intel VTune to Tune Software on the 4th Generation (Haswell) Processor [pdf]", site: "ntel.co", href: "https://software.intel.com/sites/default/files/article/394181/using-intel-vtune-amplifier-xe-on-4th-generation-intel-core-processors.pdf", time: "1 day ago"}, 
	{title : "Show HN: DART – Quickly search and discover startup engineering jobs", site: "art.rock", href: "http://www.dart.rocks/", time: "1 day ago"}, 
	{title : "A Field Guide to Design by Pros at Media Temple, Marvel, GA Dash and Product Hunt", site: "ention.co", href: "http://blog.mention.com/a-field-guide-to-design-where-to-begin/", time: "1 day ago"}, 
	{title : "Peter Thiel's Zero to One Might Be the Best Business Book I've Read", site: "heatlantic.co", href: "http://www.theatlantic.com/business/archive/2014/09/peter-thiel-zero-to-one-review/380738/?single_page=true", time: "5 days ago"}, 
	{title : "Atom: Editor window startup is slow", site: "ithub.co", href: "https://www.github.com/atom/atom/issues/2654", time: "2 days ago"}, 
	{title : "ComputerCOP: Dubious 'Internet Safety Software' Police Distributed to Families", site: "ff.or", href: "https://www.eff.org/deeplinks/2014/09/computercop-dangerous-internet-safety-software-hundreds-police-agencies", time: "2 days ago"}, 
	{title : "Could Uber be held liable for driver hammer attack?", site: "orbes.co", href: "http://www.forbes.com/sites/ellenhuet/2014/09/30/uber-driver-hammer-attack-liability/", time: "1 day ago"}, 
	{title : "Clarifai: Advanced Image Recognition", site: "larifai.co", href: "http://www.clarifai.com/", time: "1 day ago"}, 
	{title : "if (osName.startsWith("windows 9"))", site: "earchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22%29", time: "1 day ago"}, 
	{title : "MiniZinc, the medium-level constraint modelling language", site: "inizinc.or", href: "http://www.minizinc.org/index.html", time: "1 day ago"}, 
	{title : "The Medium Is the Message, 50 Years Later", site: "smag.co", href: "http://www.psmag.com/navigation/nature-and-technology/medium-message-50-years-later-91552/", time: "2 days ago"}, 
	{title : "StoreDot Charges Up with $42M for Its Fast-Charging Bio-Organic Batteries", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/01/storedot-series-b/", time: "1 day ago"}, 
	{title : "Mobile Malware: Small Numbers, but Growing", site: "ytimes.co", href: "http://www.nytimes.com/2014/10/02/technology/personaltech/mobile-malware-small-numbers-but-growing.html?ref=personaltech", time: "1 day ago"}, 
	{title : "Against Concentrations", site: "arry-lewis.blogspot.co", href: "http://harry-lewis.blogspot.com/2014/09/against-concentrations.html", time: "2 days ago"}, 
	{title : "J-expressions (2012)", site: "riku.or", href: "http://sriku.org/blog/2012/04/15/j-expressions/", time: "2 days ago"}, 
	{title : "OnionTip – Donate to volunteers who are running Tor relays", site: "niontip.co", href: "https://oniontip.com", time: "3 days ago"}, 
	{title : "Parallel In-Place Merge Sort", site: "rdobbs.co", href: "http://www.drdobbs.com/parallel/parallel-in-place-merge-sort/240169094", time: "2 days ago"}, 
	{title : "Mining Bitcoin with pencil and paper: 0.67 hashes per day", site: "ighto.co", href: "http://www.righto.com/2014/09/mining-bitcoin-with-pencil-and-paper.html", time: "4 days ago"}, 
	{title : "On the role of GRBs on life extinction in the Universe", site: "rxiv.or", href: "http://arxiv.org/abs/1409.2506", time: "1 day ago"}, 
	{title : "Coinbase Expands to 5 More Countries and Raises Limits for European Users", site: "oinbase.co", href: "http://blog.coinbase.com/post/98952363012/coinbase-expands-to-5-more-countries-and-raises-limits", time: "1 day ago"}, 
	{title : "The New York Times’ App Plan Isn’t Working, So It’s Laying Off Staff", site: "ecode.ne", href: "http://recode.net/2014/10/01/the-new-york-times-app-plan-isnt-working-so-its-laying-off-staff/", time: "1 day ago"}, 
	{title : "A DOMain of Shadows", site: "bracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html?m=1", time: "2 days ago"}, 
	{title : "Walrus mass in vast numbers on Alaska beach as sea ice retreats", site: "heguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/walrus-mass-vast-numbers-alaska-beach-sea-ice-retreats", time: "1 day ago"}, 
	{title : "On a farm in Missouri, a radical experiment in self-sufficiency (2013)", site: "ewyorker.co", href: "http://www.newyorker.com/magazine/2013/12/23/the-civilization-kit", time: "2 days ago"}, 
	{title : "Making a homemade metal semi-automatic rifle just got easy", site: "rstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/making-a-homemade-metal-semi-automatic-rifle-just-got-crazy-easy/", time: "1 day ago"}, 
	{title : "Google Drops Compute Engine Prices by 10 Percent", site: "echcrunch.co", href: "http://techcrunch.com/2014/10/01/google-drops-all-compute-engine-prices-by-10-percent/", time: "1 day ago"}, 
	{title : "Drone captures scale of Hong Kong protest [video]", site: "bc.co", href: "http://www.bbc.com/news/world-asia-29421914", time: "1 day ago"}, 
	{title : "Sxript: Arbitrary-precision math and programming environment", site: "mass.ed", href: "http://people.umass.edu/wfbarnes/STxAxTICMathWriteup.html", time: "1 day ago"}, 
]