news17 = [
	{title : "CVE-2014-7187 (yet another) Bash arbitrary execution of code", site: "edhat.co", href: "https://access.redhat.com/security/cve/CVE-2014-7187", time: "1 day ago"}, 
	{title : "Steve Wozniak on starting companies, solving problems, finding happiness", site: "astcodesign.co", href: "http://www.fastcodesign.com/3036366/the-wisdom-of-woz", time: "3 days ago"}, 
	{title : "Show HN: Dabble Me – the open source replacement for OhLife", site: "abble.m", href: "https://dabble.me", time: "3 days ago"}, 
	{title : "How Jerry Yang Made the Most Lucrative Bet in Tech History", site: "orbes.co", href: "http://www.forbes.com/sites/parmyolson/2014/09/30/how-jerry-yang-made-the-most-lucrative-bet-in-tech-history/", time: "2 days ago"}, 
	{title : "How 50 startups manage their code", site: "oundersgrid.co", href: "http://foundersgrid.com/code-management", time: "1 day ago"}, 
	{title : "Beating the Tinder game: 800+ Matches. I’ll probably get banned for this…", site: "edium.co", href: "https://medium.com/@blakejamieson/beating-the-tinder-game-4f08c9ec0d80", time: "1 day ago"}, 
	{title : "Show HN: Privacy – PGP Messenger", site: "edium.co", href: "https://medium.com/@krzyzanowskim/privacy-pgp-messenger-9612cd6bc08", time: "2 days ago"}, 
	{title : "Idiomatic Generics in Go", site: "ouk.c", href: "http://bouk.co/blog/idiomatic-generics-in-go/", time: "3 days ago"}, 
	{title : "Move Fast and Break Things", site: "kcd.co", href: "http://xkcd.com/1428/", time: "2 days ago"}, 
	{title : "Compatibility tables for default local fonts", site: "ontfamily.i", href: "http://fontfamily.io/", time: "2 days ago"}, 
	{title : "What “technical” concerns do I have with systemd?", site: "usis.or", href: "http://blog.lusis.org/blog/2014/09/23/end-of-linux/", time: "9 days ago"}, 
	{title : "What Working for Apple Is Really Like", site: "usinessinsider.com.a", href: "http://www.businessinsider.com.au/these-people-are-nuts-what-working-for-apple-is-really-like-2014-10", time: "2 days ago"}, 
	{title : "Just some simple game", site: "oxapp.co", href: "http://game.ioxapp.com/color/", time: "4 days ago"}, 
	{title : "Ello, goodbye", site: "ralbalkan.co", href: "https://aralbalkan.com/notes/ello-goodbye/", time: "7 days ago"}, 
	{title : "Windows 10 is the official name for Microsoft's next version of Windows", site: "heverge.co", href: "http://www.theverge.com/2014/9/30/6868695/microsoft-windows-9-announced-official", time: "2 days ago"}, 
	{title : "Emergent – Realtime Rumor Tracker", site: "mergent.inf", href: "http://www.emergent.info/", time: "6 days ago"}, 
	{title : "Kickstarter: film photography", site: "ickstarter.co", href: "https://www.kickstarter.com/projects/filmferrania/100-more-years-of-analog-film", time: "2 days ago"}, 
	{title : "Londoners give up eldest children in public Wi-Fi security horror show", site: "heguardian.co", href: "http://www.theguardian.com/technology/2014/sep/29/londoners-wi-fi-security-herod-clause", time: "4 days ago"}, 
	{title : "Bugging out: How rampant online piracy squashed one insect photographer", site: "rstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/one-mans-endless-hopeless-struggle-to-protect-his-copyrighted-images/", time: "8 days ago"}, 
	{title : "The Design and Implementation of the FreeBSD Operating System, 2nd ed.", site: "mazon.co", href: "http://www.amazon.com/Design-Implementation-FreeBSD-Operating-Edition/dp/0321968972/ref=zg_bs_3756_28", time: "16 days ago"}, 
	{title : "Exposing Hidden Biases at Google to Improve Diversity", site: "ytimes.co", href: "http://www.nytimes.com/2014/09/25/technology/exposing-hidden-biases-at-google-to-improve-diversity.html", time: "8 days ago"}, 
	{title : "Quick Explore of the Ello API", site: "ithub.co", href: "https://gist.github.com/conatus/cc665f917d5558c123bc", time: "5 days ago"}, 
	{title : "Why a Dead Alkaline Battery Bounces [video]", site: "outube.co", href: "https://www.youtube.com/watch?v=qrGV7zKEdtU", time: "28 days ago"}, 
	{title : "Bypassing AngularJS Sandbox and winning a $5,000 Google bug bounty", site: "vlidienbrunn.s", href: "http://avlidienbrunn.se/angular.txt", time: "9 days ago"}, 
	{title : "Why can't you track periods in Apple's Health app?", site: "tlk.ne", href: "http://ntlk.net/2014/09/26/why-cant-you-track-periods-in-apples-health-app/", time: "6 days ago"}, 
	{title : "Cons is your friend", site: "aygun.tumblr.co", href: "http://kaygun.tumblr.com/post/96866991234/cons-is-your-friend", time: "21 days ago"}, 
	{title : "The Fake Terror Threat Used to Justify Bombing Syria", site: "irstlook.or", href: "https://firstlook.org/theintercept/2014/09/28/u-s-officials-invented-terror-group-justify-bombing-syria/", time: "3 days ago"}, 
	{title : "What Happens When We All Live to 100?", site: "heatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/what-happens-when-we-all-live-to-100/379338/", time: "15 days ago"}, 
]