news20 = [
	{title : "A PDF that contains its own TeX source", site: "ode.google.co", href: "https://code.google.com/p/corkami/source/detail?r=1907", time: "2 days ago"}, 
	{title : "The $1,200 Machine That Lets Anyone Make a Metal Gun at Home", site: "ired.co", href: "http://www.wired.com/2014/10/cody-wilson-ghost-gunner/", time: "2 days ago"}, 
	{title : "Realtime Lyft Surge Prices", site: "onscript.ne", href: "http://lyft.konscript.net", time: "1 day ago"}, 
	{title : "U.S. Takes Asteroid Threat Seriously, Saves Nukes", site: "sj.co", href: "http://online.wsj.com/articles/u-s-takes-asteroid-threat-seriously-1412119610", time: "2 days ago"}, 
	{title : "Reddit to force relocation of remote workers", site: "witter.co", href: "https://twitter.com/yishan/status/517364923320385536", time: "1 day ago"}, 
	{title : "End of an era – No more pics from Trading Floor", site: "arketwatch.co", href: "http://www.marketwatch.com/story/this-is-the-last-photo-well-ever-run-of-the-nyse-trading-floor-2014-10-01?dist=countdown", time: "1 day ago"}, 
	{title : "Tony Hsieh Steps Down from Lead Role at Las Vegas Downtown Project", site: "ecode.ne", href: "http://recode.net/2014/09/30/tony-hsieh-steps-down-from-lead-role-at-las-vegas-downtown-project/", time: "2 days ago"}, 
	{title : "Command-line file sharing", site: "ransfer.s", href: "https://transfer.sh/", time: "3 days ago"}, 
	{title : "Scriptable Operating Systems with Lua [pdf]", site: "etbsd.or", href: "http://www.netbsd.org/~lneto/dls14.pdf", time: "2 days ago"}, 
	{title : "Click on the tile that has a different color", site: "oxapp.co", href: "http://game.ioxapp.com/color/?", time: "2 days ago"}, 
	{title : "The Internet of Furbies", site: "emsql.co", href: "http://blog.memsql.com/the-internet-of-furbies/", time: "1 day ago"}, 
	{title : "What one engineer learned when he stopped taking photos and started drawing", site: "astcompany.co", href: "http://www.fastcompany.com/3036378/my-creative-life/slowgrams-what-one-silicon-valley-engineer-learned-when-he-stopped-taking-p", time: "2 days ago"}, 
	{title : "Ellison: Sparc M7 is Oracle's most important silicon EVER", site: "heregister.co.u", href: "http://www.theregister.co.uk/2014/09/29/ellison_sparc_m7/", time: "1 day ago"}, 
	{title : "Tree-based Seekable Sequential Key Generators", site: "acr.or", href: "https://eprint.iacr.org/2014/479", time: "2 days ago"}, 
	{title : "A strange green organism has spread, clogging up the world's rivers", site: "bc.co", href: "http://www.bbc.com/earth/story/20140922-green-snot-takes-over-worlds-rivers?OCID=fbindia", time: "2 days ago"}, 
	{title : "T – a command-line power tool for Twitter", site: "ferik.github.i", href: "http://sferik.github.io/t/", time: "3 days ago"}, 
	{title : "Are Ivy League schools overrated?", site: "ndrewgelman.co", href: "http://andrewgelman.com/2014/09/30/23581/", time: "1 day ago"}, 
	{title : "Is My Shift Key on or Not", site: "smyshiftkeyonornot.co", href: "http://ismyshiftkeyonornot.com/", time: "1 day ago"}, 
	{title : "Miguel de Icaza's Markdown Style Guide", site: "irania.or", href: "http://tirania.org/blog/archive/2014/Sep-30.html", time: "2 days ago"}, 
	{title : "Under Rainier’s crater, a natural laboratory like no other", site: "eattletimes.co", href: "http://seattletimes.com/html/localnews/2024638286_rainiercavesxml.html", time: "3 days ago"}, 
	{title : "Houzz Raises $165M, Launches Online Store", site: "ecode.ne", href: "http://recode.net/2014/10/01/houzz-raises-165-million-launches-online-store/", time: "1 day ago"}, 
	{title : "10% price cuts on Google Compute Engine", site: "ooglecloudplatform.blogspot.co", href: "http://googlecloudplatform.blogspot.com/2014/10/Announcing-across-the-board-price-cuts-on-Compute-Engine.html", time: "1 day ago"}, 
	{title : "The Secret to Getting Top-Secret Secrets", site: "edium.co", href: "https://medium.com/matter/the-secret-to-getting-top-secret-secrets-1f693eaf609a", time: "2 days ago"}, 
	{title : "LinkedIn releases undergraduate university ratings", site: "inkedin.co", href: "https://www.linkedin.com/edu/rankings/us/undergraduate-software-engineering", time: "2 days ago"}, 
	{title : "My $300 Home Cloud Server", site: "cm.or", href: "http://xrds.acm.org/blog/2014/09/my-300-home-cloud-server-a-story-of-blood-sweat-and-ebay/", time: "6 days ago"}, 
	{title : "What we learned from YC S14 (even though we weren't accepted)", site: "edium.co", href: "https://medium.com/@Open_Listings/what-we-learned-from-yc-summer-2014-a419e7ffb55c", time: "1 day ago"}, 
	{title : "Taboola: The Internet firm at the forefront of 'click-bait'", site: "bc.co", href: "http://www.bbc.com/news/business-29322578", time: "2 days ago"}, 
	{title : "The economics of a web-based book", site: "racticaltypography.co", href: "http://practicaltypography.com/economics-year-one.html", time: "7 days ago"}, 
	{title : "New experimental console features in Windows “Threshold”", site: "ithinrafael.co", href: "http://withinrafael.com/new-experimental-console-features-in-windows-threshold/", time: "2 days ago"}, 
]