news6 = [
	{title : "RamanPi – The 3D Printable Raspberry Pi Raman Spectrometer", site: "ubliclab.or", href: "http://publiclab.org/notes/flatCat/08-29-2014/ramanpi-the-3d-printable-raspberry-pi-raman-spectrometer", time: "1 day ago"}, 
	{title : "Beyond Light Table", site: "hris-granger.co", href: "http://www.chris-granger.com/2014/10/01/beyond-light-table/", time: "2 days ago"}, 
	{title : "Information age tarot deck", site: "ettarot.ne", href: "http://nettarot.net", time: "12 hours ago"}, 
	{title : "iCarus – Raspberry Pi-Powered Head Unit for Cars", site: "-carus.co", href: "http://i-carus.com", time: "22 hours ago"}, 
	{title : "How to Calculate Your Startup Idea's Potential", site: "afrikan.co", href: "http://www.iafrikan.com/2014/10/03/lean-startup/", time: "7 hours ago"}, 
	{title : "California Cracks Down on Farmers Market Cheaters", site: "pr.or", href: "http://www.npr.org/blogs/thesalt/2014/10/02/352979875/california-cracks-down-on-farmers-market-cheaters?sc=tw", time: "22 hours ago"}, 
	{title : "This payload is currently being distributed using the Shellshock vulnerability", site: "ithub.co", href: "https://gist.github.com/jacquerie/0569a4a192b06f25d764", time: "18 hours ago"}, 
	{title : "U.S. v. Ross Ulbricht: Declaration of Joshua J. Horowitz [pdf]", site: "ntilop.c", href: "http://antilop.cc/sr/files/2014_10_01_Declaration_of_Josh_Horowitz_defense_attorney.pdf", time: "23 hours ago"}, 
	{title : "Why are hash functions one way?", site: "tackexchange.co", href: "http://security.stackexchange.com/questions/11717/why-are-hash-functions-one-way-if-i-know-the-algorithm-why-cant-i-calculate-t", time: "8 hours ago"}, 
	{title : "Soylent 1.1", site: "oylent.m", href: "http://blog.soylent.me/post/98982202087/introducing-soylent-1-1", time: "17 hours ago"}, 
	{title : "Shell Unshock?", site: "ash.s", href: "http://bash.sh/shell-unshock/", time: "20 hours ago"}, 
	{title : "The shodan programmer", site: "ichaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2013/04/22/gervais-macleod-23-the-shodan-programmer/", time: "9 hours ago"}, 
	{title : "Show HN: Make your site faster", site: "ager.i", href: "https://eager.io/app/ZYBle8qUhKFJ?n", time: "15 hours ago"}, 
	{title : "The Last Days of an Ancient Sword", site: "oadsandkingdoms.co", href: "http://roadsandkingdoms.com/2014/the-last-days-of-an-ancient-sword/", time: "15 hours ago"}, 
	{title : "List of Words Google considers curse words", site: "ithub.co", href: "https://github.com/jakesyl/WDYL-Curse/blob/master/output.txt", time: "18 hours ago"}, 
	{title : "Ex-Apple managers reveal Cupertino’s killer workload", site: "ultofmac.co", href: "http://www.cultofmac.com/298485/ex-apple-managers-reveal-cupertinos-killer-workload/", time: "9 hours ago"}, 
	{title : "The Betamax vs. VHS Format War", site: "ediacollege.co", href: "http://www.mediacollege.com/video/format/compare/betamax-vhs.html", time: "23 hours ago"}, 
	{title : "Re: MemSQL the “world's fastest database”? (2012)", site: "ostgresql.or", href: "http://www.postgresql.org/message-id/4FE8A2DE.5050806@agliodbs.com", time: "1 day ago"}, 
	{title : "Why no one wants to host the 2022 olympics", site: "ahoo.co", href: "https://sports.yahoo.com/news/why-no-one-wants-to-host-the-2022-olympics-225450509.html?soc_src=mediacontentstory", time: "1 day ago"}, 
	{title : "A beginners guide to writing documentation", site: "ritethedocs.or", href: "http://docs.writethedocs.org/writing/beginners-guide-to-docs/", time: "19 hours ago"}, 
	{title : "The trajectory of a software engineer… and where it all goes wrong", site: "ichaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "9 hours ago"}, 
	{title : "How I Accidentally Became an Android Developer", site: "edium.co", href: "https://medium.com/@redman/how-i-accidentally-became-an-android-developer-my-journey-from-ios-to-android-52438ca4fd0", time: "9 hours ago"}, 
	{title : "How to Stop Time", site: "ytimes.co", href: "http://www.nytimes.com/2014/09/28/opinion/sunday/how-to-stop-time.html", time: "4 days ago"}, 
	{title : "After raising $50M, Reddit forces all remote workers to relocate to SF", site: "enturebeat.co", href: "http://venturebeat.com/2014/10/01/after-raising-50m-reddit-forces-remote-workers-to-relocate-to-sf-or-get-fired/", time: "1 day ago"}, 
	{title : "Actions have consequences (or: why I'm not fixing Intel's bugs any more)", site: "jg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32778.html", time: "21 hours ago"}, 
	{title : "When a Simple Rule of Thumb Beats a Fancy Algorithm", site: "br.or", href: "http://blogs.hbr.org/2014/10/when-a-simple-rule-of-thumb-beats-a-fancy-algorithm/", time: "16 hours ago"}, 
	{title : "USB has a huge security problem that could take years to fix", site: "heverge.co", href: "http://www.theverge.com/2014/10/2/6896095/this-published-hack-could-be-the-beginning-of-the-end-for-usb", time: "11 hours ago"}, 
	{title : "The Fallacy of Premature Optimization (2009)", site: "cm.or", href: "http://ubiquity.acm.org/article.cfm?id=1513451", time: "2 days ago"}, 
	{title : "Show HN: GifBook – Animated GIFs as paper flip books", site: "ifbook.i", href: "https://gifbook.io/?hn", time: "8 hours ago"}, 
]