news21 = [
	{title : "The Most Expensive One-byte Mistake (2011)", site: "cm.or", href: "http://queue.acm.org/detail.cfm?id=2010365", time: "3 days ago"}, 
	{title : "Use Salt to manage and deploy Docker containers", site: "acksoncage.s", href: "http://jacksoncage.se/posts/2014/10/01/use-salt-to-manage-and-deploy-docker-containers/", time: "1 day ago"}, 
	{title : "The Evolution of Storm at Yahoo and Apache", site: "ahoohadoop.tumblr.co", href: "http://yahoohadoop.tumblr.com/post/98751512631/the-evolution-of-storm-at-yahoo-and-apache", time: "2 days ago"}, 
	{title : "Self-Destructing SSDs Will Nuke Themselves If You Text Them a Code Word", site: "izmodo.co", href: "http://gizmodo.com/self-destructing-ssds-will-nuke-themselves-if-you-text-1640733628", time: "2 days ago"}, 
	{title : "What the Tortoise Said to Achilles (1895)", site: "itext.co", href: "http://www.ditext.com/carroll/tortoise.html", time: "6 days ago"}, 
	{title : "Game development resources page", site: "eef.co", href: "https://game-development.zeef.com/", time: "1 day ago"}, 
	{title : "Apple's livesteam outage was easily preventable", site: "verythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/apple-livestream-outage.html", time: "2 days ago"}, 
	{title : "An Apology", site: "ackspace.co", href: "http://www.rackspace.com/blog/an-apology/", time: "2 days ago"}, 
	{title : "The government says iPhone encryption helps criminals. They're wrong", site: "ox.co", href: "http://www.vox.com/2014/9/29/6854679/iphone-encryption-james-comey-government-backdoor", time: "2 days ago"}, 
	{title : "EveryoneAPI", site: "veryoneapi.co", href: "https://www.everyoneapi.com/", time: "3 days ago"}, 
	{title : "John Carmack on Inlined Code", site: "umber-none.co", href: "http://number-none.com/blow/john_carmack_on_inlined_code.html", time: "6 days ago"}, 
	{title : "Lecture 2: How to Start a Startup", site: "amaltman.co", href: "http://startupclass.samaltman.com/courses/lec02/", time: "7 days ago"}, 
	{title : "Bad science is tolerable, résumé padding is not", site: "ohndcook.co", href: "http://www.johndcook.com/blog/2011/09/12/bad-science-is-tolerable-resume-padding-is-not/", time: "3 days ago"}, 
	{title : "Linux from Scratch", site: "inuxfromscratch.or", href: "http://www.linuxfromscratch.org/", time: "2 days ago"}, 
	{title : "Cognitive Artificial Intelligence: The MicroPsi Project", site: "icropsi.co", href: "http://www.micropsi.com/", time: "7 days ago"}, 
	{title : "How to Start a Startup: Fall 2014", site: "amaltman.co", href: "http://startupclass.samaltman.com/", time: "16 days ago"}, 
	{title : "One of the ShellShock perl script used to take control of vulnerable machines", site: "astebin.c", href: "http://pastebin.ca/2850380", time: "2 days ago"}, 
	{title : "Apple takes down another indie dev", site: "ollins.i", href: "http://blog.rollins.io/2014/09/30/the-king-makers-apple-takes-down-an-indie-dev/", time: "3 days ago"}, 
	{title : "SwiftOnSecurity: A story about Jessica", site: "wiftonsecurity.tumblr.co", href: "http://swiftonsecurity.tumblr.com/post/98675308034/a-story-about-jessica", time: "3 days ago"}, 
	{title : "The Compucolor 8001 (1976)", site: "ldcomputers.ne", href: "http://oldcomputers.net/compucolor-8001.html", time: "2 days ago"}, 
	{title : "How RAM Scrapers Work: The Tool Behind the Latest Credit Card Hacks", site: "ired.co", href: "http://www.wired.com/2014/09/ram-scrapers-how-they-work/", time: "2 days ago"}, 
	{title : "Blink an LED with JavaScript – Spark Blog", site: "park.i", href: "http://blog.spark.io/2014/09/29/blink-an-led-with-javascript/", time: "2 days ago"}, 
	{title : "I'm not sure it's Mou against the world", site: "arryhynes.ne", href: "http://larryhynes.net/2014/09/mou-against-the-world.html", time: "2 days ago"}, 
	{title : "Show HN: Realm for Android", site: "ealm.i", href: "http://realm.io/news/realm-for-android/", time: "3 days ago"}, 
	{title : "Adobe joins the Chromebook party, starting with Photoshop", site: "hrome.blogspot.co", href: "http://chrome.blogspot.com/2014/09/adobe-joins-chromebook-party-starting.html", time: "3 days ago"}, 
	{title : "Microsoft’s new Sway app – WYSIWYG", site: "heverge.co", href: "http://www.theverge.com/2014/10/1/6879999/microsoft-sway-office-app", time: "2 days ago"}, 
	{title : "Functional Programming in Swift", site: "bjc.i", href: "http://www.objc.io/books/", time: "2 days ago"}, 
]