news12 = [
	{title : "Piracy at the Old Bailey", site: "ublicdomainreview.or", href: "http://publicdomainreview.org/2014/10/01/piracy-at-the-old-bailey/", time: "1 day ago"}, 
	{title : "Search Funds: The quiet, dependable, risk-averse sibling to the startup", site: "late.co", href: "http://www.slate.com/articles/business/buy_a_small_business/2014/10/search_funds_the_quiet_dependable_risk_averse_sibling_to_the_startup.html", time: "1 day ago"}, 
	{title : "Rovio Announces Redundancies", site: "ovio.co", href: "http://www.rovio.com/en/news/blog/552/towards-a-simplified-organization", time: "1 day ago"}, 
	{title : "Cloudflare experiencing upstream network issues", site: "witter.co", href: "https://twitter.com/CloudFlareSys/status/517699118680911872", time: "1 day ago"}, 
	{title : "How Product Hunt + Hacker News fueled 300k views in 30 days", site: "edium.co", href: "https://medium.com/design-philosophies/an-overnight-success-660739c2a7e9", time: "1 day ago"}, 
	{title : "Opternative: Eye exams from the comfort of home", site: "pternative.co", href: "http://www.opternative.com/", time: "1 day ago"}, 
	{title : "Terms of Service; Didn't Read", site: "osdr.or", href: "https://tosdr.org/", time: "2 days ago"}, 
	{title : "“Do you wear pants”: T. S. Eliot’s first magazine", site: "arvard.ed", href: "http://blogs.law.harvard.edu/houghton/2014/10/01/do-you-wear-pants-t-s-eliots-first-magazine/", time: "1 day ago"}, 
	{title : "“Gasbuggy” tests nuclear fracking in the late 1960s", site: "oghs.or", href: "http://aoghs.org/technology/project-gasbuggy/", time: "1 day ago"}, 
	{title : "Delorean: Microsoft skips Windows 9, jumps to Windows 10 (2013)", site: "nfoworld.co", href: "http://www.infoworld.com/article/2613504/microsoft-windows/microsoft-windows-microsoft-skips-too-good-windows-9-jumps-to-windows-10.html", time: "23 hours ago"}, 
	{title : "Hank Green: Why am I using this shitty iPhone 4", site: "edium.co", href: "https://medium.com/@hankgreen/why-am-i-using-this-shitty-iphone-4-29c8a8514e99", time: "1 day ago"}, 
	{title : "SweetAlert – a beautiful replacement for JavaScript's alert()", site: "ristanedwards.m", href: "http://tristanedwards.me/sweetalert", time: "1 day ago"}, 
	{title : "What You Need to Know About the Ebola Outbreak", site: "ytimes.co", href: "http://www.nytimes.com/interactive/2014/07/31/world/africa/ebola-virus-outbreak-qa.html", time: "2 days ago"}, 
	{title : "Proof that HubSpot CMS sites can have amazing UI/UX", site: "reenhouse.i", href: "http://www.greenhouse.io?utm_campaign=hn", time: "1 day ago"}, 
	{title : "CDC confirms first Ebola case diagnosed in US", site: "nbc.co", href: "http://www.cnbc.com/id/102037055", time: "2 days ago"}, 
	{title : "Advanced iOS virus targeting Hong Kong protestors", site: "euters.co", href: "http://www.reuters.com/article/2014/09/30/hongkong-china-cybersecurity-apple-idUSL2N0RV2D320140930", time: "2 days ago"}, 
	{title : "Fedora Workstation Progress Report (Wayland and More)", site: "nome.or", href: "http://blogs.gnome.org/uraeus/2014/10/02/fedora-workstation-progress-report-wayland-and-more/", time: "1 day ago"}, 
	{title : "EBay to Spin Off PayPal", site: "ytimes.co", href: "http://dealbook.nytimes.com/2014/09/30/ebay-to-spin-off-paypal-adopting-strategy-backed-by-icahn/", time: "3 days ago"}, 
	{title : "Man allegedly shoots down neighbor’s drone with shotgun", site: "igitaltrends.co", href: "http://www.digitaltrends.com/cool-tech/new-jersey-man-allegedly-shoots-neighbors-drone/?utm_source=o1&utm_medium=cpc&utm_campaign=o1", time: "1 day ago"}, 
	{title : "Parallel scheduling of task trees with limited memory [pdf]", site: "rxiv.or", href: "http://arxiv.org/pdf/1410.0329.pdf", time: "1 day ago"}, 
	{title : "How to Deploy Play Framework on AWS OpsWorks", site: "riginate.co", href: "http://blog.originate.com/blog/2014/10/02/how-to-deploy-play-framework-on-aws-opsworks/", time: "23 hours ago"}, 
	{title : "Hound Reviews JavaScript for Style Violations", site: "houghtbot.co", href: "http://robots.thoughtbot.com/hound-reviews-javascript-for-style-violations", time: "22 hours ago"}, 
	{title : "Cloudflare is down", site: "witter.co", href: "https://twitter.com/search?f=realtime&q=cloudflare", time: "1 day ago"}, 
	{title : "Three years later, Pentagon unit still hides Internet voting test results", site: "cclatchydc.co", href: "http://www.mcclatchydc.com/2014/10/01/241746_three-years-later-pentagon-unit.html", time: "1 day ago"}, 
	{title : "Clock Edge Detection in Excel", site: "rdobbs.co", href: "http://www.drdobbs.com/embedded-systems/clock-edge-detectionin-excel/240169084", time: "1 day ago"}, 
	{title : "NearlyFreeSpeech.NET now supports persistent processes", site: "earlyfreespeech.ne", href: "https://blog.nearlyfreespeech.net/2014/09/24/more-power-more-control-more-insight-less-cost/", time: "2 days ago"}, 
	{title : "Show HN: Open-Source extensible personal assistant on your desktop", site: "ithub.co", href: "https://github.com/29decibel/assistant", time: "1 day ago"}, 
	{title : "Lies, Damn Lies and Version Numbers", site: "elerik.co", href: "http://developer.telerik.com/featured/lies-damn-lies-version-numbers/", time: "1 day ago"}, 
	{title : "Emotional Intelligence is Overrated", site: "inkedin.co", href: "https://www.linkedin.com/pulse/article/20140930125543-69244073-emotional-intelligence-is-overrated", time: "2 days ago"}, 
]