news30 = [
	{title : "A strange green organism has spread, clogging up the world's rivers", site: "bbc.co", href: "http://www.bbc.com/earth/story/20140922-green-snot-takes-over-worlds-rivers?OCID=fbindia", time: "4 days ago"}, 
	{title : "T – a command-line power tool for Twitter", site: "sferik.github.i", href: "http://sferik.github.io/t/", time: "5 days ago"}, 
	{title : "Are Ivy League schools overrated?", site: "andrewgelman.co", href: "http://andrewgelman.com/2014/09/30/23581/", time: "3 days ago"}, 
	{title : "Is My Shift Key on or Not", site: "ismyshiftkeyonornot.co", href: "http://ismyshiftkeyonornot.com/", time: "3 days ago"}, 
	{title : "Under Rainier’s crater, a natural laboratory like no other", site: "seattletimes.co", href: "http://seattletimes.com/html/localnews/2024638286_rainiercavesxml.html", time: "4 days ago"}, 
	{title : "Houzz Raises $165M, Launches Online Store", site: "recode.ne", href: "http://recode.net/2014/10/01/houzz-raises-165-million-launches-online-store/", time: "3 days ago"}, 
	{title : "10% price cuts on Google Compute Engine", site: "googlecloudplatform.blogspot.co", href: "http://googlecloudplatform.blogspot.com/2014/10/Announcing-across-the-board-price-cuts-on-Compute-Engine.html", time: "3 days ago"}, 
	{title : "LinkedIn releases undergraduate university ratings", site: "linkedin.co", href: "https://www.linkedin.com/edu/rankings/us/undergraduate-software-engineering", time: "3 days ago"}, 
	{title : "My $300 Home Cloud Server", site: "acm.or", href: "http://xrds.acm.org/blog/2014/09/my-300-home-cloud-server-a-story-of-blood-sweat-and-ebay/", time: "8 days ago"}, 
	{title : "What we learned from YC S14 (even though we weren't accepted)", site: "medium.co", href: "https://medium.com/@Open_Listings/what-we-learned-from-yc-summer-2014-a419e7ffb55c", time: "3 days ago"}, 
	{title : "Taboola: The Internet firm at the forefront of 'click-bait'", site: "bbc.co", href: "http://www.bbc.com/news/business-29322578", time: "3 days ago"}, 
	{title : "The economics of a web-based book", site: "practicaltypography.co", href: "http://practicaltypography.com/economics-year-one.html", time: "8 days ago"}, 
	{title : "New experimental console features in Windows “Threshold”", site: "withinrafael.co", href: "http://withinrafael.com/new-experimental-console-features-in-windows-threshold/", time: "4 days ago"}, 
	{title : "The Most Expensive One-byte Mistake (2011)", site: "acm.or", href: "http://queue.acm.org/detail.cfm?id=2010365", time: "4 days ago"}, 
	{title : "Use Salt to manage and deploy Docker containers", site: "jacksoncage.s", href: "http://jacksoncage.se/posts/2014/10/01/use-salt-to-manage-and-deploy-docker-containers/", time: "3 days ago"}, 
	{title : "The Evolution of Storm at Yahoo and Apache", site: "yahoohadoop.tumblr.co", href: "http://yahoohadoop.tumblr.com/post/98751512631/the-evolution-of-storm-at-yahoo-and-apache", time: "3 days ago"}, 
	{title : "Self-Destructing SSDs Will Nuke Themselves If You Text Them a Code Word", site: "gizmodo.co", href: "http://gizmodo.com/self-destructing-ssds-will-nuke-themselves-if-you-text-1640733628", time: "3 days ago"}, 
	{title : "What the Tortoise Said to Achilles (1895)", site: "ditext.co", href: "http://www.ditext.com/carroll/tortoise.html", time: "7 days ago"}, 
	{title : "Game development resources page", site: "zeef.co", href: "https://game-development.zeef.com/", time: "3 days ago"}, 
	{title : "An Apology", site: "rackspace.co", href: "http://www.rackspace.com/blog/an-apology/", time: "3 days ago"}, 
	{title : "The government says iPhone encryption helps criminals. They're wrong", site: "vox.co", href: "http://www.vox.com/2014/9/29/6854679/iphone-encryption-james-comey-government-backdoor", time: "3 days ago"}, 
	{title : "EveryoneAPI", site: "everyoneapi.co", href: "https://www.everyoneapi.com/", time: "4 days ago"}, 
	{title : "John Carmack on Inlined Code", site: "number-none.co", href: "http://number-none.com/blow/john_carmack_on_inlined_code.html", time: "8 days ago"}, 
	{title : "Lecture 2: How to Start a Startup", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec02/", time: "8 days ago"}, 
	{title : "Bad science is tolerable, résumé padding is not", site: "johndcook.co", href: "http://www.johndcook.com/blog/2011/09/12/bad-science-is-tolerable-resume-padding-is-not/", time: "4 days ago"}, 
	{title : "Linux from Scratch", site: "linuxfromscratch.or", href: "http://www.linuxfromscratch.org/", time: "3 days ago"}, 
	{title : "How to Start a Startup: Fall 2014", site: "samaltman.co", href: "http://startupclass.samaltman.com/", time: "18 days ago"}, 
	{title : "One of the ShellShock perl script used to take control of vulnerable machines", site: "pastebin.c", href: "http://pastebin.ca/2850380", time: "3 days ago"}, 
]