news11 = [
	{title : "Olfactory Dysfunction Predicts 5-Year Mortality in Older Adults", site: "plosone.or", href: "http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0107541", time: "2 days ago"}, 
	{title : "Read Slowly to Benefit Your Brain and Cut Stress", site: "wsj.co", href: "http://online.wsj.com/articles/read-slowly-to-benefit-your-brain-and-cut-stress-1410823086?", time: "15 days ago"}, 
	{title : "Write every day", site: "mlafeldt.github.i", href: "http://mlafeldt.github.io/blog/write-every-day/", time: "12 days ago"}, 
	{title : "Mou 1.0 coming early 2015", site: "indiegogo.co", href: "https://www.indiegogo.com/projects/mou-1-0-markdown-editor-on-os-x-for-you/x/8756561", time: "1 day ago"}, 
	{title : "Show HN: GifBook – Animated GIFs as paper flip books", site: "gifbook.i", href: "https://gifbook.io/?hn", time: "1 day ago"}, 
	{title : "If programming languages were vehicles", site: "amazonaws.co", href: "http://s3.crashworks.org.s3-website-us-east-1.amazonaws.com/if-programming-languages-were-vehicles/", time: "1 day ago"}, 
	{title : "Boring Future, Volume 1", site: "frankchimero.co", href: "http://frankchimero.com/blog/boring-future-volume-1/", time: "2 days ago"}, 
	{title : "Ranking universities based on career outcomes", site: "linkedin.co", href: "http://blog.linkedin.com/2014/10/01/ranking-universities-based-on-career-outcomes/", time: "3 days ago"}, 
	{title : "Show HN: 1HOP, a free tool to handle deep linking across all devices", site: "commandiq.co", href: "https://1hop.commandiq.com", time: "24 days ago"}, 
	{title : "Nosh – filling the gap caused by the systemd tool not being portable", site: "ntlworld.co", href: "http://homepage.ntlworld.com/jonathan.deboynepollard/Softwares/nosh.html", time: "8 days ago"}, 
	{title : "Why the Heyday of Credit Card Fraud Is Almost Over", site: "slate.co", href: "http://www.slate.com/blogs/moneybox/2014/10/03/credit_card_fraud_getting_rid_of_magstripes_will_stop_fake_cards.html", time: "1 day ago"}, 
	{title : "When Ben Bernanke can't refinance his house loan", site: "bloomberg.co", href: "http://mobile.bloomberg.com/news/2014-10-02/you-know-it-s-a-tough-market-when-ben-bernanke-can-t-refinance.html", time: "1 day ago"}, 
	{title : "Route leak incident on October 2, 2014", site: "cloudflare.co", href: "https://blog.cloudflare.com/route-leak-incident-on-october-2-2014/", time: "2 days ago"}, 
	{title : "The USSR used a nuclear charge to stop a gas well fire in 1966", site: "coal-seam-gas.co", href: "http://www.coal-seam-gas.com/accidents/ussr.htm", time: "2 days ago"}, 
	{title : "Dollar a Day", site: "dollaraday.c", href: "https://dollaraday.co/", time: "3 days ago"}, 
	{title : "Ericsson open-sources OpenWebRTC, rival to Google’s WebRTC implementation", site: "gigaom.co", href: "https://gigaom.com/2014/10/02/ericsson-open-sources-openwebrtc-to-provide-alternative-to-googles-webrtc-implementation/", time: "2 days ago"}, 
	{title : "CUPS 2.0", site: "cups.or", href: "https://www.cups.org/documentation.php/doc-2.0/relnotes.html", time: "2 days ago"}, 
	{title : "Beautiful Chemistry", site: "beautifulchemistry.ne", href: "http://beautifulchemistry.net/", time: "2 days ago"}, 
	{title : "Sway: A new presentation application from Microsoft", site: "sway.co", href: "https://sway.com/", time: "3 days ago"}, 
	{title : "Orleans – Distributed Virtual Actors for Programmability and Scalability", site: "microsoft.co", href: "http://research.microsoft.com/en-us/projects/orleans/", time: "1 day ago"}, 
	{title : "How do project owners use pull requests on GitHub?", site: "gousios.g", href: "http://www.gousios.gr/blog/How-do-project-owners-use-pull-requests-on-Github/", time: "1 day ago"}, 
	{title : "A possible future for PHP", site: "karlitschek.d", href: "http://karlitschek.de/2014/10/a-possible-future-for-php/", time: "2 days ago"}, 
	{title : "Facebook plots first steps into healthcare", site: "reuters.co", href: "http://www.reuters.com/article/2014/10/03/us-facebook-health-idUSKCN0HS09720141003", time: "1 day ago"}, 
	{title : "Hackers Have Found a Flaw in Macs", site: "businessinsider.co", href: "http://www.businessinsider.com/hackers-use-macbackdooriworm-on-mac-os-x-and-reddit-2014-10?utm_content=buffer9fb64&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer", time: "1 day ago"}, 
	{title : "Reddit requiring remote office, WFH employees to move to SF or lose their jobs", site: "nbcbayarea.co", href: "http://www.nbcbayarea.com/news/local/Reddit-Criticized-On-Reddit-For-Requiring-Workers-To-Move-to-SF--277930941.html", time: "1 day ago"}, 
	{title : "Lyft Drivers Are Burning Their Pink Mustaches", site: "vice.co", href: "http://www.vice.com/read/burning-mustaches-with-angry-lift-drivers-103", time: "1 day ago"}, 
	{title : "The Herculean Effort Taken by One Group to Show Hollywood Is Sexist", site: "fivethirtyeight.co", href: "http://fivethirtyeight.com/features/how-to-measure-women-film-annenberg/", time: "1 day ago"}, 
	{title : "Foodservice Startup Sourcery (YC W13) Streamlines How Kitchens Source Food", site: "forbes.co", href: "http://www.forbes.com/sites/ellenhuet/2014/10/03/sourcery-foodservice-platform-launch/", time: "1 day ago"}, 
]