news14 = [
	{title : "An Overview of General Performance Metrics of Binary Classifier Systems [pdf]", site: "sebastianraschka.co", href: "http://sebastianraschka.com/PDFs/articles/performance_metrics.pdf", time: "1 day ago"}, 
	{title : "FloppyNerd – WebGL/Three.js datacenter game", site: "floppynerd.s", href: "http://floppynerd.se", time: "1 day ago"}, 
	{title : "Booking.com donates $60000 to Perl development", site: "perlfoundation.or", href: "http://news.perlfoundation.org/2014/10/bookingcom-donates-60000-to-pe.html", time: "1 day ago"}, 
	{title : "What if AWS goes pop, runs out of cash?", site: "channelregister.co.u", href: "http://www.channelregister.co.uk/2014/09/25/public_iaas_crisis/", time: "1 day ago"}, 
	{title : "Sudoku, Linear Optimization, and the Ten Cent Diet", site: "googleresearch.blogspot.co", href: "http://googleresearch.blogspot.com/2014/09/sudoku-linear-optimization-and-ten-cent.html", time: "4 days ago"}, 
	{title : "Dear Reddit Employees: No Desire to Move? Let’s Talk", site: "odesk.co", href: "https://www.odesk.com/blog/2014/10/dear-reddit-employees-desire-move-lets-talk/", time: "1 day ago"}, 
	{title : "Why no one wants to host the 2022 olympics", site: "yahoo.co", href: "https://sports.yahoo.com/news/why-no-one-wants-to-host-the-2022-olympics-225450509.html?soc_src=mediacontentstory", time: "2 days ago"}, 
	{title : "Why Scrum Should Basically Just Die in a Fire", site: "gilesbowkett.blogspot.co", href: "http://gilesbowkett.blogspot.com/2014/09/why-scrum-should-basically-just-die-in.html", time: "1 day ago"}, 
	{title : "A Path to Full-time Open Source", site: "mikeperham.co", href: "http://www.mikeperham.com/2014/10/01/the-path-to-full-time-open-source/", time: "3 days ago"}, 
	{title : "I can see why it would be impossible to explain quaternions without boobs", site: "twitter.co", href: "https://twitter.com/HazelMcKendrick/status/516897598608003072", time: "1 day ago"}, 
	{title : "1 Year development plan for Straight, a Bitcoin payment processor", site: "romansnitko.co", href: "http://straight.romansnitko.com/1yeardevplan.html", time: "1 day ago"}, 
	{title : "A Visual Tour of Erlang (2012) [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lHoWfeNuAN8", time: "2 days ago"}, 
	{title : "Best Papers vs. Top Cited Papers in Computer Science", site: "arnetminer.or", href: "http://arnetminer.org/conferencebestpapers", time: "2 days ago"}, 
	{title : "A Lua interpreter written in C#", site: "moonsharp.or", href: "http://www.moonsharp.org/", time: "2 days ago"}, 
	{title : "Disassembling an attempted Shellshock exploit", site: "iinteractive.co", href: "http://iinteractive.com/notebook/2014/10/02/shellshock.html", time: "1 day ago"}, 
	{title : "Aerodrums", site: "aerodrums.co", href: "http://aerodrums.com/aerodrums/", time: "2 days ago"}, 
	{title : "Lever (YC S12) Raises $10M to Build a Human Resources and Hiring Platform", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/02/lever/", time: "1 day ago"}, 
	{title : "Ex-Apple managers reveal Cupertino’s killer workload", site: "cultofmac.co", href: "http://www.cultofmac.com/298485/ex-apple-managers-reveal-cupertinos-killer-workload/", time: "1 day ago"}, 
	{title : "Ello Says You're Not a Product, but You Are – The Atlantic", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/09/ello-says-youre-not-a-product-but-you-are/380809/", time: "1 day ago"}, 
	{title : "Actions have consequences (or: why I'm not fixing Intel's bugs any more)", site: "mjg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32778.html", time: "2 days ago"}, 
	{title : "Reddit source code", site: "github.co", href: "https://github.com/reddit/reddit/", time: "3 days ago"}, 
	{title : "How We Use AWS, Ansible, and Packer to Make Deployment Awesome", site: "branchmetrics.i", href: "http://branchmetrics.io/blog/2014/09/19/how-we-deploy/", time: "2 days ago"}, 
	{title : "BAP: Binary Analysis Platform", site: "cmu.ed", href: "http://bap.ece.cmu.edu/", time: "3 days ago"}, 
	{title : "How to find growing files on Linux", site: "aarvik.d", href: "http://aarvik.dk/how-to-find-growing-files-on-linux/", time: "1 day ago"}, 
	{title : "Lecture 3: How to Start a Startup", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec03/", time: "3 days ago"}, 
	{title : "A Fresh Look at Rust", site: "pocoo.or", href: "http://lucumr.pocoo.org/2014/10/1/a-fresh-look-at-rust/", time: "3 days ago"}, 
	{title : "Scientists twist radio beams to send data at 32 Gb/sec (x30 faster than LTE)", site: "ibtimes.co.u", href: "http://www.ibtimes.co.uk/scientists-twist-radio-beams-to-send-data-at-32-gigabits-per-second-30-times-faster-than-4g-lte-1465957", time: "1 day ago"}, 
]