news4 = [
	{title : "Machine Learning is the new Algorithms", site: "nlpers.blogspot.co", href: "http://nlpers.blogspot.com/2014/10/machine-learning-is-new-algorithms.html", time: "19 hours ago"}, 
	{title : "HFT in my backyard – III", site: "sniperinmahwah.wordpress.co", href: "http://sniperinmahwah.wordpress.com/2014/10/02/hft-in-my-backyard-iii/", time: "2 days ago"}, 
	{title : "Show HN: GoldenLayout – JavaScript Layout Manager", site: "golden-layout.co", href: "https://golden-layout.com/", time: "2 days ago"}, 
	{title : "Mistakes AngularJS Developers Make", site: "airpair.co", href: "http://www.airpair.com/angularjs/posts/top-10-mistakes-angularjs-developers-make", time: "1 day ago"}, 
	{title : "Unpatchable Malware That Infects USBs", site: "wired.co", href: "http://www.wired.com/2014/10/code-published-for-unfixable-usb-attack/", time: "2 days ago"}, 
	{title : "Introducing the World’s Most Precise Clock", site: "ieee.or", href: "http://spectrum.ieee.org/aerospace/satellites/introducing-the-worlds-most-precise-clock", time: "1 day ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math-rd", time: "2 days ago"}, 
	{title : "Cool-retro-term: A terminal emulator which mimics the old cathode display", site: "github.co", href: "https://github.com/Swordfish90/cool-retro-term", time: "2 days ago"}, 
	{title : "Privacy Statements for Windows 10 Technical Preview", site: "microsoft.co", href: "http://windows.microsoft.com/en-gb/windows/preview-privacy-statement", time: "6 hours ago"}, 
	{title : "Postgres 9.5 feature highlight: row-level security and policies", site: "otacoo.co", href: "http://michael.otacoo.com/postgresql-2/postgres-9-5-feature-highlight-row-level-security/", time: "1 day ago"}, 
	{title : "Installing Apple CarPlay and Taking It for a Spin", site: "consumerreports.or", href: "http://www.consumerreports.org/cro/news/2014/10/installing-apple-carplay-on-pioneer-stereo-and-taking-it-for-spin/index.htm", time: "1 day ago"}, 
	{title : "Reading the Silk Road configuration", site: "erratasec.co", href: "http://blog.erratasec.com/2014/10/reading-silk-road-configuration.html", time: "1 day ago"}, 
	{title : "Why I took on building a better way to frame any poster, print or photo", site: "medium.co", href: "https://medium.com/@jhubball/custom-framing-is-a-racket-61461b12278d", time: "2 days ago"}, 
	{title : "What It's Like to Build a Startup in Gaza", site: "wired.co", href: "http://www.wired.com/2014/10/like-build-startup-gaza-strip-bombs-drop/", time: "1 day ago"}, 
	{title : "Hacker's Guide to Setting Up Your Mac", site: "lapwinglabs.co", href: "http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac", time: "2 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://paulgraham.com/before.html", time: "2 days ago"}, 
	{title : "We Got Accepted into Techstars and Turned Them Down", site: "talkroute.co", href: "http://talkroute.com/got-accepted-into-techstars-turned-it-down/", time: "1 day ago"}, 
	{title : "Show HN: Franc – Detect natural languages", site: "github.co", href: "https://github.com/wooorm/franc", time: "1 day ago"}, 
	{title : "Most People with Addiction Simply Grow Out of It", site: "substance.co", href: "http://www.substance.com/most-people-with-addiction-simply-grow-out-of-it-why-is-this-widely-denied/13017/", time: "3 days ago"}, 
	{title : "Labour is steadily losing out to capital", site: "economist.co", href: "http://www.economist.com/news/special-report/21621160-labour-steadily-losing-out-capital-those-have-shall-be-given", time: "1 day ago"}, 
	{title : "Show HN: HelloBitcoin. A “Hello World” of Bitcoin, Written in Go", site: "github.co", href: "https://github.com/prettymuchbryce/hellobitcoin", time: "1 day ago"}, 
	{title : "India, U.S. Agree to Joint Exploration of Mars", site: "wsj.co", href: "http://blogs.wsj.com/indiarealtime/2014/10/01/india-u-s-to-agree-to-joint-exploration-of-mars", time: "2 days ago"}, 
	{title : "Power Up Your Team with Nonviolent Communication Principles", site: "firstround.co", href: "http://firstround.com/article/power-up-your-team-with-nonviolent-communication-principles", time: "10 hours ago"}, 
	{title : "Major Updates to Firebase User Authentication", site: "firebase.co", href: "https://www.firebase.com/blog/2014-10-03-major-updates-to-firebase-user-auth.html", time: "1 day ago"}, 
	{title : "Aids: Origin of pandemic 'was 1920s Kinshasa'", site: "bbc.co", href: "http://www.bbc.com/news/health-29442642", time: "1 day ago"}, 
	{title : "Apple allows hot code push for JS downloaded and run by WebKit", site: "meteor.co", href: "https://www.meteor.com/blog/2014/10/02/Apple-hot-code-push-mobile", time: "2 days ago"}, 
	{title : "Creating your own Heroku on EC2", site: "clearbit.c", href: "http://blog.clearbit.co/ec2-heroku?hn", time: "1 day ago"}, 
	{title : "Three months at Y Combinator: what it’s like and how to get in", site: "frontapp.co", href: "http://blog.frontapp.com/three-months-at-y-combinator-what-its-like-and-how-to-get-in/", time: "2 days ago"}, 
	{title : "Adventures in 19th-century photography", site: "mortalmuses.co", href: "http://mortalmuses.com/2014/10/03/adventures-in-19th-century-photography/", time: "1 day ago"}, 
]