news9 = [
	{title : "After raising $50M, Reddit forces all remote workers to relocate to SF", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/01/after-raising-50m-reddit-forces-remote-workers-to-relocate-to-sf-or-get-fired/", time: "2 days ago"}, 
	{title : "A startup who just presented in TC Disrupt Battlefield refuses to pay for design", site: "layervault.co", href: "https://news.layervault.com/stories/35272-client-a-startup-who-just-presented-in-tc-disrupt-battlefield-refuses-to-pay-for-design", time: "18 hours ago"}, 
	{title : "Systemd to the rescue", site: "achernya.co", href: "http://blog.achernya.com/2014/10/systemd-to-rescue.html", time: "1 day ago"}, 
	{title : "Beyond Light Table", site: "chris-granger.co", href: "http://www.chris-granger.com/2014/10/01/beyond-light-table/", time: "3 days ago"}, 
	{title : "Unreal Intro – WebGL reimplementation", site: "shadertoy.co", href: "https://www.shadertoy.com/view/ls2SDD", time: "20 hours ago"}, 
	{title : "The Ebola Patient Was Sent Home Because of Bad Software", site: "theatlantic.co", href: "http://m.theatlantic.com/health/archive/2014/10/the-ebola-patient-was-sent-home-because-of-an-electronic-health-record-problem/381087/", time: "23 hours ago"}, 
	{title : "Code that should never be reached", site: "github.co", href: "https://github.com/search?o=desc&q=%22should+never+be+reached%22&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93", time: "21 hours ago"}, 
	{title : "Show HN: Gmail Extension to track and secure docs you send", site: "streak.co", href: "https://www.streak.com/docsend", time: "1 day ago"}, 
	{title : "Partial list of ethical concerns in the video game industry", site: "leighalexander.ne", href: "http://leighalexander.net/list-of-ethical-concerns-in-video-games-partial/", time: "23 hours ago"}, 
	{title : "Hackers are using Reddit to control 17,000 Apple computers", site: "independent.co.u", href: "http://www.independent.co.uk/life-style/gadgets-and-tech/hackers-are-using-reddit-to-control-17000-apple-computers-9773032.html", time: "1 day ago"}, 
	{title : "Relativistic hash tables", site: "lwn.ne", href: "http://lwn.net/SubscriberLink/612021/92c8ccb5b82d4d90/", time: "10 days ago"}, 
	{title : "Quantum mechanics as a generalization of probability (2007)", site: "scottaaronson.co", href: "http://www.scottaaronson.com/democritus/lec9.html", time: "7 days ago"}, 
	{title : "Hacking with DNS", site: "docs.google.co", href: "https://docs.google.com/presentation/d/1HfXVJyXElzBshZ9SYNjBwJf_4MBaho6UcATTFwApfXw", time: "7 days ago"}, 
	{title : "My Google Interview Experience", site: "mallya.m", href: "http://mallya.me/2014/09/30/google-interview.html", time: "1 day ago"}, 
	{title : "The trajectory of a software engineer… and where it all goes wrong", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "1 day ago"}, 
	{title : "Ebola hospital statement blaming earlier missed diagnosis on software", site: "texashealth.or", href: "http://www.texashealth.org/body.cfm?id=1629&action=detail&ref=1871", time: "1 day ago"}, 
	{title : "Good looking addresses – solving the “Berlin, Berlin” bug", site: "opencagedata.co", href: "http://blog.opencagedata.com/post/99059889253/good-looking-addresses-solving-the-berlin-berlin", time: "1 day ago"}, 
	{title : "How NYC's New On-Demand Shipping App Could Survive", site: "citylab.co", href: "http://www.citylab.com/tech/2014/10/heres-how-nycs-new-on-demand-shipping-app-could-actually-survive/381006/", time: "1 day ago"}, 
	{title : "Making Fast-Paced Multiplayer Networked Games Is Hard", site: "gamasutra.co", href: "http://www.gamasutra.com/blogs/MarkMennell/20140929/226628/Making_FastPaced_Multiplayer_Networked_Games_is_Hard.php", time: "2 days ago"}, 
	{title : "Logstalgia: website access log visualization", site: "code.google.co", href: "https://code.google.com/p/logstalgia/", time: "2 days ago"}, 
	{title : "JPMorgan Chase Breach Reveals a Dire Talent Emergency", site: "forbes.co", href: "http://www.forbes.com/sites/brucekasanoff/2014/10/03/jpmorgan-chase-breach-reveals-a-dire-talent-emergency/", time: "23 hours ago"}, 
	{title : "Qattara Depression Project", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Qattara_Depression_Project", time: "23 hours ago"}, 
	{title : "Court extends Butterfly Labs asset freeze", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/court-extends-butterfly-labs-asset-freeze/", time: "23 hours ago"}, 
	{title : "Japan stocks rattled by $617bn 'fat finger' trading error", site: "bbc.co", href: "http://www.bbc.com/news/business-29454265", time: "1 day ago"}, 
	{title : "Librarians won’t stay quiet about government surveillance", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/the-switch/wp/2014/10/03/librarians-wont-stay-quiet-about-government-surveillance/", time: "1 day ago"}, 
	{title : "17,000 Macs recruited into malware botnet, with a little help from Reddit", site: "grahamcluley.co", href: "http://grahamcluley.com/2014/10/mac-malware-botnet-reddit/", time: "1 day ago"}, 
	{title : "Algolia (YC W14) debuts free plan, opens West Coast data center", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/01/search-as-a-service-provider-algolia-debuts-free-plan-opens-west-coast-data-center", time: "2 days ago"}, 
	{title : "JPMorgan Says Data Breach Affected 76M Households", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/jpmorgan-says-data-breach-affected-76-million-households.html", time: "1 day ago"}, 
]