news10 = [
	{title : "Founder Suicides", site: "feld.co", href: "http://www.feld.com/archives/2014/10/founder-suicides.html", time: "1 day ago"}, 
	{title : "CDN53", site: "zorinaq.co", href: "http://blog.zorinaq.com/?e=77", time: "1 day ago"}, 
	{title : "How I Accidentally Became an Android Developer", site: "medium.co", href: "https://medium.com/@redman/how-i-accidentally-became-an-android-developer-my-journey-from-ios-to-android-52438ca4fd0", time: "1 day ago"}, 
	{title : "Adaptive Path: Where We’re Going Next", site: "adaptivepath.co", href: "http://www.adaptivepath.com/ideas/adaptive-path-where-were-going-next/", time: "2 days ago"}, 
	{title : "‘The Innovators’ by Walter Isaacson: How Women Shaped Technology", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/fashion/the-innovators-by-walter-isaacson-how-women-shaped-technology.html?_r=1", time: "2 days ago"}, 
	{title : "Clojure from the ground up: debugging", site: "aphyr.co", href: "http://aphyr.com/posts/319-clojure-from-the-ground-up-debugging", time: "1 day ago"}, 
	{title : "The Secret to Getting Top-Secret Secrets", site: "medium.co", href: "https://medium.com/matter/the-secret-to-getting-top-secret-secrets-1f693eaf609a", time: "4 days ago"}, 
	{title : "Write your own Virtual CPU in C++", site: "megalomaniacbore.blogspot.co", href: "http://megalomaniacbore.blogspot.com/2014/04/virtual-cpu-in-c-4001-cpu.html", time: "7 days ago"}, 
	{title : "Cops kill Georgia grandpa in no-knock raid triggered by burglary suspect’s tip", site: "rawstory.co", href: "http://www.rawstory.com/rs/2014/10/cops-kill-georgia-grandpa-in-no-knock-raid-triggered-by-burglary-suspects-tip", time: "1 day ago"}, 
	{title : "Cognitive Artificial Intelligence: The MicroPsi Project", site: "micropsi.co", href: "http://www.micropsi.com/", time: "8 days ago"}, 
	{title : "Show HN: Pagerbot, a chat bot for managing PagerDuty on-call schedules", site: "stripe.co", href: "https://stripe.com/blog/pagerbot", time: "8 days ago"}, 
	{title : "On the Design of Editors for Small Computers (1972)", site: "ed.ac.u", href: "http://history.dcs.ed.ac.uk/archive/apps/Whitfield-Thesis/thesis.html", time: "7 days ago"}, 
	{title : "Shen – A Sufficiently Advanced Lisp [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=lMcRBdSdO_U&list=UU_QIfHvN9auy2CoOdSfMWDw", time: "10 days ago"}, 
	{title : "Why Docker and containerization is a boon to web software startups", site: "dell.co", href: "http://eir.dell.com/docker-containerization-boon-web-software-startups/", time: "1 day ago"}, 
	{title : "The Urban Village", site: "mit.ed", href: "http://senseable.mit.edu/urbanvillages/", time: "2 hours ago"}, 
	{title : "Computers are made of metal, not category theory", site: "chrisstucchio.co", href: "http://www.chrisstucchio.com/blog/2014/computers_are_made_of_metal.html", time: "3 days ago"}, 
	{title : "A Tiny Emissary from the Ancient Past", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/25/science/a-tiny-emissary-from-the-ancient-past.html", time: "8 days ago"}, 
	{title : "Amazon Warehouse Workers Want to Be Paid for Waiting in Line", site: "businessweek.co", href: "http://www.businessweek.com/articles/2014-10-02/security-checks-paid-as-work-supreme-court-will-decide", time: "1 day ago"}, 
	{title : "SSHARK – DNS-based expiration and revocation of SSH client keys", site: "sshark.or", href: "http://www.sshark.org/", time: "1 day ago"}, 
	{title : "How to Ace a Data Science Interview", site: "alyaabbott.wordpress.co", href: "http://alyaabbott.wordpress.com/2014/10/01/how-to-ace-a-data-science-interview/", time: "1 day ago"}, 
	{title : "The Earliest Known Color Photographs of the 1906 San Francisco Earthquake ", site: "mashable.co", href: "http://mashable.com/2014/10/03/san-francisco-earthquake-color-photos", time: "1 day ago"}, 
	{title : "Fighting to Honor a Father’s Last Wish: To Die at Home", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/26/nyregion/family-fights-health-care-system-for-simple-request-to-die-at-home.html", time: "8 days ago"}, 
	{title : "Cavium sponsors FreeBSD's ARMv8 implementation", site: "cavium.co", href: "http://www.cavium.com/newsevents-Cavium-Sponsor-FreeBSD-ARMv8-Based-Implementation.html", time: "2 days ago"}, 
	{title : "The Missing SDK for Hybrid App Development", site: "mozilla.or", href: "https://hacks.mozilla.org/2014/10/the-missing-sdk-for-hybrid-app-development/", time: "3 days ago"}, 
	{title : "When a Simple Rule of Thumb Beats a Fancy Algorithm", site: "hbr.or", href: "http://blogs.hbr.org/2014/10/when-a-simple-rule-of-thumb-beats-a-fancy-algorithm/", time: "1 day ago"}, 
	{title : "How to Calculate Your Startup Idea's Potential", site: "iafrikan.co", href: "http://www.iafrikan.com/2014/10/03/lean-startup/", time: "1 day ago"}, 
	{title : "Simple is Fucking Hard", site: "medium.co", href: "https://medium.com/@kyle_ohara/simple-is-ing-hard-91730cf72301", time: "2 days ago"}, 
]