news2 = [
	{title : "IRIS+", site: "3drobotics.co", href: "http://3drobotics.com/iris-plus/", time: "1 day ago"}, 
	{title : "Tobacco plant may be key to Ebola drugs", site: "cnn.co", href: "http://www.cnn.com/2014/10/03/health/ebola-tobacco-plant/", time: "21 hours ago"}, 
	{title : "Pace4000 hidden testing modes", site: "sodnpoo.co", href: "http://www.sodnpoo.com/posts.xml/pace4000_testing_modes.xml", time: "3 hours ago"}, 
	{title : "Engineering management lessons", site: "defmacro.or", href: "http://www.defmacro.org/2014/10/03/engman.html", time: "1 day ago"}, 
	{title : "Saeed Malekpour, programmer and political prisoner in Iran", site: "github.co", href: "https://github.com/saeedmalekpour", time: "1 hour ago"}, 
	{title : "The Ambiguities of Prison Gangs", site: "theatlantic.co", href: "http://www.theatlantic.com/national/archive/2014/10/gangs-and-prisons/381034/?single_page=true", time: "19 hours ago"}, 
	{title : "Pangrams on the web", site: "farside.org.u", href: "https://www.farside.org.uk/201410/pangrams_on_the_web", time: "19 hours ago"}, 
	{title : "Can Big Data Tell Us What Clinical Trials Don’t?", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/magazine/can-big-data-tell-us-what-clinical-trials-dont.html?rref=magazine&module=Ribbon&version=context&region=Header&action=click&contentCollection=Magazine&pgtype=article", time: "14 hours ago"}, 
	{title : "Colleges Make It Easier for Students to Show, Not Tell, in Their Applications", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/28/education/college-admissions-goucher-video.html", time: "13 hours ago"}, 
	{title : "Haskell, Monads and Purity", site: "jelv.i", href: "http://jelv.is/blog/Haskell-Monads-and-Purity/", time: "19 hours ago"}, 
	{title : "ForestDb – A Fast Key-Value Storage Engine Based on Hierarchical B+-Tree Trie", site: "github.co", href: "https://github.com/couchbaselabs/forestdb", time: "8 hours ago"}, 
	{title : "Accidental release of 45L of polio virus solution into the environment – Belgium", site: "europa.e", href: "http://www.ecdc.europa.eu/en/press/news/_layouts/forms/News_DispForm.aspx?List=8db7286c-fe2d-476c-9133-18ff4cb1b568&ID=1065", time: "20 hours ago"}, 
	{title : "Arduino LED Startup Counter", site: "matthack.co", href: "http://matthack.com/startup-counter/", time: "7 hours ago"}, 
	{title : "NgMario", site: "blnight.github.i", href: "http://blnight.github.io/ngMario/#/game", time: "15 hours ago"}, 
	{title : "National Nurse Survey Shows Hospitals Still Not Prepared for U.S. Ebola Patients", site: "nationalnursesunited.or", href: "http://www.nationalnursesunited.org/press/entry/national-nurse-survey-shows-hospitals-still-not-prepared-for-us-ebola/", time: "2 hours ago"}, 
	{title : "Supporting idea convergence through pedagogical scripts and Etherpad APIs", site: "reganmian.ne", href: "http://reganmian.net/blog/2014/10/03/supporting-idea-convergence-through-pedagogical-scripts/", time: "2 hours ago"}, 
	{title : "Consider the Lobster (2004)", site: "gourmet.co", href: "http://www.gourmet.com/magazine/2000s/2004/08/consider_the_lobster?printable=true", time: "23 hours ago"}, 
	{title : "Show HN: Dependency Update as a Service", site: "tachikoma.i", href: "http://tachikoma.io/", time: "9 hours ago"}, 
	{title : "Schneier on Incident Response", site: "lwn.ne", href: "http://lwn.net/Articles/612818/", time: "7 hours ago"}, 
	{title : "WebSharper: Make web apps in F#", site: "websharper.co", href: "http://websharper.com/", time: "23 hours ago"}, 
	{title : "The Man Who Smuggles Traders Joe’s into Canada", site: "priceonomics.co", href: "http://priceonomics.com/the-man-who-smuggles-traders-joes-into-canada/", time: "1 day ago"}, 
	{title : "Why is 0x00400000 the default base address for an executable?", site: "msdn.co", href: "http://blogs.msdn.com/b/oldnewthing/archive/2014/10/03/10562176.aspx", time: "1 day ago"}, 
	{title : "Bang – An Atari 2600 VCS Demo", site: "xayax.ne", href: "http://xayax.net/bang!/", time: "17 hours ago"}, 
	{title : "The Magic CmdLine and how I got it back", site: "ntua.g", href: "http://users.softlab.ece.ntua.gr/~ttsiod/bashheimer.html", time: "1 day ago"}, 
	{title : "Refactoring Ruby with Monads", site: "codon.co", href: "http://codon.com/refactoring-ruby-with-monads", time: "1 day ago"}, 
	{title : "Aboard Amtrak", site: "spnzr.co", href: "http://spnzr.com/aboard-amtrak", time: "1 day ago"}, 
	{title : "Aboard a Cargo Colossus: Maersk’s New Container Ships", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/business/international/aboard-a-cargo-colossus-maersks-new-container-ships.html?hp&action=click&pgtype=Homepage&version=HpSumSmallMediaHigh&module=second-column-region&region=top-news&WT.nav=top-news&_r=0", time: "1 day ago"}, 
]