news27 = [
	{title : "Move Fast and Break Things", site: "xkcd.co", href: "http://xkcd.com/1428/", time: "3 days ago"}, 
	{title : "Compatibility tables for default local fonts", site: "fontfamily.i", href: "http://fontfamily.io/", time: "4 days ago"}, 
	{title : "What “technical” concerns do I have with systemd?", site: "lusis.or", href: "http://blog.lusis.org/blog/2014/09/23/end-of-linux/", time: "10 days ago"}, 
	{title : "What Working for Apple Is Really Like", site: "businessinsider.com.a", href: "http://www.businessinsider.com.au/these-people-are-nuts-what-working-for-apple-is-really-like-2014-10", time: "3 days ago"}, 
	{title : "Just some simple game", site: "ioxapp.co", href: "http://game.ioxapp.com/color/", time: "5 days ago"}, 
	{title : "Windows 10 is the official name for Microsoft's next version of Windows", site: "theverge.co", href: "http://www.theverge.com/2014/9/30/6868695/microsoft-windows-9-announced-official", time: "4 days ago"}, 
	{title : "Emergent – Realtime Rumor Tracker", site: "emergent.inf", href: "http://www.emergent.info/", time: "8 days ago"}, 
	{title : "Kickstarter: film photography", site: "kickstarter.co", href: "https://www.kickstarter.com/projects/filmferrania/100-more-years-of-analog-film", time: "4 days ago"}, 
	{title : "Bugging out: How rampant online piracy squashed one insect photographer", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/one-mans-endless-hopeless-struggle-to-protect-his-copyrighted-images/", time: "9 days ago"}, 
	{title : "The Design and Implementation of the FreeBSD Operating System, 2nd ed.", site: "amazon.co", href: "http://www.amazon.com/Design-Implementation-FreeBSD-Operating-Edition/dp/0321968972/ref=zg_bs_3756_28", time: "17 days ago"}, 
	{title : "Exposing Hidden Biases at Google to Improve Diversity", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/25/technology/exposing-hidden-biases-at-google-to-improve-diversity.html", time: "10 days ago"}, 
	{title : "Quick Explore of the Ello API", site: "github.co", href: "https://gist.github.com/conatus/cc665f917d5558c123bc", time: "6 days ago"}, 
	{title : "Why a Dead Alkaline Battery Bounces [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=qrGV7zKEdtU", time: "29 days ago"}, 
	{title : "Bypassing AngularJS Sandbox and winning a $5,000 Google bug bounty", site: "avlidienbrunn.s", href: "http://avlidienbrunn.se/angular.txt", time: "10 days ago"}, 
	{title : "Why can't you track periods in Apple's Health app?", site: "ntlk.ne", href: "http://ntlk.net/2014/09/26/why-cant-you-track-periods-in-apples-health-app/", time: "8 days ago"}, 
	{title : "Cons is your friend", site: "kaygun.tumblr.co", href: "http://kaygun.tumblr.com/post/96866991234/cons-is-your-friend", time: "23 days ago"}, 
	{title : "The Fake Terror Threat Used to Justify Bombing Syria", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/09/28/u-s-officials-invented-terror-group-justify-bombing-syria/", time: "5 days ago"}, 
	{title : "What Happens When We All Live to 100?", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/what-happens-when-we-all-live-to-100/379338/", time: "16 days ago"}, 
	{title : "Synergy (mouse and keyboard sharing over a network) goes from free to paid", site: "synergy-project.or", href: "http://synergy-project.org/download/", time: "10 days ago"}, 
	{title : "Recruiter: Startups Are Offering Crazy, 1999-Like Hiring Incentives", site: "businessinsider.co", href: "http://www.businessinsider.com/startups-offering-1-million-signing-bonuses-2014-9", time: "6 days ago"}, 
	{title : "Live attacks against the Norse honeypot infrastructure", site: "ipviking.co", href: "http://map.ipviking.com/", time: "57 days ago"}, 
	{title : "Entrepreneurs anonymous: People should understand how hard their lives can be", site: "economist.co", href: "http://www.economist.com/news/business/21618816-instead-romanticising-entrepreneurs-people-should-understand-how-hard-their-lives-can", time: "16 days ago"}, 
	{title : "Affinity Designer – Illustrator alternative", site: "serif.co", href: "https://affinity.serif.com/", time: "65 days ago"}, 
	{title : "The Cardinal Sin of Software Engineering", site: "theeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/cardinal-sin-of-software-engineering", time: "10 days ago"}, 
	{title : "Show HN: Socktunes, the music search engine", site: "socktunes.co", href: "http://socktunes.com", time: "7 days ago"}, 
	{title : "Using your RDBMS for messaging is totally OK", site: "jooq.or", href: "http://blog.jooq.org/2014/09/26/using-your-rdbms-for-messaging-is-totally-ok/", time: "7 days ago"}, 
	{title : "Effective Code Reviews", site: "originate.co", href: "http://blog.originate.com/blog/2014/09/29/effective-code-reviews/", time: "5 days ago"}, 
	{title : "Why startups fail (according to their founders)", site: "fortune.co", href: "http://fortune.com/2014/09/25/why-startups-fail-according-to-their-founders/", time: "9 days ago"}, 
	{title : "Tour of pyramids of Giza using Google Maps street view", site: "google.co", href: "http://www.google.com/maps/about/behind-the-scenes/streetview/treks/pyramids-of-giza/", time: "24 days ago"}, 
	{title : "Living Simply in a Dumpster", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/09/the-simple-life-in-a-dumpster/379947/", time: "23 days ago"}, 
]