news12 = [
	{title : "Wal-Mart Senior Greeter Story", site: "interomojo.co", href: "http://interomojo.com/2011/07/04/monday-mojo-wal-mart-senior-greeter/", time: "1 day ago"}, 
	{title : "Trends in the Silk Road 2.0", site: "lau.i", href: "http://lau.im/articles/analyzing-silk-road-2-0-part-1/", time: "5 days ago"}, 
	{title : "Place SSH users in Docker jails (or as replacement for docker-bash / dockersh)", site: "github.co", href: "https://github.com/clevcode/docker-cmd", time: "1 day ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977&c=5&lng=en&p=0", time: "1 day ago"}, 
	{title : "Building an alternative Silicon Valley", site: "austingrandt.co", href: "http://austingrandt.com/building-alternative-silicon-valley/", time: "1 day ago"}, 
	{title : "Growth, efficiency, and yield of commercial broilers from 1957, 1978, and 2005", site: "oxfordjournals.or", href: "http://ps.oxfordjournals.org/content/early/2014/09/26/ps.2014-04291.abstract", time: "1 day ago"}, 
	{title : "Moving to Sublime 3 after 15 yrs with TextPad – reasons, comparisons, and tips", site: "aliteralmind.wordpress.co", href: "http://aliteralmind.wordpress.com/2014/10/02/textpad_to_sublime/", time: "2 days ago"}, 
	{title : "Etsy’s Trying to Fix Tech’s Women Problem. Why Aren’t You?", site: "medium.co", href: "https://medium.com/matter/this-is-the-last-thing-youll-ever-need-to-read-about-sexism-in-tech-56b9a3a77af0", time: "1 day ago"}, 
	{title : "Implementing highly efficient data structures with Monoids and Fingertrees", site: "codementor.i", href: "https://www.codementor.io/haskell-tutorial/monoids-fingertrees-implement-abstract-data", time: "2 days ago"}, 
	{title : "Y Combinator and the Negative Externalities of Hackernews", site: "danilocampos.co", href: "http://danilocampos.com/2014/09/y-combinator-and-the-negative-externalities-of-hacker-news/", time: "4 days ago"}, 
	{title : "Why women leave tech because they have good taste", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/why-women-leave-tech-they-have-good-taste.html", time: "1 day ago"}, 
	{title : "My experience with using cp to copy 432 million files (39 TB)", site: "gnu.or", href: "http://lists.gnu.org/archive/html/coreutils/2014-08/msg00012.html", time: "22 days ago"}, 
	{title : "My coworkers made me use Mac OS 9", site: "arstechnica.co", href: "http://arstechnica.com/apple/2014/09/my-coworkers-made-me-use-mac-os-9-for-their-and-your-amusement/", time: "6 days ago"}, 
	{title : "Cubic Bezier Curves – Under the Hood", site: "vimeo.co", href: "http://vimeo.com/106757336", time: "2 days ago"}, 
	{title : "Apple's livesteam outage was easily preventable", site: "everythingsysadmin.co", href: "http://everythingsysadmin.com/2014/10/apple-livestream-outage.html", time: "3 days ago"}, 
	{title : "CppCon 2014: Mike Acton “Data-Oriented Design and C++”", site: "youtube.co", href: "https://www.youtube.com/watch?v=rX0ItVEVjHc", time: "3 days ago"}, 
	{title : "Microsoft’s Cube debuts at Decibel, creating a one-of-a-kind digital dance party", site: "microsoft.co", href: "http://blogs.microsoft.com/next/2014/09/24/microsoft-cube-decibel-dance-music/", time: "7 days ago"}, 
	{title : "Beaker Notebook v1.0 released – open-source polyglot data science web app", site: "beakernotebook.co", href: "http://beakernotebook.com", time: "9 days ago"}, 
	{title : "Is Coding Art?", site: "newrepublic.co", href: "http://www.newrepublic.com/article/119215/geek-sublime-vikram-chandra-review-coding-art", time: "3 days ago"}, 
	{title : "Cloudera Acquires DataPad Technology Assets and Team", site: "cloudera.co", href: "http://www.cloudera.com/content/cloudera/en/about/press-center/press-releases/2014/09/30/cloudera-acquires-datapad-technology-assets-and-team-to-strength.html", time: "3 days ago"}, 
	{title : "An Inside Look at Anonymous, the Radical Hacking Collective", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/09/08/masked-avengers", time: "31 days ago"}, 
	{title : "Dear clueless assholes: stop bashing bash and GNU", site: "weev.livejournal.co", href: "https://weev.livejournal.com/409835.html", time: "6 days ago"}, 
	{title : "Windows 10: Code that uses 'os.StartsWith(“Windows 9”)'", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22", time: "7 hours ago"}, 
	{title : "Patoline: A modern digital typesetting system", site: "patoline.or", href: "http://patoline.org/", time: "84 days ago"}, 
	{title : "Reddit’s crappy ultimatum to remote workers and offices", site: "shortlogic.tumblr.co", href: "http://shortlogic.tumblr.com/post/99014759324/reddits-crappy-ultimatum", time: "1 day ago"}, 
	{title : "Why I've Said Goodbye to Mobile in Favor of PC", site: "gamasutra.co", href: "http://gamasutra.com/blogs/ThomasHenshell/20140807/222732/Why_Ive_Said_Goodbye_to_Mobile_in_Favor_of_PC.php", time: "54 days ago"}, 
	{title : "Butterfly: Your everyday terminal in your web browser", site: "paradoxxxzero.github.i", href: "http://paradoxxxzero.github.io/2014/02/28/butterfly.html", time: "218 days ago"}, 
]