news15 = [
	{title : "CVE-2014-7284: Lack of randomness in Linux kernel network secrets", site: "secondlookforensics.co", href: "http://secondlookforensics.com/ngro-linux-kernel-bug/", time: "2 days ago"}, 
	{title : "Uncharted ocean mountains, trenches and ridges revealed by satellite map", site: "theguardian.co", href: "http://www.theguardian.com/science/2014/oct/03/uncharted-mountains-underwater-scars-revealed-satellite-map", time: "1 day ago"}, 
	{title : "Turn an Android smartphone into a cosmic ray telescope", site: "wisc.ed", href: "http://wipac.wisc.edu/news/view/262", time: "1 day ago"}, 
	{title : "How to do research at the MIT AI Lab (1988) [pdf]", site: "umass.ed", href: "https://people.cs.umass.edu/~emery/misc/how-to.pdf", time: "2 days ago"}, 
	{title : "The State of C (1988)", site: "drdobbs.co", href: "http://www.drdobbs.com/cpp/the-state-of-c/223000089", time: "2 days ago"}, 
	{title : "How Hong Kong Protesters Are Connecting, Without Cell or Wi-Fi Networks", site: "npr.or", href: "http://www.npr.org/blogs/alltechconsidered/2014/09/29/352476454/how-hong-kong-protesters-are-connecting-without-cell-or-wi-fi-networks", time: "4 days ago"}, 
	{title : "Redesigning the OpenDNS DNS database for low latency", site: "opendns.co", href: "http://labs.opendns.com/2014/10/01/redesigning-dns-database-low-latency/", time: "2 days ago"}, 
	{title : "First Blood Test to Diagnose Depression in Adults?", site: "northwestern.ed", href: "http://www.northwestern.edu/newscenter/stories/2014/09/first-blood-test-to-diagnose-depression-in-adults.html", time: "3 days ago"}, 
	{title : "Atlantic.net launches $0.99 SSD-based VPS servers", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/atlantic-net-launches-0-99month-ssd-based-vps-hosting-service/", time: "4 days ago"}, 
	{title : "C for Rubyists", site: "omniref.co", href: "https://www.omniref.com/ruby/2.1.2/files/ruby.c#annotation=4029392&line=1", time: "4 days ago"}, 
	{title : "The Source of Bad Writing", site: "wsj.co", href: "http://online.wsj.com/articles/the-cause-of-bad-writing-1411660188", time: "1 day ago"}, 
	{title : "My data is bigger than your data", site: "lintool.github.i", href: "http://lintool.github.io/my-data-is-bigger-than-your-data/", time: "2 days ago"}, 
	{title : "Learning Online", site: "christinacacioppo.co", href: "http://christinacacioppo.com/blog/learning-online", time: "5 days ago"}, 
	{title : "Universal SSL", site: "cloudflare.co", href: "https://blog.cloudflare.com/introducing-universal-ssl/", time: "5 days ago"}, 
	{title : "Show HN: OrderCircle – Wholesale ordering software for small businesses", site: "ordercircle.co", href: "http://ordercircle.com", time: "3 days ago"}, 
	{title : "Synergy (GPL'd Software KVM) switches to paid downloads", site: "synergy-project.or", href: "http://synergy-project.org/download/?paid", time: "1 day ago"}, 
	{title : "New material steals oxygen from the air", site: "sciencedaily.co", href: "http://www.sciencedaily.com/releases/2014/09/140930113254.htm", time: "2 days ago"}, 
	{title : "C# 6 Cuts", site: "trelford.co", href: "http://www.trelford.com/blog/post/austerity.aspx", time: "2 days ago"}, 
	{title : "Backer News: fresh crowdfunding projects", site: "backernews.co", href: "http://backernews.com/", time: "2 days ago"}, 
	{title : "Douglas Model 671/684: The X-15’s Shadow (2012)", site: "falsesteps.wordpress.co", href: "http://falsesteps.wordpress.com/2012/08/11/douglas-model-671684-the-x-15s-shadow/", time: "2 days ago"}, 
	{title : "The New and Improved C# 6.0", site: "microsoft.co", href: "http://msdn.microsoft.com/en-us/magazine/dn802602.aspx", time: "2 days ago"}, 
	{title : "U.S. Law Enforcement Seeks to Halt Apple-Google Encryption of Mobile Data", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/u-s-seeks-to-reverse-apple-android-data-locking-decision.html", time: "4 days ago"}, 
	{title : "Modules in C99", site: "snaipe.m", href: "http://snaipe.me/c/modules-in-c99/", time: "2 days ago"}, 
	{title : "The story of the longest-held American POW", site: "slate.co", href: "http://www.slate.com/articles/news_and_politics/history/2014/09/john_t_downey_cia_agent_captured_by_china_during_the_korean_war_the_story.single.html", time: "2 days ago"}, 
	{title : "An iconic phone before the iPhone", site: "juxtapoz.co", href: "http://www.juxtapoz.com/design/an-iconic-phone-before-the-iphone", time: "2 days ago"}, 
	{title : "Containers [pdf]", site: "usenix.or", href: "https://www.usenix.org/system/files/login/articles/login_1410_02-bottomley.pdf", time: "2 days ago"}, 
	{title : "RamanPi – The 3D Printable Raspberry Pi Raman Spectrometer", site: "publiclab.or", href: "http://publiclab.org/notes/flatCat/08-29-2014/ramanpi-the-3d-printable-raspberry-pi-raman-spectrometer", time: "3 days ago"}, 
	{title : "15 years of whois client", site: "bofh.i", href: "http://blog.bofh.it/debian/id_452", time: "1 day ago"}, 
]