news22 = [
	{title : "Cloudflare experiencing upstream network issues", site: "twitter.co", href: "https://twitter.com/CloudFlareSys/status/517699118680911872", time: "2 days ago"}, 
	{title : "How Product Hunt + Hacker News fueled 300k views in 30 days", site: "medium.co", href: "https://medium.com/design-philosophies/an-overnight-success-660739c2a7e9", time: "2 days ago"}, 
	{title : "Opternative: Eye exams from the comfort of home", site: "opternative.co", href: "http://www.opternative.com/", time: "2 days ago"}, 
	{title : "Terms of Service; Didn't Read", site: "tosdr.or", href: "https://tosdr.org/", time: "3 days ago"}, 
	{title : "“Do you wear pants”: T. S. Eliot’s first magazine", site: "harvard.ed", href: "http://blogs.law.harvard.edu/houghton/2014/10/01/do-you-wear-pants-t-s-eliots-first-magazine/", time: "3 days ago"}, 
	{title : "“Gasbuggy” tests nuclear fracking in the late 1960s", site: "aoghs.or", href: "http://aoghs.org/technology/project-gasbuggy/", time: "2 days ago"}, 
	{title : "Delorean: Microsoft skips Windows 9, jumps to Windows 10 (2013)", site: "infoworld.co", href: "http://www.infoworld.com/article/2613504/microsoft-windows/microsoft-windows-microsoft-skips-too-good-windows-9-jumps-to-windows-10.html", time: "2 days ago"}, 
	{title : "Hank Green: Why am I using this shitty iPhone 4", site: "medium.co", href: "https://medium.com/@hankgreen/why-am-i-using-this-shitty-iphone-4-29c8a8514e99", time: "2 days ago"}, 
	{title : "SweetAlert – a beautiful replacement for JavaScript's alert()", site: "tristanedwards.m", href: "http://tristanedwards.me/sweetalert", time: "2 days ago"}, 
	{title : "What You Need to Know About the Ebola Outbreak", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/07/31/world/africa/ebola-virus-outbreak-qa.html", time: "3 days ago"}, 
	{title : "Proof that HubSpot CMS sites can have amazing UI/UX", site: "greenhouse.i", href: "http://www.greenhouse.io?utm_campaign=hn", time: "2 days ago"}, 
	{title : "CDC confirms first Ebola case diagnosed in US", site: "cnbc.co", href: "http://www.cnbc.com/id/102037055", time: "3 days ago"}, 
	{title : "Advanced iOS virus targeting Hong Kong protestors", site: "reuters.co", href: "http://www.reuters.com/article/2014/09/30/hongkong-china-cybersecurity-apple-idUSL2N0RV2D320140930", time: "3 days ago"}, 
	{title : "Fedora Workstation Progress Report (Wayland and More)", site: "gnome.or", href: "http://blogs.gnome.org/uraeus/2014/10/02/fedora-workstation-progress-report-wayland-and-more/", time: "2 days ago"}, 
	{title : "EBay to Spin Off PayPal", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/09/30/ebay-to-spin-off-paypal-adopting-strategy-backed-by-icahn/", time: "4 days ago"}, 
	{title : "Man allegedly shoots down neighbor’s drone with shotgun", site: "digitaltrends.co", href: "http://www.digitaltrends.com/cool-tech/new-jersey-man-allegedly-shoots-neighbors-drone/?utm_source=o1&utm_medium=cpc&utm_campaign=o1", time: "2 days ago"}, 
	{title : "Parallel scheduling of task trees with limited memory [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1410.0329.pdf", time: "2 days ago"}, 
	{title : "How to Deploy Play Framework on AWS OpsWorks", site: "originate.co", href: "http://blog.originate.com/blog/2014/10/02/how-to-deploy-play-framework-on-aws-opsworks/", time: "2 days ago"}, 
	{title : "Hound Reviews JavaScript for Style Violations", site: "thoughtbot.co", href: "http://robots.thoughtbot.com/hound-reviews-javascript-for-style-violations", time: "2 days ago"}, 
	{title : "Cloudflare is down", site: "twitter.co", href: "https://twitter.com/search?f=realtime&q=cloudflare", time: "2 days ago"}, 
	{title : "Three years later, Pentagon unit still hides Internet voting test results", site: "mcclatchydc.co", href: "http://www.mcclatchydc.com/2014/10/01/241746_three-years-later-pentagon-unit.html", time: "2 days ago"}, 
	{title : "Clock Edge Detection in Excel", site: "drdobbs.co", href: "http://www.drdobbs.com/embedded-systems/clock-edge-detectionin-excel/240169084", time: "2 days ago"}, 
	{title : "NearlyFreeSpeech.NET now supports persistent processes", site: "nearlyfreespeech.ne", href: "https://blog.nearlyfreespeech.net/2014/09/24/more-power-more-control-more-insight-less-cost/", time: "3 days ago"}, 
	{title : "Show HN: Open-Source extensible personal assistant on your desktop", site: "github.co", href: "https://github.com/29decibel/assistant", time: "2 days ago"}, 
	{title : "Lies, Damn Lies and Version Numbers", site: "telerik.co", href: "http://developer.telerik.com/featured/lies-damn-lies-version-numbers/", time: "2 days ago"}, 
	{title : "Emotional Intelligence is Overrated", site: "linkedin.co", href: "https://www.linkedin.com/pulse/article/20140930125543-69244073-emotional-intelligence-is-overrated", time: "4 days ago"}, 
	{title : "Google Classroom", site: "google.co", href: "https://www.google.com/edu/classroom/", time: "5 days ago"}, 
	{title : "Using Intel VTune to Tune Software on the 4th Generation (Haswell) Processor [pdf]", site: "intel.co", href: "https://software.intel.com/sites/default/files/article/394181/using-intel-vtune-amplifier-xe-on-4th-generation-intel-core-processors.pdf", time: "2 days ago"}, 
]