news19 = [
	{title : "Facebook Promises a Deeper Review of Its User Research", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/technology/facebook-promises-a-deeper-review-of-its-user-research.html", time: "2 days ago"}, 
	{title : "Google Project Zero: More Mac OS X and iPhone Sandbox Escapes", site: "googleprojectzero.blogspot.co", href: "http://googleprojectzero.blogspot.com/2014/10/more-mac-os-x-and-iphone-sandbox.html", time: "2 days ago"}, 
	{title : "Matchstick Brings Firefox OS to Your HDTV", site: "mozilla.or", href: "https://hacks.mozilla.org/2014/09/matchstick-brings-firefox-os-to-your-hdtv-be-the-first-to-get-a-developer-stick/", time: "4 days ago"}, 
	{title : "NASA found a mysterious rectangular shape on the moon", site: "sciencemag.or", href: "http://news.sciencemag.org/space/2014/10/ancient-magma-plumbing-found-buried-below-moons-largest-dark-spot", time: "1 day ago"}, 
	{title : "Parenting as a Gen Xer: The 1st generation of parents in the age of iEverything", site: "washingtonpost.co", href: "http://www.washingtonpost.com/news/parenting/wp/2014/09/29/parenting-as-a-gen-xer-what-its-like-to-be-the-first-generation-of-parents-in-the-age-of-ieverything/", time: "2 days ago"}, 
	{title : "Visualizing and Understanding Convolutional Networks", site: "arxiv.or", href: "http://arxiv.org/abs/1311.2901", time: "2 days ago"}, 
	{title : "J.P. Morgan Says About 76M Households Affected by Cyber Breach", site: "marketwatch.co", href: "http://www.marketwatch.com/story/jp-morgan-says-about-76-million-households-affected-by-cyber-breach-2014-10-02-17103316", time: "1 day ago"}, 
	{title : "Show HN: Crowdsourced Summaries of Facebook's Human-Subjects Research", site: "sauvik.m", href: "https://experiment.sauvik.me/", time: "2 days ago"}, 
	{title : "AT", site: "acker invoices Justice Dept. for time spent in federal pri", href: "http://rt.com/usa/160216-weev-invoice-fed-bitcoin/", time: "2 days ago"}, 
	{title : "Council removes Banksy artwork after complaints of racism", site: "theguardian.co", href: "http://www.theguardian.com/artanddesign/2014/oct/01/banksy-mural-clacton-racist", time: "1 day ago"}, 
	{title : "A Nomic game in Haskell", site: "nomyx.ne", href: "http://www.nomyx.net/", time: "2 days ago"}, 
	{title : "At 17, Setting Off Protests That Roil Hong Kong", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/world/asia/hong-kong-china-democracy-protests-students.html", time: "2 days ago"}, 
	{title : "MemSQL Does Oracle’s Own Demo Ten Times as Fast, Sixty Times Cheaper", site: "memsql.co", href: "http://blog.memsql.com/memsql-does-oracles-own-demo-ten-times-as-fast-sixty-times-cheaper/", time: "2 days ago"}, 
	{title : "Hopscotch: Towards User Interface Composition (2008) [pdf]", site: "bracha.or", href: "http://bracha.org/hopscotch-wasdett.pdf", time: "2 days ago"}, 
	{title : "After 31 years, Lotus-1-2-3 spreadsheet support has ended", site: "zdnet.co", href: "http://www.zdnet.com/so-farewell-then-lotus-1-2-3-spreadsheet-extraordinaire-7000034288/", time: "1 day ago"}, 
	{title : "Google reportedly tried to buy Cyanogen", site: "arstechnica.co", href: "http://arstechnica.com/gadgets/2014/10/google-reportedly-tried-to-buy-cyanogen-inc/", time: "1 day ago"}, 
	{title : "Extensible Web Resource Loading Manifesto", site: "igvita.co", href: "https://www.igvita.com/2014/10/02/extensible-web-resource-loading-manifesto/", time: "2 days ago"}, 
	{title : "Research at Facebook", site: "fb.co", href: "http://newsroom.fb.com/news/2014/10/research-at-facebook/", time: "2 days ago"}, 
	{title : "The Quiet Zone: No wifi or cell phone service for 13,000 sq. miles", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/United_States_National_Radio_Quiet_Zone", time: "1 day ago"}, 
	{title : "Texas Contacts 100, Citing Possible Links to Ebola Patient", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/dallas-ebola-case-thomas-duncan-contacts.html?_r=0", time: "2 days ago"}, 
	{title : "Systems of Logic Based on Ordinals (1938) [pdf]", site: "princeton.ed", href: "https://webspace.princeton.edu/users/jedwards/Turing%20Centennial%202012/Mudd%20Archive%20files/12285_AC100_Turing_1938.pdf", time: "3 days ago"}, 
	{title : "Show HN: All available three letter .io domains", site: "edward.i", href: "http://edward.io/io", time: "2 days ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "youtube.co", href: "https://www.youtube.com/watch?v=yP176MBG9Tk", time: "1 day ago"}, 
	{title : "Zentail.com (YC S12) Now Accepts Bitcoin", site: "reddit.co", href: "http://www.reddit.com/r/Bitcoin/comments/2i3ssd/zentailcom_now_accepts_bitcoin/", time: "2 days ago"}, 
	{title : "Elon Musk: Tesla 90% autonomous in 2015", site: "youtube.co", href: "https://www.youtube.com/watch?v=EJmhpgW0Dmc", time: "2 days ago"}, 
	{title : "Losing the sense of smell predicts death within five years", site: "theguardian.co", href: "http://www.theguardian.com/science/neurophilosophy/2014/oct/01/your-nose-knows-death-is-imminent", time: "2 days ago"}, 
	{title : "Joshua Wong: the teenager who is the public face of the Hong Kong protests", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/joshua-wong-teenager-public-face-hong-kong-protests", time: "1 day ago"}, 
	{title : "Cassini Watches Mysterious Feature Evolve in Titan Sea", site: "nasa.go", href: "http://www.nasa.gov/jpl/cassini/cassini-watches-mysterious-feature-evolve-in-titan-sea/", time: "4 days ago"}, 
	{title : "Cyanogen refuses Google's money in an effort to keep Android 'open'", site: "engadget.co", href: "http://www.engadget.com/2014/10/02/cyanogen-refuses-google/", time: "1 day ago"}, 
	{title : "Show HN: TypeWonder – Test web fonts on any site on the fly", site: "typewonder.co", href: "http://typewonder.com/", time: "3 days ago"}, 
]