news1 = [
	{title : "Modernized time.h for ISO C (1998)", site: "cam.ac.u", href: "http://www.cl.cam.ac.uk/~mgk25/time/c/", time: "1 hour ago"}, 
	{title : "First womb-transplant baby born", site: "bbc.co", href: "http://www.bbc.com/news/health-29485996", time: "54 minutes ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://m.bbc.com/news/science-environment-29465446", time: "54 minutes ago"}, 
	{title : "Granny Smith apples promote growth of friendly bacteria in the colon", site: "wsu.ed", href: "https://news.wsu.edu/2014/09/29/an-apple-a-day-could-keep-obesity-away/#.VCqA_GeSz94", time: "1 hour ago"}, 
	{title : "The Books We Talk About (and Those We Don’t)", site: "nybooks.co", href: "http://www.nybooks.com/blogs/nyrblog/2014/oct/01/books-we-talk-about/", time: "4 hours ago"}, 
	{title : "In Colorado, a Rebranding of Pot Inc", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/05/fashion/in-colorado-a-rebranding-of-pot-inc-marijuana.html?hp&action=click&pgtype=Homepage&version=LargeMediaHeadlineSum&module=photo-spot-region&region=top-news&WT.nav=top-news", time: "2 hours ago"}, 
	{title : "Lilblue Linux: Adventures Beyond the Land of Posix", site: "gentoo.or", href: "http://blogs.gentoo.org/blueness/2014/10/04/lilblue-linux-release-20140925-adventures-beyond-the-land-of-posix/", time: "3 hours ago"}, 
	{title : "How con artists trick your mind", site: "bbc.co", href: "http://www.bbc.com/future/story/20141003-the-mind-tricks-of-scammers", time: "1 hour ago"}, 
	{title : "Show HN: Mojulo – Pixelated Math Rendering Sandbox Toy", site: "maxbittker.github.i", href: "http://maxbittker.github.io/Mojulo/", time: "1 hour ago"}, 
	{title : "Do Deep Nets Really Need to be Deep? [pdf]", site: "arxiv.or", href: "http://arxiv.org/pdf/1312.6184v5.pdf", time: "18 hours ago"}, 
	{title : "TXR: A Programming Language for Convenient Data Munging", site: "nongnu.or", href: "http://www.nongnu.org/txr", time: "7 hours ago"}, 
	{title : "New tool helps debug Java exceptions faster", site: "excepterror.co", href: "http://www.excepterror.com", time: "1 hour ago"}, 
	{title : "Stampede – Texas Advanced Computing Center", site: "utexas.ed", href: "https://www.tacc.utexas.edu/stampede/", time: "4 hours ago"}, 
	{title : "CERN turns 60", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/september-2014/cern-turns-60", time: "1 hour ago"}, 
	{title : "How Archerfish Hunt With Their Spit (2013)", site: "wired.co", href: "http://www.wired.com/2013/11/archerfish-physics/", time: "52 minutes ago"}, 
	{title : "A Plan to Use Survivors’ Blood for Ebola Treatment in Africa", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/health/use-of-ebola-survivors-blood-as-possible-treatment-gains-support.html?ref=science", time: "35 minutes ago"}, 
	{title : "Times Articles Removed from Google Results in Europe", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/media/times-articles-removed-from-google-results-in-europe.html", time: "11 hours ago"}, 
	{title : "Why Not Eat Octopus?", site: "newyorker.co", href: "http://www.newyorker.com/tech/elements/eating-octopus", time: "2 hours ago"}, 
	{title : "Storage Scalability in Docker", site: "redhat.co", href: "http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/?utm_content=buffer8a955&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer", time: "8 hours ago"}, 
	{title : "Sthttpd: Tiny and fast http server with a mature codebase", site: "gentoo.or", href: "http://blogs.gentoo.org/blueness/2014/10/03/sthttpd-a-very-tiny-and-very-fast-http-server-with-a-mature-codebase/", time: "3 hours ago"}, 
	{title : "An Analysis of Shell Shock Malware", site: "erenyagdiran.github.i", href: "http://erenyagdiran.github.io/An-Analysis-of-Shell-shock-malware/", time: "1 hour ago"}, 
	{title : "To catch a gravitational wave", site: "symmetrymagazine.or", href: "http://www.symmetrymagazine.org/article/october-2014/to-catch-a-gravitational-wave", time: "1 hour ago"}, 
	{title : "Code Browser – A Folding Text Editor", site: "tibleiz.ne", href: "http://tibleiz.net/code-browser/index.html", time: "11 hours ago"}, 
	{title : "The Fourth Skull: A Tale of Authenticity and Fraud (2013)", site: "theappendix.ne", href: "http://theappendix.net/issues/2013/4/the-fourth-skull-a-tale-of-authenticity-and-fraud", time: "52 minutes ago"}, 
	{title : "Linked lists with wait-free reads in C++", site: "concurrencyfreaks.blogspot.co", href: "http://concurrencyfreaks.blogspot.com/2014/10/linked-lists-with-wait-free-reads-in-c.html", time: "20 hours ago"}, 
	{title : "Caesium: A brief history of timekeeping", site: "bbc.co", href: "http://www.bbc.com/news/magazine-29476893", time: "9 hours ago"}, 
	{title : "A mixed bag on apps: What the NY Times learned with NYT Opinion and NYT Now", site: "niemanlab.or", href: "http://www.niemanlab.org/2014/10/a-mixed-bag-on-apps-what-the-new-york-times-learned-with-nyt-opinion-and-nyt-now/", time: "12 hours ago"}, 
	{title : "The Ebola Patient Was Sent Home Because of Bad Software", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/10/the-ebola-patient-was-sent-home-because-of-an-electronic-health-record-problem/381087/", time: "2 hours ago"}, 
]