news26 = [
	{title : "Rails is great! Thank you", site: "github.co", href: "https://github.com/rails/rails/issues/16731", time: "3 days ago"}, 
	{title : "Gilad Bracha: A DOMain of Shadows", site: "gbracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html", time: "4 days ago"}, 
	{title : "Students are cash cows, and schools the predators", site: "salon.co", href: "http://www.salon.com/2014/10/01/college_is_ripping_you_off_students_are_cash_cows_and_schools_the_predators/?", time: "2 days ago"}, 
	{title : "COGNITIVE SLAVES (aka Crowdslaving)", site: "globalguerrillas.typepad.co", href: "http://globalguerrillas.typepad.com/globalguerrillas/2010/09/cognitive-slaves.html", time: "2 days ago"}, 
	{title : "US top cop decries encryption, demands backdoors", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/us-top-cop-decries-encryption-demands-backdoors/", time: "2 days ago"}, 
	{title : "Show HN: Airtable, a real-time spreadsheet-database hybrid", site: "airtable.co", href: "https://airtable.com/invite/a3sz9t7b", time: "8 days ago"}, 
	{title : "Vogue magazine interview with Jony Ive", site: "vogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive", time: "3 days ago"}, 
	{title : "React Apps Using Flux and Backbone: A How To", site: "toptal.co", href: "http://www.toptal.com/front-end/simple-data-flow-in-react-applications-using-flux-and-backbone", time: "3 days ago"}, 
	{title : "Google execs have ideas on how to run your business", site: "technologyreview.co", href: "http://www.technologyreview.com/news/531056/google-execs-have-ideas-on-how-to-run-your-business/", time: "5 days ago"}, 
	{title : "10x: Architecture at Clay.io", site: "zolmeister.co", href: "http://zolmeister.com/2014/10/10x-architecture-at-clay-io.html", time: "3 days ago"}, 
	{title : "Microsoft developer explains on Reddit why Windows 10 is called Windows 10", site: "imgur.co", href: "https://i.imgur.com/SeH6xiI.png", time: "3 days ago"}, 
	{title : "Literary Lions Unite in Protest Over Amazon’s E-Book Tactics", site: "nytimes.co", href: "http://www.nytimes.com/2014/09/29/business/literary-lions-unite-in-protest-over-amazons-e-book-tactics.html", time: "5 days ago"}, 
	{title : "UK Legalizes CD Ripping and Cloud Backups Today", site: "torrentfreak.co", href: "http://torrentfreak.com/uk-government-legalizes-cd-ripping-cloud-backups-today-141001/", time: "3 days ago"}, 
	{title : "Google announces 10% price cut for all Compute Engine instances", site: "thenextweb.co", href: "http://thenextweb.com/google/2014/10/01/google-announces-10-price-cut-compute-engine-instances-google-drive-passed-240m-active-users/", time: "3 days ago"}, 
	{title : "Show HN: NIH-DB fork it and write your own", site: "github.co", href: "https://github.com/tjake/nih-db", time: "3 days ago"}, 
	{title : "Eleventh Grade Tech Trends", site: "medium.co", href: "https://medium.com/musings-about-text-boxes/eleventh-grade-tech-trends-aca537e9ce62", time: "17 days ago"}, 
	{title : "Universal SSL: Be just a bit more patient", site: "cloudflare.co", href: "https://blog.cloudflare.com/universal-ssl-be-just-a-bit-more-patient/", time: "4 days ago"}, 
	{title : "NerdytData patches Shellshock in a single crawl", site: "nerdydata.co", href: "http://blog.nerdydata.com/post/98906853956/nerdydata-patches-shellshock-in-a-single-crawl", time: "2 days ago"}, 
	{title : "Lecture 3: Counterintuitive Parts of Startups, and How to Have Ideas", site: "genius.co", href: "http://tech.genius.com/Paul-graham-lecture-3-counterintuitive-parts-of-startups-and-how-to-have-ideas-annotated", time: "3 days ago"}, 
	{title : "Firefox Considering Tor Integration", site: "torproject.or", href: "https://lists.torproject.org/pipermail/tor-dev/2014-September/007533.html", time: "3 days ago"}, 
	{title : "CVE-2014-7187 (yet another) Bash arbitrary execution of code", site: "redhat.co", href: "https://access.redhat.com/security/cve/CVE-2014-7187", time: "3 days ago"}, 
	{title : "Steve Wozniak on starting companies, solving problems, finding happiness", site: "fastcodesign.co", href: "http://www.fastcodesign.com/3036366/the-wisdom-of-woz", time: "4 days ago"}, 
	{title : "Show HN: Dabble Me – the open source replacement for OhLife", site: "dabble.m", href: "https://dabble.me", time: "4 days ago"}, 
	{title : "How Jerry Yang Made the Most Lucrative Bet in Tech History", site: "forbes.co", href: "http://www.forbes.com/sites/parmyolson/2014/09/30/how-jerry-yang-made-the-most-lucrative-bet-in-tech-history/", time: "4 days ago"}, 
	{title : "How 50 startups manage their code", site: "foundersgrid.co", href: "http://foundersgrid.com/code-management", time: "2 days ago"}, 
	{title : "Beating the Tinder game: 800+ Matches. I’ll probably get banned for this…", site: "medium.co", href: "https://medium.com/@blakejamieson/beating-the-tinder-game-4f08c9ec0d80", time: "3 days ago"}, 
	{title : "Show HN: Privacy – PGP Messenger", site: "medium.co", href: "https://medium.com/@krzyzanowskim/privacy-pgp-messenger-9612cd6bc08", time: "3 days ago"}, 
	{title : "Idiomatic Generics in Go", site: "bouk.c", href: "http://bouk.co/blog/idiomatic-generics-in-go/", time: "4 days ago"}, 
]