news23 = [
	{title : "Show HN: DART – Quickly search and discover startup engineering jobs", site: "dart.rock", href: "http://www.dart.rocks/", time: "3 days ago"}, 
	{title : "A Field Guide to Design by Pros at Media Temple, Marvel, GA Dash and Product Hunt", site: "mention.co", href: "http://blog.mention.com/a-field-guide-to-design-where-to-begin/", time: "2 days ago"}, 
	{title : "Peter Thiel's Zero to One Might Be the Best Business Book I've Read", site: "theatlantic.co", href: "http://www.theatlantic.com/business/archive/2014/09/peter-thiel-zero-to-one-review/380738/?single_page=true", time: "6 days ago"}, 
	{title : "Atom: Editor window startup is slow", site: "github.co", href: "https://www.github.com/atom/atom/issues/2654", time: "3 days ago"}, 
	{title : "ComputerCOP: Dubious 'Internet Safety Software' Police Distributed to Families", site: "eff.or", href: "https://www.eff.org/deeplinks/2014/09/computercop-dangerous-internet-safety-software-hundreds-police-agencies", time: "3 days ago"}, 
	{title : "Could Uber be held liable for driver hammer attack?", site: "forbes.co", href: "http://www.forbes.com/sites/ellenhuet/2014/09/30/uber-driver-hammer-attack-liability/", time: "2 days ago"}, 
	{title : "Clarifai: Advanced Image Recognition", site: "clarifai.co", href: "http://www.clarifai.com/", time: "3 days ago"}, 
	{title : "MiniZinc, the medium-level constraint modelling language", site: "minizinc.or", href: "http://www.minizinc.org/index.html", time: "2 days ago"}, 
	{title : "The Medium Is the Message, 50 Years Later", site: "psmag.co", href: "http://www.psmag.com/navigation/nature-and-technology/medium-message-50-years-later-91552/", time: "3 days ago"}, 
	{title : "StoreDot Charges Up with $42M for Its Fast-Charging Bio-Organic Batteries", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/storedot-series-b/", time: "2 days ago"}, 
	{title : "Mobile Malware: Small Numbers, but Growing", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/02/technology/personaltech/mobile-malware-small-numbers-but-growing.html?ref=personaltech", time: "2 days ago"}, 
	{title : "Against Concentrations", site: "harry-lewis.blogspot.co", href: "http://harry-lewis.blogspot.com/2014/09/against-concentrations.html", time: "3 days ago"}, 
	{title : "J-expressions (2012)", site: "sriku.or", href: "http://sriku.org/blog/2012/04/15/j-expressions/", time: "3 days ago"}, 
	{title : "OnionTip – Donate to volunteers who are running Tor relays", site: "oniontip.co", href: "https://oniontip.com", time: "4 days ago"}, 
	{title : "Parallel In-Place Merge Sort", site: "drdobbs.co", href: "http://www.drdobbs.com/parallel/parallel-in-place-merge-sort/240169094", time: "3 days ago"}, 
	{title : "Mining Bitcoin with pencil and paper: 0.67 hashes per day", site: "righto.co", href: "http://www.righto.com/2014/09/mining-bitcoin-with-pencil-and-paper.html", time: "6 days ago"}, 
	{title : "On the role of GRBs on life extinction in the Universe", site: "arxiv.or", href: "http://arxiv.org/abs/1409.2506", time: "3 days ago"}, 
	{title : "Coinbase Expands to 5 More Countries and Raises Limits for European Users", site: "coinbase.co", href: "http://blog.coinbase.com/post/98952363012/coinbase-expands-to-5-more-countries-and-raises-limits", time: "2 days ago"}, 
	{title : "The New York Times’ App Plan Isn’t Working, So It’s Laying Off Staff", site: "recode.ne", href: "http://recode.net/2014/10/01/the-new-york-times-app-plan-isnt-working-so-its-laying-off-staff/", time: "3 days ago"}, 
	{title : "A DOMain of Shadows", site: "gbracha.blogspot.co", href: "http://gbracha.blogspot.com/2014/09/a-domain-of-shadows.html?m=1", time: "3 days ago"}, 
	{title : "Walrus mass in vast numbers on Alaska beach as sea ice retreats", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/01/walrus-mass-vast-numbers-alaska-beach-sea-ice-retreats", time: "2 days ago"}, 
	{title : "On a farm in Missouri, a radical experiment in self-sufficiency (2013)", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2013/12/23/the-civilization-kit", time: "3 days ago"}, 
	{title : "Making a homemade metal semi-automatic rifle just got easy", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/making-a-homemade-metal-semi-automatic-rifle-just-got-crazy-easy/", time: "2 days ago"}, 
	{title : "Google Drops Compute Engine Prices by 10 Percent", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/google-drops-all-compute-engine-prices-by-10-percent/", time: "3 days ago"}, 
	{title : "Drone captures scale of Hong Kong protest [video]", site: "bbc.co", href: "http://www.bbc.com/news/world-asia-29421914", time: "2 days ago"}, 
	{title : "Sxript: Arbitrary-precision math and programming environment", site: "umass.ed", href: "http://people.umass.edu/wfbarnes/STxAxTICMathWriteup.html", time: "3 days ago"}, 
	{title : "Linear Optimization with Glop", site: "developers.google.co", href: "https://developers.google.com/optimization/docs/lp/glop", time: "3 days ago"}, 
	{title : "Show HN: HackerBracket – What are you working on?", site: "hackerbracket.co", href: "https://www.hackerbracket.com/v/2", time: "3 days ago"}, 
	{title : "Tor growth rates", site: "docs.google.co", href: "https://docs.google.com/document/d/1SaBK664SchhZOP9XBsB8KK63k4xlmMTlkhfF28f2204/pub", time: "3 days ago"}, 
	{title : "Scientific writing: the online cooperative", site: "nature.co", href: "http://www.nature.com/news/scientific-writing-the-online-cooperative-1.16039", time: "2 days ago"}, 
]