news13 = [
	{title : "Choosing a Web Framework/Language Combo – Ruby on Rails", site: "jacquesmattheij.co", href: "http://jacquesmattheij.com/choosing-web-framework-language-combo-srs-ruby-on-rails", time: "37 days ago"}, 
	{title : "Ageing: The girls who never grow older", site: "bbc.co", href: "http://www.bbc.com/future/story/20140520-the-girls-who-never-age", time: "136 days ago"}, 
	{title : "Jibo, the first family robot", site: "myjibo.co", href: "http://www.myjibo.com/", time: "80 days ago"}, 
	{title : "The Architecture of Open Source Applications", site: "aosabook.or", href: "http://aosabook.org/en/index.html", time: "381 days ago"}, 
	{title : "Two technologies which are bad for you", site: "medium.co", href: "https://medium.com/@jlouis666/two-technologies-which-are-bad-for-you-160311ad6b24", time: "28 days ago"}, 
	{title : "The Happy Demise of the 10X Engineer", site: "a16z.co", href: "http://a16z.com/2014/07/30/the-happy-demise-of-the-10x-engineer/", time: "66 days ago"}, 
	{title : "Fly offspring can resemble mother's previous sexual partner", site: "smh.com.a", href: "http://www.smh.com.au/technology/sci-tech/ghosts-of-mothers-sexual-past-show-up-in-fly-offspring-study-shows-20141001-10onn3.html", time: "2 days ago"}, 
	{title : "“Not” Neutrality?", site: "level3.co", href: "http://blog.level3.com/open-internet/not-neutrality/", time: "3 days ago"}, 
	{title : "Against Empathy", site: "bostonreview.ne", href: "http://bostonreview.net/forum/paul-bloom-against-empathy", time: "2 days ago"}, 
	{title : "Seen a font in use and want to know what it is?", site: "myfonts.co", href: "https://www.myfonts.com/WhatTheFont/?", time: "2 days ago"}, 
	{title : "Inspeqtor: easy application infrastructure monitoring", site: "mikeperham.co", href: "http://www.mikeperham.com/2014/10/02/introducing-inspeqtor/", time: "2 days ago"}, 
	{title : "Run Your Startup Like a Cult", site: "wired.co", href: "http://www.wired.com/2014/09/run-startup-like-cult-heres/", time: "2 days ago"}, 
	{title : "Why They Called It the Manhattan Project (2007)", site: "nytimes.co", href: "http://www.nytimes.com/2007/10/30/science/30manh.html?pagewanted=all", time: "2 days ago"}, 
	{title : "Apple Pay: An in-depth look at what's behind the secure payment system", site: "tuaw.co", href: "http://www.tuaw.com/2014/10/02/apple-pay-an-in-depth-look-at-whats-behind-the-secure-payment/", time: "2 days ago"}, 
	{title : "Germany’s great tuition fees U-turn", site: "timeshighereducation.co.u", href: "http://www.timeshighereducation.co.uk/features/feature-germanys-great-tuition-fees-u-turn/2011168.fullarticle", time: "3 days ago"}, 
	{title : "World’s first “solar battery” runs on light and air", site: "osu.ed", href: "http://news.osu.edu/news/2014/10/03/batteries-included-a-solar-cell-that-stores-its-own-power/", time: "1 day ago"}, 
	{title : "William Binney Explains Snowden Docs", site: "alexaobrien.co", href: "http://www.alexaobrien.com/secondsight/wb/binney.html", time: "3 days ago"}, 
	{title : "Looking for help improving performance of GNU Make", site: "gnu.or", href: "http://lists.gnu.org/archive/html/help-make/2014-10/msg00000.html", time: "2 days ago"}, 
	{title : "Cumulus Linux – first impressions", site: "packetlife.ne", href: "http://packetlife.net/blog/2014/oct/1/cumulus-linux-first-impressions/", time: "2 days ago"}, 
	{title : "XSA-108 Advisory", site: "xen.or", href: "http://xenbits.xen.org/xsa/advisory-108.html", time: "3 days ago"}, 
	{title : "Whats Wrong with Markdown", site: "adamhyde.ne", href: "http://www.adamhyde.net/whats-wrong-with-markdown/", time: "1 day ago"}, 
	{title : "Celebs whose nude photos were stolen threaten Google with $100M lawsuit", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/10/celebs-whose-nude-photos-were-stolen-threaten-google-with-100m-lawsuit/", time: "1 day ago"}, 
	{title : "Korea begins commercialized LTE service based on IPv6", site: "whowired.co", href: "http://www.whowired.com/news/articleView.html?idxno=404401", time: "2 days ago"}, 
	{title : "Bye Bye JavaScript Promises", site: "sriku.or", href: "http://sriku.org/blog/2014/02/11/bye-bye-js-promises/", time: "3 days ago"}, 
	{title : "Reducing Infrustration: smooth delivery with immutable infrastructure", site: "radify.i", href: "http://radify.io/blog/reducing-infrustration", time: "1 day ago"}, 
	{title : "Chickens have gotten ridiculously large since the 1950s", site: "vox.co", href: "http://www.vox.com/xpress/2014/10/2/6875031/chickens-breeding-farming-boilers-giant", time: "1 day ago"}, 
	{title : "The Researcher's Bible (1985)", site: "ed.ac.u", href: "http://homepages.inf.ed.ac.uk/bundy/how-tos/resbible.html", time: "2 days ago"}, 
	{title : "Maaxi app aims to help black cabs counter rise of Uber", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/technology-29458897", time: "1 day ago"}, 
]