news25 = [
	{title : "What’s a Bitcoin Look Like? The Story Behind This Popular Photograph", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-09-30/what-s-a-bitcoin-look-like-popular-photograph-has-story.html", time: "2 days ago"}, 
	{title : "The Race to the Bottom of the 3D Engines", site: "irrlicht3d.or", href: "http://www.irrlicht3d.org/pivot/entry.php?id=1440", time: "2 days ago"}, 
	{title : "Machine learning is teaching us the secret to teaching", site: "nautil.u", href: "http://nautil.us/issue/6/secret-codes/teaching-me-softly", time: "6 days ago"}, 
	{title : "Current and upcoming robots on American farms", site: "engadget.co", href: "http://www.engadget.com/2014/09/22/robot-farming-explainer/", time: "3 days ago"}, 
	{title : "Security Breach: The London Mail Rail (2011)", site: "placehacking.co.u", href: "http://www.placehacking.co.uk/2011/04/24/security-breach-london-mail-rail/", time: "3 days ago"}, 
	{title : "DevOps: From Unicorns to Horses", site: "amplifypartners.co", href: "http://www.amplifypartners.com/interviews/devops-from-unicorns-to-horses/", time: "2 days ago"}, 
	{title : "SendGrid Replaces CEO", site: "xconomy.co", href: "http://www.xconomy.com/boulder-denver/2014/09/30/franklin-out-vmlogix-and-citrix-exec-in-as-sendgrid-replaces-ceo/", time: "3 days ago"}, 
	{title : "The Man Who Fought the Synanon Cult and Won", site: "gizmodo.co", href: "http://paleofuture.gizmodo.com/the-man-who-fought-cults-and-won-1634267961", time: "5 days ago"}, 
	{title : "Mobile Web App Checklist", site: "luster.i", href: "http://www.luster.io/blog/9-29-14-mobile-web-checklist.html", time: "10 days ago"}, 
	{title : "Show HN: ScaleDrone, push messaging that makes sense", site: "scaledrone.co", href: "https://www.scaledrone.com/", time: "3 days ago"}, 
	{title : "Simple, secure cloud storage", site: "leastauthority.co", href: "https://leastauthority.com/", time: "3 days ago"}, 
	{title : "Clojure Cup 2014 Apps", site: "clojurecup.co", href: "https://clojurecup.com/#/apps", time: "5 days ago"}, 
	{title : "Visual Revolution of the Vanishing of Ethan Carter", site: "theastronauts.co", href: "http://www.theastronauts.com/2014/03/visual-revolution-vanishing-ethan-carter/", time: "4 days ago"}, 
	{title : "Reddit disallows remote work after $50MM investment round", site: "twitter.co", href: "https://twitter.com/dhh/status/517372782976696321", time: "3 days ago"}, 
	{title : "Building OS X Apps with JavaScript", site: "tylergaw.co", href: "http://tylergaw.com/articles/building-osx-apps-with-js", time: "6 days ago"}, 
	{title : "Why Windows 9 is Windows 10", site: "imgur.co", href: "http://i.imgur.com/p7eQQK3.png", time: "2 days ago"}, 
	{title : "It Just Works", site: "rustyshelf.or", href: "http://rustyshelf.org/2014/10/01/it-just-works/", time: "3 days ago"}, 
	{title : "Digital Ocean gives away t-shirts for commiting to public GitHub repo in October", site: "digitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/", time: "2 days ago"}, 
	{title : "Gauged – Fast, append-only storage layer for numeric data that changes over time", site: "github.co", href: "https://github.com/chriso/gauged", time: "3 days ago"}, 
	{title : "Immigration Crackdown on Digital Nomads in Chiang Mai, Thailand", site: "johnnyfd.co", href: "http://www.johnnyfd.com/2014/09/live-updates-immigration-crackdown-in.html", time: "3 days ago"}, 
	{title : "The very laws of physics imply that artificial intelligence must be possible", site: "aeon.c", href: "http://aeon.co/magazine/technology/david-deutsch-artificial-intelligence/", time: "3 days ago"}, 
	{title : "Show HN: A Google Calendar Door Sign", site: "newfangled.m", href: "http://newfangled.me/door-sign/", time: "6 days ago"}, 
	{title : "Your Agile, Free and Open Source Project Management Tool", site: "taiga.i", href: "https://taiga.io/", time: "3 days ago"}, 
	{title : "Hacktoberfest", site: "digitalocean.co", href: "https://www.digitalocean.com/company/blog/hacktoberfest/#comment-1615829197", time: "2 days ago"}, 
	{title : "Apple Says iPhone 6 and 6 Plus Bending Complaints Number Less Than 10", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/25/apple-says-iphone-6-and-6-plus-bending-complaints-number-less-than-10/?ncid=rss&cps=gravity", time: "2 days ago"}, 
	{title : "Microsoft developer explains why Windows 10 is called Windows 10", site: "reddit.co", href: "http://www.reddit.com/r/technology/comments/2hwlrk/new_windows_version_will_be_called_windows_10/ckwq83x", time: "3 days ago"}, 
	{title : "How American parenting is killing the American marriage", site: "qz.co", href: "http://qz.com/273255/how-american-parenting-is-killing-the-american-marriage/", time: "2 days ago"}, 
	{title : "Make in India", site: "makeinindia.co", href: "http://makeinindia.com/sectors/", time: "9 days ago"}, 
]