news7 = [
	{title : "Your Ancestors Didn't Sleep Like You – Are We Doing It Wrong?", site: "earthweareone.co", href: "http://earthweareone.com/your-ancestors-didnt-sleep-like-you-are-we-doing-it-wrong/", time: "19 hours ago"}, 
	{title : "Ham radio exams, algorithms, and scaling on the fly", site: "dobbe.u", href: "http://grant.dobbe.us/2014/10/ham-radio-exams-algorithms-and-scaling-on-the-fly/", time: "2 days ago"}, 
	{title : "Google planning to launch own mobile messaging app similar to WhatsApp", site: "economictimes.co", href: "http://m.economictimes.com/tech/internet/google-planning-to-launch-own-mobile-messaging-app-similar-to-whatsapp/articleshow/44141070.cms", time: "1 day ago"}, 
	{title : "Show HN: Make your site faster", site: "eager.i", href: "https://eager.io/app/ZYBle8qUhKFJ?n", time: "1 day ago"}, 
	{title : "RamdaJS – A practical functional library for JavaScript", site: "ramdajs.co", href: "http://ramdajs.com/", time: "1 day ago"}, 
	{title : "MiniKanren – An embedded DSL for logic programming", site: "minikanren.or", href: "http://minikanren.org/", time: "3 days ago"}, 
	{title : "Using Tweets to Predict Which States Are Overweight", site: "slate.co", href: "http://www.slate.com/blogs/future_tense/2014/10/02/university_of_arizona_researchers_analyze_food_references_in_twitter_data.html", time: "1 day ago"}, 
	{title : "It's time to shout stop on this war on the living world", site: "theguardian.co", href: "http://www.theguardian.com/environment/georgemonbiot/2014/oct/01/george-monbiot-war-on-the-living-world-wildlife?CMP=twt_gu", time: "6 hours ago"}, 
	{title : "Adventures in empty UDP scanning", site: "rapid7.co", href: "https://community.rapid7.com/community/infosec/blog/2014/10/03/adventures-in-empty-udp-scanning", time: "1 day ago"}, 
	{title : "Samsung paid Microsoft $1B in Android patent-licensing royalties in 2013", site: "zdnet.co", href: "http://www.zdnet.com/samsung-paid-microsoft-1-billion-in-android-patent-licensing-royalties-in-2013-7000034342/", time: "12 hours ago"}, 
	{title : "6DOF Positional Tracking with the Wiimote", site: "franklinta.co", href: "http://franklinta.com/2014/09/30/6dof-positional-tracking-with-the-wiimote", time: "1 day ago"}, 
	{title : "Phison USB Custom Firmware and Existing Firmware Patches", site: "github.co", href: "https://github.com/adamcaudill/Psychson", time: "1 day ago"}, 
	{title : "What is Yahoo really worth?", site: "economist.co", href: "http://www.economist.com/news/business/21621812-investors-put-low-value-yahoos-core-businessfor-now-what-it-really-worth", time: "1 day ago"}, 
	{title : "A PHP class for retrieving accurate IP address information for the client", site: "github.co", href: "https://github.com/Vectorface/whip", time: "1 day ago"}, 
	{title : "The single vigilante behind Facebook's 'real name' crackdown", site: "dailydot.co", href: "http://www.dailydot.com/technology/realnamepolice-facebook-real-names-policy/", time: "1 day ago"}, 
	{title : "Amazon Launches WriteOn to Compete Against Crowd-Writing Sites Like Wattpad", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/amazon-launches-writeon-to-compete-against-crowd-writing-sites-like-wattpad/", time: "23 hours ago"}, 
	{title : "With Dry Taps and Toilets, California Drought Turns Desperate", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/california-drought-tulare-county.html?smid=tw-share", time: "1 day ago"}, 
	{title : "USB armory – a open hardware flash drive sized computer", site: "inversepath.co", href: "http://inversepath.com/usbarmory", time: "1 day ago"}, 
	{title : "New Map Exposes Previously Unseen Details of Seafloor", site: "ucsd.ed", href: "https://scripps.ucsd.edu/news/new-map-exposes-previously-unseen-details-seafloor", time: "1 day ago"}, 
	{title : "D3.geo.zoom now supports smooth animated zooming", site: "jasondavies.co", href: "http://www.jasondavies.com/maps/zoom/", time: "22 hours ago"}, 
	{title : "An interactive 3D visualization of the stellar neighborhood", site: "chromeexperiments.co", href: "http://stars.chromeexperiments.com/", time: "1 day ago"}, 
	{title : "Web Audio Hackday 2014 Berlin", site: "janmonschke.co", href: "http://janmonschke.com/blog/2014/10/03/web-audio-hackday-2014.html", time: "1 day ago"}, 
	{title : "Washington Post employees slam owner Jeff Bezos", site: "salon.co", href: "http://www.salon.com/2014/10/03/%E2%80%9Canother_wall_street_smash_and_grab%E2%80%9D_washington_post_employees_slam_owner_jeff_bezos/", time: "16 hours ago"}, 
	{title : "Why women leave tech: It's the culture, not because 'math is hard'", site: "fortune.co", href: "http://fortune.com/2014/10/02/women-leave-tech-culture/", time: "1 day ago"}, 
	{title : "Work Habits at Apple", site: "oleb.ne", href: "http://oleb.net/blog/2014/09/work-habits-at-apple/", time: "4 days ago"}, 
]