news17 = [
	{title : "Recruiter Trolling on GitHub", site: "github.co", href: "https://github.com/thoughtbot/liftoff/pull/178#issuecomment-57688590", time: "1 day ago"}, 
	{title : "Lee Sedol wins historic jubango against Gu Li", site: "gogameguru.co", href: "https://gogameguru.com/lee-sedol-wins-jubango/", time: "5 days ago"}, 
	{title : "Reddit Forces Remote Workers to Live in San Francisco or Lose Job", site: "cbslocal.co", href: "http://sanfrancisco.cbslocal.com/2014/10/02/reddit-forcing-remote-workers-to-move-to-san-francisco-or-lose-job-tech-employee-fired-termination-relocate/", time: "1 day ago"}, 
	{title : "GCSS – Pure Go CSS Preprocessor", site: "github.co", href: "https://github.com/yosssi/gcss", time: "7 days ago"}, 
	{title : "How Two Men Unlocked Modern Encryption", site: "theatlantic.co", href: "http://www.theatlantic.com/technology/archive/2014/09/how-two-men-unlocked-modern-encryption/380520/", time: "11 days ago"}, 
	{title : "Before the Startup", site: "paulgraham.co", href: "http://www.paulgraham.com/before.html", time: "2 days ago"}, 
	{title : "What I Learned from My Time in Prison", site: "dailystormer.co", href: "http://www.dailystormer.com/what-i-learned-from-my-time-in-prison/", time: "2 days ago"}, 
	{title : "Test your email server encryption", site: "ssl-tools.ne", href: "https://ssl-tools.net/mailservers/", time: "8 days ago"}, 
	{title : "Londoners give up eldest children in public Wi-Fi security horror show", site: "theguardian.co", href: "http://www.theguardian.com/technology/2014/sep/29/londoners-wi-fi-security-herod-clause", time: "5 days ago"}, 
	{title : "Gaspard, the anti-assault accessory: never be alone again", site: "mygaspard.co", href: "http://mygaspard.com/index.php?lang=en", time: "1 day ago"}, 
	{title : "What It’s Like to Fly the $23,000 Singapore Airlines Suites Class", site: "medium.co", href: "https://medium.com/travel-adventure/what-its-like-to-fly-the-23-000-singapore-airlines-suites-class-17d9f3fee0d", time: "4 days ago"}, 
	{title : "Eve Raises $2.3M to Rethink Programming", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/eve-raises-2-3m-to-rethink-programming/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29", time: "3 days ago"}, 
	{title : "What It's Like to Fly the $23,000 Singapore Airlines Suites Class", site: "dereklow.c", href: "http://dereklow.co/what-its-like-to-fly-the-23000-singapore-airlines-suites-class/", time: "4 days ago"}, 
	{title : "ACPI, kernels and contracts with firmware", site: "mjg59.dreamwidth.or", href: "http://mjg59.dreamwidth.org/32369.html", time: "17 days ago"}, 
	{title : "Game about squares", site: "gameaboutsquares.co", href: "http://gameaboutsquares.com/", time: "69 days ago"}, 
	{title : "Call me maybe: Elasticsearch", site: "aphyr.co", href: "http://aphyr.com/posts/317-call-me-maybe-elasticsearch", time: "107 days ago"}, 
	{title : "Being in “flow”: the most addictive element in programming", site: "valbonneconsulting.wordpress.co", href: "http://valbonneconsulting.wordpress.com/2014/09/24/flow-the-addiction-behind-programming/", time: "9 days ago"}, 
	{title : "JPMorgan Discovers Further Cyber Security Issues", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/02/jpmorgan-discovers-further-cyber-security-issues/", time: "2 days ago"}, 
	{title : "Compressor.io – Compress and optimize your images", site: "compressor.i", href: "http://compressor.io", time: "135 days ago"}, 
	{title : "Merkle tree", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Merkle_tree", time: "15 days ago"}, 
	{title : "Neural-Network", site: "nxxcxx.github.i", href: "https://nxxcxx.github.io/Neural-Network", time: "1 day ago"}, 
	{title : "Google's Physical Web", site: "google.github.i", href: "http://google.github.io/physical-web/", time: "1 day ago"}, 
	{title : "History of T", site: "paulgraham.co", href: "http://www.paulgraham.com/thist.html", time: "316 days ago"}, 
	{title : "Is Docker Ready for Production? Feedbacks of a 2 Weeks Hands On", site: "t37.ne", href: "http://t37.net/is-docker-ready-for-production-feedbacks-of-a-2-weeks-hands-on.html", time: "25 days ago"}, 
	{title : "The Art of Naming (Military) Operations", site: "army.mi", href: "http://strategicstudiesinstitute.army.mil/pubs/parameters/Articles/1995/sieminsk.htm", time: "305 days ago"}, 
	{title : "Finger Trees: A Simple General-purpose Data Structure", site: "city.ac.u", href: "http://www.soi.city.ac.uk/~ross/papers/FingerTree.html", time: "561 days ago"}, 
]