news8 = [
	{title : "Fun with HTTP Headers (2005)", site: "nextthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers?Cneonction=close", time: "2 days ago"}, 
	{title : "Soylent 1.1", site: "soylent.m", href: "http://blog.soylent.me/post/98982202087/introducing-soylent-1-1", time: "1 day ago"}, 
	{title : "Show HN: Build real-time web apps with other people... in real-time!", site: "loggur.co", href: "https://www.loggur.com", time: "1 day ago"}, 
	{title : "Technology is not creating jobs: it is eating them", site: "onepercentbreadsticks.co", href: "http://onepercentbreadsticks.com/first-world-problems", time: "21 hours ago"}, 
	{title : "Could Ebola vaccine delay be due to an intellectual property spat?", site: "cbc.c", href: "http://www.cbc.ca/news/canada/manitoba/could-ebola-vaccine-delay-be-due-to-an-intellectual-property-spat-1.2786214", time: "1 day ago"}, 
	{title : "Show HN: MGBDTC – the easiest way to track what your employees are learning", site: "mgbdtc.co", href: "https://mgbdtc.com", time: "1 day ago"}, 
	{title : "if (osName.startsWith('windows 9'))", site: "searchcode.co", href: "https://searchcode.com/?q=if%28version%2Cstartswith%28%22windows+9%22%29", time: "2 days ago"}, 
	{title : "The Dropbox terabyte conundrum", site: "sixcolors.co", href: "http://sixcolors.com/post/2014/09/the-dropbox-terabyte-conundrum/", time: "11 days ago"}, 
	{title : "Ello, goodbye", site: "aralbalkan.co", href: "https://aralbalkan.com/notes/ello-goodbye/", time: "8 days ago"}, 
	{title : "The Kerning of Neil DeGrasse Tyson, Fearless Denier Killer", site: "rawstory.co", href: "http://www.rawstory.com/rs/2014/10/the-kerning-of-neil-degrasse-tyson-fearless-denier-killer/", time: "4 hours ago"}, 
	{title : "Amazon Launches WriteOn to Compete Against Crowd-Writing Sites Like Wattpad", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/amazon-launches-writeon-to-compete-against-crowd-writing-sites-like-wattpad", time: "1 day ago"}, 
	{title : "Early Digital Research CP/M Source Code", site: "computerhistory.or", href: "http://www.computerhistory.org/_static/atchm/early-digital-research-cpm-source-code/", time: "2 days ago"}, 
	{title : "Is Docker ready for production? Feedbacks of a 2 weeks hands on", site: "t37.ne", href: "https://t37.net/is-docker-ready-for-production-feedbacks-of-a-2-weeks-hands-on.html", time: "20 hours ago"}, 
	{title : "Aaron's Law Is Doomed Leaving US Hacking Law 'Broken'", site: "forbes.co", href: "http://www.forbes.com/sites/thomasbrewster/2014/08/06/aarons-law-is-doomed-leaving-us-hacking-law-broken/", time: "19 hours ago"}, 
	{title : "Heat- and booze-tolerant yeast make more biofuels", site: "arstechnica.co", href: "http://arstechnica.com/science/2014/10/heat-booze-tolerant-yeast-make-more-biofuels/", time: "1 day ago"}, 
	{title : "Understanding sources of unfairness in data driven decision making", site: "medium.co", href: "https://medium.com/@mrtz/how-big-data-is-unfair-9aa544d739de", time: "1 day ago"}, 
	{title : "A re-enactment of a 1967 animal movement simulator", site: "etiennebenson.co", href: "http://www.etiennebenson.com/simplot/", time: "1 day ago"}, 
	{title : "Soil Doctors Hit Pay Dirt in Manhattan's Central Park", site: "npr.or", href: "http://www.npr.org/2014/10/02/353066730/soil-doctors-hit-pay-dirt-in-manhattans-central-park&sa=U&ei=tAouVLHXHsGryATlo4KoDw&ved=0CA4QqQIwAA&usg=AFQjCNGQKtdiodU8GxwPdl8ed7hFAeedSQ", time: "1 day ago"}, 
	{title : "How RAM Scrapers Work: The Tool Behind the Latest Credit Card Hacks", site: "wired.co", href: "http://www.wired.com/2014/09/ram-scrapers-how-they-work/", time: "4 days ago"}, 
	{title : "Hackers Are Controling 17,000 Apple Computers", site: "yahoo.co", href: "http://finance.yahoo.com/news/hackers-found-flaw-macs-using-121808264.html", time: "1 day ago"}, 
	{title : "The Mirrorball", site: "textfiles.co", href: "http://ascii.textfiles.com/archives/4395", time: "1 day ago"}, 
	{title : "Marriott Pays $600,000 Fine for Blocking Guests' Wi-Fi Hotspots", site: "skift.co", href: "http://skift.com/2014/10/03/marriott-pays-600000-fine-for-blocking-guests-wi-fi-hotspots/", time: "1 day ago"}, 
	{title : "Jobless Rate in U.S. Falls Below 6% as Hiring Picks Up", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/04/business/economy/monthly-jobs-report-september.html", time: "1 day ago"}, 
	{title : "ELI5: Why are there so many MEAN stacks?", site: "stackoverflow.co", href: "http://stackoverflow.com/questions/23199392/difference-between-mean-js-and-mean-io", time: "17 hours ago"}, 
	{title : "The 10,000 Hour Rule for deliberate practice is wrong", site: "slate.co", href: "http://www.slate.com/articles/health_and_science/science/2014/09/malcolm_gladwell_s_10_000_hour_rule_for_deliberate_practice_is_wrong_genes.single.html", time: "3 days ago"}, 
	{title : "Hong Kong protesters beaten and bloodied as thugs attack sit-in", site: "theguardian.co", href: "http://www.theguardian.com/world/2014/oct/03/hong-kong-protestesters-democracy-occupy", time: "18 hours ago"}, 
]