news18 = [
	{title : "The trajectory of a software engineer… and where it all goes wrong.", site: "michaelochurch.wordpress.co", href: "http://michaelochurch.wordpress.com/2012/01/26/the-trajectory-of-a-software-engineer-and-where-it-all-goes-wrong/", time: "195 days ago"}, 
	{title : "How Chris McCandless Died (2013)", site: "newyorker.co", href: "http://www.newyorker.com/books/page-turner/how-chris-mccandless-died", time: "8 days ago"}, 
	{title : "The Cult of Done Manifesto", site: "brepettis.co", href: "http://www.brepettis.com/blog/2009/3/3/the-cult-of-done-manifesto.html", time: "1961 days ago"}, 
	{title : "Are you Living in a Computer Simulation?", site: "simulation-argument.co", href: "http://www.simulation-argument.com/simulation.html", time: "1390 days ago"}, 
	{title : "Find your color scheme", site: "colourco.d", href: "http://colourco.de/", time: "211 days ago"}, 
	{title : "CouchDB 'joins'. Some NoSQL design considerations", site: "cmlenz.ne", href: "http://www.cmlenz.net/archives/2007/10/couchdb-joins", time: "1672 days ago"}, 
	{title : "The Brain That Changed Everything", site: "esquire.co", href: "http://www.esquire.com/print-this/henry-molaison-brain-1110?page=all", time: "1433 days ago"}, 
	{title : "Instant.io - Massive Google Translate (built in 8 hours)", site: "instant.i", href: "http://instant.io/", time: "1236 days ago"}, 
	{title : "The Next Big Programming Language You've Never Heard of – WIRED", site: "wired.co", href: "http://www.wired.com/2014/07/d-programming-language/", time: "11 hours ago"}, 
	{title : "I want my Apple back", site: "svpino.co", href: "http://blog.svpino.com/2014/10/04/i-want-my-apple-back", time: "6 hours ago"}, 
	{title : "Evercookie used by NSA to track TOR users across browsers", site: "wikipedia.or", href: "https://en.wikipedia.org/wiki/Evercookie", time: "17 hours ago"}, 
	{title : "JPMorgan Employee Password Was Key in Hack Hitting 76M Homes", site: "bloomberg.co", href: "http://mobile.bloomberg.com/news/2014-10-02/jpmorgan-says-data-breach-affected-76-million-households.html", time: "17 hours ago"}, 
	{title : "RIP: Rapportive.  Finally stopped working today :(", site: "rapportive.co", href: "https://rapportive.com/", time: "169 days ago"}, 
	{title : "Creepy guys inspire Seattle women to make a new dating app", site: "seattletimes.co", href: "http://seattletimes.com/html/localnews/2024665918_sirendatingappxml.html", time: "2 days ago"}, 
	{title : "Google threatened with lawsuit over nude celebrity photos", site: "theguardian.co", href: "http://www.theguardian.com/technology/2014/oct/02/google-lawsuit-nude-celebrity-photos", time: "1 day ago"}, 
	{title : "Butterfly Labs mined Bitcoins on customers’ boxes before shipping", site: "arstechnica.co", href: "http://arstechnica.com/tech-policy/2014/09/feds-butterfly-labs-mined-bitcoins-on-customers-boxes-before-shipping/", time: "5 days ago"}, 
	{title : "How History Forgot Its Role in Public Debate", site: "aeon.c", href: "http://aeon.co/magazine/society/how-history-forgot-its-role-in-public-debate/", time: "2 days ago"}, 
	{title : "Python REPL with syntax highlighting, autocomplete and multiline editing", site: "github.co", href: "https://github.com/jonathanslenders/python-prompt-toolkit", time: "4 days ago"}, 
	{title : "Raw data from rDNS scan of the whole v4 Internet (2011)", site: "archive.or", href: "https://archive.org/details/mass-rdns-2011-02", time: "2 days ago"}, 
	{title : "Ken Silverman's PND3D engine", site: "advsys.ne", href: "http://advsys.net/ken/voxlap/pnd3d.htm", time: "2 days ago"}, 
	{title : "The Evolution of Sleep: 700M Years of Melatonin", site: "nytimes.co", href: "http://nytimes.com/2014/10/02/science/the-evolution-of-sleep-700-million-years-of-melatonin.html?_r=0&referrer=", time: "2 days ago"}, 
	{title : "“A Tesla car next year will probably be 90 percent capable of autopilot.”", site: "venturebeat.co", href: "http://venturebeat.com/2014/10/02/elon-musk-tesla-will-be-90-automated-next-year-shame-on-silicon-valley-if-were-not-the-leader/", time: "1 day ago"}, 
	{title : "Silk Road Lawyers Poke Holes in FBI’s Story", site: "krebsonsecurity.co", href: "http://krebsonsecurity.com/2014/10/silk-road-lawyers-poke-holes-in-fbis-story/", time: "1 day ago"}, 
	{title : "A Danish company is building a $335M seawall around New York", site: "theverge.co", href: "http://www.theverge.com/2014/10/1/6874925/can-a-massive-seawall-save-new-york-from-flooding", time: "2 days ago"}, 
	{title : "Online Linear Regression Using a Kalman Filter", site: "thealgoengineer.co", href: "http://www.thealgoengineer.com/2014/online_linear_regression_kalman_filter/", time: "2 days ago"}, 
	{title : "Police Used a Drone to Chase Down and Arrest Four DUI Suspects in a Cornfield", site: "vice.co", href: "http://motherboard.vice.com/read/police-used-a-drone-to-chase-down-and-arrest-four-dui-suspects-in-a-cornfield", time: "2 days ago"}, 
	{title : "SyncFree Consortium / Programming Models, Part 2: QuickChecking Derflow", site: "christophermeiklejohn.co", href: "http://christophermeiklejohn.com/derflow/erlang/2014/10/01/quickchecking-derflow.html", time: "2 days ago"}, 
]