news3 = [
	{title : "Dirty Assembly Tricks in NES Assembly (2013)", site: "andrewkelley.m", href: "http://andrewkelley.me/post/jamulator.html#dirty-assembly-tricks", time: "1 day ago"}, 
	{title : "Libsqlfs: A POSIX-style file system on top of an SQLite database", site: "github.co", href: "https://github.com/guardianproject/libsqlfs", time: "1 day ago"}, 
	{title : "Show HN: JuliusJS – Speech recognition in JavaScript", site: "github.co", href: "https://github.com/zzmp/juliusjs", time: "1 day ago"}, 
	{title : "Novena Update", site: "bunniestudios.co", href: "http://www.bunniestudios.com/blog/?p=4146", time: "1 day ago"}, 
	{title : "Digital revolution has yet to fulfil its promise of productivity and better jobs", site: "economist.co", href: "http://www.economist.com/news/special-report/21621237-digital-revolution-has-yet-fulfil-its-promise-higher-productivity-and-better", time: "1 day ago"}, 
	{title : "How to Pitch Your Startup on Stage", site: "justinkan.co", href: "http://justinkan.com/how-to-pitch-your-startup-on-stage", time: "7 hours ago"}, 
	{title : "How to get every game on STEAM for free", site: "gamasutra.co", href: "http://www.gamasutra.com/blogs/LeszekLisowski/20141001/226840/How_to_get_every_game_on_STEAM_for_free.php", time: "3 hours ago"}, 
	{title : "Bill Gates: Bitcoin Is 'Better Than Currency'", site: "entrepreneur.co", href: "http://www.entrepreneur.com/article/238103", time: "4 hours ago"}, 
	{title : "When 911 calls fail", site: "theverge.co", href: "http://www.theverge.com/2014/10/3/6414949/911-call-failures-fcc", time: "1 day ago"}, 
	{title : "The Quest to Build an Elevator into Space", site: "gizmodo.co", href: "http://gizmodo.com/the-quest-to-build-an-elevator-to-space-1638192427", time: "23 hours ago"}, 
	{title : "Researchers see signature of “Majorana particles” inside superconducting iron", site: "scientificamerican.co", href: "http://www.scientificamerican.com/article/majorana-particle-matter-and-antimatter/", time: "1 day ago"}, 
	{title : "As Many as 5K .Com’s Taken Away by Sealed Court Order by Verisign", site: "thedomains.co", href: "http://www.thedomains.com/2014/10/02/as-many-as-5k-coms-taken-away-by-sealed-court-order-by-verisign-including-some-of-mine/", time: "19 hours ago"}, 
	{title : "Analyzing AngelList Job Postings, Part 2: Salary and Equity Benchmarks", site: "codingvc.co", href: "http://codingvc.com/analyzing-angellist-job-postings-part-2-salary-and-equity-benchmarks", time: "1 day ago"}, 
	{title : "Decoding Nature's Soundtrack", site: "nautil.u", href: "http://nautil.us/issue/12/feedback/decoding-natures-soundtrack?utm_source=tss&utm_medium=desktop&utm_campaign=linkfrom", time: "9 hours ago"}, 
	{title : "Lecture 4: Building Product, Talking to Users, and Growing", site: "samaltman.co", href: "http://startupclass.samaltman.com/courses/lec04/#", time: "1 day ago"}, 
	{title : "HTTP/2 Frequently Asked Questions", site: "http2.github.i", href: "http://http2.github.io/faq/", time: "1 day ago"}, 
	{title : "Sourcery (YC W13) Raises $2.5M to Connect Kitchens and Local Food Suppliers", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/sourcery-raises-2-5m-to-connect-kitchens-and-local-food-suppliers/", time: "1 day ago"}, 
	{title : "The Physical Web", site: "github.co", href: "https://github.com/google/physical-web", time: "2 days ago"}, 
	{title : "How Exercise May Protect Against Depression", site: "well.blogs.nytimes.co", href: "http://well.blogs.nytimes.com/2014/10/01/how-exercise-may-protect-against-depression/?src=me", time: "2 days ago"}, 
	{title : "Usaddress – Python library for parsing unstructured address strings with NLP", site: "rtfd.or", href: "http://usaddress.rtfd.org/", time: "1 day ago"}, 
	{title : "Marriott Hotels fined $600,000 by FCC for jamming Wi-Fi hotspots [pdf]", site: "fcc.go", href: "http://transition.fcc.gov/Daily_Releases/Daily_Business/2014/db1003/DA-14-1444A1.pdf", time: "1 day ago"}, 
	{title : "Why Coconuts Could Be the Hydrogen Storage Material of the Future", site: "technologyreview.co", href: "http://www.technologyreview.com/view/531416/why-coconuts-could-be-the-hydrogen-storage-material-of-the-future/", time: "23 hours ago"}, 
	{title : "The Mac.BackDoor.iWorm threat in detail", site: "drweb.co", href: "http://news.drweb.com/show/?i=5977", time: "1 day ago"}, 
	{title : "Ebola: The tolling bell", site: "stanford.ed", href: "http://stanfordlawyer.law.stanford.edu/2014/10/ebola-the-tolling-bell/", time: "21 hours ago"}, 
	{title : "Show HN: Open-Source, Free, Agile Project Management Tool", site: "taiga.i", href: "http://www.taiga.io", time: "3 days ago"}, 
	{title : "Shapecatcher: Draw the Unicode character you want", site: "shapecatcher.co", href: "http://shapecatcher.com", time: "1 day ago"}, 
	{title : "Contact Lost with Planes One by One as FAA Fire Spread", site: "bloomberg.co", href: "http://www.bloomberg.com/news/2014-10-02/contact-lost-with-planes-one-by-one-as-faa-center-fire-spread.html", time: "2 days ago"}, 
	{title : "The NSA and Me", site: "firstlook.or", href: "https://firstlook.org/theintercept/2014/10/02/the-nsa-and-me/", time: "2 days ago"}, 
	{title : "An Australian researcher has worked out how to store 1000TB on a CD", site: "sciencealert.com.a", href: "http://www.sciencealert.com.au/news/20140309-26116.html", time: "2 days ago"}, 
]