news6 = [
	{title : "The Price of Music", site: "recode.ne", href: "http://recode.net/2014/03/18/the-price-of-music/", time: "1 day ago"}, 
	{title : "As Housing Costs Soar, San Francisco Seeks Ballot Solution", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/03/us/as-housing-costs-soar-san-francisco-seeks-ballot-solution.html?contentCollection=us&action=click&module=NextInCollection&region=Footer&pgtype=article", time: "1 day ago"}, 
	{title : "Mozilla Brick", site: "mozilla.i", href: "http://brick.mozilla.io/", time: "4 days ago"}, 
	{title : "Inside Shellshock: How hackers are using it to exploit systems", site: "cloudflare.co", href: "https://blog.cloudflare.com/inside-shellshock/", time: "3 days ago"}, 
	{title : "The day of the technopath", site: "thesprawl.or", href: "http://thesprawl.org/simstim/day-technopath/", time: "1 day ago"}, 
	{title : "RethinkDB and CoreOS: Navigating Digital Ocean Together", site: "justonepixel.co", href: "http://blog.justonepixel.com/geek/2014/10/03/rethinkdb-and-coreos/", time: "1 day ago"}, 
	{title : "Yahoo Nears Investment in Snapchat", site: "wsj.co", href: "http://online.wsj.com/articles/yahoo-nears-investment-in-snapchat-1412361684", time: "1 day ago"}, 
	{title : "Three Years on Rikers Without Trial", site: "newyorker.co", href: "http://www.newyorker.com/magazine/2014/10/06/law-3", time: "1 day ago"}, 
	{title : "Forty Portraits in Forty Years", site: "nytimes.co", href: "http://www.nytimes.com/interactive/2014/10/03/magazine/01-brown-sisters-forty-years.html", time: "16 hours ago"}, 
	{title : "Prison Bankers Who Profit from the Inmates", site: "time.co", href: "http://time.com/3446372/criminal-justice-prisoners-profit/", time: "4 days ago"}, 
	{title : "Don't build pages, build modules – Rethinking front-end engineering at eBay", site: "ebaytechblog.co", href: "http://www.ebaytechblog.com/2014/10/02/dont-build-pages-build-modules/", time: "1 day ago"}, 
	{title : "Social Media as Understood by Oracle Marketing vs. Oracle Legal", site: "imgur.co", href: "http://imgur.com/BGdAvWa", time: "2 hours ago"}, 
	{title : "Tilde Club", site: "tilde.clu", href: "http://tilde.club", time: "18 hours ago"}, 
	{title : "Show HN: Peercast – Stream BitTorrent video to your Chromecast in real time", site: "github.co", href: "https://github.com/mafintosh/peercast", time: "1 day ago"}, 
	{title : "Weev comes out as neo Nazi and white supremacist", site: "breitbart.co", href: "http://www.breitbart.com/Breitbart-London/2014/10/04/Convicted-hacker-and-darling-of-the-left-weev-emerges-from-prison-a-neo-Nazi-white-supremacist", time: "10 hours ago"}, 
	{title : "AngularJS Tutorial: a comprehensive 10,000 word guide", site: "airpair.co", href: "http://www.airpair.com/angularjs", time: "1 day ago"}, 
	{title : "Ancient campfires may have aided the rise of storytelling", site: "sciencemag.or", href: "http://news.sciencemag.org/archaeology/2014/09/ancient-campfires-led-rise-storytelling", time: "2 days ago"}, 
	{title : "How I Rewired My Brain to Become Fluent in Math", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/how-i-rewired-my-brain-to-become-fluent-in-math", time: "2 days ago"}, 
	{title : "Is it legitimate to “buy” Stack Overflow reputation?", site: "stackoverflow.co", href: "http://meta.stackoverflow.com/questions/270795/is-it-legitimate-to-buy-stack-overflow-reputation", time: "9 hours ago"}, 
	{title : "Introducing Modelling by Example", site: "everzet.co", href: "http://everzet.com/post/99045129766/introducing-modelling-by-example", time: "1 day ago"}, 
	{title : "New Mac OS X botnet discovered", site: "drweb.co", href: "http://news.drweb.com/show/?i=5976&lng=en", time: "1 day ago"}, 
	{title : "Yahoo Acquires Mobile Messaging App MessageMe", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/03/yahoo-acquires-mobile-messaging-app-messageme/", time: "1 day ago"}, 
	{title : "Hacker News comments with greatest number of upvotes, by month of posting", site: "docs.google.co", href: "https://docs.google.com/spreadsheets/d/1ZwonVX_KlDYhuhPnAAnVpdVRgu4LxldP74-c_kvOd5k/edit?usp=sharing", time: "20 hours ago"}, 
	{title : "A review of free sparse sequence taggers for NLP", site: "fnl.e", href: "http://fnl.es/a-review-of-sparse-sequence-taggers.html", time: "1 day ago"}, 
	{title : "Show HN: Create Your Own Startup Metrics Dashboard", site: "pubnub.co", href: "http://www.pubnub.com/developers/demos/startup-metrics-dashboard/", time: "1 day ago"}, 
	{title : "After the Quake: Earliest Known Color Photographs of San Francisco", site: "mashable.co", href: "http://mashable.com/2014/10/03/san-francisco-earthquake-color-photos/", time: "1 day ago"}, 
	{title : "SortedContainers: Pure-Python sorted containers that are as fast as C extensions", site: "grantjenks.co", href: "http://www.grantjenks.com/docs/sortedcontainers/", time: "1 day ago"}, 
	{title : "U.S. stockpiling nukes to protect Earth from asteroids", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/federal-eye/wp/2014/10/02/u-s-plan-to-save-earth-from-giant-asteroids-use-old-nukes/", time: "17 hours ago"}, 
]