news28 = [
	{title : "MIT launches Laboratory for Social Machines", site: "mit.ed", href: "http://newsoffice.mit.edu/2014/twitter-funds-mit-media-lab-program-1001", time: "3 days ago"}, 
	{title : "Notation as a Tool of Thought (1979) [pdf]", site: "toronto.ed", href: "http://www.eecg.toronto.edu/~jzhu/csc326/readings/iverson.pdf", time: "3 days ago"}, 
	{title : "Denmark tackles youth unemployment with university cuts", site: "west-info.e", href: "http://www.west-info.eu/denmark-tackles-youth-unemployment-with-university-cuts/", time: "3 days ago"}, 
	{title : "Houzz Raises $165M Series D Funding Round Led by Sequoia", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/houzz-raises-165m-series-d-led-by-sequoia-to-fuel-international-expansion/", time: "3 days ago"}, 
	{title : "The most important chart about the American economy you'll see this year", site: "vox.co", href: "http://www.vox.com/xpress/2014/9/25/6843509/income-distribution-recoveries-pavlina-tcherneva", time: "2 days ago"}, 
	{title : "Lunchtime Hack: Decoding LocationHistory", site: "lshift.ne", href: "http://www.lshift.net/blog/2014/09/30/lunchtime-hack-decoding-locationhistory/", time: "3 days ago"}, 
	{title : "Marka: Icon transformations", site: "fian.my.i", href: "http://fian.my.id/marka/", time: "55 days ago"}, 
	{title : "An interactive exploration of Boston's subway system", site: "mbtaviz.github.i", href: "http://mbtaviz.github.io/", time: "116 days ago"}, 
	{title : "GitHub.com is officially banned in Russia by the Government", site: "twitter.co", href: "https://twitter.com/orangy/status/517714936974561280", time: "2 days ago"}, 
	{title : "Synergy FOSS: Connect your keyboard to multiple PCs", site: "synergy-project.or", href: "http://synergy-project.org/", time: "31 days ago"}, 
	{title : "ISPs in Russia are blocking GitHub", site: "amazonaws.co", href: "https://s3.amazonaws.com/kato-share/18e61a9a5fb1c6906002801197086fbbe35d531c7b64d3d5afe764823ed2f1a/Screen%20Shot%202014-10-02%20at%208.37.11%20PM.png", time: "2 days ago"}, 
	{title : "Systemd may drive Linux admins to FreeBSD", site: "infoworld.co", href: "http://www.infoworld.com/d/data-center/you-have-your-windows-in-my-linux-249483", time: "31 days ago"}, 
	{title : "Are coders worth it? (2013)", site: "aeon.c", href: "http://aeon.co/magazine/society/james-somers-web-developer-money/", time: "36 days ago"}, 
	{title : "Dug.js – A JSONP to HTML Script", site: "rog.i", href: "http://rog.ie/blog/dugjs-a-jsonp-to-html-script", time: "233 days ago"}, 
	{title : "JPEG image glitching / corruption", site: "snorpey.github.i", href: "http://snorpey.github.io/jpg-glitch/", time: "391 days ago"}, 
	{title : "What Qualities Make a Good Startup Engineer?", site: "theeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/what-qualities-make-a-good-startup-engineer", time: "86 days ago"}, 
	{title : "Programming Sucks", site: "stilldrinking.or", href: "http://stilldrinking.org/programming-sucks", time: "158 days ago"}, 
	{title : "Unsung Hero of the Nuclear Age", site: "slate.co", href: "http://www.slate.com/articles/life/the_spectator/2011/02/an_unsung_hero_of_the_nuclear_age.single.html", time: "237 days ago"}, 
	{title : "Daniel Shiffman launches 'The Nature of Code' online for free", site: "natureofcode.co", href: "http://natureofcode.com/", time: "706 days ago"}, 
	{title : "BOXEN – GitHub's configuration tool for osx", site: "github.co", href: "https://boxen.github.com/", time: "153 days ago"}, 
	{title : "Apple will buy Tesla – rumor", site: "venturebeat.co", href: "http://venturebeat.com/2014/02/16/rumor-says-apple-will-buy-tesla/", time: "229 days ago"}, 
	{title : "Fun With HTTP Headers", site: "nextthing.or", href: "http://www.nextthing.org/archives/2005/08/07/fun-with-http-headers", time: "2061 days ago"}, 
	{title : "Simplify Decisions by Computing How Much Your Time Is Worth", site: "theeffectiveengineer.co", href: "http://www.theeffectiveengineer.com/blog/how-much-is-your-time-worth", time: "158 days ago"}, 
	{title : "The Y Combinator (Slight Return) (2008)", site: "mvanier.livejournal.co", href: "http://mvanier.livejournal.com/2897.html", time: "492 days ago"}, 
	{title : "Maze Generation In Thirteen Bytes", site: "oldskool.or", href: "http://trixter.oldskool.org/2012/12/17/maze-generation-in-thirteen-bytes/", time: "656 days ago"}, 
	{title : "Normalizing a CSV file using MySQL", site: "dangoldin.co", href: "http://dangoldin.com/2014/10/01/normalizing-a-csv-file-using-mysql/", time: "2 days ago"}, 
	{title : "Tesla to Unveil the “D” on October 9th", site: "twitter.co", href: "https://twitter.com/elonmusk/status/517486950589014016/photo/1", time: "2 days ago"}, 
	{title : "The commit Russia uses as an excuse to block GitHub", site: "translate.google.co", href: "https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fgithub.com%2Famdf%2Fobjidlib%2Fcommit%2Fe9c31e97c0ca7863516fa6e21c9f6441453d9149&edit-text=", time: "2 days ago"}, 
	{title : "I Hate Commander Chris Hadfield", site: "amazon.co", href: "http://www.amazon.com/review/R6L2EVLMPPEQS", time: "2 days ago"}, 
]