news29 = [
	{title : "Byte: The Smalltalk Issue (1981) [pdf]", site: "archive.or", href: "https://ia601506.us.archive.org/12/items/byte-magazine-1981-08/1981_08_BYTE_06-08_Smalltalk.pdf", time: "3 days ago"}, 
	{title : "Microbiome researcher does fecal transplant from African hunger-gatherer", site: "humanfoodproject.co", href: "http://humanfoodproject.com/rebecoming-human-happened-day-replaced-99-genes-body-hunter-gatherer/", time: "3 days ago"}, 
	{title : "If You Have Unlimited Vacation, Will You Take It?", site: "op-talk.blogs.nytimes.co", href: "http://op-talk.blogs.nytimes.com/2014/09/30/if-you-have-unlimited-vacation-will-you-take-it/", time: "2 days ago"}, 
	{title : "Simple Language Implementation Techniques for the 21st Century", site: "stefan-marr.d", href: "http://stefan-marr.de/papers/ieee-soft-marr-et-al-are-we-there-yet/", time: "4 days ago"}, 
	{title : "Show HN: Invoicerb, a simple, command line invoice tool", site: "github.co", href: "https://github.com/emson/invoicerb", time: "3 days ago"}, 
	{title : "New brain implants can restore autonomy to damaged minds", site: "aeon.c", href: "http://aeon.co/magazine/psychology/how-new-brain-implants-affect-free-will/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+AeonMagazineEssays+%28Aeon+Magazine+Essays%29", time: "3 days ago"}, 
	{title : "Dispatch from Worldcon", site: "nplusonemag.co", href: "https://nplusonemag.com/online-only/online-only/dispatch-from-worldcon/", time: "3 days ago"}, 
	{title : "Drop-a-Brick in your Toilet campaign aims to fight West Coast drought", site: "indiegogo.co", href: "https://www.indiegogo.com/projects/drop-a-brick-in-your-toilet/x/6550456", time: "2 days ago"}, 
	{title : "Chrysler 200 Factory [video]", site: "chrysler200factory.co", href: "http://www.chrysler200factory.com/", time: "3 days ago"}, 
	{title : "Startup Community the Film – A Documentary About Startups in Kitchener-Waterloo", site: "youtube.co", href: "https://www.youtube.com/watch?v=Q4EzYAB8Q4A", time: "2 days ago"}, 
	{title : "Holder urges tech companies to leave device backdoors open for police", site: "washingtonpost.co", href: "http://www.washingtonpost.com/blogs/the-switch/wp/2014/09/30/holder-urges-tech-companies-to-leave-device-backdoors-open-for-police/", time: "3 days ago"}, 
	{title : "Incredible Close-Up Drone Video of an Erupting Volcano in Iceland", site: "wired.co", href: "http://www.wired.com/2014/10/drone-video-iceland-eruption-bardarbunga-volcano", time: "3 days ago"}, 
	{title : "Sikuli Script", site: "sikuli.or", href: "http://www.sikuli.org/", time: "3 days ago"}, 
	{title : "Benefits of Writing a DSL in Ruby", site: "zenpayroll.co", href: "http://engineering.zenpayroll.com/benefits-of-writing-a-dsl/", time: "3 days ago"}, 
	{title : "Download Windows Technical 10 Preview", site: "microsoft.co", href: "http://windows.microsoft.com/en-us/windows/preview-download?ocid=tp_site_downloadpage", time: "3 days ago"}, 
	{title : "A PDF that contains its own TeX source", site: "code.google.co", href: "https://code.google.com/p/corkami/source/detail?r=1907", time: "3 days ago"}, 
	{title : "The $1,200 Machine That Lets Anyone Make a Metal Gun at Home", site: "wired.co", href: "http://www.wired.com/2014/10/cody-wilson-ghost-gunner/", time: "3 days ago"}, 
	{title : "Realtime Lyft Surge Prices", site: "konscript.ne", href: "http://lyft.konscript.net", time: "3 days ago"}, 
	{title : "U.S. Takes Asteroid Threat Seriously, Saves Nukes", site: "wsj.co", href: "http://online.wsj.com/articles/u-s-takes-asteroid-threat-seriously-1412119610", time: "3 days ago"}, 
	{title : "Reddit to force relocation of remote workers", site: "twitter.co", href: "https://twitter.com/yishan/status/517364923320385536", time: "3 days ago"}, 
	{title : "End of an era – No more pics from Trading Floor", site: "marketwatch.co", href: "http://www.marketwatch.com/story/this-is-the-last-photo-well-ever-run-of-the-nyse-trading-floor-2014-10-01?dist=countdown", time: "3 days ago"}, 
	{title : "Tony Hsieh Steps Down from Lead Role at Las Vegas Downtown Project", site: "recode.ne", href: "http://recode.net/2014/09/30/tony-hsieh-steps-down-from-lead-role-at-las-vegas-downtown-project/", time: "3 days ago"}, 
	{title : "Command-line file sharing", site: "transfer.s", href: "https://transfer.sh/", time: "4 days ago"}, 
	{title : "Scriptable Operating Systems with Lua [pdf]", site: "netbsd.or", href: "http://www.netbsd.org/~lneto/dls14.pdf", time: "4 days ago"}, 
	{title : "Click on the tile that has a different color", site: "ioxapp.co", href: "http://game.ioxapp.com/color/?", time: "3 days ago"}, 
	{title : "The Internet of Furbies", site: "memsql.co", href: "http://blog.memsql.com/the-internet-of-furbies/", time: "3 days ago"}, 
	{title : "What one engineer learned when he stopped taking photos and started drawing", site: "fastcompany.co", href: "http://www.fastcompany.com/3036378/my-creative-life/slowgrams-what-one-silicon-valley-engineer-learned-when-he-stopped-taking-p", time: "4 days ago"}, 
	{title : "Ellison: Sparc M7 is Oracle's most important silicon EVER", site: "theregister.co.u", href: "http://www.theregister.co.uk/2014/09/29/ellison_sparc_m7/", time: "3 days ago"}, 
	{title : "Tree-based Seekable Sequential Key Generators", site: "iacr.or", href: "https://eprint.iacr.org/2014/479", time: "3 days ago"}, 
]