news5 = [
	{title : "Yehuda Katz: Let's Talk about Rust", site: "confreaks.co", href: "http://confreaks.com/videos/4159-gogaruco2014-lets-talk-about-rust", time: "21 hours ago"}, 
	{title : "Samsung paid Microsoft 1B under the patent agreement last year", site: "recode.ne", href: "http://recode.net/2014/10/03/microsoft-says-samsung-owes-it-6-9-million-in-contract-dispute/", time: "5 hours ago"}, 
	{title : "Can You Rewire a Batter's Brain with Video Games?", site: "wsj.co", href: "http://online.wsj.com/articles/baseballs-science-experiment-1411135882", time: "21 hours ago"}, 
	{title : "Evaluating the security of OpenWRT, Part 3: adventures in NOEXECSTACK’land", site: "oldcomputerjunk.ne", href: "http://blog.oldcomputerjunk.net/2014/evaluating-the-security-of-openwrt-part-3-adventures-in-noexecstackland/", time: "1 day ago"}, 
	{title : "Satellites detect 'thousands' of new ocean-bottom mountains", site: "bbc.co", href: "http://www.bbc.com/news/science-environment-29465446", time: "18 hours ago"}, 
	{title : "Show HN: Duckling – Open-source datetime expression parsing", site: "duckling-lib.or", href: "http://duckling-lib.org/", time: "3 days ago"}, 
	{title : "Tarana Wireless: connecting the last-mile with non-line-of-sight wireless", site: "taranawireless.co", href: "http://www.taranawireless.com", time: "2 days ago"}, 
	{title : "How does SQLite work? Part 2: disk seeks are slow don't do them", site: "jvns.c", href: "http://jvns.ca/blog/2014/10/02/how-does-sqlite-work-part-2-btrees/", time: "1 day ago"}, 
	{title : "The tourist map of laptops", site: "gnod.co", href: "http://things.gnod.com/laptops/", time: "1 day ago"}, 
	{title : "Hackers’ Attack Cracked 10 Financial Institutions in Major Assault", site: "nytimes.co", href: "http://dealbook.nytimes.com/2014/10/03/hackers-attack-cracked-10-banks-in-major-assault/", time: "17 hours ago"}, 
	{title : "We need to stop pushing our kids", site: "theguardian.co", href: "http://www.theguardian.com/lifeandstyle/2014/oct/04/we-need-stop-pushing-our-kids-parents", time: "11 hours ago"}, 
	{title : "“How to Start a Startup” Audio Files", site: "github.co", href: "https://github.com/NathanEpstein/How_To_Start_A_Startup.git", time: "1 day ago"}, 
	{title : "Drug recommended to help cut drink dependence", site: "bbc.co.u", href: "http://www.bbc.co.uk/news/uk-29468885", time: "1 day ago"}, 
	{title : "Geometric Madness: Implementation of computational geometry algorithms [video]", site: "youtube.co", href: "https://www.youtube.com/watch?v=fu-uW7CQkVo", time: "1 day ago"}, 
	{title : "The origins of language are not what inherited disorders seemed to suggest", site: "nautil.u", href: "http://nautil.us/issue/17/big-bangs/the-family-that-couldnt-say-hippopotamus?utm_source=RSS_Feed&utm_medium=RSS&utm_campaign=RSS_Syndication", time: "1 day ago"}, 
	{title : "Study suggests that memory loss in Alzheimer's patients may be reversed", site: "neurosciencenews.co", href: "http://neurosciencenews.com/alzheimers-memory-loss-reversal-1377/", time: "2 days ago"}, 
	{title : "Data science: How mood and tempo can influence artist discovery?", site: "apassant.ne", href: "http://apassant.net/2014/10/03/how-mood-and-tempo-can-influence-artist-discovery/", time: "9 hours ago"}, 
	{title : "BookKeeper: High-availability scalable distributed logging", site: "muratbuffalo.blogspot.co", href: "http://muratbuffalo.blogspot.com/2014/09/paper-summary-high-availability.html", time: "1 day ago"}, 
	{title : "Elusive Form of Evolution Seen in Spiders", site: "simonsfoundation.or", href: "http://www.simonsfoundation.org/quanta/20141002-in-social-spiders-evidence-that-groups-evolve/", time: "2 days ago"}, 
	{title : "Jank Free: Let's Make the Web Silky Smooth", site: "jankfree.or", href: "http://jankfree.org/", time: "1 day ago"}, 
	{title : "A State of Xen – Chaos Monkey and Cassandra", site: "netflix.co", href: "http://techblog.netflix.com/2014/10/a-state-of-xen-chaos-monkey-cassandra.html", time: "1 day ago"}, 
	{title : "SAT solving – An alternative to brute force Bitcoin mining (2013)", site: "jheusser.github.i", href: "https://jheusser.github.io/2013/02/03/satcoin.html", time: "2 days ago"}, 
	{title : "Reddit", site: "samaltman.co", href: "http://blog.samaltman.com/reddit", time: "4 days ago"}, 
	{title : "Scientists to ‘fast-track’ evidence linking global warming to wild weather", site: "independent.co.u", href: "http://www.independent.co.uk/environment/climate-change/scientists-to-fasttrack-evidence-linking-global-warming-to-wild-weather-9773767.html", time: "4 hours ago"}, 
	{title : "Show HN: X-Windows independent C library for Linux that simulates keyboard input", site: "github.co", href: "https://github.com/solusipse/cpress", time: "15 hours ago"}, 
	{title : "Offline-first is people-first", site: "nolanlawson.co", href: "http://nolanlawson.com/2014/10/03/offline-first-is-people-first/", time: "17 hours ago"}, 
]