news24 = [
	{title : "Recruiting Tech Talent in High School", site: "wsj.co", href: "http://online.wsj.com/articles/recruiting-tech-talent-in-high-school-1412220618", time: "2 days ago"}, 
	{title : "LibreSSL: More Than 30 Days Later", site: "openbsd.or", href: "http://www.openbsd.org/papers/eurobsdcon2014-libressl.html", time: "6 days ago"}, 
	{title : "Clustering of bigram frequencies", site: "gottwurfelt.co", href: "http://gottwurfelt.com/2014/10/01/clustering-of-bigram-frequencies/", time: "2 days ago"}, 
	{title : "The Future of Iced Coffee", site: "theatlantic.co", href: "http://www.theatlantic.com/features/archive/2014/08/the-future-of-iced-coffee/375114/", time: "3 days ago"}, 
	{title : "Is this why Microsoft named it Windows 10?", site: "cnet.co", href: "http://www.cnet.com/news/is-this-why-microsoft-named-it-windows-10/", time: "2 days ago"}, 
	{title : "Show HN: WeTopTen – Create top 10 of books, movies, albums and more", site: "wetopten.co", href: "http://wetopten.com", time: "3 days ago"}, 
	{title : "A Rare Look at Apple's Design Genius Jony Ive", site: "vogue.co", href: "http://www.vogue.com/1415025/apple-design-genius-jonathan-ive/", time: "3 days ago"}, 
	{title : "Anti-selfconsciousness and John Stuart Mill and Carlyle", site: "theliterarylink.co", href: "http://theliterarylink.com/anti_selfconsciousness.html", time: "2 days ago"}, 
	{title : "Universal SSL: How It Scales", site: "cloudflare.co", href: "https://blog.cloudflare.com/universal-ssl-how-it-scales/", time: "2 days ago"}, 
	{title : "Show HN: Shared reading list and bookmarks for teams", site: "readonomy.co", href: "https://www.readonomy.com/?hn", time: "3 days ago"}, 
	{title : "This Time The Bubble Will Implode", site: "arielmichaeli.co", href: "http://arielmichaeli.com/2014/09/this-time-the-bubble-will-implode/", time: "3 days ago"}, 
	{title : "Adam Sandler to star in four movies exclusively for Netflix", site: "ew.co", href: "http://insidemovies.ew.com/2014/10/02/adam-sandler-netflix-movies/", time: "2 days ago"}, 
	{title : "Webfont optimization", site: "developers.google.co", href: "https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization", time: "3 days ago"}, 
	{title : "The Effort to Bring “Habitat” Back to Life", site: "wired.co", href: "http://www.wired.com/2014/10/restoring-habitat/", time: "3 days ago"}, 
	{title : "Raising Capital: Advice We Give Our Founders", site: "a16z.co", href: "https://a16z.com/2014/09/26/valuation-this-is-the-advice-we-give-our-founders/", time: "6 days ago"}, 
	{title : "Show HN: Go channels as a C library (with Obj-C wrapper)", site: "github.co", href: "https://github.com/davekeck/eb_chan", time: "3 days ago"}, 
	{title : "Microsoft Announces Windows 10", site: "theverge.co", href: "http://live.theverge.com/microsoft-windows-9-event-live-blog/", time: "4 days ago"}, 
	{title : "Facebook Apologizes to LGBT Community and Promises Changes to Real Name Policy", site: "techcrunch.co", href: "http://techcrunch.com/2014/10/01/facebook-apologizes-to-lgbt-community-and-promises-changes-to-real-name-policy/", time: "3 days ago"}, 
	{title : "Node.js Best Practices", site: "joyent.co", href: "https://www.joyent.com/developers/node/design", time: "15 days ago"}, 
	{title : "Inside the Cosmonaut Survival Kit (2013)", site: "theappendix.ne", href: "http://theappendix.net/blog/2013/11/the-cosmonauts-survival-kit", time: "3 days ago"}, 
	{title : "Is Alzheimer's Type 3 Diabetes? (2012)", site: "opinionator.blogs.nytimes.co", href: "http://opinionator.blogs.nytimes.com/2012/09/25/bittman-is-alzheimers-type-3-diabetes/", time: "2 days ago"}, 
	{title : "Digital.nyc – NYC's hub for tech and startups", site: "digital.ny", href: "http://www.digital.nyc", time: "3 days ago"}, 
	{title : "Source Code Optimization (2009) [pdf]", site: "linux-kongress.or", href: "http://www.linux-kongress.org/2009/slides/compiler_survey_felix_von_leitner.pdf", time: "3 days ago"}, 
	{title : "35,000 Walruses Gathered in Alaska", site: "businessinsider.co", href: "http://www.businessinsider.com/35000-walruses-gathered-in-alaska-2014-10", time: "2 days ago"}, 
	{title : "Show HN: EBay for 3D Printing", site: "printthis4.m", href: "https://printthis4.me", time: "2 days ago"}, 
	{title : "Doctors Find Barriers to Sharing Digital Medical Records", site: "nytimes.co", href: "http://www.nytimes.com/2014/10/01/business/digital-medical-records-become-common-but-sharing-remains-challenging.html", time: "2 days ago"}, 
]