news21 = [
	{title : "Holy Grail", site: "wikipedia.or", href: "http://en.wikipedia.org/wiki/Holy_Grail_(web_design)", time: "1 day ago"}, 
	{title : "Farewell CoffeeScript", site: "github.co", href: "https://github.com/staltz/rxmarbles/commit/57e37f176e0e005abd2c4fa0253bbd8f57fe1bd9", time: "2 days ago"}, 
	{title : "OpenWrt BarrierBreaker 14.07", site: "openwrt.or", href: "https://forum.openwrt.org/viewtopic.php?pid=242292#p242292", time: "2 days ago"}, 
	{title : "Bash bug: the other two RCEs, or how we chipped away at the original fix", site: "lcamtuf.blogspot.co", href: "http://lcamtuf.blogspot.com/2014/10/bash-bug-how-we-finally-cracked.html", time: "3 days ago"}, 
	{title : "Design for Assembly in KiCad", site: "rheingoldheavy.co", href: "http://rheingoldheavy.com/design-assembly-kicad/", time: "2 days ago"}, 
	{title : "C++11/14 compiler and library shootout", site: "cpprocks.co", href: "http://cpprocks.com/c1114-compiler-and-library-shootout/", time: "2 days ago"}, 
	{title : "Declassified photos from Tinian Island as the B-29 “Enola Gay” was being loaded", site: "archive.toda", href: "https://archive.today/94EKG", time: "4 days ago"}, 
	{title : "The Downtown Project Suicides", site: "recode.ne", href: "http://recode.net/2014/10/01/the-downtown-project-suicides-can-the-pursuit-of-happiness-kill-you/", time: "3 days ago"}, 
	{title : "Moscone Effect: What Dreamforce and Big Conferences Mean for Airbnb", site: "beyondpricing.co", href: "https://blog.beyondpricing.com/the-moscone-effect?rel=hn", time: "2 days ago"}, 
	{title : "Lever (YC S12) raises $10M to make hiring awesome", site: "lever.c", href: "https://blog.lever.co/the-next-chapter/", time: "2 days ago"}, 
	{title : "EC2 Maintenance Update II", site: "amazon.co", href: "http://aws.amazon.com/blogs/aws/ec2-maintenance-update-2/", time: "3 days ago"}, 
	{title : "Dart and Internet Explorer", site: "uservoice.co", href: "http://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6511262-add-the-dart-vm", time: "2 days ago"}, 
	{title : "Groove Deletes Their Facebook Page", site: "groovehq.co", href: "http://www.groovehq.com/blog/focus", time: "2 days ago"}, 
	{title : "Show HN: QDB, a remote python debugger", site: "github.co", href: "https://github.com/quantopian/qdb", time: "3 days ago"}, 
	{title : "A Sea Story (2004)", site: "theatlantic.co", href: "http://www.theatlantic.com/magazine/archive/2004/05/a-sea-story/302940/?single_page=true#show-last-Point", time: "2 days ago"}, 
	{title : "Join the Computing for Ebola Challenge Hackathon", site: "hackerleague.or", href: "https://www.hackerleague.org/hackathons/computing-for-ebola-challenge", time: "2 days ago"}, 
	{title : "Islamic State Social Media Strangely Silent Since Strikes", site: "vice.co", href: "http://motherboard.vice.com/en_ca/read/the-islamic-state-has-been-quieter-online-after-us-air-strikes", time: "2 days ago"}, 
	{title : "Tesla to unveil D and other product on October 9th", site: "twitter.co", href: "https://twitter.com/elonmusk/status/517486950589014016", time: "2 days ago"}, 
	{title : "Open-source client scaffolds and API pricing", site: "inboxapp.co", href: "https://www.inboxapp.com/blog/clients-and-pricing", time: "3 days ago"}, 
	{title : "API Docs for URX's Deeplink Search Engine", site: "urx.co", href: "http://developers.urx.com/", time: "5 days ago"}, 
	{title : "Technical analysis of client identification mechanisms", site: "chromium.or", href: "http://www.chromium.org/Home/chromium-security/client-identification-mechanisms", time: "7 days ago"}, 
	{title : "Sile, a typesetting system inspired by TeX and InDesign", site: "sile-typesetter.or", href: "http://www.sile-typesetter.org/what-is/index.html", time: "3 days ago"}, 
	{title : "Show HN: Open source, JavaScript game", site: "veerasundar.co", href: "http://veerasundar.com/suzhi/?hn", time: "2 days ago"}, 
	{title : "The Sound So Loud That It Circled the Earth Four Times", site: "nautil.u", href: "http://nautil.us/blog/the-sound-so-loud-that-it-circled-the-earth-four-times", time: "5 days ago"}, 
	{title : "Reddit Plans Cryptocurrency to Give Back to Its Users After $50M Raise", site: "techcrunch.co", href: "http://techcrunch.com/2014/09/30/reddit-scoops-up-50m-series-b-from-sam-altman-a16z-sequoia-at-500m-valuation/?ncid=rss", time: "4 days ago"}, 
	{title : "Piracy at the Old Bailey", site: "publicdomainreview.or", href: "http://publicdomainreview.org/2014/10/01/piracy-at-the-old-bailey/", time: "2 days ago"}, 
	{title : "Search Funds: The quiet, dependable, risk-averse sibling to the startup", site: "slate.co", href: "http://www.slate.com/articles/business/buy_a_small_business/2014/10/search_funds_the_quiet_dependable_risk_averse_sibling_to_the_startup.html", time: "3 days ago"}, 
	{title : "Rovio Announces Redundancies", site: "rovio.co", href: "http://www.rovio.com/en/news/blog/552/towards-a-simplified-organization", time: "2 days ago"}, 
]